VKCOM/VKUI

- package-lock.json
- package.json
- src/components/ConfigProvider/ConfigProvider.js
- webpack.config.js
Moved @vkontakte/icons from dependencies to peerDependencies. Fixed externals in webpack.config.js: now icons are out of bundle.
> Icons changes

- package-lock.json
- package.json
- src/components/Select/Select.css
- src/components/SelectMimicry/SelectMimicry.js
SelectMimicry: multiline, switched to functional component with memo; React 16.6.0
> SelectMimicry: multiline, functional component; new React version

- src/components/View/View.js
```
this.document.this = undefined
```
> Fix scroolTop in View component

- src/components/Alert/Alert.css
- src/components/Alert/Alert.js
- src/components/Alert/Readme.md
* Обновил Readme. Возникало много вопросов про оформление кнопок, щас вроде понятно стало.
* Пофиксил дизайн кнопок на Android (убрал всю стилизацию для разных `action.style`).
* Пофиксил баги. В Android версии в какой-то момент пропали стили для `actionsLayout="vertical"`.
> alerts fixes: updated readme, design fixes, bug fixes

- src/components/Epic/Readme.md
- src/components/Tabbar/Tabbar.js
- src/components/TabbarItem/TabbarItem.css
- src/components/TabbarItem/TabbarItem.js
В `TabbarItem` теперь можно добавлять текст
> tabbar item text props added

- src/components/Button/Button.js
> Revert "Button: remove extra HTML type attribute and buttonType prop"

- src/components/SearchIOS/SearchIOS.css
https://github.com/VKCOM/VKUI/issues/251
Делает область в конце инпута не кликабельной
> Set pointer-events none for SearchIOS after

- src/components/SearchAndroid/SearchAndroid.css
- src/components/SearchAndroid/SearchAndroid.js
https://github.com/VKCOM/VKUI/issues/276
> Search: header theme VK Apps close icon position

- src/components/Slider/Readme.md
Fix https://github.com/VKCOM/VKUI/issues/281
> Fix-Slider-Styleguide

- src/components/SearchIOS/SearchIOS.css
Fix 
https://github.com/VKCOM/VKUI/issues/251#issuecomment-498558449
> Fix-Input-Clear-Area-IOS

- src/components/Gallery/Gallery.tsx
- src/types/props.ts
- styleguide/config.js
> Gallery fix

- src/components/Button/Button.tsx
- styleguide/config.js
> Button: supported base html attributes

- src/components/PanelHeader/PanelHeader.css
- src/components/PanelHeader/PanelHeaderTransitions.css
> PanelHeader: fixed border cluster for iOS, fixed transition styles.

- src/components/Gallery/Gallery.tsx
- src/components/ModalPage/ModalPage.tsx
- src/components/ModalPageHeader/ModalPageHeader.tsx
- src/components/PanelHeader/PanelHeader.css
- src/components/Placeholder/Placeholder.tsx
- src/components/Snackbar/Snackbar.tsx
- src/components/View/View.tsx
- src/lib/classNames.ts
- src/types/props.ts
- styleguide/Components/PathlineRenderer.js
- styleguide/Components/Preview.js
- styleguide/Components/StyleGuideRenderer.js
- styleguide/utils.js
* PanelHeader: fixed font for Android
* Gallery
* fixes 465
* fixes 450
* docs: removed old scheme, fixed firefox bugs with iframe initializing
> Beta fixes

- src/components/Alert/Alert.tsx
> fixed Alert double onClose; fixed ts

- src/components/PanelHeader/PanelHeader.css
- src/components/PanelHeaderButton/PanelHeaderButton.css
- src/components/Search/Search.css
> PanelHeader, PanelHeaderButton, Search: fixed paddings

- src/components/Card/Card.css
- src/components/Card/Card.tsx
- src/components/CardScroll/CardScroll.css
На iOS тонкая граница из box-shadow не работает. С border работает и на iOS, и на Android
> card border fix

- src/components/Checkbox/Checkbox.tsx
- src/components/FormField/FormField.tsx
- src/components/FormLayoutGroup/FormLayoutGroup.tsx
- src/components/Input/Input.tsx
- src/components/Radio/Radio.tsx
- src/components/RangeSlider/RangeSlider.tsx
- src/components/Select/Select.tsx
- src/components/SelectMimicry/SelectMimicry.tsx
- src/components/Slider/Slider.tsx
- src/components/Textarea/Textarea.tsx
- src/types/props.ts
> `top` and `bottom` props fixes

- src/components/ModalRoot/ModalRoot.css
- src/components/Root/Root.css
- src/components/View/View.css
> fixed modal and popout z-index

- src/components/Search/Readme.md
- src/components/Search/Search.css
- src/components/Search/Search.tsx
> Search: supported clear field button and custom icon property

- src/components/TabsItem/TabsItem.css
> TabsItem: added min-width for scroll mode

- src/components/Search/Search.tsx
> fixed search ids

- src/components/Panel/Panel.css
- src/components/Panel/Readme.md
- src/components/PanelHeaderSimple/PanelHeaderSimple.css
- src/components/PanelHeaderSimple/PanelHeaderSimple.tsx
- src/components/PanelHeaderSimple/Readme.md
> Panel: fixed centered mode

- src/components/CellButton/CellButton.css
- src/components/Group/Group.css
- src/components/Group/Group.tsx
* Поправил отступы у `CellButton`
* Добавил немного "интеллекта" в отступы между `Group`. Теперь они зависят от того, что за `children` передан в группу.
> Margin fixes

- src/components/ModalPage/ModalPage.tsx
> ModalPage: removed updateModalHeight from propslist, marked it as optional

- babel.config.js
- babel.es6.config.js
- postcss.config.js
- src/components/FixedLayout/FixedLayout.tsx
- src/components/View/View.tsx
- webpack.config.js
Пофиксил ошибки линтера в FixedLayout и в конфигах babel, postcss и webpack
> Eslint fixes

- .eslintrc.json
- src/components/Cell/Cell.tsx
- src/components/ModalCard/ModalCard.tsx
- src/components/ModalRoot/ModalRoot.tsx
- src/components/Snackbar/Snackbar.tsx
- src/components/View/View.tsx
- src/lib/polyfills.ts
- src/lib/removeObjectKeys.ts
Подготавливаю проект к `noImplicitAny` режиму
> No implicit any

- src/components/PromoBanner/PromoBanner.css
> Fix title overflow

- src/components/PromoBanner/PromoBanner.css
- src/components/PromoBanner/PromoBanner.tsx
- src/components/PromoBanner/Readme.md
Добавлены пиксели статистики, которые подгружаются при начале показа рекламы и при клике на рекламу
> Add stats pixels

- src/components/ActionSheet/ActionSheet.css
- src/components/ActionSheet/ActionSheet.tsx
- src/components/ActionSheet/ActionSheetDropdown.tsx
- src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
- src/components/ActionSheet/Readme.md
- src/components/PopoutRoot/PopoutRoot.css
- src/components/PopoutRoot/PopoutRoot.tsx
- src/styles/styles.css
ActionSheet on desktop:
— keep Android and iOS styles
— issue with open popup and scrolling
ActionSheet on iOS:
— checking for a platform no more needed to make last closing element
> ActionSheet platforms-aware fixes

- src/components/Avatar/Avatar.tsx
- src/components/RichCell/Readme.md
- src/components/RichCell/RichCell.css
- src/components/RichCell/RichCell.tsx
- src/components/SimpleCell/Readme.md
- src/components/SimpleCell/SimpleCell.css
- src/components/SimpleCell/SimpleCell.tsx
- src/components/Switch/Switch.css
- src/styles/styles.css
- styleguide/config.js
- styleguide/setup.js
Создал новый компонент `SimpleCell`, который является очень упрощенной версией `Cell`. Со временем он заменит собой Cell, когда разнесем удаление, перетаскивание и выделение на подкомпоненты. Пока его можно использовать вместо `Cell` в тех местах, где того требуют оптимизации. 
Так же создал `RichCell`, который раньше костыльно реализовывался через `<Cell size="l" />`
Учел многие дизайнерские тонкости и попутно пофиксил несколько багов.
> Упрощения в Cell

- src/components/InfoRow/InfoRow.css
- src/components/InfoRow/Readme.md
> InfoRow: fixes ellipsis

- src/components/RichCell/RichCell.css
> RichCell fixes

- src/components/ModalPageHeader/ModalPageHeader.css
- src/components/PanelHeader/PanelHeader.css
> Panel header fixes

- src/components/ModalRoot/ModalRootDesktop.tsx
> add RAF to wait for initialization of modal element before animation

- src/components/Group/Group.css
- src/components/Group/Group.tsx
Чинит отступы между ячейками и сепаратором. Раньше для такого разделения использовалась Group, но теперь такое разделение может быть внутри самой Group и между сепараторами должен появляться отступ.
> Groups offsets & separators

- src/components/RichCell/RichCell.css
- src/components/SimpleCell/SimpleCell.css
> RichCell, Cell: fixed styles for case, when cell is link

- src/components/Button/Button.css
- src/components/Button/Button.tsx
- src/components/Button/Readme.md
- src/components/Counter/Readme.md
- src/components/Div/Readme.md
- src/components/File/Readme.md
- src/components/FormLayout/Readme.md
- src/components/ModalCard/ModalCard.tsx
- src/components/ModalRoot/Readme.md
- src/components/Placeholder/Readme.md
- src/components/RichCell/RichCell.tsx
- src/components/Typography/Headline/Headline.tsx
- src/components/Typography/Subhead/Subhead.tsx
- src/components/Typography/Title/Title.tsx
Для требуемых изменений в Button. пришлось поправить src/components/Typography/Title/Title.tsx, 
src/components/Typography/Subhead/Subhead.tsx  
и src/components/Typography/Headline/Headline.tsx для того чтобы текст кнопки использовал стили этих компонентов, но без тегов h*
> Button updates

- src/components/Group/Group.css
- src/components/Group/Readme.md
- src/components/SplitLayout/SplitLayout.tsx
- Переделал отступы на бордерах. Вместо них теперь padding и margin.
- Поправил Readme
- В SplitContext анимации включен по-умолчанию
> Group offset

- src/components/PromoBanner/PromoBanner.css
- src/components/PromoBanner/PromoBanner.tsx
- src/components/PromoBanner/Readme.md
- src/components/SimpleCell/SimpleCell.tsx
- src/types.ts
- Использовали SimpleCell вместо Cell
- Убрали ненужные блоки из вёрстки
- closes #775 
- closes #774
> Promo banner fixes

- src/hooks/useInsets.ts
Инсеты из VK Bridge теперь подменяют значения css-переменных
> Smart insets

- src/components/Tooltip/Readme.md
- src/components/Tooltip/Tooltip.css
- src/components/Tooltip/Tooltip.tsx
> Tooltip: added mode property and supported light version

- src/components/Tabs/Readme.md
- src/components/Tabs/Tabs.tsx
> Tabs: draw default style if platform is android and mode is segmented

- src/components/Banner/Banner.css
- src/components/Banner/Banner.tsx
- src/components/Tooltip/Tooltip.tsx
> Banner: fixed dismiss button for android

- src/components/Snackbar/Snackbar.css
> Snackbar: fixed padding in Modal

- src/components/Tabs/Tabs.css
> Tabs: fixed z-index for FixedLayout vertical="bottom"

- package.json
- src/components/Counter/Counter.css
- src/components/Counter/Counter.tsx
- src/components/Epic/Readme.md
- src/components/TabbarItem/TabbarItem.css
- src/components/TabbarItem/TabbarItem.tsx
- styleguide/setup.js
- yarn.lock
> Tabbar item fixes

- src/components/Epic/Readme.md
- styleguide/setup.js
> Fixed constant Icon28UserCircleOutline in styleguide

- src/components/Epic/Readme.md
Прости, забыл про вкладку с уведомлениями, там тоже заголовок забыли
> [Epic] Fixed title noti -> clips

- src/components/PanelSpinner/PanelSpinner.tsx
- src/components/Spinner/Spinner.tsx
PanelSpinner is wrapper for Spinner, so we can pass size prop to PanelSpinner too
> Added optional size prop for PanelSpinner

- src/components/PromoBanner/PromoBanner.tsx
- src/components/PromoBanner/Readme.md
> Fix PromoBanner options

- package.json
- src/components/MiniInfoCell/MiniInfoCell.css
- src/components/MiniInfoCell/MiniInfoCell.tsx
- src/components/MiniInfoCell/Readme.md
- src/index.ts
- src/styles/styles.css
- styleguide/config.js
- styleguide/setup.js
- yarn.lock
> InformationCell component

- src/components/CustomSelect/CustomSelect.tsx
- src/components/Select/Select.tsx
поправил прокидывание рефа снаружи
проверил и для NativeSelect и для CustomSelect
> fixed select ref

- src/components/CustomScrollView/CustomScrollView.tsx
> remove scroll view focus ability to fix custom select in Firefox focus ring

- src/components/Footer/Readme.md
Исправил черноту в коде примера компонента [Footer](https://vkcom.github.io/vkui-styleguide/#footer)
> Fixed spaces in Read.me component Footer

- src/components/Typography/Caption/Readme.md
https://github.com/VKCOM/VKUI/blob/63890673f32dcf66da29490dae24094a42af33ae/src/components/Typography/Caption/Caption.css#L41-L43
> Update Readme for Caption

- package.json
- src/components/Checkbox/Checkbox.css
- src/components/Checkbox/Checkbox.tsx
- src/components/CustomSelect/CustomSelect.css
- src/components/CustomSelect/CustomSelect.tsx
- src/components/FormStatus/FormStatus.css
- src/components/FormStatus/FormStatus.tsx
- src/components/Input/Input.css
- src/components/Input/Input.tsx
- src/components/ModalRoot/ModalRootTouch.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/Radio/Radio.css
- src/components/Radio/Radio.tsx
- src/components/RangeSlider/RangeSlider.tsx
- src/components/Select/Select.css
- src/components/SelectMimicry/SelectMimicry.tsx
- src/components/Slider/Slider.css
- src/components/Slider/Slider.tsx
- src/components/Textarea/Textarea.css
- src/components/Textarea/Textarea.tsx
Compact-версии следующих контролов:
- Input
- Textarea
- Select
- Radio
- Checkbox
- Slider
- RangeSlider
- FormStatus
> VKUI-5: Поддержка sizeY=COMPACT

- src/components/Checkbox/Checkbox.css
- src/components/CustomSelect/CustomSelect.tsx
- src/components/FormField/FormField.css
- src/components/FormStatus/FormStatus.css
- src/components/Input/Input.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/Radio/Radio.css
- src/components/SelectMimicry/SelectMimicry.tsx
- src/components/Slider/Slider.css
- src/components/Textarea/Textarea.tsx
- src/lib/platform.ts
Цвета без изменения, пока нет соответствующих токенов
> VKIU-12: Перевод основных компонентов на тему vk.com

- src/components/Slider/Slider.css
- src/components/Slider/Slider.tsx
1. fix left coordinate calculation
2. fix click on gray line
> Fix slider for desktop

- src/components/Cell/Cell.tsx
- src/components/Cell/Readme.md
- Дополнен компонент Cell на реагирование на входящие пропсы checked и defaultChecked
- В readme добавлены соответствующие примеры
> Дополнен компонент Cell

- src/components/Radio/Radio.css
…m, fix radio icon for vkcom platform
> VKUI fix radio icon for android platform

- src/components/CardScroll/CardScroll.tsx
- src/components/HorizontalScroll/HorizontalScroll.tsx
- src/components/Tabs/Tabs.css
В некоторых случаях сдвиг при hover на стрелке влияет на scrollWidth, в некоторых - нет, из-за этого не всегда корректно работала прокрутка к правому краю.
В качестве решения изменен порядок обработки  и убирания сдвига, убрана завязка на размер сдвига.
> VKUI-18: improve scrolling logic

- src/components/HorizontalScroll/HorizontalScroll.css
- src/components/HorizontalScroll/HorizontalScroll.tsx
Изменились значения по умолчанию для 
- сдвига при hover на стрелку
- продолжительности анимации прокрутки
Добавил возможность задать длительность анимации прокрутки через props
> VKUI-18: fix constants after design review: hover offset, animation duration

- .github/workflows/pull_request.yml
На каждый PR теперь будет создаваться артефакт с докой. И тесты будут прогоняться.
> creating styleguide on pr

- src/components/View/View.tsx
- src/lib/utils.ts
Добавил создание CustomEvent отдельным методом во view для ie11
> add creation of custom event to view

- src/components/PromoBanner/Readme.md
ageRestrictions это строка
https://github.com/VKCOM/VKUI/blob/f1ac0e1b382dbea9cf74b5f70c4d0d34e9328a6d/src/components/PromoBanner/PromoBanner.tsx#L32
> Fix PromoBanner example

- src/lib/touch.ts
```diff
- кординату
+ координату
```
> lib/touch: fixed spell error

- src/components/CardGrid/CardGrid.css
Фикс проблемы с лишними отступами слева #1026
> Card: fixed bug with left extra margin

- src/components/HorizontalScroll/HorizontalScroll.css
- src/components/HorizontalScroll/HorizontalScroll.tsx
Анимация стрелок при наведении в компоненте HorizontalScroll
> Arrow opacity animation on hover

- src/components/Card/Card.tsx
Добавлена поддержка ref в Card.
> No ref in card component

- src/components/CellButton/CellButton.css
- src/components/CellButton/CellButton.tsx
- src/components/CellButton/Readme.md
- src/components/RichCell/RichCell.css
- src/components/RichCell/RichCell.tsx
- src/components/SimpleCell/SimpleCell.css
- src/components/SimpleCell/SimpleCell.tsx
- src/styles/styles.css
- Адапдтировал компоненты под sizeY compact
- Внутри `CellButton` переиспользовал `SimpleCell`
- В `RichCell` игнорю `onClick`, если передан `disabled`
> Cell button

- src/components/FormField/FormField.css
Отключено изменение цвета бордера при наведении у disabled форм
> Disabled fields hover

- src/components/Banner/Readme.md
- src/components/FixedLayout/Readme.md
- src/components/Group/Group.css
- src/components/PanelHeader/PanelHeader.css
- src/components/PanelHeader/PanelHeader.tsx
- src/components/Placeholder/Readme.md
- src/components/Search/Search.css
- src/components/Spinner/Readme.md
- src/components/Tabs/Tabs.css
- src/styles/styles.css
- styleguide/Components/Preview.js
- styleguide/pages/helpers.md
* Обновлен дизайн `PanelHeader` для  платформы `vkcom`
* У `PanelHeader` добавлен флаг `fixed`, позволяющий не фиксировать шапку сверху, если передан `fixed={false}`
* `PanelHeader` на платформе `vkcom` не зафиксирована сверху, а находится в потоке с другими элементами панели.
* Содержимое любой панели должно быть обрамлено хотя бы в один `Group`. Пример:
```jsx
<Panel>
<PanelHeader>Шапка</PanelHeader>
<Group>Содержимое</Group>
</Panel>
```
> PanelHeader: vkcom

- src/components/HorizontalCell/HorizontalCell.css
- src/components/HorizontalCell/HorizontalCell.tsx
- src/components/HorizontalCell/Readme.md
- src/index.ts
- src/styles/styles.css
- styleguide/config.js
* Принимает валидные для платформы отступы.
* В блоке с альбомами используется img с стилями описанными в примере для stylguidist'а.
Вырвал из [@vk](https://www.figma.com/community/file/842774413870475604) в Figma
> Implemented HorizontalCell component

- src/components/Gallery/Gallery.tsx
> Gallery: fixed case, when current > slides.length - 1

- src/components/Placeholder/Placeholder.css
- src/components/Placeholder/Placeholder.tsx
* `Placeholder`: добавлено свойство `getRootRef`.
> Placeholder fixes

- src/components/FormField/FormField.css
- src/components/Input/Input.css
- src/components/Select/Select.css
- src/components/Textarea/Textarea.css
live preview https://vkui-storybook-git-fix-formfield-autofill.ewgenius.vercel.app/?path=/story/forms-formfield--default
Safari:
> Fix Input, Textarea autofill

- src/components/Panel/Panel.css
- src/components/PullToRefresh/PullToRefresh.css
- src/components/PullToRefresh/Readme.md
> #933 [Bug] Рабочая область PullToRefresh

- src/components/PanelHeader/PanelHeader.css
> #1073 [Bug] неправильный размер шрифта Title в Pannel Header на Android

- src/components/FormStatus/FormStatus.css
- src/components/FormStatus/FormStatus.tsx
- src/index.ts
* `FormStatus`: обновлен дизайн
> FormStatus

- src/components/HorizontalScroll/HorizontalScroll.tsx
* `HorizontalScroll`: исправлено зацикливание анимации скролла.
> [HorizontalScroll] Fix scroll animation recursion

- src/components/Cell/Cell.css
- src/components/Cell/Cell.tsx
- src/components/CellButton/CellButton.tsx
- src/components/ContentCard/ContentCard.tsx
- src/components/Gallery/Gallery.tsx
- src/components/PanelHeader/PanelHeader.css
- src/components/PanelHeaderContent/PanelHeaderContent.tsx
- src/index.ts
* `Cell`: поправлен overflow в `removable` режиме (fixes #1165)
* `CellButton`: разрешено передавать атрибуты button (fixes #1174)
* `ContentCard`: поправлен экспорт и типы (fixes #1176, fixes#1177)
* `PanelHeaderContent`: все свойства помечены как необязательные (fixes #1172)
* `PanelHeader`: поправен box-sizing, чтобы padding и height суммировались (fixes #1145)
* `Gallery`: добавлены `getRef` и `getRootRef` (fixes #1135)
> V4 bug fixes

- src/components/ModalRoot/Readme.md
> Update ModalRoot demo

- src/components/ModalPage/ModalPage.css
> Set proper width for ModalPage on vkcom platform

- src/components/HorizontalCell/HorizontalCell.css
Упустил такой момент, когда текст может вылететь из-за отсутствия в нём пробелов.
> Fix overlapping text in HorizontalCell

- src/components/HorizontalCell/Readme.md
- src/components/Typography/Text/Readme.md
- Надписи "показать все" для HorizontalCell
- Лишний отступ у Text
> Styleguide review fixes

- src/components/SplitLayout/Readme.md
> Add SplitLayout adaptivity demo

- src/components/PullToRefresh/PullToRefresh.css
- src/components/PullToRefresh/PullToRefresh.tsx
> #1207: [Bug] [PTR] PTR не прячется под шапку

- src/components/Tappable/Tappable.tsx
Концепт решения проблемы одновременных ховеров и активных состояний у `Tappable` внутри которого находится другой `Tappable`
> Tappable inside Tappable

- package.json
- src/components/Group/Group.css
- src/components/Header/Header.css
- src/components/Header/Header.tsx
- src/components/Header/Readme.md
- src/components/Link/Link.css
- src/components/Link/Link.tsx
- src/components/Tappable/Tappable.css
- yarn.lock
* `Header`: добавлен новый `mode` `tertiary`, обновлены дизайн и документация
* `Link`: добавлены active и hover состояния, поправлено выравнивание иконок
> Header & Link

- src/components/SplitLayout/Readme.md
Исправления в демке
- убирает общий PanelHeader в демке под vkcom
- навигация внутри Group (на все платформы)
vkcom
vkcom
iOS
Android
> Fix SplitLayout demo for VKCOM

- .github/workflows/pull_request.yml
- package.json
- yarn.lock
Замеряем размер полной либы и цсс + проверяем три-шейкинг.
Чек size падает, потому что в v4 его еще нет https://github.com/andresz1/size-limit-action/issues/33
> INFRA: Add size-limit

- src/components/Epic/Epic.tsx
- src/components/Epic/Readme.md
- tabbar опционален на больших экранах (SMALL_TABLET и выше)
- обновлена демка для использования вместе с SplitLayout
> Adaptive Epic

- src/components/Card/Card.css
- src/components/Card/Card.tsx
- src/components/CardGrid/CardGrid.css
- src/components/CardGrid/CardGrid.tsx
- src/components/CardGrid/Readme.md
- src/components/CardScroll/CardScroll.css
- src/components/CardScroll/CardScroll.tsx
- src/components/CardScroll/Readme.md
- src/components/ContentCard/ContentCard.tsx
- `CardScroll` и `CardGrid`: обновлён дизайн. Теперь есть возможность использовать компоненты как внутри Group, так и за её пределами.
> CardScroll & CardGrid

- e2e/index.ts
- src/testing/e2e/utils.tsx
> TEST: Починить скриншоты

- src/components/Gallery/Gallery.tsx
> #1243 [Bug] Первая принудительная смена слайда происходит без анимации

- src/components/RangeSlider/RangeSlider.test.tsx
- src/components/RangeSlider/RangeSlider.tsx
- src/components/Slider/Slider.tsx
- src/components/Touch/Touch.tsx
- src/helpers/math.test.ts
- src/helpers/math.ts
- src/testing/utils.ts
> #600: RangeSlider: невозможно выставить значения у краев диапазона (min и max) отличающиеся на 1 step

- styleguide/Components/Preview.js
> #1202: [Feature][Документация] Ускорить стайлгайд

- src/hooks/useInsets.ts
Исправлено обновление --safe-area
при открытой клавиатуре в webview не происходило обнуление
> Fixed update safe area insets

- .eslintrc.json
> Restrict imports from @vkontakte/icons/dist

- package.json
Transformed to get the newest version -> @vkontakte/vkjs@^0.5.0
Added support of React v17
I currently use VKUI4 with React 17, library is compatible with the latest major version
> [Version bump] Updated package versions

- src/components/RangeSlider/RangeSlider.tsx
- src/components/RangeSlider/Readme.md
- src/components/Slider/Readme.md
- src/components/Slider/Slider.css
- src/components/Slider/Slider.tsx
Дизайн (opacity 40%): https://www.figma.com/file/lLXmjJhnJa4OhgZXzcNJD9/VKUI-Android-Library?node-id=10128%3A0
> Slider: disabled state

- src/components/Tappable/Tappable.tsx
> Tappable: don't pass onEnter, onLeave if disabled

- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/Readme.md
Превью на видео: 
https://user-images.githubusercontent.com/36237725/105053318-d671df00-5a81-11eb-8572-50f385bc1aff.mov
fixes #335
> ModalRoot: onPageTouchMove now not prevents horizontal scrolling

- src/components/PanelHeaderContext/PanelHeaderContext.css
- src/components/PanelHeaderContext/PanelHeaderContext.tsx
- src/components/PanelHeaderContext/Readme.md
> PanelHeaderContext: adopt for desktop

- src/components/ModalRoot/ModalRoot.css
- src/components/ModalRoot/ModalRoot.tsx
> ModalRoot: check if touch target is scrollable

- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/Readme.md
Reverts VKCOM/VKUI#1309
Reverts VKCOM/VKUI#1321
> Revert "ModalRoot: onPageTouchMove now not prevents horizontal scrolling"

- src/components/ChipsSelect/ChipsSelect.tsx
- src/components/ChipsSelect/Readme.md
- src/components/CustomSelectOption/CustomSelectOption.tsx
**ChipsSelect:** `creatableText` теперь отвечает за отрисовку опции для создания тегов в режими `creatable`
**CustomSelectOption:** удален лишний параметр `className`
> Доработки ChipsSelect и CustomSelectOption

- src/components/Tabbar/Tabbar.e2e.tsx
- src/components/Tabbar/__image_snapshots__/tabbar-android-bright_light-1-snap.png
- src/components/Tabbar/__image_snapshots__/tabbar-android-space_gray-1-snap.png
- src/components/Tabbar/__image_snapshots__/tabbar-ios-bright_light-1-snap.png
- src/components/Tabbar/__image_snapshots__/tabbar-ios-space_gray-1-snap.png
- src/components/TabbarItem/TabbarItem.css
> #900: TabbarItem: отключить перенос строк подписи

- src/components/Counter/Counter.test.tsx
- src/components/Counter/Counter.tsx
> feat: Hide empty counter

- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/Tooltip.tsx
> fix: Preserve ref on tooltip target

- src/components/ModalCard/ModalCard.css
- src/components/ModalRoot/Readme.md
> ModalCard: fix max-width

- src/components/View/View.tsx
`
<View {...restProps} className="myclass">
...
</View>
`
Этот pr исправляет замену class="View View--ios/android" на class="myclass".
> View: fix prop classname

- src/components/PullToRefresh/PullToRefresh.tsx
> PullToRefresh: checking if event cancelable

- src/components/ModalPageHeader/ModalPageHeader.css
- src/components/ModalPageHeader/ModalPageHeader.e2e.tsx
- src/components/ModalPageHeader/__image_snapshots__/modalpageheader-android-bright_light-1-snap.png
- src/components/ModalPageHeader/__image_snapshots__/modalpageheader-android-space_gray-1-snap.png
- src/components/ModalPageHeader/__image_snapshots__/modalpageheader-ios-bright_light-1-snap.png
- src/components/ModalPageHeader/__image_snapshots__/modalpageheader-ios-space_gray-1-snap.png
- src/components/ModalPageHeader/__image_snapshots__/modalpageheader-vkcom-vkcom-1-snap.png
Вместо #1223 — без правок отступов
> #661: Заголовок модального окна не сокращается тремя точками

- src/components/Card/Card.tsx
- src/components/PanelHeaderBack/PanelHeaderBack.tsx
- src/components/Root/Root.tsx
- src/components/Tabs/Tabs.tsx
- src/testing/utils.tsx
> Не удалять стандартный className, если есть кастомный

- src/components/ChipsInput/ChipsInput.tsx
> ChipsInput: fix typo in method

- src/components/Cell/Cell.css
- src/components/Cell/Cell.test.tsx
- src/components/Cell/Cell.tsx
- src/components/FormItem/FormItem.css
- src/components/FormItem/FormItem.tsx
- src/components/FormItem/Readme.md
- src/components/FormLayoutGroup/FormLayoutGroup.css
- src/components/FormLayoutGroup/FormLayoutGroup.tsx
- src/components/FormLayoutGroup/Readme.md
- src/components/Removable/Removable.css
- src/components/Removable/Removable.test.tsx
- src/components/Removable/Removable.tsx
- src/index.ts
- src/styles/styles.css
- Выделила из Cell компонент Removable, чтобы не дублировать логику показа кнопок для Android/iOS и их стили
- Добавила Removable с примерами в:
- FormItem для инпута/селекта
- FormLayoutGroup для группы инпутов/селектов (только для mode="horizontal")
- Подправила стили для remove marker на iOS, чтобы он был как в макете
- Переписала Cell на хуки
> VKUI-135: Удаляемые элементы форм

- e2e/index.ts
- e2e/styles.test.css
- src/components/ChipsSelect/ChipsSelect.e2e.tsx
- src/components/ChipsSelect/ChipsSelect.tsx
- src/components/ChipsSelect/__image_snapshots__/chipsselect-scrolls-to-item-via-arrows-1-snap.png
- src/components/CustomScrollView/CustomScrollView.css
- src/components/CustomScrollView/CustomScrollView.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelectOption/CustomSelectOption.tsx
- src/components/Typography/Text/Text.tsx
- src/lib/utils.ts
- src/testing/e2e/index.ts
- Заменил classList в CustomScrollView на цсс
- Заменил скролл-по-стрелкам в ChipsSelect на реф (+ тест!)
- Починил демку ChipsSelect
- Заменил класс-реф из ChipsSelect на обычный реф
> refactor: Убрать селекторы из CustomScrollView и ChipsSelect

- src/components/AppRoot/AppRoot.test.tsx
- src/components/AppRoot/AppRoot.tsx
-1 блок для нескольких инстансов vkui на странице
> refactor: Убрать селекторы для portal-root 

- src/components/Group/Group.css
- src/components/Group/Group.tsx
Reverts VKCOM/VKUI#1345
- Вложенные группы не имеют SizeY - Compact варианта
> Revert "Group: adopt inner group paddings for compact size"

- src/components/Alert/Alert.css
- src/components/Alert/Alert.tsx
> Alert: correct width on VKCOM and Android

- src/components/ActionSheet/ActionSheet.css
- src/components/ActionSheetItem/ActionSheetItem.css
* Убраны лишние отступы для контекстного ActionSheet на iOS;
* Поправлены минимальные отступы между текстом и маркером в ActionSheetItem;
> ActionSheet: design fixes

- src/components/File/File.tsx
> File: disable auto submit inside form; Exclude 'type' from props

- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/Readme.md
> ModalRoot: fix undefined modalState in checkPageContentHeight

- TESTING.md
> fix typo in TESTING.md

- package.json
- styleguide/Components/Preview.js
- styleguide/config.js
- webpack.config.js
В дев-режиме стили обновляются при редактировании без перезагрузки! Также теперь работают сорсмапы.
> Хотрелоад стилей в стайлгайде

- src/components/DatePicker/DatePicker.css
> DatePicker: Allowing month shrinking in case of insufficient container width

- src/components/ChipsSelect/ChipsSelect.css
- src/components/CustomSelect/CustomSelect.css
> Custom and ChipsSelect: moved z-index options upper

- styleguide/Components/Preview.js
1. Пишем в примере код с ошибкой
2. Чиним ошибку
ОР: Пример ожил
ФР: Белый экран в примере
> fix: Восстанавливать пример после ошибки компиляции

- src/components/AppRoot/AppRoot.test.tsx
- src/components/AppRoot/AppRoot.tsx
- src/components/AppRoot/ScrollContext.ts
- src/components/Epic/ScrollSaver.tsx
- src/components/PullToRefresh/PullToRefresh.tsx
- src/components/Root/Root.tsx
- src/components/Tooltip/Readme.md
- src/components/View/View.tsx
- styleguide/Components/PlaygroundRenderer.js
- styleguide/Components/Preview.js
- styleguide/pages/modes.md
- styleguide/setup.js
Поддерживаем 2 режима скролла для `AppRoot embedded`: 
- VKUI встраивается в контентную зону приложения и скроллится вместе с ним
- VKUI живет в отдельном контейнере с независимым скроллом
> feat: Contain scroll to AppRoot

- README.md
- styleguide/pages/hello_world.md
Добавлены обязательные AppRoot, SplitLayout, SplitCol в стайлгайде и README.md репозитория
https://github.com/VKCOM/VKUI/tree/fix/readme_helloworld
> Обновление Hello World в README.md и styleguide

- package.json
- src/components/Avatar/Avatar.css
- src/components/Cell/Cell.css
- src/components/Cell/Cell.tsx
- src/components/CellButton/CellButton.css
- yarn.lock
- `CellButton`: Исправлен фон внутреннего `Avatar`
- `Cell`: в `selectable` для отрисовки маркера используются готоые иконки вместо самописного дизайна
> Cell fixes

- src/components/IconButton/IconButton.test.tsx
- src/components/IconButton/IconButton.tsx
> IconButton: fix ignoring of Component property

- src/components/DatePicker/DatePicker.tsx
> DatePicker: removed monthNames from DOM

- src/components/CustomSelect/CustomSelect.test.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/NativeSelect/NativeSelect.test.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/Select/Select.tsx
> Select: defaultValue fix

- src/components/IconButton/IconButton.css
Фикс цвета кнопки удаления для Removable (android/vkcom).
> IconButton: e2e tests hotfix

- styleguide/pages/installation.md
Оказывается эта ссылка есть и в документации...
> fix(docs): update link to peerDependencies

- e2e/index.ts
- src/components/Search/Search.e2e.tsx
- src/components/Search/Search.test.tsx
- src/components/Search/Search.tsx
- src/components/Search/__image_snapshots__/search-android-bright_light-1-snap.png
- src/components/Search/__image_snapshots__/search-android-space_gray-1-snap.png
- src/components/Search/__image_snapshots__/search-ios-bright_light-1-snap.png
- src/components/Search/__image_snapshots__/search-ios-space_gray-1-snap.png
- src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-1-snap.png
- src/components/Search/__image_snapshots__/search-vkcom-vkcom-1-snap.png
- src/hooks/useEnsuredControl.ts
Нашелся баг, из-за которого можно очистить поле с `value` и без `onChange`, но тут я его чинить не буду (скипнутый тест добавил)
> Search to FunctionComponent

- src/components/ActionSheet/ActionSheet.tsx
- src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
Добавляет возможность передавать в качестве popupDirection функцию. 
Связано с https://github.com/VKCOM/VKUI/issues/1618
> Feature: ActionSheet popupDirection function

- src/components/Gallery/Gallery.tsx
> [Bug] Сломанные рефы в Gallery

- src/components/SliderSwitch/SliderSwitch.test.tsx
- src/components/SliderSwitch/SliderSwitchButton.tsx
> [Bug] SliderSwitch тригерит событие submit

- src/components/Tooltip/Tooltip.e2e.tsx
- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/__image_snapshots__/tooltip-android-bright_light-1-snap.png
- src/components/Tooltip/__image_snapshots__/tooltip-android-space_gray-1-snap.png
- src/components/Tooltip/__image_snapshots__/tooltip-ios-bright_light-1-snap.png
- src/components/Tooltip/__image_snapshots__/tooltip-ios-space_gray-1-snap.png
- src/components/Tooltip/__image_snapshots__/tooltip-vkcom-vkcom-1-snap.png
- src/hooks/useExternRef.ts
Также пометил пропы `onClose, isShown, mode` как необязательные
> Refactor: Tooltip to FC

- src/lib/utils.ts
> hasReactNode: added empty string check

- src/components/Search/Search.css
- src/components/Search/Search.test.tsx
- src/components/Search/Search.tsx
> Search: allow to override input type; set default type as "search"

- src/components/Touch/Touch.test.tsx
- src/components/Touch/Touch.tsx
> fix: Prevent click event on Touch content after slide 

- .eslintrc.json
- src/components/NativeSelect/NativeSelect.tsx
- src/hooks/useExternRef.test.tsx
- src/lib/useIsomorphicLayoutEffect.ts
Если нужно использовать useLayoutEffect, пусть за этим следит машина, я не могу
> infra: Warn on useLayoutEffect

- src/components/DatePicker/DatePicker.tsx
- Добавила прокидывание пропса disabled на child инпуты
> Added disabled prop to datepicker

- src/components/AppRoot/AppRoot.tsx
- src/components/Epic/Epic.tsx
- src/components/FixedLayout/FixedLayout.tsx
- src/components/ModalCard/ModalCard.tsx
- src/components/ModalPage/ModalPage.tsx
- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/ModalRootDesktop.tsx
- src/components/Panel/Panel.tsx
- src/components/Root/Root.tsx
- src/components/Typography/Text/Text.tsx
- src/components/View/View.tsx
- src/components/View/ViewInfinite.tsx
- src/lib/getNavId.test.ts
- src/lib/getNavId.ts
- src/lib/warnOnce.ts
> enhancement: Warn once

- src/components/RangeSlider/UniversalSlider.tsx
> fix: Prevent Slider drag propagation

- src/components/Tooltip/Tooltip.tsx
> enhancement: Warn on incorrect Tooltip usage

- src/components/ChipsSelect/ChipsSelect.tsx
> Fixed closed with enter on Tab

- src/components/ChipsInput/ChipsInput.css
- src/components/ChipsInput/Readme.md
- src/components/ChipsSelect/ChipsSelect.css
- src/components/ChipsSelect/Readme.md
- src/components/FormField/FormField.css
fixes #1708: поправила стили, чтобы длинный `Chip` больше не ломал `ChipsInput` и `ChipsSelect`.
> #1708 Wrap long Chip

- src/components/Banner/Banner.css
- src/components/Banner/Banner.tsx
- src/components/Button/Button.css
У Banner оказалось достаточно много всего, так что я и его вынесла отдельной веткой.
**Что сделала по доступности:**
- Поменяла `<div/>` на `<section/>` в обертке;
- Добавила пропсы `role` и `Component` для `Tappable` внутри баннера;
- Добавила текстовые компоненты вместо `div` для текстового контента баннера;
- Поменяла для кнопки скрытия баннера `<button/>` на `IconButton` и добавила ей `dismissLabel`;
- Добавила `aria-hidden="true"` для бэкграунда.
Дополнительно:
- вынесла обнаружившиеся стили для `Button` в `Button`;
- порефакторила код и подчистила css.
> Доступность: Banner

- src/components/Tooltip/Tooltip.css
- src/components/Tooltip/Tooltip.tsx
- Хвостик при `placement=top | bottom` не заезжает на 2px под плашку
- Позиционирование хвостика переехало в цсс
- Тултип не пытается влезть внутрь шапки
- Использовал для document.onClick наш фирменный хук
> Refactor: причесать Tooltip

- src/components/Banner/Banner.tsx
- src/components/ContentCard/ContentCard.css
- src/components/ContentCard/ContentCard.tsx
- src/components/Counter/Counter.css
- src/components/Counter/Counter.tsx
- src/components/Footer/Footer.css
- src/components/Footer/Footer.tsx
- src/components/Group/Group.css
- src/components/Group/Group.tsx
- src/components/List/List.tsx
- src/components/MiniInfoCell/MiniInfoCell.css
- src/components/MiniInfoCell/MiniInfoCell.tsx
- src/components/Progress/Progress.css
- src/components/Progress/Progress.tsx
- src/components/ScreenSpinner/ScreenSpinner.tsx
- src/components/Separator/Separator.tsx
- src/components/Spacing/Spacing.tsx
- src/components/Spinner/Spinner.css
- src/components/Spinner/Spinner.tsx
- src/components/SubnavigationBar/SubnavigationBar.css
- src/components/SubnavigationBar/SubnavigationBar.tsx
- src/components/SubnavigationButton/SubnavigationButton.tsx
- src/components/WriteBarIcon/WriteBarIcon.tsx
> Доступность: семантическая верстка блочных компонентов, роли и aria

- src/components/CustomSelect/CustomSelect.tsx
> CustomSelect: onClick support

- styleguide/Components/StyleGuide/StyleGuide.js
- styleguide/Components/StyleGuide/StyleGuideHeader.js
- styleguide/Components/TableOfContents/TableOfContents.js
* Редиректы со старых урлов
* Changelog => Релизы
* Предотвращаем отрисовку простыни из всех секций
> Doc updates

- src/components/IconButton/IconButton.e2e.tsx
- src/components/IconButton/__image_snapshots__/iconbutton-android-bright_light-1-snap.png
- src/components/IconButton/__image_snapshots__/iconbutton-android-space_gray-1-snap.png
- src/components/IconButton/__image_snapshots__/iconbutton-ios-bright_light-1-snap.png
- src/components/IconButton/__image_snapshots__/iconbutton-ios-space_gray-1-snap.png
- src/components/IconButton/__image_snapshots__/iconbutton-vkcom-vkcom-1-snap.png
- src/components/SimpleCell/SimpleCell.e2e.tsx
- src/components/SimpleCell/__image_snapshots__/simplecell-android-bright_light-1-snap.png
- src/components/SimpleCell/__image_snapshots__/simplecell-android-space_gray-1-snap.png
- src/components/SimpleCell/__image_snapshots__/simplecell-ios-bright_light-1-snap.png
- src/components/SimpleCell/__image_snapshots__/simplecell-ios-space_gray-1-snap.png
- src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-vkcom-1-snap.png
> Tests (e2e): SimpleCell, IconButton

- src/components/HorizontalScroll/HorizontalScroll.css
- src/components/HorizontalScroll/HorizontalScrollArrow.css
- src/components/HorizontalScroll/HorizontalScrollArrow.tsx
- Переписала `button` внутри `HorizontalScrollArrow` на `Tappable`.
- Поправила классы, чтобы они соответствовали БЭМу.
- Причесала стили.
> Refactor: HorizontalScrollArrow

- src/components/Placeholder/Placeholder.css
Чинит ситуацию, когда в заголовке или тексте компонента случается переполнение по ширине.
> fix(Placeholder): Set inner el max-width

- src/hooks/useKeyboardInputTracker.ts
> useKeyboardInputTracker: fallback to keyCode

- src/components/MiniInfoCell/MiniInfoCell.e2e.tsx
- src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-bright_light-1-snap.png
- src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-space_gray-1-snap.png
- src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-bright_light-1-snap.png
- src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-space_gray-1-snap.png
- src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-vkcom-1-snap.png
- src/components/RichCell/RichCell.e2e.tsx
- src/components/RichCell/__image_snapshots__/richcell-android-bright_light-1-snap.png
- src/components/RichCell/__image_snapshots__/richcell-android-space_gray-1-snap.png
- src/components/RichCell/__image_snapshots__/richcell-ios-bright_light-1-snap.png
- src/components/RichCell/__image_snapshots__/richcell-ios-space_gray-1-snap.png
- src/components/RichCell/__image_snapshots__/richcell-vkcom-vkcom-1-snap.png
- src/components/Tabs/Tabs.e2e.tsx
- src/components/Tabs/__image_snapshots__/tabs-android-bright_light-1-snap.png
- src/components/Tabs/__image_snapshots__/tabs-android-space_gray-1-snap.png
- src/components/Tabs/__image_snapshots__/tabs-ios-bright_light-1-snap.png
- src/components/Tabs/__image_snapshots__/tabs-ios-space_gray-1-snap.png
- src/components/Tabs/__image_snapshots__/tabs-vkcom-vkcom-1-snap.png
> tests(e2e): Скриншотные тесты

- src/components/AppRoot/AppRoot.tsx
- src/components/Root/Root.tsx
- src/components/View/View.tsx
- src/index.ts
fixes #1783 
fixes #1769
fixes #1766
> Small fixes

- .npmignore
гляжу в нод модули а там скриншоты
> infra: Remove tests from npm publish

- src/styles/common.css
- src/styles/components.css
- styleguide/setup.js
- Вынесла внешние стили из `components.css` в отдельный `common.css`,
- Заимпортила `common.css` в нужные места.
> [Bug] External styles are missing in doc

- src/components/Button/Button.css
- src/components/Button/Button.tsx
> [Bug] У `<Button Component="a" />` отличается выравнивание текста

- src/components/Cell/Cell.css
- src/components/CellButton/CellButton.css
- src/components/Checkbox/Checkbox.css
- src/components/FormItem/FormItem.css
- src/components/FormItem/FormItem.e2e.tsx
- src/components/FormItem/FormItem.tsx
- src/components/FormItem/__image_snapshots__/formitem-android-bright_light-1-snap.png
- src/components/FormItem/__image_snapshots__/formitem-android-space_gray-1-snap.png
- src/components/FormItem/__image_snapshots__/formitem-ios-bright_light-1-snap.png
- src/components/FormItem/__image_snapshots__/formitem-ios-space_gray-1-snap.png
- src/components/FormItem/__image_snapshots__/formitem-vkcom-vkcom-1-snap.png
- src/components/FormLayoutGroup/FormLayoutGroup.css
- src/components/Radio/Radio.css
- src/components/Removable/Removable.css
- src/components/RichCell/RichCell.css
- src/components/SimpleCell/SimpleCell.css
- src/styles/constants.css
- раскидала стили в другие компоненты и причесала оставшиеся
- перекинула пропсы и убрала `defaultProps`
- поменяла `withAdaptivity()` на `useAdaptivity()`
- и обновила скриншотные тесты и скрины (пока без `Cell`, раз отступы `Cell` заведомо поломаны)
> [refactor] FormItem

- src/components/Cell/Cell.css
- src/components/Cell/__image_snapshots__/cell-ios-bright_light-1-snap.png
- src/components/Cell/__image_snapshots__/cell-ios-space_gray-1-snap.png
- src/components/FormItem/FormItem.css
- src/components/FormItem/FormItem.tsx
- src/components/FormLayoutGroup/FormLayoutGroup.css
- src/components/FormLayoutGroup/FormLayoutGroup.tsx
- src/components/Removable/Removable.css
- src/components/Removable/Removable.tsx
- переименовала классы, чтобы css был полегче и попроще
- убрала `defaultProps`
- подправила стили кнопок и отступы
- обновила скриншоты для `Cell`
> [refactor] Removable

- src/components/RichCell/RichCell.css
- src/components/RichCell/RichCell.tsx
- прибрала ненужный `.RichCell__top`
- немного причесала css
> [refactor] RichCell

- src/components/RichCell/RichCell.css
Спасибо @eolme за бдительность. 😉 
https://github.com/VKCOM/VKUI/pull/1853#pullrequestreview-744258240
> fix(RichCell): remove unnecessary overflow

- src/components/Alert/Alert.tsx
> Add target prop for actions in Alert

- .github/workflows/publish.yml
... чтобы не держать эту информацию в голове. 😏
>  Publish.yml: clarify tags input syntax

- src/components/ChipsInput/ChipsInput.tsx
- src/components/FormField/FormField.test.tsx
- src/components/FormField/FormField.tsx
- src/components/FormField/Readme.md
- src/components/Input/Input.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/SelectMimicry/SelectMimicry.tsx
- src/components/Textarea/Textarea.tsx
- src/index.ts
- styleguide/config.js
> feat: Export `FormField`

- src/components/FixedLayout/FixedLayout.tsx
> FixedLayout: fixed css classes

- src/components/Search/Search.css
fixes #1867 
Сабж: http://diveintohtml5.info/forms.html. Долистать до search boxes.
Пока не мержим, нужно посмотреть через BrowserStack, рабочий ли фикс.
> Search: fixed Safari 13 bug with input styling

- src/components/Link/Link.css
> Link: removed border-radius

- src/components/AppRoot/AppRoot.tsx
- src/hooks/useInsets.ts
> applying insets on root element

- src/components/ActionSheetItem/ActionSheetItem.css
- пофиксила `z-index`, чтобы `ActionSheetItem` всегда подсвечивался при навигации с клавиатуры,
- пофиксила `border-radius` для iOS, чтобы последний `ActionSheetItem` на десктопе подсвечивался покрасивее
> [Bug] FocusVisible в ActionSheetItem

- src/components/NativeSelect/NativeSelect.e2e.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/NativeSelect/__image_snapshots__/nativeselect-android-bright_light-1-snap.png
- src/components/NativeSelect/__image_snapshots__/nativeselect-ios-bright_light-1-snap.png
- src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-vkcom-1-snap.png
- src/components/Select/Select.css
- src/components/SelectMimicry/SelectMimicry.e2e.tsx
- src/components/SelectMimicry/__image_snapshots__/selectmimicry-android-bright_light-1-snap.png
- src/components/SelectMimicry/__image_snapshots__/selectmimicry-ios-bright_light-1-snap.png
- src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-vkcom-1-snap.png
> [Bug] `multiline` в SelectMimicry

- src/components/HorizontalScroll/HorizontalScroll.tsx
- src/components/SubnavigationBar/SubnavigationBar.tsx
> fix(SubnavigationBar): Pass HorizontalScroll arrow and scrolling props

- package.json
- src/styles/vkcom_light.css
- yarn.lock
> Appearance: 9.27.3 => 9.29.0

- src/components/Touch/Touch.test.tsx
- src/components/Touch/Touch.tsx
Во всех тач-событиях всегда передаем все параметры, даже если это старт или чистый тап
fixes #1444
> fix: Fire full gesture on Touch start / clean tap end

- src/components/HorizontalScroll/HorizontalScrollArrow.css
Предотвращает случайные нажатия на элементы при нажатии на стрелочки
> HorizontallScroll: Prevent click fallthrough

- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/ModalRootContext.tsx
- src/components/ModalRoot/ModalRootDesktop.tsx
- src/components/ModalRoot/types.ts
- src/components/ModalRoot/useModalManager.test.tsx
- src/components/ModalRoot/useModalManager.ts
- src/components/ModalRoot/useModalManager.tsx
1. Умеют переходить во время перехода
2. Модалки можно добавлять динамически
3. Переиспользуют управление переходами между десктопом и тачом
> Новые модалки

- src/components/Search/Search.css
> Search: iOS 15.1 bug fix

- src/components/Card/Readme.md
Size doesn't exist in props of Card, but described on CardGrid component https://vkcom.github.io/VKUI/#/CardGrid
pls)
> Size doesn't exist in props of Card

- src/lib/prefixClass.ts
> [Bug] Убрать лишние пробелы в классах

- src/components/View/View.test.tsx
- src/components/View/View.tsx
- src/components/View/ViewInfinite.tsx
> fix: Flush View transitions if transition motion disabled

- src/components/Cell/Cell.tsx
> [Bug] Не пробрасывается className у компонента Cell

- src/components/Progress/Progress.tsx
> fix(progress): check value range

- src/components/Progress/Progress.tsx
> Progress: fix trailing spaces

- src/components/Removable/Removable.test.tsx
- src/components/Removable/Removable.tsx
> [Bug][Removable] Конфликт слушателей на iOS

- src/components/TabsItem/TabsItem.css
> TabsItem: fixed segmented border-radius

- src/components/Footer/Footer.test.tsx
- src/components/Footer/Footer.tsx
- src/index.ts
> [Feature] Экспорт FooterProps

- styleguide/config.js
> build(docs): fix `VKUI_STYLEGUIDE_PROPSPARSER` check

- src/components/Switch/Switch.css
- src/components/Switch/Switch.tsx
> Switch: fix cursor for disabled state

- src/components/Radio/Radio.css
- src/components/RadioGroup/RadioGroup.css
- src/components/RadioGroup/RadioGroup.e2e.tsx
- src/components/RadioGroup/RadioGroup.test.tsx
- src/components/RadioGroup/RadioGroup.tsx
- src/components/RadioGroup/Readme.md
- src/components/RadioGroup/__image_snapshots__/radiogroup-android-bright_light-1-snap.png
- src/components/RadioGroup/__image_snapshots__/radiogroup-ios-bright_light-1-snap.png
- src/components/RadioGroup/__image_snapshots__/radiogroup-vkcom-vkcom-1-snap.png
- src/index.ts
- src/styles/components.css
- styleguide/config.js
> [Feature] RadioGroup

- src/components/FocusTrap/FocusTrap.tsx
> FocusTrap: SSR fix

- src/components/Tappable/Tappable.tsx
> Pass events to Tappable

- src/components/View/View.tsx
> Fix view marginTop calc

- src/components/CustomSelect/CustomSelect.tsx
> Fix select onChange

- src/hooks/useKeyboard.ts
> Fix useKeyboard

- styleguide/config.js
> Опечатка в документации

- .eslintrc.json
- src/tokenized/tokenized.ts
- tokenized/index.d.ts
- tokenized/package.json
Added entrypoint for components that support vkui-tokens
> Separated entry point for tokenized components

- src/components/HorizontalScroll/HorizontalScroll.tsx
> Fix HorizontalScroll right arrow

- styleguide/Components/Section/SectionRenderer.js
- styleguide/Components/Section/index.js
Чтобы импорт везде соответствовал alias, который мы задаем в конфиге для документации:
https://github.com/VKCOM/VKUI/blob/master/styleguide/webpack.config.js#L14-L18
> docs: fix rgs-components imports

- src/components/ActionSheet/ActionSheet.e2e.tsx
- src/components/ActionSheet/ActionSheet.test.tsx
- src/components/ActionSheetItem/ActionSheetItem.test.tsx
- src/components/ActionSheetItem/ActionSheetItem.tsx
- src/components/FocusTrap/FocusTrap.test.tsx
- src/index.ts
> named export: ActionSheetItem

- src/components/ActionSheet/ActionSheet.test.tsx
- src/components/AdaptivityProvider/AdaptivityProvider.test.tsx
- src/components/AdaptivityProvider/AdaptivityProvider.tsx
- src/components/Alert/Alert.test.tsx
- src/components/Banner/Banner.test.tsx
- src/components/ChipsSelect/ChipsSelect.e2e.tsx
- src/components/DatePicker/DatePicker.test.tsx
- src/components/FocusTrap/FocusTrap.test.tsx
- src/components/HorizontalScroll/HorizontalScroll.e2e.tsx
- src/components/PanelHeaderContext/PanelHeaderContext.test.tsx
- src/components/Tappable/Tappable.test.tsx
- src/index.ts
- src/testing/e2e/utils.tsx
- src/testing/utils.tsx
> named export: AdaptivityProvider

- src/components/Alert/Alert.test.e2e.tsx
- src/components/Alert/Alert.test.tsx
- src/components/Alert/Alert.tsx
- src/index.ts
> named export: Alert

- src/components/AppRoot/AppRoot.test.tsx
- src/components/AppRoot/AppRoot.tsx
- src/components/ChipsSelect/ChipsSelect.e2e.tsx
- src/components/FocusTrap/FocusTrap.test.tsx
- src/components/HorizontalScroll/HorizontalScroll.e2e.tsx
- src/components/ModalCard/ModalCard.e2e.tsx
- src/components/Panel/Panel.e2e.tsx
- src/components/Search/Search.e2e.tsx
- src/components/Textarea/Textarea.e2e.tsx
- src/testing/e2e/utils.tsx
> named export: AppRoot

- src/components/ContentCard/ContentCard.tsx
- src/components/CustomSelectOption/CustomSelectOption.tsx
- src/components/IconButton/IconButton.tsx
- src/components/PromoBanner/PromoBanner.tsx
- src/components/Root/Root.tsx
- src/components/TabbarItem/TabbarItem.tsx
- src/components/View/View.tsx
(Вытаскиваю куски из #2004.)
Добавляем `warnOnce` к тем депрекейтам, где их сейчас нет, чтобы видеть их в консоли.
> [Enhancement] Deprecated warnings

- src/components/Gradient/Gradient.test.tsx
- src/components/Gradient/Gradient.tsx
- src/index.ts
> [refactor] Gradient

- src/components/Chip/Chip.e2e.tsx
- src/components/Chip/Chip.test.tsx
- src/components/Chip/Chip.tsx
- src/components/ChipsInput/ChipsInput.tsx
- src/index.ts
#2191.
(плюс микрофикс небольшой ошибки typescript)
> named export: Chip

- src/components/HorizontalScroll/HorizontalScroll.tsx
- src/components/HorizontalScroll/HorizontalScrollArrow.css
- src/components/HorizontalScroll/HorizontalScrollArrow.tsx
- src/tokenized/index.ts
- styleguide/tokenized.js
> Revert "Перевести на токены HorizontalScrollArrow"

- src/components/HorizontalScroll/HorizontalScroll.tsx
- src/components/HorizontalScroll/HorizontalScrollArrow.css
- src/components/HorizontalScroll/HorizontalScrollArrow.tsx
- src/tokenized/index.ts
- styleguide/tokenized.js
> Revert "Revert "Перевести на токены HorizontalScrollArrow""

- src/components/UsersStack/Readme.md
> UsersStack: example fix

- src/components/Removable/Removable.tsx
> [Bug] Не работает Cell с mode="removable" на ios

- src/components/Footer/Readme.md
> Fix typo in Footer Readme.md

- src/components/CustomSelectOption/CustomSelectOption.tsx
> Fix CustomSelectOption__afterIn className

- src/components/Div/Div.css
- src/components/Div/Div.test.tsx
- src/components/Div/Div.tsx
- src/index.ts
> [refactor] Div

- src/components/GridAvatar/GridAvatar.css
- src/components/GridAvatar/GridAvatar.tsx
Это максимально внезапный пулл-реквест. 🤣 
Момент с [фиксированием длины массива через Typescript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#optional-elements-in-tuple-types) оставим для v5.
> [Enhancement] `GridAvatar`

- .github/workflows/pull_request.yml
This reverts commits:
- 76ad84a5db03f624dc00ca33718315aa45b5ad8c
- 0b2176d858a259292e9859b4c2929a2eeb3a75d2
- 6254d93bd85557ed8092b1a5a7c6c71ee037584d
- fc8d8a2979b5d7df816377074f7e5d3d9ef90003
- f529a5b9fe87bfb033d85effeb1ce46293a3e557
> INFRA: revert merge_master job

- src/components/Header/Header.e2e.tsx
- src/components/Header/Header.tsx
- src/components/Header/__image_snapshots__/header-android-light-1-snap.png
- src/components/Header/__image_snapshots__/header-ios-light-1-snap.png
- src/components/Header/__image_snapshots__/header-vkcom-light-1-snap.png
Есть компонент `HeaderSubtitle`, который меняется в зависимости от `mode`
https://github.com/VKCOM/VKUI/blob/8a5c8c499deac5f5c1bc0c07734c1d7615314c1d/src/components/Header/Header.tsx#L87-L96
Но используя этот компонент, свойство `mode` не прокидывается  внутрь 
https://github.com/VKCOM/VKUI/blob/8a5c8c499deac5f5c1bc0c07734c1d7615314c1d/src/components/Header/Header.tsx#L150-L152
> Fix HeaderSubtitle mode property

- src/index.ts
> Export more props

- src/components/ModalCard/ModalCard.css
- src/components/ModalCardBase/ModalCardBase.css
- src/components/ModalCardBase/ModalCardBase.tsx
Перенес стили для dismiss кнопки из `ModalCard` в `ModalCardBase`.
> Fix ModalCardBase dismiss button style

- styleguide/Components/StyleGuide/StyleGuideMobile.js
`popout` в компоненте `View` устарел
> StyleGuideMobile use SplitLayout

- src/components/Typography/Subhead/Subhead.tsx
**проблема**: [Subhead](https://vkcom.github.io/VKUI/#/Subhead) без свойств имеет класс `vkuiSubhead--w-undefined`
> fix(Subhead): weight=undefined

- src/components/ActionSheet/ActionSheet.test.tsx
- src/components/ActionSheet/ActionSheet.tsx
- src/components/ActionSheet/ActionSheetContext.ts
- src/components/ActionSheet/Readme.md
- src/components/ActionSheetItem/ActionSheetItem.tsx
- src/components/ActionSheetItem/Readme.md
- src/components/Alert/Alert.test.tsx
- src/components/Alert/Alert.tsx
- src/components/Alert/Readme.md
- src/components/FocusTrap/FocusTrap.test.tsx
- src/lib/touch.ts
- styleguide/Components/Setting/Setting.js
f5f0b1f7d BREAKING CHANGE: ActionSheetItem `autoclose` -> `autoClose`
9632d8fbc BREAKING CHANGE: AlertAction `autoclose` -> `autoClose`
6d7a288b7 BREAKING CHANGE: `VKUITouchEventHander` -> `VKUITouchEventHandler`
#1522
> BREAKING CHANGE: fix typo

- src/components/Tappable/Tappable.css
- src/components/Tappable/Tappable.tsx
> fix(Tappable): Set `cursor: pointer` if state is hasHover or hasActive

- src/components/HorizontalScroll/HorizontalScroll.tsx
Добавляет стандартную прокрутку для стрелок, равную `offsetWidth`
This closed #2032
> HorizontalScroll.tsx: default getScrollPosition

- styleguide/Components/Preview.js
Добавил очистку консоли при изменении кода. Чтобы консоль не очищалась, в DevTools есть опция **Preserve log**
> docs(styleguide): Preview add console.clear()

- src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> fix(SegmentedControlOption): hover selector

- src/components/SegmentedControl/SegmentedControl.test.tsx
- src/components/SegmentedControl/SegmentedControl.tsx
> fix(SegmentedControl): update active value

- src/components/TabbarItem/TabbarItem.css
> fix(TabbarItem): remove overflow

- src/hooks/useWaitTransitionFinish.ts
> fix(waitTransitionFinish): check document.hidden

- src/components/CustomSelectOption/CustomSelectOption.css
- src/components/CustomSelectOption/CustomSelectOption.e2e.tsx
- src/components/CustomSelectOption/CustomSelectOption.tsx
- src/components/CustomSelectOption/Readme.md
- src/components/CustomSelectOption/__image_snapshots__/customselectoption-android-light-1-snap.png
- src/components/CustomSelectOption/__image_snapshots__/customselectoption-ios-light-1-snap.png
- src/components/CustomSelectOption/__image_snapshots__/customselectoption-vkcom-light-1-snap.png
1. Добавил параметр `hierarchy`
1. Поправил e2e тесты
1. Добавил `jsdoc` для остальных параметров
1. Поправил немного доку
---
resolve #2373
> feat(CustomSelectOption): add hierarchy prop; docs for other props

- src/components/AdaptivityProvider/AdaptivityProvider.test.tsx
- src/components/AdaptivityProvider/AdaptivityProvider.tsx
- src/hooks/useBridgeAdaptivity.ts
> Add bridge adaptivity

- src/components/GridAvatar/GridAvatar.test.tsx
- src/components/GridAvatar/GridAvatar.tsx
- убрала лишние тесты и поправила тот, что на максимальную длину — теперь он берет `MAX_GRID_LENGTH`, заданную в компоненте
- поправила `aria-hidden`
- немного переформулировала варнинг
> [Refactor] GridAvatar

- src/components/Gallery/Gallery.tsx
> Gallery: add callbacks for arrows

- src/components/Snackbar/Snackbar.css
ограничение в 3 строки (https://github.com/VKCOM/VKUI/issues/767#issuecomment-636064310)
Fixes #767
> fix(Snackbar): content add overflow: hidden

- src/components/Gradient/Gradient.css
https://vkcom.github.io/VKUI/pull/2435/#/Gradient
Fixes #2434
> fix(Gradient): add vkcom_dark

- src/components/ActionSheet/ActionSheet.tsx
- src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
- src/components/AppRoot/AppRoot.tsx
- src/components/ConfigProvider/ConfigProvider.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/Epic/Epic.tsx
- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/useModalManager.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Typography/Text/Text.tsx
- src/lib/getNavId.ts
> Перевод англоязычных варнингов на русски

- src/components/NativeSelect/NativeSelect.e2e.tsx
- src/components/NativeSelect/NativeSelect.test.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/Select/Select.tsx
- src/index.ts
> named export: NativeSelect

- src/components/AppRoot/AppRoot.tsx
- styleguide/Components/Frame/Frame.js
- styleguide/Components/StyleGuide/StyleGuideRenderer.js
Добавляем `color-scheme` на документ для окрашивания скроллбаров и прочего
> feat(ConfigProvider): add color-scheme

- src/components/ModalRoot/Readme.md
- src/components/PanelHeader/Readme.md
- src/components/Tooltip/Readme.md
- styleguide/Components/Playground/PlaygroundRenderer.js
- styleguide/Components/Settings/Settings.js
- styleguide/Components/Settings/WebviewTypeSelect.js
- styleguide/Components/StyleGuide/StyleGuideRenderer.js
<details>
<summary>Оригинальное ошибочное описание</summary>
**Проблема**
С версии v4.27.2 был установлен webviewType = WebviewType. VKAPPS по умолчанию. Это изменение ломает [PanelHeader](https://vkcom.github.io/VKUI/#/PanelHeader), если там была правая часть.
В документации у нас сказано:
> Правая часть шапки будет скрыта, если в ConfigProvider передан webviewType={WebviewType.VKAPPS}
Это подразумевает, что мы должны передавать `webviewType={WebviewType.VKAPPS}` чтобы отключить правую часть. Но с версии v4.27.2 правая часть уже отключена по умолчанию.
Также из-за этого сломался пример [Tooltip](https://vkcom.github.io/VKUI/#/Tooltip)
https://github.com/VKCOM/VKUI/commit/88324d35d2d40f48d34bf736fc6368ea4b062843#diff-625a867faf94f7db1ee0b746011668f6c750c6efc3a297fe6399b2f1c3c0099eR68 …
> docs: add webviewType setting

- src/components/DateInput/DateInput.tsx
https://vkcom.github.io/VKUI/#/DateInput
При клике по заполненному ному полю не открывается календарь
> Fix DateInput onHeaderChange

- package.json
- src/components/CardScroll/__image_snapshots__/cardscroll-ios-light-1-snap.png
- src/components/Cell/Cell.css
- src/components/Cell/__image_snapshots__/cell-ios-light-1-snap.png
- src/components/CellButton/CellButton.css
- src/components/Checkbox/Checkbox.css
- src/components/FormItem/FormItem.css
- src/components/FormLayoutGroup/FormLayoutGroup.css
- src/components/Radio/Radio.css
- src/components/RadioGroup/RadioGroup.css
- src/components/Removable/Removable.css
- src/components/RichCell/RichCell.css
- src/components/SimpleCell/SimpleCell.css
- src/styles/constants.css
- yarn.lock
> feat: replace --formitem_padding

- jest.unit.config.js
- package.json
- postcss-custom-properties-fallback/__tests__/customPropertiesFallback.test.js
- postcss-custom-properties-fallback/__tests__/custom_properties.css
- postcss-custom-properties-fallback/index.js
- postcss.config.js
- tsconfig.json
- yarn.lock
> Add custom-properties-fallback plugin

- src/components/SegmentedControl/SegmentedControl.css
- src/components/SegmentedControl/SegmentedControl.e2e.tsx
- src/components/SegmentedControl/SegmentedControl.tsx
- src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
- src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-android-light-1-snap.png
- src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-ios-light-1-snap.png
- src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-light-1-snap.png
> SegmentedControl: add compact styles

- src/components/CardGrid/Readme.md
- src/components/Group/Group.tsx
- src/components/ModalPageHeader/ModalPageHeader.tsx
- src/components/PanelHeader/PanelHeader.tsx
- src/components/Search/Search.tsx
- src/components/Separator/Readme.md
- src/components/Separator/Separator.css
- src/components/Separator/Separator.test.tsx
- src/components/Separator/Separator.tsx
- src/components/Spacing/Readme.md
- src/components/Spacing/Spacing.css
- src/components/Spacing/Spacing.tsx
- src/index.ts
> Deprecate Separator

- src/components/ActionSheetItem/ActionSheetItem.tsx
- src/components/Alert/Alert.tsx
- src/components/Banner/Banner.tsx
- src/components/Button/Button.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/FormStatus/FormStatus.tsx
- src/components/Header/Header.tsx
- src/components/InfoRow/InfoRow.tsx
- src/components/ModalCardBase/ModalCardBase.tsx
- src/components/PanelHeaderContent/PanelHeaderContent.tsx
- src/components/Placeholder/Placeholder.tsx
- src/components/Radio/Radio.tsx
- src/components/Search/Search.tsx
- src/components/Select/Select.tsx
- src/components/SimpleCell/SimpleCell.tsx
- src/components/Switch/__image_snapshots__/switch-android-light-1-snap.png
- src/components/TabsItem/TabsItem.tsx
- src/components/Typography/Headline/Headline.css
- src/components/Typography/Headline/Headline.e2e.tsx
- src/components/Typography/Headline/Headline.tsx
- src/components/Typography/Headline/Readme.md
- src/components/Typography/Headline/__image_snapshots__/headline-android-light-1-snap.png
- src/components/Typography/Headline/__image_snapshots__/headline-ios-light-1-snap.png
- src/components/Typography/Headline/__image_snapshots__/headline-vkcom-light-1-snap.png
- src/index.ts
- src/tokenized/index.ts
- styleguide/Components/Heading/HeadingRenderer.js
- styleguide/Components/Setting/Setting.js
- styleguide/tokenized.js
Добавлены новые свойства
- `weight?: "1" | "2" | "3"`
- `level?: "1" | "2"`
---
---
Компоненты которые имеют Headline внутри
- [ActionSheetItem](https://vkcom.github.io/VKUI/pull/2502/#/ActionSheet) ([master](https://vkcom.github.io/VKUI/#/ActionSheet))
- [Alert](https://vkcom.github.io/VKUI/pull/2502/#/Alert) ([master](https://vkcom.github.io/VKUI/#/Alert))
- [Banner](https://vkcom.github.io/VKUI/pull/2502/#/Banner) ([master](https://vkcom.github.io/VKUI/#/Banner))
- [Button](https://vkcom.github.io/VKUI/pull/2502/#/Button) ([master](https://vkcom.github.io/VKUI/#/Button))
- [Checkbox](https://vkcom.github.io/VKUI/pull/2502/#/Checkbox) ([master](https://vkcom.github.io/VKUI/#/Checkbox))
- …
> feat(Headline): add vkui-tokens

- src/components/AdaptivityProvider/AdaptivityContext.tsx
- src/components/AdaptivityProvider/AdaptivityProvider.test.tsx
- src/components/AdaptivityProvider/AdaptivityProvider.tsx
- src/components/Tappable/Tappable.css
- src/components/Tappable/Tappable.tsx
- src/helpers/getHoverClassName.test.ts
- src/helpers/getHoverClassName.ts
- src/styles/customMedia.css
> Move deviceHasHover to css

- src/components/File/File.css
- src/components/File/File.test.tsx
- src/components/File/File.tsx
- src/components/File/Readme.md
- src/index.ts
- src/styles/components.css
- src/tokenized/index.ts
- styleguide/tokenized.js
Посмотрела я на `File` и решила, что пора его причесать.
> [refactor] File

- postcss.config.js
- src/styles/themes.css
> fix: add onlyVariablesLocal.css for vkBase

- src/components/NavTransitionContext/NavTransitionContext.tsx
- src/index.ts
> feat: Экспортировать useNavTransition 

- src/components/SegmentedControl/SegmentedControl.css
- src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-android-light-1-snap.png
- src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-ios-light-1-snap.png
- src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-light-1-snap.png
> fix(SegmentControl): compact height

- src/tokenized/index.ts
- styleguide/tokenized.js
> bug(DateInput): Отметить DateInput как токенизированный

- src/tokenized/index.ts
- styleguide/tokenized.js
> bug(DateRangeInput): Отметить DateRangeInput как токенизированный

- src/components/Alert/Alert.tsx
- src/hooks/useWaitTransitionFinish.ts
- использован useWaitTransitionFinish
resolve #2453
> refactor: Alert to FC

- .github/workflows/publish.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_screens.yml
- package.json
- src/components/ModalRoot/ModalRoot.test.tsx
- yarn.lock
> ci: update node version

- package.json
- yarn.lock
> TypeError: message.split is not a function
- Нужно для обновления #2620
> deps: react-styleguidist@^11.2.0

- src/components/PanelSpinner/PanelSpinner.test.tsx
- src/components/PanelSpinner/PanelSpinner.tsx
- src/index.ts
- src/tokenized/index.ts
- styleguide/tokenized.js
> feat(PanelSpinner): tokenized

- src/components/Cell/Cell.tsx
- src/components/Cell/useDraggable.tsx
- src/components/Removable/Removable.tsx
> bug(Cell): В Cell не работает getRootRef

- src/components/SplitCol/SplitCol.css
- src/components/SplitCol/SplitCol.tsx
> BREAKING CHANGE: SplitCol set top: 0

- src/components/CalendarHeader/CalendarHeader.tsx
> Force sizeX=compact for CalendarHeader

- src/components/PullToRefresh/PullToRefresh.css
- src/components/PullToRefresh/PullToRefresh.tsx
- src/components/PullToRefresh/PullToRefreshSpinner.tsx
- src/tokenized/index.ts
- styleguide/tokenized.js
> feat(PullToRefresh): Tokenize

- postcss.config.js
Временно отключаем postcss-plugin-vk-sans до полноценного внедрения vk-sans-text в проект
Link #2448
> Disable postcss-plugin-vk-sans

- src/hooks/useKeyboard.ts
- isPrecise нигде не используется
> fix(useKeyboard): remove isPrecise

- src/components/PullToRefresh/PullToRefresh.css
- src/components/PullToRefresh/PullToRefresh.tsx
> fix: remove .PullToRefresh--android

- src/components/Typography/Footnote/Footnote.css
- src/components/Typography/Footnote/Footnote.e2e.tsx
- src/components/Typography/Footnote/Footnote.tsx
- src/components/Typography/Footnote/Readme.md
- src/components/Typography/Footnote/__image_snapshots__/footnote-android-light-1-snap.png
- src/components/Typography/Footnote/__image_snapshots__/footnote-ios-light-1-snap.png
- src/components/Typography/Footnote/__image_snapshots__/footnote-vkcom-light-1-snap.png
- src/index.ts
- src/styles/components.css
- src/tokenized/index.ts
- styleguide/config.js
- styleguide/tokenized.js
> feat: add Footnote

- src/components/CustomScrollView/CustomScrollView.tsx
- src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
> refactor: CustomScrollView to FC

- src/components/PullToRefresh/PullToRefresh.test.tsx
- src/components/PullToRefresh/PullToRefresh.tsx
- src/components/PullToRefresh/PullToRefreshSpinner.tsx
- src/components/PullToRefresh/Readme.md
- src/hooks/usePrevious.ts
- src/index.ts
- src/tokenized/index.ts
> refactor: PullToRefresh to FC

- src/components/Tappable/Tappable.tsx
https://user-images.githubusercontent.com/14944123/171907300-3e061739-9a0b-4f40-a4fc-12a0b0eca90e.mov
> fix(Tappable): cleaning wave

- src/components/FixedLayout/FixedLayout.css
- src/components/FixedLayout/FixedLayout.test.tsx
- src/components/FixedLayout/FixedLayout.tsx
- src/components/PanelHeader/PanelHeader.tsx
- src/components/PanelHeaderContext/PanelHeaderContext.tsx
- src/components/PullToRefresh/PullToRefresh.tsx
- src/index.ts
- src/tokenized/index.ts
- styleguide/tokenized.js
---
- https://github.com/VKCOM/VKUI/issues/2191
- Close #2539
> feat(FixedLayout): tokenized

- README.md
- styleguide/pages/intro.md
> docs: add discussions link

- .github/danger/dangerfile.js
Ссылка ведёт на https://github.com/VKCOM/VKUI/actions?query=workflow%3A"Update+screenshots"
https://user-images.githubusercontent.com/5850354/172634515-fcbcb409-cdb9-4f32-936d-c81bee069d81.mov
Ссылка ведёт на https://github.com/VKCOM/VKUI/actions/workflows/update_screens.yml
> chore(ci): fix `updateScreensActionLink`

- src/components/FocusTrap/FocusTrap.test.tsx
- src/components/Root/Root.test.tsx
- src/components/View/View.css
- src/components/View/View.test.tsx
- src/components/View/View.tsx
- src/index.ts
- src/testing/e2e/utils.tsx
- src/tokenized/index.ts
- styleguide/tokenized.js
> feat(View): tokenized

- src/components/HorizontalScroll/HorizontalScroll.tsx
Анимация прокрутки не может завершится из-за дробных чисел в размерах
- fix #2078
- fix #1441
> fix(HorizontalScroll): add animation timeout

- styleguide/Components/StyleGuide/StyleGuideRenderer.js
> bug(DOC): Add useCallback dependency for color scheme callback

- src/components/GridAvatar/GridAvatar.tsx
- src/tokenized/index.ts
> feat(GridAvatar): tokenized

- src/components/Snackbar/Snackbar.css
> Fix tertiary Button in Snackbar

- src/components/PopoutWrapper/PopoutWrapper.css
- src/components/PopoutWrapper/PopoutWrapper.tsx
- src/tokenized/index.ts
> feat(PopoutWrapper): tokenized

- src/components/Spacing/Spacing.css
- src/components/Spacing/Spacing.tsx
- src/tokenized/index.ts
> feat(Spacing): tokenized

- src/components/ScreenSpinner/Icon48CancelCircle.tsx
- src/components/ScreenSpinner/Icon48DoneOutline.tsx
- src/components/ScreenSpinner/Readme.md
- src/components/ScreenSpinner/ScreenSpinner.css
- src/components/ScreenSpinner/ScreenSpinner.tsx
- src/tokenized/index.ts
---
- Добавлены новые состояния
- Обновлен пример
- #2191
- closed #2571
> feat(ScreenSpinner): tokenized

- src/components/ActionSheet/ActionSheet.tsx
- src/components/CardGrid/CardGrid.tsx
- src/components/MiniInfoCell/MiniInfoCell.tsx
- src/components/Snackbar/Snackbar.tsx
- src/components/SubnavigationButton/SubnavigationButton.tsx
Решила, что остатков совсем мало, так что можно одним махом их убабахать.
Fixes #1586.
> refactor: remove `defaultProps` from FCs

- src/components/Typography/Title/Title.tsx
> fix(Title): `level` set optional

- src/components/ActionSheet/ActionSheet.tsx
- src/components/CardGrid/CardGrid.tsx
- src/components/ScreenSpinner/Icon48CancelCircle.tsx
- src/components/ScreenSpinner/Icon48DoneOutline.tsx
- src/components/ScreenSpinner/Readme.md
- src/components/ScreenSpinner/ScreenSpinner.css
- src/components/ScreenSpinner/ScreenSpinner.tsx
- src/components/Snackbar/Snackbar.tsx
- src/components/SubnavigationButton/SubnavigationButton.tsx
- src/tokenized/index.ts
Ветка для добавление новой функциональности
> chore: new develop branch v4.34.0

- src/components/ModalCard/ModalCard.css
> fix(ModalCard): translateY add 16px

- src/components/WriteBar/WriteBar.tsx
> fix(WriteBar): Убирать scroll, пока не достигнуто значение max-height

- src/components/ModalRoot/ModalRoot.tsx
Чинит скролл, если модалка уже раскрыта
> Fix modal scroll

- src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
- src/components/Popper/Popper.tsx
> fix(CustomSelectDropdown): Перерасчет расположения выпадающего меню в CustomSelect

- src/components/CustomScrollView/CustomScrollView.css
- src/components/CustomScrollView/CustomScrollView.tsx
- src/components/CustomScrollView/useTrackerVisibility.ts
- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelect/Readme.md
- src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
> [Feature][CustomScrollView] Добавить возможность скрывать scrollbar

- postcss.config.js
> fix adding fallback values for css custom properties

- src/components/FixedLayout/FixedLayout.css
> fix(FixedLayout): add platform indent

- .github/workflows/publish.yml
- .github/workflows/pull_request.yml
> ci: use JamesIves/github-pages-deploy-action@v4

- src/components/SubnavigationButton/SubnavigationButton.e2e.tsx
- src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-android-light-1-snap.png
- src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-ios-light-1-snap.png
- src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-light-1-snap.png
> e2e(SubnavigationButton): add screenshot tests

- .github/workflows/pr_close.yml
- .github/workflows/publish.yml
- .github/workflows/pull_request.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
> ci: add concurrency

- .eslintignore
- .github/workflows/publish.yml
- .github/workflows/pull_request.yml
- .gitignore
- .npmignore
- .prettierignore
- styleguide/config.js
Меняем папку `docs` на `styleguide-build`
> chore: styleguide change build folder

- src/components/Button/Button.css
Не уехал из-за конфликта со скриншотами(см #2836)
> fix(Button): remove transform

- src/components/ConfigProvider/ConfigProvider.test.tsx
- src/helpers/getScheme.ts
- src/helpers/scheme.ts
> fix(ConfigProvider): check `scheme === undefined`

- styleguide/Components/StyleGuide/StyleGuideRenderer.js
> docs: fix transitionMotionEnabled

- src/components/BaseGallery/BaseGallery.tsx
- src/components/HorizontalScroll/HorizontalScroll.e2e.tsx
- src/components/HorizontalScroll/HorizontalScroll.tsx
- src/components/HorizontalScroll/HorizontalScrollArrow.css
- src/components/HorizontalScroll/HorizontalScrollArrow.tsx
- src/components/HorizontalScroll/Readme.md
- src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-light-w_2-1-snap.png
- src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-has-arrows-on-mouse-hover-1-snap.png
`HorizontalScrollArrow`
* добавил `size`
* поправил значение в `opacity` при наведении на токен
* добавил пропущенный селектор `HorizontalScrollArrow--ios`
---
---
- close #2842
> feat(HorizontalScroll): add `arrowSize` prop

- src/components/AppRoot/AppRoot.tsx
- src/components/AppRoot/AppRootContext.ts
- src/components/AppRoot/AppRootPortal.tsx
> Add ability to disable portals in the app

- .github/gitflow/patch.js
- .github/gitflow/stable_branch.js
- .github/gitflow/utils.js
- .github/workflows/pr_close.yml
- .github/workflows/publish.yml
Обернул пуш стабильной ветки в `try...catch`, чтобы не зафейлился релиз
> ci(patch): catch push error

- src/components/Cell/Cell.css
- src/components/Cell/Cell.tsx
- src/components/Cell/__image_snapshots__/cell-android-light-1-snap.png
- src/components/Cell/__image_snapshots__/cell-ios-light-1-snap.png
- src/components/Cell/__image_snapshots__/cell-vkcom-light-1-snap.png
- src/components/List/List.tsx
- src/components/Removable/Removable.css
- src/components/Removable/Removable.tsx
- src/tokenized/index.ts
> feat(Cell, Removable): Tokenize

- src/helpers/scheme.ts
https://user-images.githubusercontent.com/14944123/179728160-8b800c73-aeaa-4e6d-8823-d740e79b50ad.mov
> fix(ConfigProvider): nested appearance

- src/components/CustomSelect/Readme.md
- styleguide/setup.js
- styleguide/utils.js
Fixes #2671.
Плюс подправила пример асинхронной загрузки списка и снова немного перетасовала организацию кода в целом, чтобы было полегче читать примеры в принципе.
п.с. Смотреть лучше по коммитам. 😉
> [Docs] Фикс примеров `CustomSelect`

- src/components/Search/Search.css
- src/components/Search/__image_snapshots__/search-android-light-1-snap.png
- src/components/Search/__image_snapshots__/search-ios-light-1-snap.png
- src/components/Search/__image_snapshots__/search-vkcom-light-1-snap.png
> fix-search-styles

- src/components/AppRoot/AppRoot.tsx
> Fix removing of vkui class in react 18

- src/components/Popper/Popper.css
- src/components/Popper/Popper.tsx
- src/components/PopperArrow/PopperArrow.css
- src/components/PopperArrow/PopperArrow.tsx
- src/components/RichTooltip/RichTooltip.css
- src/components/RichTooltip/RichTooltip.tsx
- src/components/TextTooltip/TextTooltip.css
- src/components/TextTooltip/TextTooltip.tsx
- src/components/Tooltip/Readme.md
- src/components/Tooltip/Tooltip.css
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/__image_snapshots__/tooltip-android-light-1-snap.png
- src/components/Tooltip/__image_snapshots__/tooltip-ios-light-1-snap.png
- src/components/Tooltip/__image_snapshots__/tooltip-vkcom-light-1-snap.png
- src/styles/components.css
- src/tokenized/index.ts
- styleguide/Components/Frame/Frame.js
- styleguide/Components/Preview.js
> feat(Tooltip, TextTooltip, RichTooltip): Tokenize

- src/components/SplitCol/SplitCol.css
Исправляет отступы для выравнивания WriteBar
> fix(SplitCol): Заменить padding на margin

- src/components/Epic/Epic.tsx
- src/tokenized/index.ts
> feat(Epic): tokenized

- src/components/ChipsSelect/ChipsSelect.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
> fix ChipsSelect dropdown position when chips change

- src/components/ScreenSpinner/ScreenSpinner.css
> fix(ScreenSpinner): Add token fallback

- src/components/AppRoot/AppRoot.tsx
- src/components/ChipsSelect/ChipsSelect.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
- src/components/SplitCol/SplitCol.css
- src/hoc/withAdaptivity.tsx
- src/hoc/withContext.tsx
- src/hoc/withPlatform.tsx
git cherry-pick f8b09b7a6e2491ba500ce3dde1941e55c6784dbf e9ed1b732768c1e865727c1e48bfee21881b7ff5 72a28dcdbe09ae8af1fc9c54f954e055c5985ffb 3161f449acc33b63a8ab8471ada8489b6c073068
> stable: cherry-pick 4.34.1

- src/components/ConfigProvider/ConfigProviderContext.tsx
- src/components/SplitCol/SplitCol.tsx
- src/components/View/Readme.md
- src/components/View/View.tsx
> refactor(View): use FC

- src/components/AppRoot/AppRoot.tsx
- src/components/Button/Button.tsx
- src/components/ChipsSelect/ChipsSelect.tsx
- src/components/HorizontalScroll/HorizontalScroll.tsx
- src/components/Input/Input.tsx
- src/components/ModalCardBase/ModalCardBase.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/Panel/Panel.tsx
- src/components/PanelHeader/PanelHeader.tsx
- src/components/Radio/Radio.tsx
- src/components/RangeSlider/UniversalSlider.tsx
- src/components/Select/Select.tsx
- src/components/SelectMimicry/SelectMimicry.tsx
- src/components/SimpleCell/SimpleCell.tsx
- src/components/Textarea/Textarea.tsx
> fix: add displayName

- .github/gitflow/patch.js
- .github/gitflow/utils.js
> ci(patch): add comment about conflict

- src/components/ChipsSelect/__image_snapshots__/chipsselect-scrolls-to-item-via-arrows-1-snap.png
Забыл здесь скриншот обновить #2914
- related #2911
> fix(CustomScrollView): update screenshot

- src/components/CustomSelect/CustomSelect.tsx
> rewrite CustomSelect to FC

- src/components/Popper/Popper.tsx
> fix(RichTooltip, Popper): Исправить зависание при sameWidth=true

- src/components/Snackbar/Readme.md
- src/components/Snackbar/Snackbar.css
- src/components/Snackbar/Snackbar.tsx
- src/tokenized/index.ts
> feat(Snackbar): Tokenize

- src/components/Group/Readme.md
(cherry picked from commit cec8be506e05b4dc3c94996dbd25e2a4549ad096)
Стоило навесить `patch` на PR 😞
> docs(Group): fix typo

- src/components/SimpleCell/SimpleCell.e2e.tsx
- src/components/Switch/Switch.css
Исправление конфликта патча из #2929
> fix(Switch): margin in <SimpleCell before={...} />

- .browserslistrc
- README.md
> Up android version to 5

- postcss.config.js
Поправил регулярку в `shouldTransformableDecl()`, который принимает самописный postcss плагин `custom-properties-fallback`
---
- fix #2897
- related #2489
> tech(postcss): fix shouldTransformableDecl()

- src/components/MiniInfoCell/MiniInfoCell.css
- src/components/MiniInfoCell/MiniInfoCell.tsx
Похоже, что с момента токенизации поменялся дизайн 😿 
Вношу актуальные правки:
- замена Text на Paragraph
- теперь другой токен для иконки
- токены для цвета текста в `mode=add` и `mode=more`
> fix(MiniInfoCell): Исправляем токены

- src/components/ChipsSelect/ChipsSelect.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelectOption/CustomSelectOption.tsx
> remove option from CustomSelectOption

- src/components/HorizontalScroll/HorizontalScroll.e2e.tsx
- src/components/HorizontalScroll/HorizontalScrollArrow.tsx
- src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-light-w_3-1-snap.png
- src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-has-arrows-on-mouse-hover-1-snap.png
> fix(HorizontalScroll): Change icon

- src/components/Alert/Alert.css
- src/components/Alert/Alert.tsx
- src/components/Alert/Readme.md
- src/components/Alert/__image_snapshots__/alert-android-light-1-snap.png
- src/tokenized/index.ts
> feat(Alert): tokenized

- src/components/ChipsInput/ChipsInput.css
- src/components/DateInput/DateInput.css
- src/components/DateRangeInput/DateRangeInput.css
- src/components/FormField/FormField.css
- src/components/FormItem/FormItem.css
- src/components/FormLayoutGroup/FormLayoutGroup.css
- src/components/FormLayoutGroup/FormLayoutGroup.e2e.tsx
- src/components/FormLayoutGroup/FormLayoutGroup.tsx
- src/components/FormLayoutGroup/Readme.md
- src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-light-1-snap.png
- src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-light-1-snap.png
- src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-light-1-snap.png
- src/components/Input/Input.css
- src/components/Select/Select.css
- src/components/Textarea/Textarea.css
Добавляем свойство склейки полей для `FormLayoutGroup`
- closed #2868
> feat(FormLayoutGroup): add `segmented`

- src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
- src/components/Popper/Popper.tsx
> fix popper modifiers

- src/components/CustomSelect/CustomSelect.tsx
> Fix CustomSelect change event

- styleguide/Components/StyleGuide/StyleGuideRenderer.js
- styleguide/utils/index.js
- styleguide/utils/useViewPortSize.js
> Fix anchor link in docs

- src/components/Alert/__image_snapshots__/alert-android-light-1-snap.png
- src/components/Alert/__image_snapshots__/alert-vkcom-light-1-snap.png
- src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-light-w_3-1-snap.png
- src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-light-w_3-1-snap.png
- src/components/ModalCard/__image_snapshots__/modalcard-vkcom-light-1-snap.png
- src/components/ModalDismissButton/ModalDismissButton.css
- src/components/ModalDismissButton/ModalDismissButton.tsx
- src/components/ModalPage/ModalPage.tsx
- src/components/ModalRoot/Readme.md
- src/tokenized/index.ts
> feat(ModalDismissButton): Tokenize

- src/components/Panel/Panel.css
- src/components/Panel/Panel.e2e.tsx
- src/components/Panel/Panel.tsx
- src/components/PanelHeader/PanelHeader.css
- src/components/PanelHeader/PanelHeader.tsx
- src/components/PanelHeaderBack/PanelHeaderBack.tsx
- src/components/PanelHeaderButton/PanelHeaderButton.css
- src/components/PanelHeaderButton/PanelHeaderButton.tsx
- src/components/PanelHeaderClose/PanelHeaderClose.tsx
- src/components/PanelHeaderContent/PanelHeaderContent.css
- src/components/PanelHeaderContent/PanelHeaderContent.tsx
- src/components/PanelHeaderContext/PanelHeaderContext.css
- src/components/PanelHeaderContext/PanelHeaderContext.tsx
- src/components/PanelHeaderContext/Readme.md
- src/components/PanelHeaderEdit/PanelHeaderEdit.tsx
- src/components/PanelHeaderSubmit/PanelHeaderSubmit.tsx
- src/tokenized/index.ts
---
- resolve #2558
- resolve #1555 
---
Не стала делать правки с типографическими элементами (непонятно, что там с токенами шрифтов), в целом только на существующие appearance токены были сделаны соответствующие vkui tokens
> feat(Panel, PanelHeader): Tokenize

- src/lib/platform.ts
> catch exception at getPlatformByQueryString

- src/components/Header/Header.css
- src/components/Header/Header.tsx
- src/tokenized/index.ts
> add vkui-tokens to Header

- src/components/Group/Group.css
- src/components/Group/Group.tsx
- src/components/Separator/Separator.css
> Fix Group separator

- src/components/PanelHeader/PanelHeader.css
- src/components/PanelHeaderContent/PanelHeaderContent.css
- src/components/PanelHeaderContent/PanelHeaderContent.tsx
- src/components/Typography/Headline/Headline.css
- src/components/Typography/Text/Text.css
> fix(PanelHeader, PanelHeaderContent): Fix 0 padding for VKCOM platform + fix text ellipsis

- src/components/Spacing/Readme.md
- src/components/Spacing/Spacing.css
> fix(Spacing): separator top/bottom

- src/components/SubnavigationBar/SubnavigationBar.css
- src/components/SubnavigationBar/SubnavigationBar.tsx
- src/components/SubnavigationButton/SubnavigationButton.css
- src/tokenized/index.ts
> feat(SubnavigationBar): tokenized

- src/components/Header/Header.css
- src/components/Header/Header.e2e.tsx
#3026 не смержился автоматически https://github.com/VKCOM/VKUI/runs/7921312697?check_suite_focus=true 😭
> fix(Header): check is int indicator for color of `mode="secondary"`

- src/components/PromoBanner/PromoBanner.css
- src/components/PromoBanner/PromoBanner.tsx
- src/tokenized/index.ts
> feat(PromoBanner): Tokenize

- src/components/SubnavigationBar/Readme.md
- src/components/SubnavigationButton/Readme.md
- src/components/SubnavigationButton/SubnavigationButton.e2e.tsx
- src/components/SubnavigationButton/SubnavigationButton.tsx
> change SubnavigationButton textLevel type

- src/components/MiniInfoCell/MiniInfoCell.css
- src/components/MiniInfoCell/MiniInfoCell.e2e.tsx
- src/components/MiniInfoCell/MiniInfoCell.tsx
- src/components/MiniInfoCell/Readme.md
Note: оставила один проп `textWrap`, вместо двух буликов `multiline` и `lineClamp` 
---
- resolve #2696
> feat(MiniInfoCell): Привести в соответствие с дизайном

- src/components/Search/Search.css
> apply vkui-tokens to Search

- src/components/DateInput/DateInput.tsx
- src/components/DateInput/Readme.md
- src/components/DateRangeInput/DateRangeInput.tsx
- src/components/DateRangeInput/Readme.md
> add option to disable calendar in DateInput/DateRangeInput

- src/components/AppRoot/AppRoot.tsx
- src/components/Avatar/Avatar.tsx
- src/components/CalendarDay/CalendarDay.tsx
- src/components/CardScroll/CardScroll.tsx
- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/ModalRootDesktop.tsx
- src/components/SliderSwitch/SliderSwitch.tsx
- src/components/SliderSwitch/SliderSwitchButton.tsx
- src/components/SubnavigationButton/SubnavigationButton.tsx
- src/components/Tappable/Tappable.tsx
- src/components/View/ViewInfinite.tsx
Добиваем оставшиеся `no-object-expression-in-arguments`
> fix: no-object-expression-in-arguments

- src/components/Cell/CellCheckbox/CellCheckbox.css
- src/components/Cell/CellDragger/CellDragger.css
- src/components/TabsItem/TabsItem.css
- styleguide/Components/StyleGuide/StyleGuideHeader.css
- styleguide/Components/StyleGuide/StyleGuideRenderer.css
> feat: more vkui-tokens

- src/components/Tabs/__image_snapshots__/tabs-android-light-1-snap.png
- src/components/Tabs/__image_snapshots__/tabs-ios-light-1-snap.png
- src/components/Tabs/__image_snapshots__/tabs-vkcom-light-1-snap.png
> CHORE: Update screenshots tabs

- src/components/FixedLayout/FixedLayout.css
- src/components/ModalRoot/ModalRoot.css
- src/components/Panel/Panel.css
- src/components/SplitLayout/SplitLayout.css
- добавила panel-header токен для всех компонентов, в которых он использовался (`FixedLayout`/`ModalRoot`/`Panel`/`SplitLayout`)
- поправила верстку в `PanelHeader`
> feat: Доработки по PanelHeader

- src/components/UsersStack/UsersStack.tsx
> feat(UsersStack): add `count`

- package.json
- yarn.lock
Этот пакет нигде не используется
> chore: remove classnames

- styleguide/pages/migration_v5.md
> update migration guide

- src/components/View/View.test.tsx
- src/components/View/View.tsx
> fix(View): remove modal blur

- src/components/Header/Header.css
> use vkui-tokens for Header paddings

- src/components/VisuallyHiddenInput/VisuallyHiddenInput.tsx
- src/index.ts
> feat(VisuallyHiddenInput): add export

- src/components/Popover/Popover.module.css
- src/components/Popover/Popover.tsx
- src/components/Popover/Readme.md
- src/styles/unstable.css
- src/tokenized/index.ts
- src/unstable/index.ts
- styleguide/config.js
- styleguide/pages/migration_v5.md
> Переименовал `Dropdown` в `Popover`

- src/components/BaseGallery/BaseGallery.tsx
- src/components/Gallery/Gallery.tsx
> fix(BaseGallery): Исправить прыгающий скролл при изменении элементов

- src/components/ChipsSelect/ChipsSelect.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelectOption/CustomSelectOption.tsx
This reverts commit 2cc807454dac419f338a037c1a908ddaef264e6d.
- closes #3145
> Revert "remove option from CustomSelectOption"

- src/components/ChipsSelect/ChipsSelect.tsx
У ChipsSelect отсутствует свойство `forceDropdownPortal`, которое есть у Select
> fix(ChipsSelect): add `forceDropdownPortal`

- src/components/Tabs/__image_snapshots__/tabs-vkcom-light-1-snap.png
- src/components/TabsItem/TabsItem.css
> fix(TabsItem): заменил `header_tint_alternate` на `button_secondary_foreground`

- src/components/CustomSelectDropdown/CustomSelectDropdown.css
> fix(CustomSelectDropdown): поправил токен для фона

- src/components/Avatar/Readme.md
- src/components/Gradient/Readme.md
- src/components/Group/Readme.md
- src/components/PromoBanner/PromoBanner.tsx
- src/components/SimpleCell/Readme.md
- src/components/SimpleCell/SimpleCell.css
- src/components/SimpleCell/SimpleCell.e2e.tsx
- src/components/SimpleCell/SimpleCell.tsx
- src/components/SimpleCell/__image_snapshots__/simplecell-android-light-1-snap.png
- src/components/SimpleCell/__image_snapshots__/simplecell-ios-light-1-snap.png
- src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-light-1-snap.png
- src/components/Tooltip/Readme.md
> feat(SimpleCell): Reconcile with figma design

- src/components/ImageBase/ImageBase.tsx
- src/components/ImageBase/ImageBaseOverlay/ImageBaseOverlay.tsx
> feat(ImageBase): берём значение для `theme` в `overlay` из `ConfigProvider`

- src/components/ModalRoot/ModalRoot.css
- src/components/ModalRoot/ModalRoot.tsx
- src/components/ModalRoot/ModalRootDesktop.tsx
> fix(ModalRoot): remove platform class

- src/components/WriteBar/Readme.md
- src/components/WriteBar/WriteBar.tsx
- src/components/WriteBarIcon/WriteBarIcon.tsx
- Заменил `form` на `div`
- Добавил `aria-hidden` для иконок
> fix(WriteBar): change `form` to `div`

- src/components/View/View.test.tsx
- src/components/View/View.tsx
Удаляем устаревщие свойства `popout` и `modal`. В гайде по миграции уже все расписано
> BREAKING CHANGE(View): remove `popout` & `modal`

- src/components/SubnavigationButton/SubnavigationButton.css
> fix(SubnavigationButton): change selected token

- src/components/Banner/Readme.md
> fix Banner documentation

- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
> fix CustomSelect scroll

- tokenized/index.d.ts
- tokenized/package.json
- unstable/index.d.ts
- unstable/package.json
"Энтрипоинты" не работают и не используются
> chore: rm -rf tokenized unstable

- src/components/FixedLayout/FixedLayout.tsx
- src/components/PanelHeaderContext/PanelHeaderContext.css
- src/components/SplitCol/SplitCol.css
- closes #3217
- closes #3211
- closes #3208
> fix FixedLayout width calculation

- src/components/FixedLayout/FixedLayout.tsx
> listen for platform change

- src/components/Button/Button.module.css
- src/components/Button/Button.tsx
- src/components/Button/Readme.md
> fix(Button): Исправляет размеры шрифтов в Button

- package.json
- src/components/Button/Button.module.css
- src/components/Counter/Counter.css
- src/components/Counter/Readme.md
- yarn.lock
> fix(Counter, Button): Исправляет цвета Button и Counter

- .github/workflows/publish_token_translator.yml
Этот воркфлоу должен быть в мастере, иначе его не запустить
> chore: add publish_token_translator

- shared.js
- src/components/SplitCol/SplitCol.css
- src/components/SplitCol/SplitCol.tsx
- src/components/ViewWidthConditionalRender/ViewWidthConditionalRender.css
- src/components/ViewWidthConditionalRender/__image_snapshots__/viewwidthconditionalrender-android-light-1-snap.png
- src/components/ViewWidthConditionalRender/__image_snapshots__/viewwidthconditionalrender-ios-light-1-snap.png
- src/components/ViewWidthConditionalRender/__image_snapshots__/viewwidthconditionalrender-vkcom-light-1-snap.png
- src/helpers/getViewWidthClassName.test.ts
- src/helpers/getViewWidthClassName.ts
- styleguide/Components/Preview.js
> fix ViewWidthConditionalRender @media

- src/components/ModalCardBase/ModalCardBase.tsx
- src/components/NativeSelect/NativeSelect.tsx
- src/components/Panel/Panel.tsx
- src/components/Select/Select.tsx
> refactor: remove React.FC

- package.json
- src/components/DeviceConditionalRender/DeviceConditionalRender.module.css
- src/components/DeviceConditionalRender/DeviceConditionalRender.tsx
- src/components/SizeXConditionalRender/SizeXConditionalRender.module.css
- src/components/SizeXConditionalRender/SizeXConditionalRender.tsx
- src/components/SizeYConditionalRender/SizeYConditionalRender.module.css
- src/components/SizeYConditionalRender/SizeYConditionalRender.tsx
- src/components/ViewWidthConditionalRender/ViewWidthConditionalRender.module.css
- src/components/ViewWidthConditionalRender/ViewWidthConditionalRender.tsx
- src/styles/components.css
- yarn.lock
- Добавляем пропавший `typescript-plugin-css-modules`
- Добавляем поддержку css modules для `*ConditionalRender`
> chore(ConditionalRender): use css modules

- src/components/Cell/Cell.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/Header/Header.tsx
- src/components/Header/Readme.md
- src/components/HorizontalCell/Readme.md
- src/components/PanelHeader/Readme.md
- src/components/PanelHeaderContent/PanelHeaderContent.tsx
- src/components/PullToRefresh/PullToRefresh.tsx
- src/components/Search/Search.tsx
- src/components/Snackbar/Snackbar.tsx
- src/components/Tooltip/Readme.md
- Избавляемся от HOC `withPlatform` в примерах
- Избавляемся от `HasPlatform`
> docs: change withPlatform to usePlatform

- .github/gitflow/utils.js
- .github/workflows/publish.yml
- создаем стабильную ветку только при публикации полноценного релиза
> ci: create stable branch only on publish

- src/components/PanelHeaderContext/PanelHeaderContext.tsx
> fix PanelHeaderContext onClose firing

- package.json
> fix(build): add tsc-cjs

- src/components/FixedLayout/FixedLayout.tsx
git cherry-pick 0360c61292a1fcadee1bf743f356c1446bba6d96
- link #3233
> Patch: listen for platform change

- src/components/ModalRoot/ModalRoot.tsx
> fix(ModalRoot): check first open

- src/components/Group/Group.css
- src/components/PanelHeader/PanelHeader.css
> hide PanelHeader shadow if separator = false

- .github/gitflow/patch.js
- .github/gitflow/stable_branch.js
- .github/gitflow/utils.js
- .github/workflows/pr_close.yml
Удаляем зависимости для flow. Установка зависимостей занимает
большое кол-во времени
> ci(patch): remove import semver

- package.json
- src/styles/vkcom_dark.css
- yarn.lock
Обновляем Appearance до версии v9.51.1
> fix: update Appearance to v9.51.1

- src/components/ModalPage/ModalPage.css
https://user-images.githubusercontent.com/14944123/191063679-f1ab41c3-2a76-42c7-a098-318aa7f21d08.mov
- fixes #3315
> fix(ModalPage): remove center content

- .github/workflows/inactive_issues.yml
Будем запускать каждый день, думаю, такого будет достаточно
Возможно, формулировки сообщений нужно подправить?
- resolve #3308
> chore: Добавляет экшен для автоматического закрытия неактивных задач

- src/components/Alert/Alert.module.css
- src/components/Alert/Alert.tsx
- src/styles/components.css
> chore(Alert): use css modules

- src/components/ActionSheet/ActionSheet.module.css
- src/components/Alert/Alert.module.css
- src/components/HorizontalScroll/HorizontalScrollArrow.css
- src/components/HorizontalScroll/HorizontalScrollArrow.tsx
- src/components/ModalCard/ModalCard.css
- src/components/ModalPage/ModalPage.css
- src/components/PanelHeader/PanelHeader.css
- src/components/PullToRefresh/PullToRefresh.css
- src/components/Radio/Radio.css
- src/components/Removable/Removable.css
- src/components/Root/Root.css
- src/components/ScreenSpinner/ScreenSpinner.css
- src/components/Search/Search.css
- src/components/Snackbar/Snackbar.css
- src/components/TabbarItem/TabbarItem.css
- src/components/Tappable/Tappable.module.css
- src/components/View/View.css
- src/components/View/ViewIOS.css
- src/styles/constants.css
> feat: Add animation token

- src/index.ts
> - feat(CustomScrollView): add to index.ts

- src/components/ModalRoot/Readme.md
> fix(ModalRoot): Исправляет в доке переход по истории модальных окон

- .github/workflows/publish_prerelease.yml
> chore: Бампаем версию с помощью yarn version flow

- .github/workflows/publish.yml
- .github/workflows/publish_prerelease.yml
- .github/workflows/publish_token_translator.yml
- .github/workflows/update_screens.yml
Добавляем новую фичу динамических имен для ci 
- https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/
> ci: add run-name

- .github/gitflow/push_with_retry.js
> ci: add email for update screenshots

- src/components/TabbarItem/Readme.md
> fix(docs): исправляет использование устаревшего пропа

- src/components/ModalRoot/Readme.md
- src/components/ModalRoot/useModalRootContext.tsx
- src/index.ts
> feat: add useModalRootContext

- styleguide/pages/migration_v5.md
> docs(migration): typography add info about weight

- .github/workflows/pull_request.yml
Ускоряем публикацию PR
до|после
-|-
Почти на целую минуту быстрее
> ci(pull_request): update publish PR

- src/components/ModalPage/ModalPage.css
> fix(ModalPage): fix shrinking content for older browsers

- e2e/index.ts
- e2e/styles.test.css
- src/components/ActionSheet/__image_snapshots__/actionsheet-ios-chromium-dark-w_2-1-snap.png
- src/components/ActionSheet/__image_snapshots__/actionsheet-ios-firefox-dark-w_2-1-snap.png
- src/components/ActionSheet/__image_snapshots__/actionsheet-ios-webkit-dark-w_2-1-snap.png
- src/components/Button/__image_snapshots__/button-android-webkit-light-1-snap.png
- src/components/ContentCard/__image_snapshots__/contentcard-android-webkit-light-1-snap.png
- src/components/Header/__image_snapshots__/header-android-webkit-dark-1-snap.png
> disable animation for pseudo elements for e2e

- packages/stylelint-atomic/index.js
- packages/stylelint-atomic/stylelint-atomic.test.js
> style(stylelint-atomic): check :global

- docs/ADAPTIVITY_GUIDE.md
> [Doc]: редактирует `ADAPTIVITY_GUIDE.md`

- src/hooks/useWaitTransitionFinish.ts
> fix(View): Исправляет двойной вызов коллбэка во View

- src/components/ActionSheetItem/ActionSheetItem.css
- src/components/ActionSheetItem/ActionSheetItem.tsx
> feat(ActionSheetItem): add `iconСhecked `

- .github/gitflow/patch.js
Добавляем `git fetch` для инструкции конфликтного патча
> ci(patch): add git fetch

- src/components/ActionSheetItem/ActionSheetItem.tsx
> fix(ActionSheetItem): add compact iconChecked

- src/components/ActionSheet/ActionSheet.tsx
- src/components/ActionSheet/ActionSheetDropdown.tsx
- src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
- src/components/ActionSheet/types.ts
- Добавил новый параметр **popupOffsetDistance**, который реализует отступ от контента на котором был вызван popover
> fix(ActionSheetDropdownDesktop): add prop popupOffsetDistance for ActionSheetDropdownDesktop

- src/components/InfoRow/InfoRow.tsx
> fix(InfoRow): fix a11y

- src/components/MiniInfoCell/MiniInfoCell.tsx
> fix(MiniInfoCell): fix a11y

- src/components/Calendar/Calendar.tsx
- src/components/Calendar/Readme.md
- src/components/CalendarDays/CalendarDays.tsx
- src/components/CalendarRange/CalendarRange.tsx
- src/hooks/useNow.ts
- src/hooks/useTodayDate.ts
- src/index.ts
- src/lib/date.ts
В компоненте Calendar при фактической смене времени в системе (было 18 октября стало 19), сегодняшний день в календаре не меняется, поскольку текущее время определялось так
```js
const [now] = useState(new Date());
```
В мре стейт обновляется в соответствии с системным временем
---
- fix #3482
> fix(Calendar): now state update with day change

- src/components/FixedLayout/FixedLayout.css
> fix(PanelHeaderContext): increase z-index for FixedLayout context

- src/components/DropdownIcon/DropdownIcon.tsx
- src/components/FormField/FormField.css
Нельзя открыть NativeSelect по нажатию на стрелку
> fix(NativeSelect): pointer-events: none for after

- src/components/CardGrid/CardGrid.css
- Исправил токенезацию компонента CardGrid 
- - Токен для **.CardGrid--m .Card** и **Group--card .CardGrid**
> fix(CardGrid): fix CardGrid tokens

- src/components/BaseGallery/BaseGallery.tsx
- src/components/BaseGallery/types.ts
- src/components/HorizontalScroll/HorizontalScrollArrow.tsx
> feat(Gallery): Pass event to onPrevClick/onNextClick callbacks

- src/components/BaseGallery/BaseGallery.css
- src/components/BaseGallery/BaseGallery.tsx
> fix(Gallery): Change cursor type when draggable=true

- src/components/BaseGallery/BaseGallery.tsx
- src/components/BaseGallery/types.ts
> feat(Gallery): Add arrow size prop

- src/components/CardGrid/CardGrid.css
> fix(CardGrid): add size_cardgrid_padding_vertical

- src/components/Counter/Counter.css
Исправляем цвета для счетчика в `<Button appearance="neutral" />`
> fix(Counter): colors for Button neutral

- src/components/SimpleCell/Readme.md
> docs(SimpleCell): label with Switch

- src/components/Snackbar/Readme.md
- src/components/Snackbar/Snackbar.module.css
- src/components/Snackbar/Snackbar.tsx
> feat(Snackbar): add subtitle prop

- .codesandbox/ci.json
- .github/ISSUE_TEMPLATE/bug_report.yml
> docs: update codesandbox

- src/helpers/scheme.ts
> fix(AppearanceScheme): add deprecated types

- yarn.lock
> build(deps-dev): bump webpack from 5.74.0 to 5.75.0

- styleguide/pages/migration_v5.md
Добавляем информацию о устаревшем свойстве
> docs(migration): File rm `controlSize`

- styleguide/config.js
> chore(doc): Add color token for code deleted line

- src/components/FormField/Readme.md
https://user-images.githubusercontent.com/14944123/202438282-00cc6cc0-9986-44a8-be2e-da0340b559cb.mov
> docs(FormField): fix z-index

- src/components/Banner/Banner.module.css
- src/components/FormStatus/FormStatus.module.css
- src/components/FormStatus/FormStatus.test.tsx
- src/components/FormStatus/FormStatus.tsx
- src/components/FormStatus/Readme.md
- src/index.ts
- src/styles/components.css
- styleguide/config.js
- styleguide/pages/migration_v5.md
> [v5][Feature]: Компонент FormStatus

- src/components/Button/Button.module.css
- src/components/PanelHeaderBack/PanelHeaderBack.module.css
- yarn.lock
changelog https://prettier.io/blog/2022/11/23/2.8.0.html
> build(deps-dev): bump prettier from 2.7.1 to 2.8.0

- src/components/PopoutRoot/PopoutRoot.module.css
- src/components/PopoutRoot/PopoutRoot.tsx
Допом удалил лишнее в стилях `PopoutRoot`
---
- Fix #3661
> fix(SSR): исправляет ошибку при SSR при использовании `PopoutRoot`

- src/components/Epic/Readme.md
- src/components/PanelHeader/PanelHeader.module.css
- src/components/PanelHeaderContext/Readme.md
- src/components/Root/Readme.md
- src/components/Search/Readme.md
- src/components/SplitCol/SplitCol.module.css
- src/components/SplitCol/SplitCol.tsx
- src/components/SplitLayout/Readme.md
- styleguide/Components/Preview.js
> fix(SplitCol): Fix autoSpace option + fix docs examples

- src/components/AppRoot/AppRoot.tsx
Исправляем префикс для инсетов
> fix(AppRoot): inset prefix

- src/index.ts
> tech: удаляет из экспорта утилитарные функции для параметров адаптивности

- src/components/PanelHeaderContext/PanelHeaderContext.css
> fix(PanelHeaderContext): Fix FixedLayout overlay when closed

- src/components/Footer/Footer.css
> fix(Footer): Fix horizontal margins

- src/components/ChipsInputBase/ChipsInputBase.css
> fix(ChipInputBase): Pay respect to margins with max-width calculation

- src/components/PromoBanner/PromoBanner.test.tsx
- src/components/PromoBanner/PromoBanner.tsx
Добавил опциональную отрисовку кнопки и аватара (+ тесты) в соответствие [этому комментарию](https://github.com/VKCOM/VKUI/issues/943#issuecomment-886573472) из #943
<details>
<summary></summary>
Говорят, что новичкам полезно помогать в open-source проектах тут и там. Этим и занимаюсь. Простите, если этот спойлер нарушает правила оформления реквестов. 🐢
</details>
> Enhancenment (PromoBanner): Render CTA Button and Avatar optionally

- README.md
- styleguide/pages/migration_v5.md
- styleguide/pages/quick_start.md
Привет, спасибо, что опенсорсите библиотеку компонентов. Предлагаю добавить `pnpm` в документацию, чтобы тем, кто использует `pnpm` было чуть-чуть проще копировать команды.
> docs: add pnpm

- src/components/Banner/Banner.module.css
> fix(Banner): add stacking context

- .eslintrc.json
- .git-blame-ignore-revs
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/danger/dangerfile.js
- .github/dependabot.yml
- .github/gitflow/patch.js
- .github/gitflow/push_with_retry.js
- .github/gitflow/stable_branch.js
- .github/gitflow/utils.js
- .github/workflows/inactive_issues.yml
- .github/workflows/pr_close.yml
- .github/workflows/publish.yml
- .github/workflows/publish_prerelease.yml
- .github/workflows/publish_token_translator.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_screens.yml
- packages/babel-plugin-transform-css-modules/tests/__snapshots__/index.test.js.snap
- Обновляем snap после prettier
- Запускаем prettier на всем
- Чиним CI для PR-ов (#3765)
> ci: fix ref and prettier

- src/components/Alert/Alert.test.e2e.tsx
- src/components/Alert/Alert.tsx
- src/components/Tappable/Tappable.tsx
- src/types.ts
Добавляем типы для `<a>`
- closed #3536
> fix: add AnchorHTMLAttributesOnly

- styleguide/Components/StyleGuide/StyleGuideDesktop.js
- styleguide/Components/StyleGuide/StyleGuideHeader.js
- styleguide/Components/StyleGuide/StyleGuideMobile.js
- styleguide/Components/StyleGuide/StyleGuideModal.js
- styleguide/Components/StyleGuide/StyleGuideRenderer.js
Добавляем возможность перейти на другую версию
- closed #1320
P.S. ci для добавления новых версий в versions.json будет отдельно
> docs: add version

- .github/gitflow/patch.js
> ci(patch.js): fix predicate for FORKED

- package.json
> ci: perf size:ci

- .github/workflows/deprecate.yml
Чтобы не ставить каждый раз задачи на DT 🙂
> chore: Add GH action for package deprecations

- .github/workflows/pull_request.yml
- package.json
Исправляем ci и добавляем тест на tree shaking
> ci: size add ref

- src/components/ImageBase/types.ts
- src/components/ImageBase/validators.ts
- src/lib/warnOnce.ts
Используем Set вместо объектов
> refactor: use Set

- src/components/SubnavigationButton/SubnavigationButton.module.css
- src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-android-chromium-dark-1-snap.png
- src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-android-chromium-light-1-snap.png
Забыли поправить TODO v5 для адаптива
> fix(SubnavigationButton): исправляет TODO v5 в CSS

- src/components/SegmentedControl/SegmentedControl.tsx
- src/lib/utils.ts
Используем `useId` вместо `generateRandomId` для поддержки SSR
> fix(SegmentedControl): remove generateRandomId

- .github/actions/patch/package.json
- .github/actions/patch/yarn.lock
- .github/actions/stable-branch/package.json
- .github/actions/stable-branch/yarn.lock
> ci(actions): add @types/semver

- src/components/InputLike/InputLike.test.tsx
- src/components/Typography/Caption/Caption.test.tsx
- src/components/Typography/Footnote/Footnote.test.tsx
- src/components/Typography/Headline/Headline.test.tsx
- src/components/Typography/Subhead/Subhead.test.tsx
- src/components/Typography/Text/Text.test.tsx
- src/components/Typography/Title/Title.test.tsx
(Вытаскиваю не относящееся непосредственно к задаче из https://github.com/VKCOM/VKUI/pull/3803.)
Добавила тесты на `baselineComponent` в:
> test: add baseline tests

- src/components/Banner/Banner.tsx
- src/components/BaseGallery/BaseGallery.tsx
- src/components/Chip/Chip.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/FocusVisible/FocusVisible.tsx
- src/components/GridAvatar/GridAvatar.tsx
- src/components/SegmentedControl/SegmentedControl.tsx
- src/components/Separator/Separator.tsx
- src/components/Spacing/Spacing.tsx
- src/components/Tappable/Tappable.tsx
(Вытаскиваю не относящееся непосредственно к задаче из https://github.com/VKCOM/VKUI/pull/3803.)
Примечание: иногда `aria-hidden` у нас натыкан в весьма неожиданных местах, причем по большей части мной самой. Надо бы это в новому году поправить. 🤣
> refactor: `aria-hidden="true"` => `aria-hidden`

- src/components/Counter/Counter.test.tsx
(Вытаскиваю не относящееся непосредственно к задаче из #3803.)
Убрала лишний тест на `baselineComponent`.
> test(Counter): remove extra `baselineComponent` test

- src/components/Banner/Banner.test.tsx
(Вытаскиваю не относящееся непосредственно к задаче из #3803.)
Убрала лишние тесты для `Banner`.
> test(Banner): remove extra tests

- src/components/Tooltip/Tooltip.tsx
> feat(Tooltip): Add className prop

- src/components/PanelHeaderButton/PanelHeaderButton.module.css
- src/components/PanelHeaderButton/PanelHeaderButton.tsx
Исправляем позиционирование лейбла
> fix(PanelHeaderButton): label position

- .github/actions/patch/src/message.ts
Добавляем больше инструкций для патча
> ci(patch): add more instructions

- src/components/PanelHeaderButton/PanelHeaderButton.module.css
- src/components/PanelHeaderButton/PanelHeaderButton.tsx
> patch: pr3850

- .github/workflows/pr_close.yml
`github.actor` это пользователь который закрыл PR, а не автор PR-а
> ci(clear_styleguide): fix login dependabot

- src/components/Tappable/Tappable.module.css
> patch: pr3833

- src/components/FixedLayout/FixedLayout.module.css
- src/components/FixedLayout/FixedLayout.tsx
Удаляем неиспользуемый элемент
> refactor(FixedLayout): remove FixedLayout__in

- src/components/Button/Readme.md
- src/components/HorizontalCell/Readme.md
- src/components/Select/Readme.md
- src/components/SubnavigationBar/Readme.md
- src/components/SubnavigationButton/Readme.md
> patch: pr3880

- src/components/CellButton/Readme.md
Свойство `shadow` переименовано в `withBorder`.
> docs(CellButton): remove shadow

- .github/actions/patch/src/main.ts
- .github/actions/stable-branch/src/main.ts
> ci: remove exec quot

- src/components/CellButton/Readme.md
> patch: pr3878

- src/components/CustomScrollView/CustomScrollView.tsx
Если в дропдауне потянуть мышкой скролл, то дропдаун закрывается
> fix(CustomScrollView): stopPropagation for barY

- src/components/CustomScrollView/CustomScrollView.tsx
> patch: pr3894

- src/components/Alert/Alert.module.css
- src/components/FocusVisible/FocusVisible.module.css
> patch: pr3868

- src/components/FormField/FormField.module.css
- src/components/Input/Input.module.css
- src/components/Textarea/Textarea.module.css
- src/components/WriteBar/WriteBar.module.css
Удаляем лишнюю обводку при фокусе
> fix(FormField): focus outline none

- src/components/Popover/Popover.tsx
- src/hooks/useEventListener.ts
> patch: pr3888

- src/components/ChipsSelect/ChipsSelect.tsx
> patch: pr3893

- src/components/Badge/Readme.md
- src/components/CustomSelectOption/CustomSelectOption.tsx
> patch: pr3889

- src/components/Cell/__image_snapshots__/cell-ios-webkit-dark-1-snap.png
- src/components/Cell/__image_snapshots__/cell-ios-webkit-light-1-snap.png
- src/components/CellButton/__image_snapshots__/cellbutton-ios-webkit-dark-1-snap.png
- src/components/CellButton/__image_snapshots__/cellbutton-ios-webkit-light-1-snap.png
- src/components/SimpleCell/SimpleCell.module.css
- src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-dark-1-snap.png
- src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-light-1-snap.png
> fix(SimpleCell): horizontal padding tokens

- styleguide/Components/Frame/Frame.js
- styleguide/Components/Frame/usePlatformStyle.js
- styleguide/Components/Modals/Platforms.js
- styleguide/Components/Modals/Versions.js
- styleguide/Components/Modals/useFetch.js
- styleguide/Components/Preview.js
- styleguide/Components/Settings/PlatformSelect.js
- styleguide/Components/StyleGuide/StyleGuideModal.js
Добавляем возможность выбрать платформу.
Платформы загружаются из vkui-tokens последней версии
> docs: add more platforms

- shared.js
- src/components/SplitCol/SplitCol.tsx
- src/hooks/useMediaQueries.ts
- src/lib/adaptivity/types.ts
- src/lib/browser.ts
- src/shared/breakpoints.js
SplitCol не подписывался на изменение размера экрана.
Из-за этого animate не менялся при изменении размеров экрана
> fix(SplitCol): add useTransitionAnimate

- src/components/ChipsSelect/ChipsSelect.module.css
- src/components/CustomSelect/CustomSelect.module.css
- src/components/FormField/FormField.module.css
Исправляем закругления для раскрывающихся селектов
До|После
-|-
> fix(Select): border with pop-up/down

- src/components/HorizontalScroll/HorizontalScrollArrow.module.css
> fix(BaseGallery): fix css modules class

- styleguide/Components/Frame/Frame.js
- styleguide/Components/Frame/usePlatformStyle.js
- styleguide/Components/Modals/Platforms.js
- styleguide/Components/Modals/Versions.js
- styleguide/Components/Modals/useFetch.js
- styleguide/Components/Preview.js
- styleguide/Components/Settings/PlatformSelect.js
- styleguide/Components/StyleGuide/StyleGuideModal.js
> patch: pr3879

- shared.js
- src/components/SplitCol/SplitCol.tsx
- src/hooks/useMediaQueries.ts
- src/lib/adaptivity/types.ts
- src/lib/browser.ts
- src/shared/breakpoints.js
> patch: pr3915

- docs/CONTRIBUTING.md
> Fix CONTRIBUTING.md typo

- yarn.lock
https://github.com/advisories/GHSA-9c47-m6qq-7p4h
> build(deps): bump json5

- .github/workflows/workflow_test_e2e.yml
Необходимо получать скриншоты из base только при PR-ах
> ci: fix checkout base snapshots

- packages/vkui/src/components/BaseGallery/BaseGallery.module.css
> fix(BaseGallery): bring back centered option

- .github/actions/reporter/src/comment.ts
> ci(reporter): fix empty comment

- .github/workflows/inactive_contributions.yml
На случай, если в Fix Bounty что-то пойдет не так 🙂
> chore: Add staled PRs action

- packages/vkui/src/components/Button/Button.test.tsx
- packages/vkui/src/components/Button/Button.tsx
> fix(Button): использует `hasReactNode()` для элементов

- packages/vkui/src/components/Cell/Cell.module.css
draggable state изменил токен активного фона на color_backround_secondary. Раньше была прозрачность на Cell
> feat(Cell): change dragging background

- packages/vkui/src/components/View/Readme.md
- packages/vkui/src/components/View/View.test.tsx
- packages/vkui/src/components/View/View.tsx
- packages/vkui/src/components/View/ViewInfinite.tsx
Изменил поведение параметра `onSwipeBackStart()`: если при вызове `onSwipeBackStart()` пользователь вернёт значение `"prevent"`, то мы блокируем свайп бэк.
Добавил пример в песочницу:
Также перенёс реализацию в нестабильный `ViewInfinite`
---
- close #3458
> feat(View, ViewInfinite): добавляет возможность блокировать свайп бэк

- .github/workflows/update_screens.yml
- .github/workflows/workflow_test_e2e.yml
Переключаем apt репозиторий, с `azure.archive.ubuntu.com` на `archive.ubuntu.com`, если тот упал
> ci: add switching apt repositories

- packages/vkui/src/components/Search/Search.tsx
При нажатии на иконку(свойство icon), очищалось поле ввода
> fix(Search): onCancel icon

- packages/vkui/src/components/ActionSheet/ActionSheet.module.css
Устанавливаем максимальную ширину
> fix(ActionSheet): set max width

- packages/vkui/src/components/ModalRoot/ModalRoot.module.css
- packages/vkui/src/components/ModalRoot/ModalRoot.tsx
- packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx
> fix(ModalRootDesktop): rm transition animation

- packages/vkui/src/shared/breakpoints.js
Был задан неверный размер
---
- caused by #3915
> fix(Adaptivity): smallTabletPlus min-width size

- packages/vkui/src/components/View/View.tsx
- packages/vkui/src/components/View/ViewInfinite.tsx
Отключаем свайпбек, если отключена анимация переходов
> fix(View): swipeBack with disableAnimation

- .github/actions/patch/action.yml
- .github/actions/patch/src/main.ts
- .github/actions/stable-branch/action.yml
- .github/actions/stable-branch/src/main.ts
- .github/workflows/pr_close.yml
- .github/workflows/publish.yml
`@actions-internal/stable-branch` и `@actions-internal/patch` смотрели в главный рутовый `package.json` вместо `packages/vkui/@actions-internal/patch` из-за чего не получали текущую версию `@vkontakte/vkui`.
Пример неправильного срабатывания `@actions-internal/stable-branch` https://github.com/VKCOM/VKUI/actions/runs/3940550417/jobs/6741806412
---
- caused by #3902
> fix: исправляет внутренние GitHub Actions

- packages/vkui/src/components/Spacing/Spacing.module.css
- packages/vkui/src/components/Spacing/Spacing.tsx
> fix(Spacing): remove display: flex

- packages/vkui/package.json
> patch: copy LICENSE and README.md files before publish

- package.json
Добавляем поддержку [corepack](https://nodejs.org/api/corepack.html)
> chore: support corepack

- package.json
- yarn.lock
> Revert "build(deps-dev): bump @types/css-font-loading-module from 0.0.7 to 0.0.8"
