package-lock.json, package.json, src/components/Panel/Panel.js, src/components/Root/Root.js, src/components/View/View.js
Убрали оптимизации, написанные на основе React.cloneElement и shouldComponentUpdate во View, Root и Panel. Их лучше описывать в компонентах уровня приложения, не прибегая к клонированию.
=> Wrong optimizations

src/components/RangeSlider/RangeSlider.js, src/components/Slider/Slider.js
#244 
Передает в качестве второго параметра **event**, который можно использовать для различных кейсов, как пример кейс из issue выше
```javascript
<Slider
min={10}
max={30}
value={Number(this.state.value1)}
onChange={(value1, e) => {
e.originalEvent.stopPropagation()
this.setState({value1})}
}
top="Simple [10, 30]"
/>
```
=> Add event as second param to Slider onChange function

styleguide/pages/html.md
Его значение по умолчанию именно `type="text/javascript"`.
=> Удаляет ненужный атрибут type="text/javascript"

src/components/Switch/Switch.tsx
Этот пулл-реквест заменяет `React.HTMLAttributes<InputHTMLElement>` на более полный `React.InputHTMLAttributes<InputHTMLElement>`, который включает в себя свойства `<input>`, а не только свойства обработчиков событий, в том числе и `checked`.
fixes #460
=> Fix Switch props types to include <input> attributes

src/lib/classNames.ts
Теперь в `classNames(...)` можно передавать `false`, `null` и `undefined`, что позволяет удобно включать и выключать классы по условию и добавлять юзерский `className` к своим:
```jsx
const Radio = ({ isSelected, className, ...restProps }) => {
return (
<input
className={classNames(
'Radio',
isSelected && 'Radio--selected',
className
)}
type="radio"
checked={isSelected}
{...restProps}
/>
);
};
```
resolves #459
=> Add falsy types to classNames args types

package.json, src/components/PanelHeaderSimple/PanelHeaderSimple.css, src/components/PanelHeaderSimple/PanelHeaderSimple.tsx, src/components/PanelHeaderSimple/Readme.md, src/components/Search/Search.css, src/index.ts, src/styles/styles.css, styleguide/config.js
`PanelHeaderSimple` — это то, что в 4-й версии заменит `PanelHeader`. У `PanelHeader` есть ряд проблем:
1. Части этого компонента рендерятся с помощью порталов в ближайший `View`, что делает невозможным SSR и замедляет
отрисовку и перерисовку компонента.
2. Невозможно было в пределах одного `View` мешать панели с шапкой и без шапки.
3. Большая вложенность вёрстки.
4. Наличием или отсутствием разделителя управляет `Panel`, было бы удобнее, если бы это делал `PanelHeader`
У `PanelHeaderSimple` этих проблем нет. Он рендерится как обычный компонент, имеет простую структуру, быстро рисуется и
поддерживает SSR.
1. Во `<View />` добавляем `header={false}`
2. В `<Panel />` добавляем `separator={false}`. Это свойство теперь есть у `PanelHeaderSimple`
3. Заменяем `<PanelHeader />` на …
=> PanelHeaderSimple

src/components/PanelHeader/PanelHeader.css
Исправляет #491 и даёт возможность изменять цвет заголовка так же, как и на iOS.
=> Added missing style for PanelHeader 

src/components/ModalPage/ModalPage.tsx, src/components/ModalRoot/ModalRoot.tsx
Убран некорректный тайпинг для onClose ожидавший возвращения пустого объекта.
=> [TypeScript] [ModalPage] Убран некорректный тайпинг для onClose ожидавший возвращения пустого объекта.

src/components/CellButton/CellButton.css, src/components/CellButton/CellButton.tsx, src/components/IconButton/IconButton.css, src/components/PanelHeaderButton/PanelHeaderButton.css, src/components/RichCell/RichCell.css, src/components/RichCell/RichCell.tsx, src/components/SimpleCell/SimpleCell.css, src/components/SimpleCell/SimpleCell.tsx, src/components/Tappable/Tappable.css, src/styles/styles.css
* Убрал закругления у Cell, SimpleCell, RichCell и CellButton для ховеров/тапов в компактной версии
* Починил баг, когда в RichCell всплывал невидимый after
* Облегчил селекторы в Tappable.css, поместив его выше в styles.css, вынеся стили для PanelHeaderButton и IconButton в соответствующие файлы.
=> Cell hover fixes

src/hooks/useInsets.ts
iOS присылает нулевой инсет сверху. Поэтому нули от VK Bridge учитывать не будем.
=> insets: setting vk bridge insets only if more than 0

src/components/ActionSheet/ActionSheet.tsx, src/components/Epic/Epic.tsx, src/components/FixedLayout/FixedLayout.tsx, src/components/ModalCard/ModalCard.tsx, src/components/ModalPage/ModalPage.tsx, src/components/Panel/Panel.tsx, src/components/Tabbar/Tabbar.tsx
Инсеты из JS теперь меняют css-перменные. Поэтому JS-логику можно выпилить.
=> Removed JS insets style logic

src/components/Link/Link.tsx
Use AnchorHTMLAttributes for `<a>` tags instead of props for `<link>` tag
---
Поправил описание типов, на которые ругался тайпчекер.\
Например при передаче атрибута `_target`, которого нет у тега `<link>`
=> Fix Link component prop types

package.json
На скриншоте видно, что после смены типа кавычек stylelint перестал выдавать ошибку.
=> fix test command on windows

src/components/ConfigProvider/ConfigProvider.tsx, src/components/FixedLayout/FixedLayout.tsx, src/components/ModalRoot/ModalRootDesktop.tsx, src/components/ModalRoot/ModalRootTouch.tsx, src/components/Panel/Panel.tsx, src/components/Panel/PanelContext.tsx, src/components/Panel/withPanelContext.tsx, src/components/PanelHeader/PanelHeader.tsx, src/components/Root/Root.tsx, src/components/Tooltip/Readme.md, src/components/Tooltip/Tooltip.tsx, src/components/View/View.tsx, src/types.ts, styleguide/Components/PathlineRenderer.js, styleguide/Components/PlatformSelect.js, styleguide/Components/Preview.js, styleguide/Components/SchemeSelect.js, styleguide/Components/StyleGuideRenderer.js, styleguide/Components/WebviewTypeSelect.js, styleguide/config.js, styleguide/setup.js, styleguide/utils.js
* `ConfigProvider`: избавился от legacy context API
* `Panel`: убрал устаревшее свойство `separator`
* Теперь каждый пример обернут в ConfigProvider
* Добавил возможность менять webviewType
* Избавился от перезагрузки при смене параметров ConfigProvider
* Избавился от ненужного ReactDOM.render внутри каждого примера
* Удалил лишний код из setup.js и config.js
=> Legacy context

.github/workflows/publish.yml, package.json
Теперь `yarn build` будет запускать перед публикацией пакета с помощью скрипта `prepare`. Этот скрипт так же будет запускаться во время установки в проект зависимости `@vkontakte/vkui` через git+ssh. Таким образом, можно будет тестировать код из pr, собирая либу на стороне проекта.
=> moved yarn build to prepare script

src/components/Slider/Slider.tsx
Из-за изменения положения слайдера использовалось неверное значение левой координаты слайдера в момент клика.
Теперь координата получается непосредственно при нажатии
=> VKUI-29: неправильный расчет позиции слайдера 

src/components/ActionSheet/ActionSheet.css, src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
После дизайн-ревью, решили убрать бордер у ActionSheet для vkcom, пока непонятно с цветами
Проброс `sizeY` в ActionSheetDropdownDesktop, для выставления корректных отступов
=> remove border, sizeY=compact для ActionSheetDropdownDesktop

src/components/Radio/Radio.css
На windows положение элемента с кругом, по умолчанию не в 0,0 родителя, поэтому и при смещении выглядело неверно
=> fix position icon for windows

.gitignore, src/components/ModalPage/ModalPage.css
Fixed blur of modal page due to using `transform` to center modals in desktop when devicePixelRatio < 2
=> Fix modal blurring

src/components/Select/Select.css, src/components/Textarea/Textarea.css
Приветствую!
Заменил селекторы тегов на селекторы классов в компонентах `Select` и `Textarea`.
Мотивация — более полноценное следование методологии БЭМ, которая не позволяет использовать селекторы тегов.
> В БЭМ не используют селекторы тегов и идентификаторов. Стили блоков и элементов описываются через селекторы классов. - https://ru.bem.info/methodology/css/#%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B
Следовать этому правило помогает правило линтера Stylelint `selector-max-type` со значением `0`.
В текущем состоянии проекта правило также находит ошибки в следующих компонентах:
- src/styles/styles.css
```
95:1  ✖  Expected "html" to have no more than 0 type selectors       selector-max-type
96:1  ✖  Expected "body" to have no more than 0 type selectors       selector-max-type …
```
=> Замена селекторов тегов на селекторы классов

src/components/SplitLayout/SplitLayout.css
Выражение `calc(var(--panelheader_height_ios) * -1)` после минификации `postcss-csso` оставалось без пробелов, что ломало некоторым сборщикам мозг.
fixes #1057
fixes #1083
=> css build error fix

src/components/FormLayoutGroup/FormLayoutGroup.css
Если `white-space: nowrap` относится не напрямую к flex child, а к вложенным в него элементам, блок будет переполняться до бесконечности. Это известная особенность (https://css-tricks.com/flexbox-truncated-text/).
Фиксится добавлением `min-width: 0` флекс-элементу.
**Сломано:**
**Пофикшено:**
=> Fix FormLayoutGroup overflow

src/components/View/View.tsx
Callback onSwipeBackStartEndAnimation нужен, чтобы отключить жесты внутри панели, чтобы не было конфликтов.
=> add onSwipeBackStartEndAnimation callback

src/components/Header/Header.css
Решение проблемы #738.
В Firefox есть проблема с выравниванием по baseline при задании элементу вертикальных пэддингов.
В багтрекере нашел несколько похожих багов, но не идентичных этому. Инфы практически нет, и единственное что сработало без создания дополнительных элементов разметки - это изменение padding на margin.
Наиболее близкое из того что нашел:
https://github.com/webcompat/web-bugs/issues/12629
=> [Header] fix baseline-aligning firefox bug

src/components/CustomSelect/CustomSelect.tsx, src/components/CustomSelect/Readme.md, src/components/FormItem/Readme.md, src/components/Select/Readme.md, src/components/Select/Select.tsx, src/components/Slider/Readme.md
* Вернули возможность передавать свойcтва CustomSelect, типа `popupDirection`
* Поправлен баг с опциями с одинаковыми `label`  (fixes #1137)
* Опции больше нельзя передавать как `children`. Теперь доступен только валидный массив `options`.  (fixes #1139)
=> Select fixes

styleguide/Components/StyleGuideRenderer.js
Фикс для сломанной высоты превью в стайлгайде, из-за устаревшего скейта в localStorage
=> Fallback to initial styleguide values, if localStorage doesn't have some property

src/components/Chip/Chip.css, src/components/ChipsInput/ChipsInput.css, src/components/ChipsInput/ChipsInput.tsx, src/components/ChipsSelect/ChipsSelect.css, src/components/ChipsSelect/ChipsSelect.tsx
- fixes #1108 
- Привел отступы в ChipsInput / ChipsSelect в соответствие с [макетом](https://www.figma.com/file/TDK0ARSsxCXRAX8VLIFMS6/VKUI-Web-Library-%C2%B7-Beta?node-id=3269%3A1) после https://github.com/VKCOM/VKUI/pull/983
- Добавил sizeY-compact
=> #1108: [Bug] [ChipsInput] вертикальное выравнивание плэйсхолдера

src/components/Tappable/Tappable.css, src/components/Tappable/Tappable.tsx
- Добавлен transition .15s если определена мышка
| With mouse | No mouse (no transition) |
|-|-|
| ![Kapture 2020-12-08 at 11 38 57](https://user-images.githubusercontent.com/827338/101461382-d68fa280-394b-11eb-8c11-82f1c5f80e87.gif) | ![Kapture 2020-12-08 at 11 39 29](https://user-images.githubusercontent.com/827338/101461403-e1e2ce00-394b-11eb-84b1-24e2b5352319.gif) |
- Убран ripple effect для Android если определена мышка
=> Tappable updates for devices with mouse

src/components/AdaptivityProvider/AdaptivityProvider.tsx, styleguide/Components/PathlineRenderer.js, styleguide/Components/StyleGuideRenderer.js
Исправляет баг: если задать `viewWidth`/`viewWidthHeight` в `AdaptivityProvider`, то `sizeX`/`sizeY` все равно вычисляются в зависимости от ширины экрана
=>  Calculate sizeX/sizeY from viewWidth/viewHeight

src/components/ActionSheet/ActionSheet.tsx, src/components/PopoutWrapper/PopoutWrapper.css, src/components/PopoutWrapper/PopoutWrapper.tsx, src/components/ScreenSpinner/ScreenSpinner.css
Пролема исходит вот от сюда:
https://github.com/VKCOM/VKUI/blob/85d3ba3e107c382ded673015dff3d49893d4a757/src/styles/styles.css#L109-L114
Высота `<body>` и  `#root` всегда равна высоте viewport.
И все абсолютно-спозиционированные внутри body блоки с `width: 100%; height: 100%` (как например PopoutRoot--absolute), по высоте будут равны высоте `<body />`. То есть высоте и ширине вьюпорта.
Выглядит это вот так:
`.PopoutRoot--absolute`, который должен ловить `click` и закрывать `<ActionSheet />`, не тянется вниз и из-за этого появляется возможность клинуть на нижестоящие элементы. 
Изначально пытался решить проблему с высотой `<body>`, но решение предусматривает использование `min-height: 100vh` что сломает мобильную Safari. Возможно можно поправить при помощи …
=> Fix popout backdrop height on desktop

src/components/FixedLayout/FixedLayout.tsx, src/components/View/View.tsx
Фикс бага, который правит следующую проблему: если панель скроллится и динамически подгружает на себя данные каждый раз, когда пользователь переходит на неё, то FixedLayout в шапке панели позиционируется учитывая предыдущий скролл. А т.к. сама панель не скроллируемая, то скролл не восстанавливается и шапка отображается посередине окна.
=> Pkorchevskiy/bugfix/header jump/sak 1918

src/components/Tooltip/Tooltip.css
=> Fix Tooltip padding

src/components/PopoutWrapper/PopoutWrapper.css
=> PopoutWrapper: fix close from overlay click

src/components/ModalCard/ModalCard.tsx, src/components/ModalPage/ModalPage.tsx, src/components/ModalRoot/ModalRootAdaptive.tsx
При наличии мышки, модалки будут открываться в десктопной режиме, независимо от высоты экрана
=> Fix ModalPage/ModalCard adaptivity behavior on small screens

src/components/ActionSheet/ActionSheet.tsx
- добавлена проверка на наличие мышки и высоту экрана
- исправлен desktop брейкпоинт в соотвествии с дизайном
| | has mouse | no mouse |
|-|-|-|
| 768 x 667 | <img width="786" alt="image" src="https://user-images.githubusercontent.com/827338/104154488-1687f080-53f6-11eb-885c-c50e9a3fe8e6.png"> | <img width="779" alt="image" src="https://user-images.githubusercontent.com/827338/104154508-23a4df80-53f6-11eb-96cf-1f8a522bd51d.png"> |
| 768 x 414 (horizontal mobile) | <img width="786" alt="image" src="https://user-images.githubusercontent.com/827338/104154607-5cdd4f80-53f6-11eb-8fd3-b25d529bf277.png"> | <img width="780" alt="image" src="https://user-images.githubusercontent.com/827338/104154620-649cf400-53f6-11eb-9b8c-02c03f35cee9.png"> |
| 1024 x 667 | <img width="1038" alt="image" …
=> ActionSheet: proper breakpoint and mouse check for adaptivity

src/components/ModalCard/ModalCard.tsx, src/components/ModalPage/ModalPage.tsx, src/components/ModalRoot/ModalRoot.tsx, src/components/ModalRoot/ModalRootContext.tsx, src/components/ModalRoot/ModalRootDesktop.tsx
Если `onClose` не задан у ModalPage/ModalCard, будет использован onClose из родительского ModalRoot
=> Modals: pass onClose from ModalRoot to Page/Card

src/components/Counter/Readme.md, src/components/Tabs/Tabs.css
fixes #1232: цвет `<Counter/>` в `<TabsItem/>` для режимов `prominent` и `primary` теперь такой, как должен быть, кастомный цвет табов применяется только к (дефолтному) режиму `secondary`.
=> #1232 Неверный цвет Counter с пропом mode="prominent"

src/components/HorizontalCell/HorizontalCell.css, src/components/HorizontalCell/Readme.md
Обновлены паддинги у HorizontalCell, они применяются нижнему контенту.
fixes #1173
=> HorizontalCell: updated paddings and now they're applied to content

src/components/Badge/Badge.css, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Badge/Readme.md, src/components/SimpleCell/Readme.md, src/components/SimpleCell/SimpleCell.css, src/components/SimpleCell/SimpleCell.tsx, src/components/TabbarItem/TabbarItem.css, src/components/TabbarItem/TabbarItem.tsx, src/components/TabsItem/TabsItem.css, src/index.ts, src/styles/constants.css, src/styles/styles.css, styleguide/config.js
resolves #626: добавить возможность вставлять иконку или бейдж справа от заголовка.
- добавляет компонент `<Badge/>` с двумя модами - `new` и `prominent`
- добавляет в `<SimpleCell/>` возможность вставить бейджик справа от текста заголовка (иконку размером 12|16 или `<Badge/>`)
- добавляет `<Badge/>` в `<TabsItem/>`
- в `<TabbarItem/>`:
- добавляется новое свойство `indicator` (на замену текущему `label`), которое принимает в себя `ReactNode`. Ему можно передавать `<Badge mode="prominent" />` или `<Counter size="s" mode="prominent" />`
- `label` становится deprecated и будет удален в 5.0.0
=> #626 Компонент Badge

src/components/ModalDismissButton/ModalDismissButton.css, src/components/ModalDismissButton/ModalDismissButton.tsx, src/components/ModalDismissButton/Readme.md
Слева текущий вид иконки, справа после 
`.ModalDismissButton .Icon {
-webkit-transform: translateX(0);
}`
fixes #1300
=> ModalDismissButton: fixed icon misplacement and typo in readme.md

src/components/ModalRoot/ModalRoot.tsx
При скроле внутри HorisontalScroll или Textarea, скролл работал, но ModalRoot продолжал обрабатывать и проверять event.shiftY: если тач во время скрола смещался хоть немного вниз, это вызывало закрывание модалки
=> ModalRoot: prevent modal calculations while scrolling inside horizontal scroll

src/components/HorizontalScroll/HorizontalScroll.tsx, src/components/HorizontalScroll/Readme.md, src/lib/fx.ts
* `HorizontalScroll`: исправлено обновление состояния прокрутки после изменения `children`.
До этого `initialScrollWidth` устанавливалась единожды после первоначального рендера компонента. Из-за чего после смены `children` прокрутка, зависящая от `initialScrollWidth`, ломалась.
=> fix(HorizontalScroll): update initialScrollWidth on children change

src/components/Root/Root.tsx, src/components/View/View.tsx
`SplitCol`, `ConfigProvider` могут выключать анимацию переходов внутри компонентов Root и View, но даже в выключенном состоянии они применяют некоторые классы анимации
-> View, Panel во время перехода разворачиваются на весь экран
-> Компоненты, зависящие от ширины контейнера неправильно высчитывают ширину (Gallery, #1315)
=> Root, View: do not apply transition classes, if animation disabled

src/components/Checkbox/Checkbox.css, src/components/ModalRoot/Readme.md
Текст перекрывал паддинги чекбокса.
=> VKUI-129: label in checkbox now doesn't overlap paddings

src/components/SliderSwitch/Readme.md, src/components/SliderSwitch/SliderSwitch.tsx
Поправлены две ошибки реакта:
- fixes #1314: когда есть `activeValue`, больше не выскакивает "React does not recognize the `activeValue` prop on a DOM element"
- когда `activeValue` нет, при первом клике по свитчу больше не выскакивает "Warning: A component is changing an uncontrolled input of type hidden to be controlled"
=> #1314 SliderSwitch: фикс ошибок, связанных с `activeValue`

src/components/Snackbar/Snackbar.css, src/components/Snackbar/Snackbar.tsx
Snackbar использует FixedLayout, которые реагировал на переходы в родительском View
На многоколоночном SplitLayout, это вызывало баг: иногда снэкбар успевал отрендериться по левому краю родительской колонки, и уже затем выравнивался по левому краю: (красным выделен FixedLayout)
- Snackbar не использует FixedLayout внутри
https://user-images.githubusercontent.com/827338/105853037-4b9b6200-5ff6-11eb-829d-17052f33b6be.MP4
=> Snackbar: ignore view transitions

src/components/Tabs/Readme.md, src/components/TabsItem/TabsItem.css, src/components/TabsItem/TabsItem.tsx
- Добавлены стили по умолчанию для `Icon16Dropdown` в `.TabsItem__after`
- Обновлён пример
=> TabsItem: updated styles for dropdown icon inside after, updated example

src/components/CustomSelect/Readme.md, src/components/CustomSelectOption/CustomSelectOption.css, src/components/CustomSelectOption/CustomSelectOption.tsx
=> CustomSelectOption: prevented text area overflow

src/components/Group/Group.css, src/components/Group/Group.tsx
=> Group: adopt inner group paddings for compact size

src/components/DatePicker/DatePicker.css, src/components/DatePicker/Readme.md
- Добавлено свойство `min-width` к `.DatePicker__day` и `.DatePicker__year`, дабы предотвратить прыжки ширины.
- Изменены плейсхолдеры в примере так, чтобы они выглядели подобно соответственно форматам даты внутри.
=> DatePicker: added min-width properties for date & year to avoid jumps

src/components/Header/Header.css, src/components/Header/Header.tsx
Переносы отсутствуют, текст не эллипсится, также внутри `Header` есть `indicator={<Counter ...}`, который ушёл под `Link` с текстом "Показать всё".
Пример с Header без пропа `multiline`. Имеем `Counter` внутри indicator, который не выносится под "Показать всё". 
`children` корректно эллипсится, `subtitle` имеет переносы по-умолчанию.
Аналогичная ситуация, но с multiline:
fixes #1238
=> Header: added multiline prop

src/components/ModalRoot/ModalRoot.tsx
При захвате и одновременном закрытии модального окна (в данном примере через `setTimeout`) приложения зависали:
`<CellButton onClick={() => {this.setActiveModal(MODAL_PAGE_FILTERS); setTimeout(()={this.modalBack();}, 500)}}>`
=> ModalRoot: fixed hang when dragging and closing modal at same time

src/components/Banner/Banner.css
=> Banner: changed z-index to not to reflect border on PanelHeaderContext

src/components/ModalRoot/ModalRoot.css, src/components/ModalRoot/ModalRootDesktop.tsx
Изменения заметны при `webviewType={'vkapps'}`.
=> WIP: ModalRoot: removed viewport top value for vkcom platform

src/components/Avatar/Avatar.css, src/components/Avatar/Avatar.tsx
* `Avatar`: исправлен цвет иконки-плейсхолдера.
* `Avatar`: border-radius теперь наследуется, больше нет необходимости устанавливать его для каждого элемента.
=> Avatar fixes

src/components/HorizontalScroll/HorizontalScroll.e2e.tsx, src/components/HorizontalScroll/HorizontalScroll.tsx, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-bright_light-w_2-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-bright_light-w_3-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-space_gray-w_2-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-space_gray-w_3-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-does-not-have-arrows-on-mouse-hover-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-does-not-have-arrows-without-mouse-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-has-arrows-on-mouse-hover-1-snap.png
- Стрелки навигации будут показываться по дефолту при наличии мышки
- hover в e2e тестах:
=> HorizontalScroll: show arrows by default; fix props docs

src/components/ActionSheetItem/ActionSheetItem.css, src/components/ActionSheetItem/ActionSheetItem.tsx, src/components/Banner/Banner.css, src/components/Banner/Banner.tsx, src/components/Button/Button.css, src/components/Button/Button.tsx, src/components/IconButton/IconButton.css, src/components/IconButton/IconButton.tsx, src/components/Link/Link.css, src/components/Link/Link.tsx, src/components/ModalDismissButton/ModalDismissButton.css, src/components/ModalDismissButton/ModalDismissButton.tsx, src/components/PanelHeaderButton/PanelHeaderButton.css, src/components/PanelHeaderButton/PanelHeaderButton.tsx, src/components/PanelHeaderContent/PanelHeaderContent.css, src/components/PanelHeaderContent/PanelHeaderContent.tsx, src/components/Search/Search.css, src/components/SliderSwitch/SliderSwitchButton.tsx, src/components/SubnavigationButton/SubnavigationButton.tsx, src/components/TabsItem/TabsItem.css, src/components/TabsItem/TabsItem.tsx, src/components/Tappable/Tappable.css, src/components/Tappable/Tappable.tsx
Вместо `activeHighlighted` и `hoverBackground` добавил свойства `activeMode` и `hoverMode` соответственно.
Преимущества:
1. Можно задать более двух значений. `background`, `opacity` или произвольно (о нём ниже)
2. Проще читается (субъективно)
3. Избавляет от нужды обращаться к классам `.Tappable` внутри стилей компонент, его использующих. Пример: `ModalDismissButton`. Если в `activeMode` (или `hoverMode`) передать произвольную строку, она навесится на `Tappable` как css-класс.
=> Tappable: hoverMode and activeMode props

src/components/ContentCard/ContentCard.tsx
В restProps попадает "maxHeight", из-за этого возникает предупреждение, т.к. React  добавляет атрибут "maxheight" к тегу img.
=> Убираем предупреждение о неизвестном атрибуте maxheight у img в компоненте ContentCard

.github/workflows/pull_request.yml, .github/workflows/update_screens.yml, package.json
Ускоряем пайплайн: 5:40 -> 3:10
- –20c на все джобы обновлением npm-install экшна
- –2,5 минуты на сайзлимит через --ignoreScripts + кеш нод-модулей
Сайз-лимит все еще работает, см. https://github.com/VKCOM/VKUI/pull/1379
=> INFRA: Ускорить ci

src/components/ModalPageHeader/ModalPageHeader.css
Для iOS устройств с шириной вьюпорта >= 320px, заголовок модалки будет растягиваться сильнее по отношению к боковым кнопкам (1|3|1)
Live example https://vkui-cra-rewired-app-git-modal-page-header.ewgenius.vercel.app
| Before | After |
|-|-|
| <img width="460" alt="image" src="https://user-images.githubusercontent.com/827338/108590406-74541480-7374-11eb-95d6-f49cc147cd61.png"> | <img width="461" alt="image" src="https://user-images.githubusercontent.com/827338/108590411-80d86d00-7374-11eb-89f2-b8320984adfe.png"> |
=> ModalPageHeader: more wide header content

src/components/ActionSheet/ActionSheet.css, src/components/ActionSheet/ActionSheet.tsx
=> ActionSheet: ignoring PopoutWrapper event on desktop platforms

src/components/ModalPageHeader/ModalPageHeader.css, src/components/ModalPageHeader/__image_snapshots__/modalpageheader-ios-bright_light-w_2-1-snap.png, src/components/ModalPageHeader/__image_snapshots__/modalpageheader-ios-bright_light-w_5-1-snap.png, src/components/ModalPageHeader/__image_snapshots__/modalpageheader-ios-space_gray-w_2-1-snap.png, src/components/ModalPageHeader/__image_snapshots__/modalpageheader-ios-space_gray-w_5-1-snap.png, src/components/PanelHeader/PanelHeader.css, src/components/PanelHeaderButton/PanelHeaderButton.css, src/components/PanelHeaderButton/PanelHeaderButton.tsx
* Обновлены инсеты для примитивного PanelHeaderButton (с текстом внутри), актуально для iOS.
=> PanelHeaderButton: updated insets, styles cleanup

src/components/ModalRoot/Readme.md
Убран неактуальный проп `fullscreen` из примера с модальными окнами.
#1427
=> Modals: removed not necessary 'fullscreen' prop from docs

src/components/SliderSwitch/SliderSwitch.tsx
**onSwitch** попадал в **restProps** и React пытался добавить свойство **onSwitch** к тегу **div**, что приводило к сообщению:
_Warning: Unknown event handler property `onSwitch`. It will be ignored._
=> onSwitch теперь не добавляется к div

src/components/CustomSelectOption/CustomSelectOption.tsx, src/components/Typography/Text/Text.tsx
В некоторых файлах импорт типа HasRootRef был через неоднозначный путь. В итоге в сторонних проектах при импорте этих компонентов тайпчекер TS ругается на неизвестный модуль 'types'.  
Из-за этого невозможно использовать компоненты в проектах с typescript проверкой самого vkui.
Пример ошибки:
```
node_modules/@vkontakte/vkui/dist/components/CustomSelectOption/CustomSelectOption.d.ts:2:28 - error TS2307: Cannot find module 'types' or its corresponding type declarations.
2 import { HasRootRef } from 'types';
~~~~~~~
node_modules/@vkontakte/vkui/dist/components/Typography/Text/Text.d.ts:2:28 - error TS2307: Cannot find module 'types' or its corresponding type declarations.
2 import { HasRootRef } from 'types';
~~~~~~~
Found 2 errors.
```
Пути заменены на однозначные относительные.
=> fix: ambiguous path in type imports of HasRootRef causing typecheck errors

src/index.ts, src/lib/classNames.test.ts, src/lib/classNames.ts
* `{ classNames } from '@vkontakte/vkui'` всегда возвращает строку, как раньше
* `{ classNames} from '@vkontakte/dist/utils/classNames'` теперь падает, но это и не публичный интерфейс
=> fix: Восстановить интерфейс публичного classNames

src/components/Banner/Banner.tsx
If you pass an empty array to actions prop, the component renders empty .Banner__actions div
**Before:**
**After:**
=> fix(Banner): Check actions prop emptiness

src/components/FixedLayout/FixedLayout.tsx, src/components/View/View.tsx
при переходе назад на панель, с отскроленным контентом хедер скачет после перехода
в фиксе #1250 был добавлен обработчик, подстраивающий FixedLayout внутри PanelHeader под высоту скролла во время перехода
| Before | After |
|-|-|
|![CleanShot 2021-03-15 at 13 27 39](https://user-images.githubusercontent.com/827338/111139641-6cae1700-8592-11eb-9417-d8332947260f.gif)|![CleanShot 2021-03-15 at 13 30 24](https://user-images.githubusercontent.com/827338/111139855-b26adf80-8592-11eb-9858-c169cbacdcdd.gif)|
=> FixedLayout: fix scroll adjustment during panel transitions

src/components/Header/Header.css, src/components/Header/Header.tsx, src/components/Header/Readme.md
* При `<Header multiline ...` режем только длинные слова.
* Обновлены примеры:
* Обновлено условие для модификатора, `.Header__content-base` не должен быть опциональным.
По мотивам #1466.
=> Header now cuts only long words 

src/components/SplitLayout/SplitLayout.css
Проблема: на iOS при наличии PanelHeader в SplitLayout, основной контент поднимается вверх только на высоту хедера, без учета safe-area-inset
=> Use top inset to calculate layout offset properly on iOS

src/components/ModalRoot/ModalRoot.tsx
=> ModalRoot: responding to viewport changes

src/components/Textarea/Textarea.tsx
Сейчас rezise вызывается только на onChange, но если значение изменяется извне - resize не происходит
=> fix(Textarea): controlled outside resize when value changes

src/components/AppRoot/AppRoot.tsx
В доке баг с восстановлением скролла из-за доступа к глобальному `document` (на [этой строке](src/components/AppRoot/ScrollContext.ts) как раз ничего не поменялось)
=> docs: Fix document access in AppRoot

src/components/Cell/Cell.css, src/components/Cell/Cell.e2e.tsx, src/components/Cell/__image_snapshots__/cell-android-bright_light-1-snap.png, src/components/Cell/__image_snapshots__/cell-android-space_gray-1-snap.png, src/components/Cell/__image_snapshots__/cell-ios-bright_light-1-snap.png, src/components/Cell/__image_snapshots__/cell-ios-space_gray-1-snap.png, src/components/Cell/__image_snapshots__/cell-vkcom-vkcom-1-snap.png, src/components/FormItem/FormItem.css, src/components/FormItem/FormItem.tsx, src/components/FormLayoutGroup/FormLayoutGroup.css, src/components/IconButton/IconButton.css, src/components/Removable/Removable.css, src/components/Removable/Removable.tsx
Fixes #1527: при отсутствии пропа multiline в Cell с removable приходящие внутрь children теперь обрезаются так, как нужно.
Дополнительно:
+ пофиксила a11y для Removable для правильного tab order,
+ добавила e2e-тесты и скриншоты для разных состояний Cell,
+ попереносила и поправила Removable-стили для всех removable компонентов.
=> [Bug] #1527 Cell с атрибутом removable не обрезает children

src/components/Chip/Chip.test.tsx, src/components/Chip/Chip.tsx, src/components/ChipsInput/ChipsInput.test.tsx, src/components/ChipsInput/ChipsInput.tsx, src/components/ChipsInput/useChipsInput.ts
Fixes #1184: чип теперь не удаляется, если ввести его еще раз, а переносится в конец.
- Оптимизировала под это решение проходку по массиву опций,
- Добавила юнит-тесты для ChipsInput,
- Пофиксила передачу пропа option в Chip. 😄
=> [Bug] #1184 ChipsInput Удаляется чип, если ввести его еще раз

src/components/ChipsSelect/ChipsSelect.tsx, src/components/File/File.tsx, src/components/WriteBar/WriteBar.tsx, src/hooks/useExternRef.test.tsx, src/hooks/useExternRef.ts
Добавляю хук `useExternRef` для корректной обработки кейсов, где мы используем реф внутри компонента + поддерживаем `get(Root)Ref`. Мотивационные примеры, которые поддерживает реализация:
```jsx
const VkuiInput = (props) => {
const ref = useExternRef(props.getRef);
useEffect(() => {
ref.current.focus();
}, []);
return <input ref={ref} />;
}
```
1. `<VkuiInput getRef={ref} />`: `ref.current` всегда готов в момент `useLayoutEffect`
2. `<VkuiInput getRef={useCallback(e => longRunningOp(e), [])}` вызывается только один раз
3. `props.hidden ? null : <input />`: `getRef` выставится в null при `hidden={true}`
4. `createElement(props.disabled ? 'div' : 'input', { ref }): getRef обновится при смене `input` на `div`
5. `showInput && <VkuiInput getRef={ref} />`: `ref.current = null` при `showInput = …
=> useExternRef

src/components/Switch/Switch.css, src/components/Switch/Switch.e2e.tsx, src/components/Switch/Switch.test.tsx, src/components/Switch/Switch.tsx, src/components/Switch/__image_snapshots__/switch-android-bright_light-1-snap.png, src/components/Switch/__image_snapshots__/switch-android-space_gray-1-snap.png, src/components/Switch/__image_snapshots__/switch-ios-bright_light-1-snap.png, src/components/Switch/__image_snapshots__/switch-ios-space_gray-1-snap.png, src/components/Switch/__image_snapshots__/switch-vkcom-vkcom-1-snap.png, src/index.ts
Привела в порядок дизайн компонента Switch:
- Android: цвет подложки теперь — `accent` с прозрачностью в соответствии с [макетом для Android](https://www.figma.com/file/lLXmjJhnJa4OhgZXzcNJD9/VKUI-Android-Library?node-id=69%3A5521) (fixes #1077);
- iOS: вместо границы в `disabled`-состоянии теперь подложка в соответствии с [макетом для iOS](https://www.figma.com/file/kvjzdHwTDO7Vcrh1VglGQ5/VKUI-iOS-Library?node-id=12785%3A0) (fixes #1560);
Также добавила скриншотные тесты для компонента и подчистила css.
=> Switch: обновление дизайна в соответствии с макетами

src/components/FixedLayout/FixedLayout.tsx
fixes #1559 
[codesandbox demo](https://codesandbox.io/s/vkui-ios-panel-transition-fix-demo-2jn5j) (wait for sandbox CI to pick it up)
| Before | After |
|-|-|
| ![CleanShot 2021-04-27 at 10 21 29](https://user-images.githubusercontent.com/827338/116201693-748cd980-a742-11eb-9e9e-f8f120d5514b.gif) | ![CleanShot 2021-04-27 at 10 23 05](https://user-images.githubusercontent.com/827338/116201822-9a19e300-a742-11eb-8d51-880831717df3.gif) |
=> FixedLayout: fix PanelHeader adjustment during panel transition on iOS

styleguide/Components/PlaygroundRenderer.js, styleguide/Components/Preview.js, styleguide/config.js, styleguide/setup.js, styleguide/utils.js
1. В проде используем профилировочную сборку реакта
2. В консоли можно `perfLogger.isEnabled = true`, и тайминги примеров будут падать в консоль
=> Docs: Add react profiler in styleguide

styleguide/Components/Preview.js
Сейчас стили вставляются в iframe примера после рендера, и измерения размера в доке не работают (например, не свайпается галерея)
=> docs: Inject styles into iframe before render

src/components/Epic/Epic.tsx, src/components/ModalCard/ModalCard.test.tsx, src/components/ModalCard/ModalCard.tsx, src/components/ModalPage/ModalPage.test.tsx, src/components/ModalPage/ModalPage.tsx, src/components/ModalRoot/ModalRoot.tsx, src/components/ModalRoot/ModalRootDesktop.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, src/components/Root/Root.tsx, src/components/View/View.tsx, src/components/View/ViewInfinite.tsx, src/lib/getNavId.test.ts, src/lib/getNavId.ts
Продолжаем готовиться ко встраиванию vkui в вк. Сейчас идентификатор навигационных компонентов (`View`, `Panel`, `ModalPage`, `ModalCard`) прокидывается через проп `id`. При этом id — DOM-проп, и прокидывается на DOM-элемент. Значит, id может конфликтовать с другими id на странице — например, делать неопределенным поведение getElementById в хост-аппе. По итогам #1414, #1400, #1398 сам vkui не зависит от id.
В этом ПР:
- Поддерживаем передачу навигационного идентификатора через проп `nav`, чтобы не поощрять конфликты
- Все еще поддерживаем `id`, чтобы сохранить обратную совместимость.
- Добавляем полезный ворнинг, если нет ни одного идентификатора
Поведение `View`, который не прокидывает id в DOM — баг, но его исправление будет брейкинг ченджем.
=> feat: Allow nav prop instead of id for navigation items

src/components/Gallery/Gallery.tsx
Before:
After:
Sandbox https://codesandbox.io/s/vkui-default-example-forked-ldd8p?file=/index.tsx
=> Gallery: fix arrows visibility for case when multiple slides visible

src/components/Gallery/Gallery.test.tsx, src/components/Gallery/Gallery.tsx
если сейчас передать пустые слайды в `Gallery`, `slideIndex` встанет в `-1` и застрянет там, так что если слайды появятся, свайпать будет нельзя. Новое поведение:
1. При `slideCount == 0` не нормализуем `slideIndex`, потому что любой будет некорректным, а так поддерживаем `slideIndex={3}` с ленивой инициализацией слайдов (отскроллится на 3, когда появятся слайды)
2. `slideIndex` внутри всегда нормализуется, чтобы нельзя было сломать галерею `slideIndex` без `onChange`
3. При нормализации `slideIndex` плюем `onChange`, чтобы в controlled-режиме контроллер синхронизировался
=> fix: Support lazy slide initialization in Gallery

src/components/ModalRoot/ModalRoot.tsx
fixes #1585 
bug reproduction - https://codesandbox.io/s/modals-example-forked-voidz?file=/example.tsx (sandbox with fix - https://github.com/VKCOM/VKUI/pull/1610#issuecomment-844016686)
=> ModalRoot: check page content only if modal type is ModalPage

src/components/FormField/FormField.css
This change will make it possible to pass in `after` prop not only one `Icon` or `IconButton`, but also text, which can be more than 44px.
=> fix(FormField): Replace width property of after element with min-width

package.json, postcss.config.js, src/components/Spinner/Spinner.css, src/styles/animations.css, stylelint.config.js, yarn.lock
Продолжаю дербанить #1335 на кусочки.
- В `unstable.css` теперь тоже есть фолбеки для css custom properties
- Линтер ругается на неизвестный custom properties
- `--duration` и `@keyframes vkui-rotator` переехали из `Spinner.css` в `animations.css`, потому что используются еще и в `PullToRefresh`
=> Fix: корректная работа с css custom properties

.eslintrc.json, src/components/NativeSelect/NativeSelect.tsx, src/components/PanelHeaderBack/PanelHeaderBack.tsx, src/components/PanelHeaderContent/PanelHeaderContent.tsx, src/components/Search/Search.tsx, src/components/SelectMimicry/SelectMimicry.tsx, src/components/Textarea/Textarea.tsx
Запрещаем импортить индекс, потому что
1. Это ломает определение измененных файлов в тестах
1. Циклические импорты нехорошо
=> style: Disallow index imports

src/components/ActionSheet/ActionSheet.test.tsx, src/components/ActionSheetItem/ActionSheetItem.tsx
fixes #1491
Детали бага:
1. Клик по `<label class="ActionSheetItem">`
2. Срабатывает onItemClick 
3. в ActionSheet из-за autoclose вылетает onClose
4. onClose анмаунтит ActionSheet
5. клик с label не успевает продублироваться на `input`
Без autoclose бага нет, потому что ActionSheet не анмаунтится
На мобилке бага нет, потому что `onClose` срабатывает после анимации, и за это время как раз отрабатывает `onChange`
=> [Bug] Не срабатывает onChange у ActionSheet

src/components/PopoutRoot/PopoutRoot.tsx
fixes #1637
https://codesandbox.io/s/f5n2j?resolutionWidth=1000&resolutionHeight=675
=> PopoutRoot: use proper isDesktop breakpoint, to be consistent with ActionSheet

src/index.ts
Экспортируем тип `NavIdProps` для:
- использования в кастомных навигационных элементах 
- возможности безопасного депрекейта `id`  
fixes #1660
=> types: Export NavIdProps from package

src/components/Root/Root.tsx
- fixes #1655 
- Просто тип добавил, всё куда можно пихнуть `Root` вроде поддерживает `nav`
=> feat: Allow nav prop in Root

package.json
Не собираем cjs и d.ts, которые не нужны для анализа размера + параллелим css и js = 80 -> 22c на локальный анализ размера
=> INFRA: Faster yarn size local runs

src/components/ChipsSelect/ChipsSelect.tsx, src/components/HorizontalScroll/HorizontalScroll.tsx, src/components/Removable/Removable.tsx, src/components/Tooltip/Tooltip.tsx, src/hooks/useEventListener.ts, src/hooks/useGlobalEventListener.ts
`useEventListener`:
- не привязывается к элементу два раза
- сам удаляется при анмаунте
- всегда вызывает актуальный колбек
`useGlobalEventListener` заодно автоматически подвязывается к стабильному элементу
=> refactor: Add useEventListener hook

src/components/Gallery/Gallery.tsx, src/components/Snackbar/Snackbar.tsx, src/hooks/useTimeout.test.ts, src/hooks/useTimeout.ts
Новый хук `useTimeout`:
- всегда вызывает актуальный листенер, даже если он изменился после setTimeout
- самоуничтожается при анмаунте
=> refactor: Add useTimeout hook

src/components/ModalRoot/ModalRoot.tsx
Фикс скролла для фулскрин модалок с динамиеским контентом
- изначально все модалки открываются не на всю высоту, и если контент больше экрана то ее нужно вытащить вверх после чего уже будет доступен скролл
- для фулскрин модалок требуется дополнительный клик чтобы скролл заработал, но он должен быть доступен сразу
Пример:
https://codesandbox.io/s/modals-example-forked-3nb2z?file=/example.tsx&resolutionWidth=320&resolutionHeight=675
По логике имплементации, модалка с settlingHeight = 100 должна быть сразу в режиме expandable
=> ModalPage: set expandable if settlingHeight === 100

src/components/ModalRoot/withModalRootContext.tsx
Поребейзил несправедливо потерявшийся #1352 от @wolframdeus 
Убирает из пропов обернутого в `withModalHeight` `updateModalHeight` — fixes #1353
=> types: Update typings for withModalRootContext

src/components/Alert/Alert.css, src/components/Button/Button.css, src/components/CellButton/CellButton.css, src/components/ChipsInput/ChipsInput.css, src/components/ChipsSelect/ChipsSelect.css, src/components/IconButton/IconButton.css, src/components/Input/Input.css, src/components/Link/Link.css, src/components/PanelHeaderButton/PanelHeaderButton.css, src/components/Removable/Removable.css, src/components/Search/Search.css, src/components/Select/Select.css, src/components/SliderSwitch/SliderSwitch.css, src/components/Textarea/Textarea.css, src/components/WriteBar/WriteBar.css, src/components/WriteBarIcon/WriteBarIcon.css, src/styles/components.css
Fixes #1682: у стрелок в `SubnavigationBar` больше нет `outline` при фокусе.
Заодно порефакторила стили `outline` в принципе — теперь они все локально убраны в одном месте, а не раскиданы по компонентам.
(`outline` обязательно вернется, но уже в процессе работы над доступностью. И выглядеть будет прилично.)
=> fix(SubnavigationBar): Remove button outline

src/components/HorizontalScroll/HorizontalScroll.tsx
fixes #1588 
Немного сомнительно, что getRef передаётся не на главный элемент, но это кажется самым полезным местом и не поощряет ковыряние в доме
=> feat: Support getRef in HorizontalScroll

src/components/Header/Header.tsx, src/components/Typography/Caption/Caption.css
- Добавила семантики для `<Header/>`,
- Добавила в типографический `Caption` ресет марджина, чтобы можно было передавать ему заголовки как `Component`,
- Порефакторила внутренности:
- `renderChildren()` => `HeaderContent`
- `renderAside()` => `HeaderAside`
=> Доступность: семантический Header

src/components/ChipsInput/ChipsInput.css, src/components/ChipsInput/__image_snapshots__/chipsinput-android-bright_light-1-snap.png, src/components/ChipsInput/__image_snapshots__/chipsinput-ios-bright_light-1-snap.png, src/components/FormField/FormField.css
Фикс вдогонку к #1709:
- Подправила еще паддинги-марджины для `ChipsInput` и `ChipsSelect`, чтобы скриншотные тесты не валились (а с помощью @thoughtspile избавились от дичи вообще);
- Те скриншоты, в которых был обрезанный текст в инпутах — обновила.
=> ChipsInput: fix paddings and margins

src/components/ConfigProvider/ConfigProvider.test.tsx, src/components/ConfigProvider/ConfigProvider.tsx, styleguide/pages/modes.md
Текущее поведение: `<ConfigProvider platform={VKCOM} scheme="inherit">` форсирует `scheme="vkcom"` и перезаписывает `body[scheme]` при встраивании в vk.com
После фикса `scheme="inherit"` сохраняется для любой платформы
=> Fix: Allow scheme=inherit on VKCOM

babel.config.js, package.json, src/components/AdaptivityProvider/AdaptivityProvider.tsx, src/components/Tappable/Tappable.tsx, src/lib/browser.ts, src/lib/dom.tsx, yarn.lock
__TLDR:__ Убираем `prop-types`, `@babel/runtime` и `@vkontakte/vkjs` из `peerDependencies` без изменения размера конечного бандла, `vk-bridge` пока не трогаем
Cлучайно остались после #954 и #1282, просто убираем его
Переносим в `dependencies` с +250b
|       |  Кb JS, min + gzip |
| --- | --- |
| Текущий, без учета рантайма | 54.58 |
| С явной версией рантайма      | 54.80 |
| Текущий, включая рантайм     | 55.95 |
| Без transform-runtime               | 63.38, плохо |
Сейчас полная библиотека добавляет 54.58..55.95Kb в зависимости от пересечения используемых хелперов из рантайма с конечным аппом. 
Если мы заносим рантайм в dependencies, то можем смелее обновлять версию (обновление версии в peerDeps это breaking change, потому что приложения перестанут собираться). За счет [лучшей …
=> refactor: Remove useless peer deps

src/components/Button/Button.css
Убирает перенос текста в Button.
fixes #1678
=> Button's content is no longer wrapped

src/components/CustomSelect/CustomSelect.css, src/components/CustomSelect/CustomSelect.tsx, src/components/CustomSelect/Readme.md
Режим поиска в `CustomSearch`. [Пример](https://vkcom.github.io/VKUI/pull/1727/#/CustomSelect).
Добавлены три свойства:
- `searchable` включает/выключает этот режим
- `emptyText` отвечает за отображение состояния пустых `options`
- `onSearchChange` предназначено для гибкой настройки поведения поиска
- Если свойство не передано, то поиск осуществляет автоматически по `option.label`. Пример "Поиск по списку"
- Если свойство передано и возвращает массив, то компонент воспринимает его как результат кастомного поиска и рисует по нему список опций. Пример "Кастомный алгоритм поиска"
- Если свойство передано и ничего не возвращает, то компонент подразумевает, что разработчик самостоятельно обновит свойство `options`. Пример "Кастомное поведение при поиске"
fixes #1551
=> CustomSelect: search

src/components/Search/Search.css
Пофиксила отрицательный `margin-top` у `Search` внутри `Group`: теперь он применяется, только если `Search` – первый child у `Group`.
=> [Bug] Search: отрицательный margin внутри Group

src/components/Avatar/Avatar.css, src/components/Avatar/Avatar.tsx, src/components/CellButton/CellButton.css, src/components/Gradient/Gradient.tsx, src/components/PanelHeader/PanelHeader.css, src/components/RichCell/RichCell.css, src/components/SimpleCell/SimpleCell.css
=> Доступность: alt, role и aria-атрибуты для компонентов с изображениями и иконками

src/components/Button/Button.tsx, src/components/PanelHeader/PanelHeader.tsx, src/components/PanelHeaderButton/PanelHeaderButton.tsx, src/components/SliderSwitch/SliderSwitchButton.tsx, src/components/Typography/Caption/Caption.css, src/components/Typography/Caption/Caption.tsx, src/components/Typography/Headline/Headline.css, src/components/Typography/Headline/Headline.tsx, src/components/Typography/Subhead/Subhead.css, src/components/Typography/Subhead/Subhead.tsx, src/components/Typography/Text/Text.css, src/components/Typography/Text/Text.tsx, src/components/Typography/Title/Title.css, src/components/Typography/Title/Title.tsx, src/components/Typography/Title/__image_snapshots__/title-android-bright_light-1-snap.png, src/components/Typography/Title/__image_snapshots__/title-android-space_gray-1-snap.png, src/components/WriteBarIcon/WriteBarIcon.tsx
Подчистила типографические компоненты:
- упростила то, как задаются `weight` и `Component`, передоверила упрощения стилей для андроида css;
- проставила для `Text` и `Caption` в качестве дефолтного компонента `span` с `display: block;` в стилях;
- добавила скриншотные тесты (и, кажется, отловила ошибку в `Title`) — _переехало в #1735_;
- выкинула лишние `Component="span"`. 😄
=> refactor: Типографические компоненты

package.json, src/components/CustomSelect/CustomSelect.test.tsx, src/components/CustomSelect/CustomSelect.tsx, src/components/CustomSelect/Readme.md
* Убрал `handleDocumentClick`. Кажется, тут этот обработчик не нужен, так как `onBlur` на `Input/SelectMimicry` успешно скрывает список опций когда надо.
* Обновляю значение `selectedOptionIndex` при поиске, так как иначе выбранной подсвечивается не та опция.
* Задепрейтил фильтрацию через `return` у `onInputChange`. Такой подход приводит к конфликтам `props.options` и `state.options`.
* Добавил свойство `filterFn` для кастомной фильтрации.
* Починил `props.onClick` в `searchable` режиме.
* В режиме поиска передаю `{...restProps}` на `Input`
=> CustomSelect: fixes

src/components/ActionSheetItem/ActionSheetItem.test.tsx, src/components/ActionSheetItem/ActionSheetItem.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/ContentCard/ContentCard.test.tsx, src/components/ContentCard/ContentCard.tsx, src/components/HorizontalCell/HorizontalCell.tsx, src/components/IconButton/IconButton.test.tsx, src/components/IconButton/IconButton.tsx, src/components/Link/Link.test.tsx, src/components/Link/Link.tsx, src/components/ModalDismissButton/ModalDismissButton.tsx, src/components/PanelHeaderButton/PanelHeaderButton.test.tsx, src/components/PanelHeaderButton/PanelHeaderButton.tsx, src/components/RichCell/RichCell.tsx, src/components/SimpleCell/SimpleCell.tsx, src/components/Tappable/Tappable.css, src/components/Tappable/Tappable.test.tsx, src/components/Tappable/Tappable.tsx
- Обнаружила, что в `Tappable` могли неправильно проставляться `role` и `type`. Подправила логику их проставления; заодно перенесла туда же выбор `Component` в зависимости от наличия/отсутствия `href`.
- Отрефакторила компоненты на базе `Tappable`, убрав ставший лишним код.
- Обновила юнит-тесты для `Tappable`.
=> Доступность кнопок и ссылок: фиксы Tappable

src/components/ConfigProvider/ConfigProvider.tsx
Исправил обращения к `document.body` без проверки на `canUseDom`
=> ConfigProvider: fixed SSR

src/components/Avatar/Avatar.test.tsx, src/components/ContentCard/ContentCard.test.tsx, src/components/ContentCard/ContentCard.tsx, src/components/ContentCard/Readme.md
По мотивам комментария Артура к #1726: перекинула `{...restProps}` на `Tappable` вместо `<img />`.
Заодно предлагаю задепрекейтить проп `image` и выкинуть его в v5, а пока использовать наравне с классическим `src`.
=> refactor: ContentCard

src/components/Badge/Badge.css, src/components/Banner/Banner.css, src/components/Banner/Banner.tsx, src/components/Button/Button.css, src/components/Button/Button.tsx, src/components/FocusVisible/FocusVisible.css, src/components/FocusVisible/FocusVisible.tsx, src/components/Link/Link.tsx, src/components/MiniInfoCell/MiniInfoCell.css, src/components/PanelHeaderButton/PanelHeaderButton.tsx, src/components/Removable/Removable.css, src/components/Removable/Removable.tsx, src/components/RichCell/RichCell.css, src/components/SubnavigationButton/SubnavigationButton.tsx, src/components/Tabs/Tabs.tsx, src/components/TabsItem/TabsItem.css, src/components/TabsItem/TabsItem.tsx, src/components/Tappable/Tappable.css, src/components/Tappable/Tappable.test.tsx, src/components/Tappable/Tappable.tsx, src/components/UsersStack/UsersStack.css, src/lib/accessibility.ts, src/styles/components.css
- Перенесла стили для аутлайна при фокусе с клавиатуры в новый компонент `FocusVisible`,
- Добавила мод `inside`, который нужен нам в большинстве компонентов для красивой подсветки, которая не уходит за границы элемента (например, для разнообразных ячеек),
- Отрефакторила `Tappable`, чтобы использовать `FocusVisible`.
- Убрала временный `hasFocusVisible`.
Должны работать все кликабельные кнопки и ссылки, включая кликабельные ячейки, **кроме**:
- `WriteBarIcon` — будет отдельно,
- Кнопка удаления чипа в `Chip` — будет поправлена в рамках задачи по доступности `ChipsInput`/`ChipsSelect`.
=> Доступность: focus visible у всех кнопок и ссылок

src/components/CustomSelect/CustomSelect.tsx, src/components/CustomSelectOption/CustomSelectOption.tsx
* Убираем `option` deprecate внутрь `CustomSelectOption`. Сейчас ts ругается, когда человек обращается к `option` внутри `renderOption` (в аргументе этой функции тип описан через `CustomSelectOptionProps`). Можно было бы разделить эти два интерфейса, но кажется, что унести ворнинг проще.
* ~~Обрабатываем `onMouseEnter` на `disabled` опции. Сейчас если сначала навести на разблокированную опцию, а потом на `disabled`, то при клике по `disabled` выберется разблокированная.~~
* Обрабатываем `onClick` по `disabled` опции. Сейчас если сначала навести на разблокированную опцию, а потом на `disabled`, то при клике по `disabled` выберется разблокированная. Сначала я попробовал решить эту проблему с помощью mouseenter, но там начались сложные приколы с наведенной на disabled мышкой и клавиатурной …
=> Custom select fixes

src/components/ModalPage/ModalPage.css, src/components/Separator/Separator.css
- Поправила скругления в `ModalPage`,
- Немного причесала css,
- Перенесла относившийся к `Separator` стиль в `Separator.css`.
=> [Bug] Скругления в модальных окнах не соответствуют макетам

src/components/Button/Button.e2e.tsx, src/components/Button/__image_snapshots__/button-android-bright_light-1-snap.png, src/components/Button/__image_snapshots__/button-android-space_gray-1-snap.png, src/components/Button/__image_snapshots__/button-ios-bright_light-1-snap.png, src/components/Button/__image_snapshots__/button-ios-space_gray-1-snap.png, src/components/Button/__image_snapshots__/button-vkcom-vkcom-1-snap.png
Состояния кнопки, зафиксированные в обновленном тесте:
=> [e2e] Button: update screenshot tests

src/components/Checkbox/Checkbox.e2e.tsx, src/components/ChipsInput/ChipsInput.tsx, src/components/Removable/Removable.css, src/hooks/useAdaptivity.ts, src/testing/e2e/utils.tsx
По совету @thoughtspile обновила `describeScreenshotFuzz` так, чтобы в `useAdaptivity()` больше не надо было передавать пропсы для корректной работы скриншотных тестов. Ура!
=> feat(useAdaptivity): update describeScreenshotFuzz

src/components/FormItem/FormItem.tsx, src/components/FormLayoutGroup/FormLayoutGroup.tsx
- пофиксила баг в патче
- сходила проверить, нет ли такого же в `FormLayoutGroup`, и обнаружила, что там в принципе реф не висел на контейнере
=> [bug] getRootRef в FormItem

src/hoc/withAdaptivity.tsx, src/hooks/useAdaptivity.ts
Если использовать `vite` с `VKUI`, то выдаёт следующую ошибку:
Это происходит из-за того, что в готовых `js` файлах идет импорт типа `AdaptivityProps`. Теперь вместо обычного импорта используется `import type`, что фиксит это поведение и ошибка больше не возникает.
=> fix: use import type instead of import for AdaptivityProps

src/components/ActionSheet/ActionSheetDropdown.tsx, src/components/ActionSheet/ActionSheetDropdownDesktop.tsx, src/components/ModalRoot/ModalRootDesktop.tsx, src/components/NativeSelect/NativeSelect.tsx, src/components/PullToRefresh/PullToRefreshSpinner.tsx, src/components/RangeSlider/UniversalSlider.tsx, src/components/Select/Select.tsx, src/components/SelectMimicry/SelectMimicry.tsx, src/components/Slider/Slider.tsx, src/components/SliderSwitch/SliderSwitchButton.tsx, src/components/View/ViewInfinite.tsx, src/index.ts
Потерялись импорты CSS в случаях, когда `Component.tsx` использует CSS не из `./Component.css`
=> fix: Import irregularly named CSS files

src/components/HorizontalScroll/HorizontalScrollArrow.css
Эти стили мы снесли вот тут #1611 и зря
fixes #1841
=> HorizontalScrollArrow: safari shadow fix

src/hooks/useKeyboardInputTracker.ts, src/lib/accessibility.ts
Добавила хелпер  `pressedKey()`, чтобы каждый раз не писать руками проверку на `key` (и фоллбек на `keyCode` для старых браузеров).
=> a11y: `pressedKey()` helper

src/components/AppRoot/AppRoot.test.tsx, src/hooks/useKeyboardInputTracker.test.tsx, src/hooks/useKeyboardInputTracker.ts
- поправила баг, нарисовавшийся после переезда на `pressedKey(e)`
- обновила и пофиксила тесты
- вынесла тесты, фактически относящиеся к работе `useKeyboardInputTracker()`, в отдельный файл
=> [Bug] useKeyboardInputTracker()

src/components/Touch/Touch.test.tsx, src/components/Touch/Touch.tsx, src/lib/touch.ts
Открыто для обсуждения:
- Исправил явный баг — при переданном `onMove` при любое перемещение определяется как slideX и slideY одновременно. Сломается ли при этом что-нибудь из нашего кода?
- Можем ли мы завязаться на [pointer-events](https://caniuse.com/pointer-events) вместо явного переключения по `window.ontouchstart`?
- Не нужен трюк с глобальными листенерами для mouseMove — есть [setPointerCapture](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture)
- Не нужна полиморфная обработка clientX / clientY
- Почему `onStartX` (и Y) вызываются, даже если жест не будет свайпом? Почему это поведение отличается от `onEndX / onMoveX`, которые вызываются только если определен свайп? Нужны ли они вообще?
- Почему наличие `onMove(X|Y)?` влияет на определение жеста? Возможно, …
=> test(Touch): Add Touch unit tests

.github/workflows/pull_request.yml, package.json
Убираем поддержку установки через github, потому что она вроде бы не работает и у есть codesandbox
=> infra: yarn prepare -> prepublishOnly

babel.cjs.config.js, babel.config.js, src/components/ChipsSelect/ChipsSelect.test.tsx, src/components/ChipsSelect/ChipsSelect.tsx, src/components/ChipsSelect/Readme.md, src/components/ChipsSelect/useChipsSelect.ts, src/components/CustomSelect/CustomSelect.tsx, src/lib/select.test.ts, src/lib/select.ts
- Пофиксил попадание `options` в `<input />`
- Уницифировал дефолтный алгоритм фильтрации у `ChipsSelect` и `CustomSelect`
- Улучшил его. Теперь он ищет по началу слова. Поддерживаются разные разделители слов в предложениях
- Дал возможность передавать `filterFn={false}` в ChipsSelect, чтобы отключать фильтрацию
- Поправил примеры, убрав оттуда лишний хлам
=> CustomSelect & ChipsSelect: unified and enhanced default filterFn

src/components/Tappable/Tappable.tsx
Приступим! вынос волн из Tappable в компонент:
- упрощает переезд на FC, потому что таймауты можно сделать через `useTimeout`
- убирает (технический) баг, из-за которого при анмаунте после серии быстрых тапов не подчищались колбеки
=> refactor: Make Tappable Wave a separate component

src/components/Tappable/Tappable.test.tsx, src/components/Tappable/Tappable.tsx, src/components/Touch/Touch.tsx
1. Используем Touch даже для Tappable disabled
2. За опцией завязываем onEnter/Leave в Touch на пойнтер-ивенты, чтобы вылетало в disabled-инпутах
Испраявляет:
- Изменение пропов hasActive / hasHover во время ховера на вложенном Tappable не возвращает ховер / активность на родителя.
- Ховер возвращается на Tappable:
- При анмаунте вложенного Tappable под ховером 
- При переходе вложенного Tappable в disabled
- При отключении disabled на самом Tappable
- Tappable теряет ховер:
- При отключении disabled на вложенном Tappable под ховером
- При переходе в disabled
Улучшает:
- При изменении disabled контент Tappable не ремаунтится, потому что компонент-обертка не меняется
- При рендере Tappable не перерисовываются все вложенные Tappable, потому что контекст стал стабильным
=> refactor: Nested Tappable hovers

src/components/Gallery/Gallery.tsx, src/components/ModalRoot/ModalRoot.tsx, src/components/ModalRoot/types.ts, src/components/Snackbar/Snackbar.tsx, src/components/Tappable/Tappable.tsx, src/components/Touch/Touch.tsx, src/components/View/View.tsx, src/components/View/ViewInfinite.tsx
- Добавляем в жесты Touch `duration` — длительность жеста, она используется в половине компонентов выше.
- Добавляем настройку `slideThreshold`, чтобы не дублировать определение слайдов в `Tappable`
=> feat: Enhance Touch

src/components/ActionSheet/ActionSheet.tsx, src/components/ActionSheet/ActionSheetDropdown.tsx, src/components/ActionSheet/ActionSheetDropdownDesktop.tsx, src/components/ActionSheet/Readme.md, src/components/ActionSheet/types.ts, src/components/FixedLayout/FixedLayout.tsx, src/components/PopoutWrapper/PopoutWrapper.tsx, src/components/Root/Root.tsx, src/components/Touch/Touch.tsx
- __types__ Сделал все пропы `ActionSheet` опциональными, как c v4.2 до v4.15. В 4.2 они стали опциональными случайно из-за появления `defaultProps`, в #1883 (релиз 4.15) стали обязательными, как и задумано. В __v5__ стоит исправить это поведение.
- __enhancement__ Добавил дев-ворнинг, если в `ActionSheet` не передан `onClose`
- __docs__ Вернул в доку описания пропов, потерявшиеся при переезде на FC: #1882, #1883, #1886, #1887, #1893
- __feat__ `ActionSheet` поддерживает `toggleRef: RefObject` — так чуть проще не передать null-реф.
=> ActionSheet optional props + docs fix pack

src/components/Tappable/Tappable.tsx
В #1930 случайно поменял длительность тапа в `Tappable` — было от начала подсвечивания, а стало от начала жеста.
=> fix: Fix tappable duration

src/components/ActionSheet/ActionSheet.tsx, src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
- Исправлен тип `onClose`
- Слушаем клик по body только после открытия дропдауна в `ActionSheetDesktop`
=> ActionSheet fixes

src/components/ActionSheet/Readme.md, src/components/Alert/Readme.md, src/components/FocusTrap/FocusTrap.test.tsx, src/components/Group/Readme.md, src/components/MiniInfoCell/Readme.md, src/components/ModalDismissButton/Readme.md, src/components/ModalRoot/Readme.md, src/components/ScreenSpinner/Readme.md, src/components/SubnavigationBar/Readme.md, styleguide/Components/Playground/PlaygroundRenderer.js, styleguide/Components/Preview.js, styleguide/Components/Settings/Settings.js
Отделила в документации свойство `layout` от свойства `adaptivity`: 
- теперь `layout` отвечает только за рендеринг обвязки из `SplitLayout` и `SplitCol` для примеров кода,
- `adaptivity` - новое свойство, контролирует рендеринг примеров кода.
----
Также убрала deprecated свойства `popout` и `modal` у `View` в примерах кода в документации.
**Список потроганных компонентов:**
----
Связанная задача: #1985.
=> [docs] Исправленные примеры `View`

src/components/Epic/Readme.md, src/components/SplitCol/SplitCol.tsx, src/components/SplitLayout/Readme.md, styleguide/Components/StyleGuide/StyleGuideDesktop.js, styleguide/Components/StyleGuide/StyleGuideHeader.js, styleguide/pages/adaptivity.md
This is convenient because these properties are passed to the `style` prop, which takes both a string and a number.
=> feat(SplitCol): Support both number and string in width props

src/components/ActionSheet/ActionSheet.tsx
- Moved `closeAction` from state to ref
- Removed `onTransitionEnd` to prevent next `ActionSheet` closing. Otherwise, it initiates with truly `closing`
fixes #2033
=> ActionSheet

src/components/Touch/Touch.test.tsx
Тест иногда валился из-за того, что `duration` был не 0, а 1 или 2
=> Touch test: fixed emptyGesture duration

package.json, src/components/ActionSheet/ActionSheet.test.tsx, src/components/FocusTrap/FocusTrap.test.tsx, src/components/Link/Link.tsx, src/components/PanelHeaderContext/PanelHeaderContext.test.tsx, src/components/PopoutWrapper/PopoutWrapper.test.tsx, src/components/Root/Root.test.tsx, src/components/Tappable/Tappable.test.tsx, src/testing/utils.tsx, yarn.lock
В обновленной версии `@types/react` обновился тип `target` у `AnchorHTMLAttributes`. Учитывая, что `Link` использует `Tappable`, который наследуется от `AllHTMLAttributes`, я решил, что экстенд от `AnchorHTMLAttributes`, приводящий к конфликтам, можно убрать.
После обновления пришлось обновить типы у `act` в тестах.
fixes #2064
=> updated @types/react and @types/react-dom

src/components/Textarea/Readme.md, src/components/Textarea/Textarea.test.tsx, src/components/Textarea/Textarea.tsx, src/testing/utils.tsx
- Не ресайзим, если `offsetParent === null`. Такое значение сигнализирует о том, что элемент или родитель скрыты с помощью стилей. Если запустить ресайз в таком случае, то `scrollHeight` вернет `0` и `textarea` схлопнется.
- Не вызываем `onResize`, если значение не поменялось.
- Ресайзим, если поменялся `sizeY` (fixes #1976)
=> Textarea: resize logic fixes

src/components/CardScroll/CardScroll.tsx, src/components/Cell/useDraggable.tsx, src/components/FocusTrap/FocusTrap.tsx
=> [Bug] e.querySelectorAll(...).forEach is not a function

src/components/ActionSheet/ActionSheet.tsx
С отложенным выполнением onItemClick есть одна проблема. В событии, которое он кидает наружу, currentTarget уже будет null. А в коде приложения есть потребность ссылаться на него. Например так:
`<ActionSheetItem data-id={123} autoclose onClick={(e) => console.log(e.currentTarget.dataset.id)} />`
Текущая реализация выполнит `onClick` отложенно, передав туда объект события с пустым `currentTarget`
=> ActionSheet: removed delayed onClick call

src/components/ActionSheet/ActionSheet.test.tsx, src/components/ActionSheet/ActionSheet.tsx, src/components/ActionSheet/ActionSheetContext.ts, src/components/ActionSheet/ActionSheetDropdownDesktop.tsx, src/components/ActionSheetItem/ActionSheetItem.tsx
Недоразумения с ActionSheet продолжаются
Мной была выпилена логика отложенного вызова `onClick` в режиме `autoclose`. Сейчас я понимаю, что такой апдейт может сломать кейсы, когда по клику происходит переход: анимация закрытия шита наслоится на анимацию перехода. Такой апдейт мог сломать бог знает что ещё. Поэтому:
1. Вернули отложенность вызова `onClick`. Так работало до переписывания компонента на функциональный и мы не должны это поведение менять. Если `autoclose === true`, `onClick` будет вызван после завершения анимации скрытия и после вызова `onClose`. Из этого следует, что в объекте события значения полей типа `currentTarget` будут не определены. Если вам нужен объект события именно на момент клика, используйте `onImmediateClick`.
2. С десктопом, где нет анимации скрытия, всё ещё …
=> Action sheet fix

src/components/Cell/Cell.tsx, src/components/FormItem/FormItem.tsx, src/components/FormLayoutGroup/FormLayoutGroup.tsx
Чтобы `onRemove` не выстреливал неожиданной ошибкой, когда в доке пытаешься посмотреть, как выглядит какой-нибудь компонент, у которого доступен `removable`.
=> default `noop` for `onRemove`

src/components/ClickPopper/ClickPopper.tsx, src/components/Dropdown/Dropdown.tsx, src/components/HoverPopper/HoverPopper.tsx, src/components/PanelHeader/PanelHeader.css, src/components/RichTooltip/RichTooltip.tsx, src/components/TextTooltip/TextTooltip.tsx
Сделал нормальный экстенд типов для выпадашек. Раньше он был невозможен из-за кривого отображения в стайлгайдисте.
=> Dropdown and co: simplified types

src/components/Button/Button.tsx, src/lib/platform.ts
Теперь в `ConfigProvider.platform` можно передавать произвольную строку. Это сделано для того, чтобы VKUI могли использовать все юниты VK, у которых есть свой набор vkui-tokens.
=> supported custom platform

src/components/PanelHeaderButton/PanelHeaderButton.tsx
Fixes #2235.
Из https://github.com/VKCOM/VKUI/issues/2235#issuecomment-1031598727:
> Мы не можем предсказать, какое действие будет осуществляться по кнопке, но если внутри только иконка, то для того, чтобы кнопка вообще была доступной, ей нужен `aria-label`. Поэтому мы со своей стороны задаем только дефолт; сейчас он — "Закрыть". Разработчикам нужно прокинуть свое значение `aria-label`, чтобы все заработало как надо.
> Другое дело, что это может быть не самый уместный дефолт для конкретной кнопки (учитывая, что есть отдельный `PanelHeaderClose`). Возможно, лучше будет чекать, что кнопка не озвучивается, и кидать варнинг в dev-сборке.
=> [Enhancement, a11y] PanelHeaderButton

src/components/ActionSheetItem/ActionSheetItem.tsx, src/components/Alert/Alert.tsx
Fixes #2246.
`react-docgen-typescript` или игнорирует `export { CmpName as AnotherName }`, или как-то по-своему его обрабатывает, потому что при запуске `yarn styleguide` проблема не повторяется. 🤦🏻‍♀️ 
Пофиксила:
=> [Docs, Bug] Именованные экспорты в доке

.idea/inspectionProfiles/Project_Default.xml
Теперь IDEA не будет ругаться на `JSX is used without importing createScopedElement`
=> feat(idea): Disable JSXNamespaceValidation in .idea

src/components/ActionSheet/ActionSheetDropdownDesktop.tsx, src/components/AppRoot/AppRoot.tsx, src/components/AppRoot/AppRootPortal.tsx, src/components/AppearanceProvider/AppearanceProvider.tsx, src/components/AppearanceProvider/AppearanceProviderContext.tsx, src/components/CustomSelectOption/CustomSelectOption.css, src/hooks/useAppearance.ts
- В `AppRoot` убрал ручное навешивание значения `scheme` на `portalRoot`
- В `AppRootPortal` читаю текущее значение `appearance` и навешиваю его на обертку портала с помощью `AppearanceProvider`
- Упростил контекст `AppearanceProviderContext`, убрав оттуда `scheme`
- В `useAppearance` читаю из `AppearanceProviderContext`, а не из `ConfigProviderContext`
=> Vkui tokens popper fix

src/components/ConfigProvider/ConfigProvider.test.tsx, src/components/ConfigProvider/ConfigProvider.tsx, src/components/ConfigProvider/ConfigProviderContext.tsx, src/hooks/usePlatform.test.tsx, src/hooks/usePlatform.ts
Проблема: если явно передать в `<ConfigProvider platform={undefined} />`, то такое значение затрет дефолтный резолв через `platform()`, и `usePlatform` станет возвращать `undefined`. При этом `getClassName` всё равно будет использовать `platform()` в случае, если вторым аргументом передан `undefined`. То есть получился рассинхрон.
=> usePlatform: fix case with <ConfigProvider platform={undefined} />

package.json
Из-за того, что пакет в `npm` содержит практически все файлы из директории проекта, ломаются сборки пользователей, у которых `postcss-loader` прогоняет стили из `node_modules/`, т.к. `postcss-loader` начинает использовать `node_modules/@vkontakte/vkui/postcss.config.js`.
Выстрелило после [изменения конфига](https://github.com/VKCOM/VKUI/blob/v4.26.0/postcss.config.js#L13-L16) в версии `v4.26.0`.
=> [Hotfix] Используем "files" в package.json, чтобы оставить в выходном пакете только нужное

src/components/PopoutWrapper/Readme.md
Свойство `popout` у компонентов `View` и `Root` устарело
=> Docs: PopoutWrapper in SplitLayout.popout

.npmignore, package.json
В PR https://github.com/VKCOM/VKUI/pull/2282 мы исключили `postcss.config.js` посредством поля "files" в `package.json`.
Но тем самым из пакета пропала директория `tasks/`, что теперь вызывает следующую ошибку при попытке установки версии [v4.28.0](https://github.com/VKCOM/VKUI/releases/tag/v4.28.0):
```
npm ERR! enoent ENOENT: no such file or directory, chmod '/node_modules/@vkontakte/vkui/tasks/generate_scheme.js'
npm ERR! enoent This is related to npm not being able to find a file.
```
Удаляем `"files"`, а `postcss.config.js` игнорируем в файле `.npmignore`.
=> fix: Remove "files" and ignore `postcss.config.js` in .npmignore

src/components/ModalPage/ModalPage.tsx, src/hooks/useOrientationChange.ts, src/lib/platform.ts
Компонент [ModalPage](https://vkcom.github.io/VKUI/#/ModalPage), в режиме Action Sheet на iOS, при смене ориентации устройства не пересчитывает свои координаты.
Режим "portrait"
Перевернули в режим "landscape"
🐛 часть контента обрезалась.
Приходится переоткрывать ActionSheet, чтобы поправить ситуацию.
Внутри компонента [ModalPage](https://vkcom.github.io/VKUI/#/ModalPage) подписаться на событие изменение ориентации экрана и, при обработке события, вызывать `updateModalHeight()`.
Тестировал через симулятор в Xcode. 
- Приложение: VK (в WebView загрузил свою локальную dev сборку)
- Устройство: iPad Air (4th generation)
- Версия iOS: 14.4
https://user-images.githubusercontent.com/5850354/158841637-d4b26f58-693a-4652-a4f9-96ea28ebb1e2.mov
Добавил хук …
=> fix(ModalPage): Call updateModalHeight() after orientation change

.github/CODEOWNERS
CODEOWNERS в GitHub не дают возможности затребовать аппрув у всех указанных групп перед мерджем реквеста. Поэтому — оставляем `yarn.lock` и `.yarnrc` в ведении @VKCOM/vk-sec.
=> [Security] Update CODEOWNERS

src/components/ChipsSelect/__image_snapshots__/chipsselect-scrolls-to-item-via-arrows-1-snap.png, src/components/CustomSelect/CustomSelect.tsx
[CustomSelect](https://vkcom.github.io/VKUI/#/CustomSelect)
При параметре `searchable`, обновляется "ребёнок", из-за чего `onMouseEnter` не срабатывает в следующих кейсах:
1. До загрузки выпадающего списка, курсор мышки находится над произвольным элементом этого списка.
> **Лечение:** только увод курсора мыши и возвращении его обратно вызывает событие `onMouseEnter` на этот элемент.
2. Если это тач-устройство.
> **Лечение:** нужно нажать на какой-нибудь произвольный элемент списка, после чего `onMouseEnter` будет работать на соседние элементы, но не на тот, на который нажали в первый раз.
Более подробно по ссылке https://github.com/facebook/react/issues/13956#issuecomment-1082055744
`onMouseEnter` был заменён на `onMouseOver`.
`onMouseOver` отличается тем, что он будет дополнительно …
=> fix(CustomSelect): Use `onMouseOver` instead `onMouseEnter`

src/components/Touch/Touch.tsx
В компоненте Touch после окончания касания (событие `touchend` или `mouseup`) не удаляются лишние обработчики событий.
_Пример для [https://vkcom.github.io/VKUI/#/PullToRefresh](PullToRefresh), если начать тянуть все элементы_
В #1988 было добавлено удаление обработчиков, вызывая `subscribe(null)`
https://github.com/VKCOM/VKUI/blob/4ffcb68f0619ab9b6cdb360bd6b1608938136c83/src/components/Touch/Touch.tsx#L182
https://github.com/VKCOM/VKUI/blob/4ffcb68f0619ab9b6cdb360bd6b1608938136c83/src/components/Touch/Touch.tsx#L191-L193
https://github.com/VKCOM/VKUI/blob/4ffcb68f0619ab9b6cdb360bd6b1608938136c83/src/hooks/useEventListener.ts#L29-L36
В #2195 функция `subscribe` изменилась
https://github.com/VKCOM/VKUI/blob/4566ee0ec11ab932b01c897fe3768c5a390ed028/src/components/Touch/Touch.tsx#L221-L225 …
=> Fix Touch.tsx unsubscribe listeners

.github/workflows/pull_request.yml
Пропускаем запуск джобы `deploy_styleguide` в PR от `@dependabot`. Во-первых, у бота нет прав на деплой (надо настраивать), во-вторых, экономим ресурсы, т.к. песочницу собирать кажется нет смысла.
**Пример.** Упавшая джоба `deploy_styleguide` в PR [#2327](https://togithub.com/VKCOM/VKUI/pull/2327)
=> [Infra] Skip `deploy_styleguide` job for "dependabot[bot]"

.idea/.gitignore
У IDEA есть файлы для служебных нужд, за которыми в данный момент следит git, пример ниже
Чтобы случайно их кто-либо не закомитил, по мотивам статьи [Sharing Your Project on GitHub
](https://blog.jetbrains.com/idea/2020/11/sharing-your-project-on-github/), создал `.gitignore` внутри папки `.idea`.
=> chore(.idea): add `.gitignore` to `/.idea` for ignore local files

src/components/Root/Root.css, src/components/Root/Root.tsx
Fixes #2274, #1999
При переключении `activeView` в [Root](https://vkcom.github.io/VKUI/#/Root) без анимации(отключена разработчиком или большой размер экрана), в одном моменте рендерится текущий и предыдущий View. Из-за этого на несколько миллисекунд появляется скролл(заметно на windows, linux)
Переход рендерится в три этапа
- `activeView="view1"` `transition=false` (переключилось свойство `_activeView`)
- `activeView="view2"` `transition=true` (начался переход, появляются новый View, происходит анимация)
- `activeView="view2"` `transition=false` (старый View убирается, выполняется onTransition...)
При отключенной анимации также рендерится в три этапа
- `activeView="view1"` `transition=false` (переключилось свойство `_activeView`)
- `activeView="view2"` `transition=true` (начался переход, …
=> fix(Root): Double View without animation

package.json, src/components/Calendar/Calendar.tsx, src/components/Calendar/Readme.md, src/components/CalendarDays/CalendarDays.tsx, src/components/CalendarHeader/CalendarHeader.tsx, src/components/CalendarRange/CalendarRange.tsx, src/components/CalendarRange/Readme.md, src/components/CalendarTime/CalendarTime.tsx, src/components/DateInput/DateInput.tsx, src/components/DateInput/Readme.md, src/components/DateRangeInput/DateRangeInput.tsx, src/components/DateRangeInput/Readme.md, src/hooks/useCalendar.ts, src/lib/calendar.ts, src/lib/date.test.ts, src/lib/date.ts, yarn.lock
Переход на dayjs с date-fns что бы уменьшить размер компонента Calendar.
Было:
```
JS
Size: 83.66 kB with all dependencies, minified and gzipped
```
Стало:
```
JS
Size: 76.7 kB with all dependencies, minified and gzipped
```
=> Move from date-fns to dayjs

src/components/CalendarHeader/CalendarHeader.tsx, src/components/Typography/Paragraph/Paragraph.css, src/components/Typography/Paragraph/Paragraph.e2e.tsx, src/components/Typography/Paragraph/Paragraph.test.tsx, src/components/Typography/Paragraph/Paragraph.tsx, src/components/Typography/Paragraph/Readme.md, src/components/Typography/Paragraph/__image_snapshots__/paragraph-android-light-1-snap.png, src/components/Typography/Paragraph/__image_snapshots__/paragraph-ios-light-1-snap.png, src/components/Typography/Paragraph/__image_snapshots__/paragraph-vkcom-light-1-snap.png, src/index.ts, src/styles/components.css, src/tokenized/index.ts, styleguide/config.js, styleguide/tokenized.js
Fixes #2396.
При переезде на токенизированный `Text` обнаружила, что `Calendar` использует новый типографический компонент `Paragraph`, которого у нас нет.
Теперь будет! (%
=> [Feature] Typography/Paragraph

src/components/ModalPage/ModalPage.tsx, src/components/ModalRoot/ModalRoot.tsx, src/components/ModalRoot/ModalRootAdaptive.tsx, src/components/ModalRoot/ModalRootDesktop.tsx, src/components/ModalRoot/Readme.md, src/components/ModalRoot/types.ts, src/components/ModalRoot/useModalManager.test.tsx, src/components/ModalRoot/useModalManager.tsx
Расширил API у `ModalRoot` и `ModalPage`:
* `onOpen` – начало открытия
* `onOpened` – окончательно открытие (имеется ввиду завершилась анимация)
* `onClosed`– окончательно открытие (имеется ввиду завершилась анимация)
`onClose` уже есть и работает как `onOpen` – начало закрытия
---
resolve #2340
resolve #680
resolve #1935
=> feat(ModalRoot,ModalPage): Add onOpen() to ModalRoot and ModalPage

src/components/Root/Root.css, src/components/View/View.css, src/components/View/ViewIOS.css
Использовал `create-react-app`
- `@vkontakte/vkui@4.28.1`
- `react@18.0.0`
- `react-dom@18.0.0`
<details>
<summary>Тестируемый код</summary>
```tsx
// @ts-nocheck
import * as React from "react";
import { createRoot } from "react-dom/client";
import { ConfigProvider, AdaptivityProvider, AppRoot, View, Panel, CellButton, PanelHeader, Group } from "@vkontakte/vkui";
import "@vkontakte/vkui/dist/vkui.css";
function App() {
const [history, setHistory] = React.useState(["main"]);
const activePanel = history[history.length - 1];
const goBack = () => setHistory(history.slice(0, -1));
const go = (panel) => setHistory([...history, panel]);
return (
<View onSwipeBack={goBack} history={history} activePanel={activePanel}>
<Panel id="main">
<PanelHeader>Main</PanelHeader>
<Group>
<CellButton …
```
=> fix(View): fix view blinking after transition to prev view

src/components/FixedLayout/FixedLayout.css, src/components/ModalRoot/ModalRoot.css, src/components/PanelHeader/PanelHeader.css, src/components/SplitLayout/SplitLayout.css, src/styles/constants.css
В частности поправил, что на Android игнорировалось использование `--safe-area-inset-top` в следующих компонентах:
- [ModalPage](https://vkcom.github.io/VKUI/#!/ModalPage)
- [SplitLayout](https://vkcom.github.io/VKUI/#!/SplitLayout)
Проверил на эмуляторе
Для iOS в `--safe-area-inset-top` в `:root` выставлялось значение по умолчанию в `20px` (прикрепляю код ниже)
https://github.com/VKCOM/VKUI/blob/ca0a2dab093152b55907e748de46529bb06213b7/src/styles/constants.css#L34-L35
Из-за этого для других платформ приходилось обнулять это значение точечно (прикрепляю пример ниже)
https://github.com/VKCOM/VKUI/blob/ca0a2dab093152b55907e748de46529bb06213b7/src/components/PanelHeader/PanelHeader.css#L155-L160
Чтобы избежать этого, сделал так, что значение по умолчанию выставлялось только для iOS ([ссылка …
=> Повсеместное использование `--safe-area-inset-top`

src/components/HorizontalScroll/HorizontalScroll.tsx
**Проблема:**
Если ширина контента в HorizontalScroll оказалась числом с дробной частью, то анимация прокрутки зацикливается
**Как воспроизвести**
Средний пример [CardScroll](https://vkcom.github.io/VKUI/#/CardScroll) прокрутить до конца через стрелки
https://user-images.githubusercontent.com/14944123/165622797-cbefcd74-50e8-41de-9260-9052ac3987d9.mov
P.S. Вообще больше похоже на баг гугл хрома. На firefox все ок
=> fix(HorizontalScroll): support half-pixel

src/components/ChipsInput/ChipsInput.tsx, src/components/CustomSelect/CustomSelect.tsx, src/components/FormField/FormField.css, src/components/FormField/FormField.tsx, src/components/FormField/Readme.md, src/components/Input/Input.tsx, src/components/SelectMimicry/SelectMimicry.tsx
- Поправил jsdoc у `before` и `after`.
- Добавил передачу `before` в `FormField` в следующих компонентах:
- [ChipsInput](https://vkcom.github.io/VKUI/#/ChipsInput)
- [CustomSelect](https://vkcom.github.io/VKUI/#/CustomSelect)
> ⚠️ тут не консистентное название
> `icon` вместо `after`
- [Input](https://vkcom.github.io/VKUI/#/Input)
- [SelectMimicry](https://vkcom.github.io/VKUI/#/SelectMimicry) + наследуем `before` и `after` от `FormFieldProps`
---
resolve https://github.com/VKCOM/VKUI/issues/2374
resolve https://github.com/VKCOM/VKUI/issues/529
resolve https://github.com/VKCOM/VKUI/issues/975
=> [Feature][FormField] Добавление параметра `before`

src/components/FixedLayout/FixedLayout.css
<details>
<summary>Старое описание</summary>
Поправил центровку при фиксированной ширине.
Здесь #2414 (коммит https://github.com/VKCOM/VKUI/pull/2414/commits/230b4dceacd3b8aa0d66af4db767763cd0130f4e) не учёл это.
Использовал старый добрый метод 😄 
```
left: 0;
right: 0;
margin-left: auto;
margin-right: auto;
```
</details>
**UPD**
После изменения https://github.com/VKCOM/VKUI/pull/2414 (коммит https://github.com/VKCOM/VKUI/commit/230b4dceacd3b8aa0d66af4db767763cd0130f4e) в `v4.29.1` сломалась:
1. центровка при фиксированной ширине
<details>
<summary>Демо</summary>        
**Было**
**Стало**
</details>
2. #2475
поэтому ревертнул коммит https://github.com/VKCOM/VKUI/commit/230b4dceacd3b8aa0d66af4db767763cd0130f4e
---
fix #2475
=> fix(FixedLayout): revert to 1364 PR number

src/components/Button/Button.tsx, src/components/Button/Readme.md
- убираем лишние узлы
- убираем в примере информацию о иконках
<details>
<summary>До</summary>
</details>
<details>
<summary>После</summary>
</details>
=>  feat(Button): before and after role presentation

jest.unit.config.js, package.json, postcss.config.js, tasks/postcss-restructure-variable.js, tasks/postcss-restructure-variable.test.js, tasks/postcss-scope-root.js
css переменные занимают большое количество места в нашей сборке.
При этом многие переменные имеют одинаковое значение, а разница между темами не большая
```diff
< .vkui--vkBase--light {
<       --vkui--theme_name: 'vkBase';
<       --vkui--theme_name_base: 'vkBase';
---
> .vkui--vkCom--light {
>       --vkui--theme_name: 'vkCom';
>       --vkui--theme_name_base: 'vkCom';
<       --vkui--size_border_radius--regular: 8px;
---
>       --vkui--size_border_radius--regular: 4px;
>       --vkui--theme_inherits_from: 'vkBase';
```
В  [vkui-tokens](https://github.com/VKCOM/vkui-tokens) добавили инкрементальную сборку, которая в сгенерированных токенах убирает переменные с одинаковыми значениями. 
```diff
< [postcss] [postcss-bundle] asset vkui.css **358 KiB** [emitted] (name: vkui) (id hint: vkui) …
```
=> [Research]: Уменьшаем размер токенов

src/components/Progress/Progress.css, src/components/Progress/Progress.test.tsx, src/components/Progress/Progress.tsx, src/components/Progress/Readme.md, src/index.ts, src/tokenized/index.ts, styleguide/tokenized.js
---
[pull/2596/#/Progress](https://vkcom.github.io/VKUI/pull/2596/#/Progress)
- В пример добавлен label для a11y
- #2191
- closed #2560
=> feat(Progress): tokenized

src/components/Footer/Footer.css, src/tokenized/index.ts, styleguide/tokenized.js
=> feat(Footer): Tokenize

src/components/Div/Div.css, src/components/Div/Div.tsx, src/tokenized/index.ts, styleguide/tokenized.js
=> feat(Div): Tokenize

src/components/SplitCol/SplitCol.css, src/components/SplitCol/SplitCol.tsx, src/tokenized/index.ts, styleguide/tokenized.js
=> feat(SplitCol): Tokenize

src/components/FormItem/FormItem.e2e.tsx, src/components/FormItem/__image_snapshots__/formitem-android-light-1-snap.png, src/components/FormItem/__image_snapshots__/formitem-ios-light-1-snap.png, src/components/FormItem/__image_snapshots__/formitem-vkcom-light-1-snap.png, src/components/Radio/Radio.css, src/components/Radio/Radio.e2e.tsx, src/components/Radio/Radio.test.tsx, src/components/Radio/Radio.tsx, src/components/Radio/__image_snapshots__/radio-android-light-1-snap.png, src/components/Radio/__image_snapshots__/radio-ios-light-1-snap.png, src/components/Radio/__image_snapshots__/radio-sizes-and-description-android-light-1-snap.png, src/components/Radio/__image_snapshots__/radio-sizes-and-description-ios-light-1-snap.png, src/components/Radio/__image_snapshots__/radio-sizes-and-description-vkcom-light-1-snap.png, src/components/Radio/__image_snapshots__/radio-vkcom-light-1-snap.png, src/components/RadioGroup/RadioGroup.e2e.tsx, src/components/RadioGroup/RadioGroup.tsx, src/components/RadioGroup/__image_snapshots__/radiogroup-android-light-1-snap.png, src/components/RadioGroup/__image_snapshots__/radiogroup-ios-light-1-snap.png, src/components/RadioGroup/__image_snapshots__/radiogroup-vkcom-light-1-snap.png, src/components/Tappable/Tappable.tsx, src/index.ts, src/tokenized/index.ts, styleguide/tokenized.js
Перевод на токены Radio и RadioGroup
---
---
Документация компонентов
- [Radio](https://vkcom.github.io/VKUI/pull/2609/#/Radio)
- [RadioGroup](https://vkcom.github.io/VKUI/pull/2609/#/RadioGroup)
---
- Отказ от использование отдельных стилей в VKCOM
- #2191
- fixed #1960
- closed #2608
- closed #2561
=> feat: Radio and RadioGroup tokenized 

src/components/Badge/Badge.css, src/components/Badge/Badge.tsx, src/tokenized/index.ts, styleguide/tokenized.js
=> feat(Badge): tokenized

src/components/Alert/Alert.tsx
**проблема:** При нажатии на фон, `onClose` вызывается два раза из-за трансформации `opacity` и `transform`. При рефакторинге в функции close упустил данное условие
=> fix(Alert): double onClose

src/components/FocusVisible/FocusVisible.css, src/components/FocusVisible/FocusVisible.tsx, src/tokenized/index.ts
=> feat(FocusVisible): tokenized

src/components/Banner/Banner.css, src/components/Banner/Banner.e2e.tsx, src/components/Banner/Banner.test.tsx, src/components/Banner/Banner.tsx, src/index.ts, src/tokenized/index.ts
---
- https://github.com/VKCOM/VKUI/issues/2191
- resolve #2509
=> feat(Banner): Tokenize

src/components/ContentCard/ContentCard.css, src/components/ContentCard/ContentCard.e2e.tsx, src/components/ContentCard/ContentCard.tsx, src/components/ContentCard/Readme.md, src/components/ContentCard/__image_snapshots__/contentcard-android-light-1-snap.png, src/components/ContentCard/__image_snapshots__/contentcard-ios-light-1-snap.png, src/components/ContentCard/__image_snapshots__/contentcard-vkcom-light-1-snap.png, src/tokenized/index.ts
=> feat(ContentCard): Tokenize

src/components/CellButton/CellButton.css, src/components/CellButton/CellButton.tsx, src/tokenized/index.ts
=> feat(CellButton): Tokenize

src/components/Group/Group.css
Сейчас на дочерних компонентах, которые обернуты в `Group` (`mode=card`) не работают ивенты, проставляем 
`pointer-events: none;` для элемента `after`
=> fix(Group): Add pointer-events: none to make events on children happy

src/components/Snackbar/Snackbar.css
Была проблема, что [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) версии `< 12` не могла распарсить минифицированнную запись умножения переменной на `-1`, где `-1` шла вторым операндом
Пример
```
calc(var(--value)*-1)
```
А вот так работает
```
calc(var(--value) * -1)
```
Упоминание о проблеме нашёл тут https://github.com/postcss/postcss-custom-properties/issues/179#issuecomment-497534247
Поэтому заменил на 
```diff
-calc(var(--value) * -1)
+calc(-1 * var(--value))
```
---
- Fix #2740
=> fix(Snackbar): fix multiplication by -1 in `calc()`

stylelint.config.js, tasks/stylelint-bad-multiplication.js
Умножение в `calc` на отрицательное число ломает некоторые сборки
```css
calc(var(--some-variable) * -1)
```
- #1083
- #1057
- #2740
Проблема пропадает, если поменять местами операнды
```
calc(-1 * var(--some-variable))
```
Подробнее можно узнать в #2741
Добавляем stylelint плагин который проверяет умножение на отрицательное число
=> chore: add stylelint-bad-multiplication

src/components/MiniInfoCell/MiniInfoCell.css, src/components/MiniInfoCell/MiniInfoCell.tsx, src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-light-1-snap.png, src/tokenized/index.ts
=> feat(MiniInfoCell): Tokenize

src/components/Link/Link.css, src/components/Link/Link.tsx, src/components/Link/Readme.md, src/tokenized/index.ts
Задал свой класс для фокуса `<Tappable focusVisibleMode="Link--focus-visible" />`, т.к. есть проблема с текущей реализацией `<FocusVisible />` (см. скриншоты)
Фокус задаю через `outline`
Также пришлось указать `!important` из-за глобального обнуления `outline` на фокус
https://github.com/VKCOM/VKUI/blob/8323f7aa9ce00ff28c17092ffc83f5146fca8a91/src/styles/common.css#L36-L39
---
- Close #2552
=> feat(Link): tokenized

src/components/Dropdown/Dropdown.css, src/components/Dropdown/Dropdown.tsx, src/tokenized/index.ts
=> feat(Dropdown): Tokenize

src/components/ConfigProvider/ConfigProvider.test.tsx, src/components/ConfigProvider/ConfigProvider.tsx, src/components/LocaleProviderContext/LocaleProviderContext.tsx
Добавил поддержку вложенных `ConfigProvider`. Теперь `ConfigProvider` по умолчанию берет свойства из родительского.
close #2483
=> Add support for nested ConfigProvider

src/components/Avatar/Avatar.css
=> feat(Avatar): add `object-fit: cover` for square images

.github/gitflow/patch.js, .github/gitflow/stable_branch.js, .github/gitflow/utils.js, .github/workflows/pr_close.yml, .github/workflows/publish.yml
> remote: error: GH006: Protected branch update failed for refs/heads/4.33-stable.        
> remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
[Упавший CI](https://github.com/VKCOM/VKUI/runs/7236771315?check_suite_focus=true)
=> ci: fix push protected branch

styleguide/Components/Link/LinkRenderer.js
Если перейти на https://vkcom.github.io/VKUI/#/View, то рендер фейлится из-за наличия фейкового элемента для якорной ссылки
=> Optional Chaining для LinkRenderer

src/components/HorizontalScroll/HorizontalScroll.css, src/components/HorizontalScroll/HorizontalScroll.tsx, src/components/HorizontalScroll/HorizontalScrollArrow.tsx
=> fix(HorizontalScroll): remove `overflow-y: hidden` from host

.github/workflows/pr_close.yml
> To use GitHub CLI in a GitHub Actions workflow,
set the GH_TOKEN environment variable.
[Close PR #55](https://github.com/VKCOM/VKUI/runs/7496269102?check_suite_focus=true)
=> ci: GH_TOKEN for GitHub CLI

src/hoc/withAdaptivity.tsx, src/hoc/withContext.tsx, src/hoc/withPlatform.tsx
react-docgen-typescript не поддерживает `ComponentType`. Из-за этого не загружались свойства компонентов
=> docs: remove ComponentType

src/components/CustomScrollView/CustomScrollView.css
Внутренний компонент.
Т.к. прозрачность по дизайну ломает  **Appearance** токен `--music_playback_icon`, он был заменён на `--icon_medium`
> согласовано с @Zaycevq
---
- close #2911
=> feat(CustomScrollView): tokenize

src/components/Tabbar/Tabbar.css, src/components/Tabbar/Tabbar.tsx, src/components/Tabbar/__image_snapshots__/tabbar-android-light-1-snap.png, src/components/Tabbar/__image_snapshots__/tabbar-ios-light-1-snap.png, src/components/TabbarItem/TabbarItem.css, src/components/TabbarItem/TabbarItem.tsx, src/tokenized/index.ts
=> feat(TabbarItem): Tokenize

src/components/SplitCol/SplitCol.css, src/components/Typography/Headline/Headline.tsx, src/components/WriteBar/WriteBar.css, src/components/WriteBar/WriteBar.tsx, src/tokenized/index.ts
=> feat(WriteBar): Tokenize

src/components/WriteBarIcon/WriteBarIcon.css, src/components/WriteBarIcon/WriteBarIcon.tsx, src/tokenized/index.ts
=> feat(WriteBarIcon): Tokenize

src/components/HorizontalCell/HorizontalCell.css, src/components/HorizontalCell/HorizontalCell.tsx, src/tokenized/index.ts
=> feat(HorizontalCell): Tokenize

src/components/Badge/Badge.css, src/components/Counter/Counter.css, src/components/HorizontalScroll/HorizontalScroll.css, src/components/Tabs/Readme.md, src/components/Tabs/Tabs.css, src/components/Tabs/Tabs.e2e.tsx, src/components/Tabs/Tabs.tsx, src/components/Tabs/__image_snapshots__/tabs-android-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-ios-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-light-1-snap.png, src/components/TabsItem/Readme.md, src/components/TabsItem/TabsItem.css, src/components/TabsItem/TabsItem.tsx, src/tokenized/index.ts
Появился новый параметр (см. подробности в PR)
- `status`
---
- Close #2584
- Close #2585
- Fixed #2536
=> feat(Tabs,TabsItem): tokenized

src/components/Tabs/__image_snapshots__/tabs-android-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-ios-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-light-1-snap.png
Забыл здесь скриншот обновить https://github.com/VKCOM/VKUI/pull/2781
- related #2584, #2585, #2536
=> CHORE: Update screenshots

src/components/Group/Readme.md
Исправлена небольшая опечатка в тексте, который использовался в коде для примера
=> docs(Group): fix typo

.github/gitflow/patch.js
Бывают разные сценарии при конфликтах. Например если коммит один, git будет требовать следующее
> hint: after resolving the conflicts, mark the corrected paths
> hint: with 'git add <paths>' or 'git rm <paths>'
> hint: and commit the result with 'git commit'
=> ci(patch): fix instructions about conflicts

src/components/Button/Button.tsx
Возвращаем возможность перебить свойства `hoverMode` и `activeMode`
- resolve #2871
=> fix(Button): add `hoverMode` and `activeMode`

src/components/SplitLayout/SplitLayout.css, src/components/SplitLayout/SplitLayout.tsx, src/tokenized/index.ts
=> feat(SplitLayout): Tokenize

src/components/ChipsInput/ChipsInput.css, src/components/Input/Input.css, src/components/Textarea/Textarea.css, src/components/WriteBar/WriteBar.css
Для Firefox
|До|После|
|-|-|
|<img width="374" alt="image" src="https://user-images.githubusercontent.com/14944123/183467094-3a67f10f-27bc-4c5e-9cc8-dbc0d10825a4.png">|<img width="387" alt="image" src="https://user-images.githubusercontent.com/14944123/183467140-c9349860-4f22-44d1-ada7-d4d9f65bb68c.png">|
|<img width="317" alt="image" src="https://user-images.githubusercontent.com/14944123/183467349-c61b994e-a361-41af-820d-b2e5d7121d4b.png">|<img width="314" alt="image" src="https://user-images.githubusercontent.com/14944123/183467397-5599f467-e769-4725-b100-7e8521ad2ea0.png">|
|<img width="313" alt="image" src="https://user-images.githubusercontent.com/14944123/183467960-15ea767c-3dd3-4eaa-963c-b2f0f96662b7.png">|<img width="319" alt="image" …
=> fix(Firefox): placeholder opacity

postcss.config.js
Отключил `postcss-calc` для `cssnano`. Подробней в issue и в комментарии к коду.
Вес минифицированного бандла, к сожалению, чуть увеличится.
---
- fix #2963
=> fix(build): disable `postcss-calc` for `cssnano`

styleguide/pages/migration_v5.md
Добавленные в доку по миграции **компоненты**, которых не хватает.
#1522
#2584
А также:
--------
resolves #1522
relates to #2351
=> v5.0.0 Добавляем в доку по миграции переименованные пропсы

src/components/ActionSheet/ActionSheet.css, src/components/ActionSheet/ActionSheet.e2e.tsx, src/components/ActionSheet/ActionSheet.tsx, src/components/ActionSheet/ActionSheetDefaultIosCloseItem.tsx, src/components/ActionSheet/ActionSheetDropdown.tsx, src/components/ActionSheet/ActionSheetDropdownDesktop.tsx, src/components/ActionSheet/Readme.md, src/components/ActionSheet/__image_snapshots__/actionsheet-android-light-w_2-1-snap.png, src/components/ActionSheet/__image_snapshots__/actionsheet-ios-light-w_2-1-snap.png, src/components/ActionSheet/__image_snapshots__/actionsheet-vkcom-light-w_2-1-snap.png, src/components/ActionSheetItem/ActionSheetItem.css, src/components/ActionSheetItem/ActionSheetItem.tsx, src/index.ts, src/tokenized/index.ts
---
- resolve #2504 
- resolve #2505
=> feat(ActionSheet, ActionSheetItem): Tokenize

src/components/Banner/Banner.tsx
Исправила внутреннюю реализацию `Banner`, чтобы починить баг доступности: теперь в `Tappable` внутренности оборачиваются только при `asideMode === "expand"`.
Заодно убрала отдельный `BannerHeader` и немного тернарники причесала, чтобы стало легче читать. 😉
----
Resolves #3006.
=> fix(Banner): Убираем `aria-disabled` и `disabled` для баннера c `asideMode !== "expand"`

styleguide/Components/Playground/PlaygroundRenderer.js, styleguide/Components/SectionSubheading/SectionSubheading.js
=> fix(docs): Исправляем переход по `id` в `SectionSubheading` и `PlaygroundRenderer`

src/components/FormStatus/FormStatus.css, src/components/FormStatus/FormStatus.tsx, src/tokenized/index.ts, styleguide/deprecated.js
=> feat(FormStatus): Tokenize

src/components/Group/Group.css, src/components/Group/Group.tsx
Добавляем свойство `padding`, которое отвечает за отступы вокруг контента для карточки
- link #3018
=> feat(Group): add `padding`

package.json, yarn.lock
Этот плагин не используется. Возможно он даже излишний,
так как в webpack есть опция `output.clean`
=> chore: remove clean-webpack-plugin

src/appearance/constants.ts
=> chore: rm -rf src/appearance

package.json
Перенести исключения `*.tmp` из поля `"files"` в `.npmignore` не сработало.
Так или иначе не вижу смысла в исключении `*.tmp` файлов внутри `dist`.
Проверял через `yarn pack`, который генерирует архив пакета в том, в каком он будет лежать в пакетном менеджере.
---
- fix #3261
=> Удалил исключения в поле `"files"` в `package.json`

src/components/AppRoot/ScrollContext.tsx, src/components/View/View.tsx
При открытии клавиатуры в iOS весь контент сдвигается вверх на высоту клавиатуры. В `window.pageYOffset` этот сдвиг учитывается, из-за чего мы получаем не верное значение для `marginTop`,
https://github.com/VKCOM/VKUI/blob/ba7991a35e0c0b84acda8ba59959427e646400c1/src/components/View/View.tsx#L581-L588
который служит для исправления бага с `overflow: hidden` в iOS.
1. Во-первых, мы в любом случае закрываем клавиатуру, т.к. это нативное поведение при свайпе в iOS.
2. Во-вторых, в [`GlobalScrollController`](https://github.com/VKCOM/VKUI/blob/v4.37.0/src/components/AppRoot/ScrollContext.tsx#L42-L120) в [`getScroll()`](https://github.com/VKCOM/VKUI/blob/v4.37.0/src/components/AppRoot/ScrollContext.tsx#L47-L50) мы вычитаем высоту клавиатуры из `window.pageYOffset` для `y`. Чтобы получить высоту …
=> fix(View): правим проблему со свайпом при открытой клавиатуре в iOS

src/components/Tabs/__image_snapshots__/tabs-vkcom-light-1-snap.png, src/components/TabsItem/TabsItem.css
=> fix(TabsItem): заменил `header_tint_alternate` на `button_secondary_foreground` для `after` при `mode="accent"`

packages/postcss-restructure-variable/__snapshots__/postcss-restructure-variable.test.js.snap, packages/postcss-restructure-variable/postcss-restructure-variable.test.js
Переписываем тест на снапшот. postcss при обновлении иногда удаляет или добавлят переносы строк
=> test(postcss-restructure-variable): to snapshot

.eslintrc.json, package.json, src/components/AppearanceProvider/AppearanceProvider.tsx, src/components/Chip/Chip.tsx, src/components/Tooltip/Tooltip.tsx, tsconfig.dist.json, tsconfig.json, types/global.d.ts
- Поправил `yarn lint:es`
- Поправил `yarn typecheck`
- **Дополнительно.** Удалил оставшиеся упомнинания `vkuiClass` (забыл сделать здесь #3318)
**Рис. 1** ESLint жалуется, что матчеры jest'а возвращают `promise`, хотя это не так
Есть два момента:
1. В `master` обновили зависимость `expect-playwright` с `0.2.6` до `0.8.0` ([`3cecda`](https://github.com/VKCOM/VKUI/pull/3326/commits/3cecda31c89866069ef3a938938983c5da71cf70#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R73)). А с версии `0.6.0` ([release note](https://github.com/playwright-community/expect-playwright/releases/tag/v0.6.0)) расширили кол-во матчеров.
Подключается здесь:
https://github.com/VKCOM/VKUI/blob/c32efca6750bde879ca068429b017a08697eca58/tsconfig.json#L45-L46
2. При слиянии `master` в `v5` …
=> ci: правит падающий `yarn test:ci` в ветке `v5`

.github/workflows/pull_request.yml
Исправляем условие для report_tests
При отмене экшона, report_tests не должен запускаться
=> ci(pr): fix report_tests condition

src/components/ModalRoot/ModalRoot.tsx
This reverts commit 5d684249a0e7bd60195118925ecbc3103f265875.
Ревертаем, потому что возвращается pull-to-refresh поведение на iOS
=> Revert "fix(ModalRoot): Исправляет скролл при touch-событиях"

src/components/ContentCard/ContentCard.tsx
Делаем возможность переназначить `hasActive` & `hasHover`
=> fix(ContentCard): support `hasActive` & `hasHover`

src/components/FormLayoutGroup/FormLayoutGroup.css, src/components/Removable/Removable.css
(+hide offset element for removable items by default)
- fix #3436
=> fix(FormLayoutGroup): Remove margin left for offset element

src/components/Tappable/Tappable.css
=> fix(Tappable): pointer-events: none for `disabled`

src/components/Link/Link.css
Воспроизводится на Samsung A6+, но не воспроизводится на A12. Не зависит от браузера
- Fixes #3469
После исправления бага:
https://user-images.githubusercontent.com/14944123/196494535-dc2a6086-d95a-4931-b9fb-bc1ba64b20c9.mp4
=> fix(Link): use `pointer: fine`

docs/ADAPTIVITY_GUIDE.md, styleguide/pages/adaptivity.md
Исправил ошибку с отображением примера кода как "редактируемого" (closes #3567)
> Также переписал функцию в useEffect на стрелочную (более распространенный вариант)
=> docs: fix Adaptivity section

yarn.lock
Обновляем до последней версии
- https://github.com/webpack/loader-utils/releases/tag/v2.0.4
- https://github.com/webpack/loader-utils/releases/tag/v3.2.1
=> build(deps): bump loader-utils from 3.2.0 to 3.2.1

package.json, styleguide/Components/ReactComponent/ReactComponent.css, styleguide/Components/ReactComponent/ReactComponent.js
Предлагаю добавить ссылку на Issues компонента, чтобы было проще найти известную проблему, прежде чем заводить баг.
Также, переименовываю Github на Source, чтобы было понятнее, куда ведет ссылка, так как в шапке был элемент с таким же текстом.
=> docs: add component issues link and rename source link

src/components/Tappable/Tappable.module.css, src/components/Tappable/Tappable.tsx
Изменяем поведение `activeMode=background`
- избавляемся от перебития специфичности
- избавляемся от `.Tappable--mouse`
- переименовываем `.Tappable__hoverShadow` в `.Tappable__stateLayer`
---
- fixes #3623
=> fix(Tappable): `activeMode=background` use stateLayer

src/components/GridAvatar/GridAvatar.test.tsx
Чтобы не вылетал варнинг об одинаковых ключах.
=> test(GridAvatar): fix GridAvatar max length test

package.json, src/components/ChipsInput/__image_snapshots__/chipsinput-android-chromium-dark-1-snap.png, src/components/ChipsInput/__image_snapshots__/chipsinput-android-chromium-light-1-snap.png, src/components/DateInput/__image_snapshots__/dateinput-android-chromium-dark-1-snap.png, src/components/DateInput/__image_snapshots__/dateinput-android-chromium-light-1-snap.png, src/components/DateRangeInput/__image_snapshots__/daterangeinput-android-chromium-dark-1-snap.png, src/components/DateRangeInput/__image_snapshots__/daterangeinput-android-chromium-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-android-chromium-dark-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-android-chromium-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-ios-webkit-dark-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-ios-webkit-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-dark-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-firefox-dark-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-firefox-light-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-webkit-dark-1-snap.png, src/components/Tabs/__image_snapshots__/tabs-vkcom-webkit-light-1-snap.png, yarn.lock
Часть иконок в репе `@vkontakte/icons` поменялась между минорами, поэтому развалилось столько скриншотов в https://github.com/VKCOM/VKUI/pull/3657 при попытке обновиться на `@vkontakte/icons@alpha`.
Соответственно — нужен бамп `@vkontakte/icons` в v4.
=> chore(build-deps): update @vkontakte/icons to 1.205.0

styleguide/pages/migration_v5.md
В пункт про типы `weight` добавил примеры с остальными типографическими компонентами, которых затрагивает это изменение.
=> docs(migration_v5): дополняет секцию "Типографика"

.github/workflows/pr_close.yml, .github/workflows/publish.yml, .github/workflows/publish_prerelease.yml, .github/workflows/publish_token_translator.yml, .github/workflows/pull_request.yml, .github/workflows/update_screens.yml, package.json, src/components/View/ViewInfinite.tsx, yarn.lock
Обновление nodeJS до последних версий, для избежания устаревания их в CI
=> ci: use 18 node.js

package.json, src/components/Cell/CellCheckbox/CellCheckbox.tsx, src/components/DropdownIcon/DropdownIcon.tsx, src/components/WriteBarIcon/WriteBarIcon.css, src/types.ts
=> build(deps_v4): support @vkontakte/icons v2 alongside v1

.github/gitflow/messages.js, .github/gitflow/patch.js, .github/workflows/pr_close.yml, .github/workflows/pull_request.yml
Чинится заменой события `["pull_request"]` на `["pull_request_target"]` ([ссылка на документацию pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)).
- в воркфлоу `pull_request.yml`
-  [x] `deploy_styleguide` – проверили с @SevereCloud в сторонней репе
-  [ ] `report_tests` – простестируем при открытии PR из форк репы
- в воркфлоу `pr_close.yml`
---
- close #3259
=> ci(pull_request): запускает все джобы для PR из форкнутной репы

yarn.lock
> [fixed] updated minimatch to 3.0.5 (and added caret semver range) to address vulnerability in minimatch 3.0.4
[Changelog](https://github.com/jergason/recursive-readdir/blob/master/CHANGELOG.md)
=> build(deps): bump recursive-readdir from 2.2.2 to 2.2.3

package.json, yarn.lock
Обновляем `@vkontakte/icons` до свежего патча, чтобы пофиксить `RichTooltip` и `Link`.
=> build(deps): bump @vkontakte/icons to v2.1.1

src/components/Calendar/Readme.md, src/components/DateInput/Readme.md
React сохраняет начальное значение один раз и игнорирует его при
следующем рендеринге
```tsx
const [value, setValue] = useState(new Date());
```
Хотя результат `new Date()` используется только  для начального
рендеринга, функция по прежнему вызывается при каждом рендеринге.
Это может быть расточительно, если создаются дорогие объекты
=> docs: fix avoiding recreating

.github/workflows/pull_request.yml
Джобы в PR из форкнутых реп не работали параллельно, т.к. у них был общий `currency.group`.
---
- relate #3765
=> ci(pull_request.yml): использует `github.event.pull_request.number` для `currency.group`

e2e/jest/globalSetup.ts, e2e/jest/globalTeardown.ts
- `listen` method is deprecated in favor async `start` or `startCallback` methods
- `close` method is deprecated in favor async `stop` or `stopCallback` methods
=> test(e2e): remove listen and close

.github/workflows/pr_close.yml
Пропускаем очистку для dependabot, поскольку тот не деплоит стайлгайд
=> ci: skip clear for dependabot

src/components/CustomSelect/CustomSelect.test.tsx, src/components/CustomSelect/CustomSelect.tsx
- Удалил лишний `setOptions`, который был в `close()` – из-за него в `onNativeSelectChange`, при `searchable={true}`, мы получали не отфильтрованный `options`, тем самым `findSelectedIndex` возвращал не соотвествующий действительности `index`. Написал **unit test** на этой кейс, по нему нагляднее понять о чём речь.
- Поправил TODO про `onInputChage`
---
- fix #3600
=> fix(CustomSelect): исправляет выбор элемента с `currentIndex - 1` при `searchable`

.github/workflows/publish.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> cI: Deprecating set-output commands

.github/actions/push-screenshots/src/main.ts
`@actions/exec` не умеет в чейнинг команд
=> chore: Fix push-screenshots action

src/components/Cell/__image_snapshots__/cell-android-chromium-dark-1-snap.png, src/components/Cell/__image_snapshots__/cell-android-chromium-light-1-snap.png, src/components/CellButton/__image_snapshots__/cellbutton-android-chromium-dark-1-snap.png, src/components/CellButton/__image_snapshots__/cellbutton-android-chromium-light-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-chromium-dark-w_2-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-chromium-dark-w_3-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-chromium-light-w_2-1-snap.png, src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-android-chromium-light-w_3-1-snap.png, src/components/IconButton/__image_snapshots__/iconbutton-android-chromium-dark-1-snap.png, src/components/IconButton/__image_snapshots__/iconbutton-android-chromium-light-1-snap.png, src/components/RichCell/__image_snapshots__/richcell-android-chromium-dark-1-snap.png, src/components/RichCell/__image_snapshots__/richcell-android-chromium-light-1-snap.png, src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-dark-1-snap.png, src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-light-1-snap.png, src/components/Tappable/Tappable.module.css
Т.к. мы [переопределяем](https://github.com/VKCOM/VKUI/blob/5.0-stable/src/components/Tappable/Tappable.module.css#L22) `z-index` для всех потомков `Tappable`, необходимо поднять `z-index` для шапки календаря, т.к. в ней инлайнится выпадашка с выбором месяца и года
_____
- адекватное решение будет в #3633
=> fix(Calendar): Fix stacking context issue

src/components/Alert/Alert.module.css, src/components/FocusVisible/FocusVisible.module.css
Используем border вместо box-shadow для inside мода
До|После
-|-
=> fix(FocusVisible): use border for inside

src/components/Popover/Popover.tsx, src/hooks/useEventListener.ts
Наткнулась на достаточно пограничный кейс - если динамически поменять `action`, то listener'ы от `hover`-состояния не удалялись, что приводило к багам
=> fix: remove listener if action type change

src/components/ChipsSelect/ChipsSelect.tsx
Выносим выпадашку за пределы FormField
Используя `forceDropdownPortal={false}` дропдаун размещался под следующим компонентом ChipsSelect.
=> fix(ChipsSelect): dropdown outside FormField

src/components/Badge/Readme.md, src/components/CustomSelectOption/CustomSelectOption.tsx
- в доке `Cell` был не переименован проп 
- в `CustomSelectOption` удаление пропа перенесено в `v6`
=> fix: Small docs typos

styleguide/package.json, yarn.lock
This reverts commit 41bce82a9c9bba2a76df8897cc17651c1ad65cfd.
See [note](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.2.5)
=> Revert "build(deps-dev): bump react-frame-component from 5.2.4 to 5.2.5"

packages/vkui/jest.config.js
Игнорируем покрытие для e2e файлов в unit тестах
=> test: ignore e2e in unit coverage

packages/vkui/global.d.ts, packages/vkui/src/components/SplitCol/SplitCol.tsx, packages/vkui/src/hooks/useAdaptivityWithJSMediaQueries.ts, packages/vkui/src/hooks/useAutoDetectAppearance.tsx, packages/vkui/src/lib/matchMedia.ts, packages/vkui/tsconfig.json
Старые версии safari не поддерживают `MediaQueryList.prototype.addEventListener` и `MediaQueryList.prototype.removeEventListener`
https://caniuse.com/mdn-api_mediaquerylistevent
=> fix(polyfills): MediaQueryListEvent API

packages/vkui/package.json
Потерялись `LICENSE` и `README.md` в артефакте
---
- caused by #3902
=> fix(@vkontakte/vkui): копирует рутовые `LICENSE` и `README.md` перед паблишом

.github/workflows/publish.yml, .github/workflows/pull_request.yml
Следовал **Version 4 Migration Guide** (https://github.com/JamesIves/github-pages-deploy-action/discussions/592)
Отключил выгрузку `styleguide` в артифакты если это PR от `dependabot`, т.к. мы не запускаем `deploy_styleguide` для него
=> ci(deps): bump JamesIves/github-pages-deploy-action from 3.7.1 to 4.4.1

src/components/CustomSelect/CustomSelect.tsx
- fix #4055
- related to #2447
=> [v4] fix(CustomSelect): provide `before` prop of `FormField` to component

.github/workflows/update_screens.yml, .github/workflows/workflow_test_e2e.yml, .gitignore
Кешируем lfs.
Используем подход, описанный в https://github.com/actions/checkout/issues/165
---
Что дает:
- уменьшение передаваемого трафика до lfs
- ускорение чекаута с кешем (~12 cек -> ~3 cек)
=> ci(e2e): lfs cache

packages/vkui/src/components/Avatar/AvatarBadge/AvatarBadgeWithPreset.tsx
По типам пробрасывается className, но не применяется
---
- caused by #3718
=> fix(AvatarBadgeWithPreset): support className

.github/workflows/publish.yml
Тег `latest` сейчас используется для **v5**.
Тег `v4` будет означать `latest` для **v4**.
=> ci(publish): use `--tag v4` for `yarn publish`

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
**Additional:** remove reachable code like `placeholder={restProps.placeholder}`
---
- fix #4055
- related to #2447
=> fix(CustomSelect): provide `before` prop of `FormField` to component

packages/vkui/src/components/Epic/Epic.module.css, packages/vkui/src/components/Epic/Epic.tsx, packages/vkui/src/components/FixedLayout/FixedLayout.module.css, packages/vkui/src/components/Panel/Panel.module.css, packages/vkui/src/components/Snackbar/Snackbar.module.css
Добавляем класс hasTabbar для проверки использования tabbar
Был вот такой запрос:
> [Epic](https://vkcom.github.io/VKUI/5.1.0/#/Epic) требует нижней панели навигации и занимают свободное место под `tabbar`.
>
> В приложении не планируются табы снизу.
=> fix(Epic): add hasTabbar

src/components/Dropdown/Dropdown.tsx, src/components/Tooltip/Tooltip.tsx
Добавляем capture: true, чтобы Dropdown точно смог закрыться
- backport #4088
- fix #3989
=> [v4] fix(Dropdown): add capture

packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
Вытаскиваю лишнее из https://github.com/VKCOM/VKUI/pull/3803, часть шестая.
Заменила `IS_DEV` везде, где он еще был, на `process.env.NODE_ENV === 'development'`, для консистентности. Как сказал @inomdzhon:
> многие сборщики, конечно, выкупят `IS_DEV` для удаления условия, но как-будто лучше если мы будем примерно одинаково такие условия писать
>
> зачастую у нас везде используется прямая (`process.env.NODE_ENV === 'development'`) проверка окружения в условиях
=> chore: replace `IS_DEV` w/ `process.env.NODE_ENV === 'development'`

packages/vkui/src/components/DateInput/DateInput.tsx
Вытаскиваю лишнее из https://github.com/VKCOM/VKUI/pull/3803, часть третья.
Убрала `tabIndex={1}` из `DateInput`. [У axe есть хорошее пояснение, почему не надо делать `tabindex`, отличающийся от `-1` и `0` (на английском)](https://dequeuniversity.com/rules/axe/4.4/tabindex).
=> fix(DateInput): remove dangerous tabIndex={1}

.github/workflows/publish_prerelease.yml
=> ci(publish_prerelease deps): bump JamesIves/github-pages-deploy-action from 3.7.1 to 4.4.1 (v4)

tools/swc-transform-css-modules/rust-toolchain.toml
На новых версиях  rust-а плагины собираются поврежденными
- see [swc 6807](https://togithub.com/swc-project/swc/issues/6807)
=> fix(swc-transform-css-modules): use rust 1.66.0

styleguide/Components/List/List.css
<details>
<summary>Стало посимпатичнее 😉 </summary>
-----
</details>
-----
- fixes https://github.com/VKCOM/VKUI/issues/2199
=> docs(styleguide): fix list styles

packages/vkui/src/components/IconButton/IconButton.tsx, packages/vkui/src/components/TabbarItem/TabbarItem.tsx, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx, packages/vkui/src/lib/warnOnce.ts
И снова вытаскиваю всякое из https://github.com/VKCOM/VKUI/pull/3803.
Что сделала:
- добавила объект `COMMON_WARNINGS`, чтобы не переписывать одни и те же варнинги по несколько раз
- `WriteBarIcon`: исправила текст варнинга на текст из `COMMON_WARNINGS` внутри 
- `IconButton`: добавила a11y-варнинг
- `TabbarItem`: добавила a11y-варнинг
**Пример варнинга со ссылками на документацию axe:**
=> feat(warnOnce): add COMMON_WARNINGS object

.github/workflows/pull_request_common.yml, .github/workflows/pull_request_packages.yml
Объединяем в одну джобу, чтобы оптимизировать установку зависимостей.
Несмотря на кэширование [actions/setup-node@v3](https://github.com/actions/setup-node/tree/v3.6.0), `yarn install` занимает небольшое время.
---
- caused by #4197
=> ci(pull_request_packages.yml): merge jobs of linters to one job

docs/ADAPTIVITY_GUIDE.md, packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/components/CardGrid/CardGrid.tsx, packages/vkui/src/components/Chip/Chip.tsx, packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/components/FormField/FormField.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx, packages/vkui/src/components/IconButton/IconButton.tsx, packages/vkui/src/components/Input/Input.tsx, packages/vkui/src/components/NativeSelect/NativeSelect.tsx, packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx, packages/vkui/src/components/Radio/Radio.tsx, packages/vkui/src/components/RangeSlider/UniversalSlider.tsx, packages/vkui/src/components/RichCell/RichCell.tsx, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx, packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx, packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx, packages/vkui/src/components/Switch/Switch.tsx, packages/vkui/src/components/TabsItem/TabsItem.tsx, packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/components/Typography/Headline/Headline.tsx, packages/vkui/src/components/Typography/Subhead/Subhead.tsx, packages/vkui/src/components/Typography/Text/Text.tsx
Пример того, что было сделано:
```diff
- const sizeXClassNames = {
-  none: styles['Component--sizeX-none'],
-  [SizeType.COMPACT]: styles['Component--sizeX-compact'],
-  [SizeType.REGULAR]: null, 
- };
-
- sizeXClassNames[sizeX]
+ const sizeXClassNames = {
+  none: styles['Component--sizeX-none'],
+  [SizeType.COMPACT]: styles['Component--sizeX-compact'],
+ };
+
+ sizeX !== SizeType.REGULAR && sizeXClassNames[sizeX]
```
Проверка дешевле, чем обращение к объекту впустую.
---
- caused by #4241
- caused by #4259
=> refactor: remove null variant from class names maps

.github/actions/patch/src/main.ts
Оборачиваем в `try catch`, потому что порой `git fetch` падает из-за якобы не валидных SHA
Пример
_https://github.com/VKCOM/VKUI/actions/runs/4196621551/jobs/7277839717_
=> ci(@actions-internal/patch): mv fetch to try catch block

docs/ADAPTIVITY_GUIDE.md, packages/vkui/src/components/SplitCol/SplitCol.module.css, packages/vkui/src/components/SplitCol/SplitCol.tsx, packages/vkui/src/lib/adaptivity/constants.ts, packages/vkui/src/lib/adaptivity/functions.test.ts, packages/vkui/src/lib/adaptivity/functions.ts, packages/vkui/src/lib/adaptivity/types.ts, packages/vkui/src/types.ts
В рамках #4275 неверно удалил `getViewWidthClassName()` – надо было её переделать под **CSS Modules**.
Переделал и переименовал во `viewWidthToClassName()`
Применил в компоненте `SplitCol` (получилось упростить CSS).
Обновил `docs/ADAPTIVITY_GUIDE.md`.
---
- caused by #4275
=> fix(adaptivity): create viewWidthToClassName()

.github/workflows/reusable_workflow_test.yml, .github/workflows/reusable_workflow_test_a11y.yml, .github/workflows/reusable_workflow_test_e2e.yml
Добавляем fail_ci_if_error чтобы ронять ci, если отчет не загрузился
=> ci(codecov): add fail_ci_if_error

packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/PanelHeader/PanelHeader.tsx, packages/vkui/src/components/SelectTypography/SelectTypography.tsx
Пропустил в #4261 варианты с пустой строкой вместо `null`.
---
- caused by #4261
=> refactor: remove empty variant from class names maps

packages/vkui/jest.config.js
Игнорируем `.stories.tsx` в покрытии
=> test(coverage): ignore .stories.tsx

packages/vkui/src/components/PopoutRoot/PopoutRoot.module.css
Не закрываем экран, если внутри PopoutRoot__popout ничего нет
=> feat(PopoutRoot): popout:empty display: none

packages/vkui/src/components/List/Readme.md
`List` не нужен для неперетаскиваемых ячеек.
=> docs(List): update docs to reflect proper usage

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
=> feat(HorizontalScroll): add scrollOnAnyWheel

.eslintrc.json, .git-blame-ignore-revs, packages/token-translator/.eslintrc.json, styleguide/.eslintrc.json, styleguide/Components/Modals/useFetch.js
Adding new eslint rules:
- `curly`: Enforce consistent brace style
- `eqeqeq`: Only type-safe equality operators
=> Add curly & eqeqeq eslint rules

.github/workflows/pull_request_packages.yml
Ошибся в регулярке в двух исключениях для `*.md` файлов.
---
- caused by #4197
- related to #4482
=> fix(pull_request_packages.yml): fix glob pattern in paths-ignore

packages/vkui/webpack.styles.config.js
Убираем предупреждения при сборке css
=> chore(webpack-styles): fix warning

.github/actions/patch/src/main.ts, .github/actions/patch/src/message.ts
Исправляем проблему с `invalid refspec`, которая возникает когда у нас несколько коммитов.
_Пример из PR #4518 https://github.com/VKCOM/VKUI/actions/runs/4465844345/jobs/7850781149_
В #4518 получилась вот такая команда
```sh
git fetch origin 5.2-stable '274939a9c0ad1e23b8552c7ef027440368777b1e 6b33f880a3936b7e0a93cfcb97b2c7b75176f26b'
```
вместо
```sh
git fetch origin 5.2-stable 274939a9c0ad1e23b8552c7ef027440368777b1e 6b33f880a3936b7e0a93cfcb97b2c7b75176f26b
```
=> ci(@actions-internal/patch): fix 'invalid refspec' problem

.github/workflows/inactive_contributions.yml
Добавляем лейбл `no-stale` для того, чтобы определенные PRы не помечались как `stale`
=> chore: Add exempt pr label

.github/file-filters.yml
Была проблема в glob паттерне – не видел изменения на уровне `packages/vkui/*`. Разбил на два.
_Пример из PR #4575. Должен был тригернуться на `packages/vkui/package.json`_
---
- related to #4197
=> ci(file-filters.yml): fix bad glob pattern for package_vkui

packages/vkui/package.json
Из-за того, что `docs/assets` лежит в корне проекта, а `README.md` копируется в `packages/vkui` при создании артефакта, получается так, что пути до лого резолвятся не верно.
_Вот примеры из NPM. Нет папки `docs/assets`, поэтому и картинка не грузится в доке_
Во время создания артефакта, также копируем `docs/assets` в `packages/vkui`
=> fix(@vkontakte/vkui): copy docs/assets dir before publish

packages/vkui/src/lib/utils.ts
Некоторые скринридеры при отсутствии пробелов даже раздробленный на разные `span` текст зачитывают как одно слово.
Добавляем уверенности, что наш `getTitleFromChildren` себя так не поведет. (%
=> fix(a11y/getTitleFromChildren): add space

packages/vkui/src/components/ModalPage/ModalPage.module.css
Требуется многим для возможности растянуть контент внутри
=> fix(ModalPage): ModalPage__content-in height: 100%

packages/vkui/src/components/UsersStack/UsersStack.tsx
NVDA зачитывает этот компонент так: "+1Алексей, Илья, Михаил и ещё 1 человек".
"+1" зачитывать вообще не нужно, аватарки здесь тоже идут скорее как визуальный мусор, поэтому я поправила `role="presentation"` на `aria-hidden` на `.UsersStack__photos`.
=> fix(UsersStack): add aria-hidden to othersElement

packages/vkui/src/components/ActionSheet/types.ts, packages/vkui/src/components/Typography/Caption/Caption.tsx, packages/vkui/src/components/Typography/Footnote/Footnote.tsx, packages/vkui/src/components/Typography/Headline/Headline.tsx, packages/vkui/src/components/Typography/Paragraph/Paragraph.tsx, packages/vkui/src/components/Typography/Subhead/Subhead.tsx, packages/vkui/src/components/Typography/Text/Text.tsx, packages/vkui/src/components/Typography/Title/Title.tsx, packages/vkui/src/components/Typography/types.ts
Подчистила типы.
**`SharedDropdownProps`**
- убрала лишний `React.AllHTMLAttributes<HTMLElement>` (он уже есть в `FocusTrapProps`)
**Компоненты типографики**
- создала `TypographyProps` и `HasCaps`,
- порефакторила все типографические компоненты на это дело,
- удалила лишние варнинги об использовании нестрокового `Component` с `getRootRef`
=> types: fixes

packages/vkui/src/components/SubnavigationButton/SubnavigationButton.a11y.test.tsx, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx
**Зачем:** в `aria-label` собиралось значение только из `children`, из-за чего значение каунтера, переданного в `after`, не учитывалось скринридерами и портило невизуальную доступность.
Выпилила `aria-label`, добавила тест на доступность.
=> fix(SubnavigationButton): fix aria-label

packages/vkui/src/components/Separator/Separator.a11y.test.tsx, packages/vkui/src/components/Separator/Separator.module.css, packages/vkui/src/components/Separator/Separator.tsx, packages/vkui/src/components/Spacing/Spacing.a11y.test.tsx, packages/vkui/src/components/Spacing/Spacing.tsx
`Separator` был отмечен как `role='separator'`, но роль не считывалась из-за `aria-hidden`. 😆
Соответственно:
- `Separator`: перевела на `hr`, выкинула `aria-hidden` и лишнюю роль, подбила стили
- `Spacing`: выкинула `aria-hidden`, т.к. внутрь может передаваться  `Separator`
- Добавила a11y-тесты для этих двух компонентов
=> refactor(Separator, Spacing): fix a11y

.github/actions/s3/src/main.ts, .github/workflows/pr_close.yml
Удаляем папку с PR-ом всегда.
Если в PR dependabot кто-то запушит коммит, то документация все равно задеплоится
=> ci(s3): undeploy always

packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/ModalPage/ModalPageContext.tsx, packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx, packages/vkui/src/components/PanelHeader/PanelHeader.tsx
Относится к https://github.com/VKCOM/VKUI/issues/3041, ориентировался на [WCAG пример](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/).
Возможно, изменение `PanelHeader` в таком явном виде не нужно (как я понял, компонент используется не только внутри модалок?), а следует трогать `ModalPageHeader`, передавая `PanelHeader` новые пропсы   - нужно ваше мнение.
Помимо `ModalPage` могу помочь и с `ModalCard` в рамках новой задачи.
=> feat(ModalPage, PanelHeader): upgrade a11y

packages/vkui/src/components/Accordion/Accordion.tsx, packages/vkui/src/components/Accordion/AccordionSummary.tsx, packages/vkui/src/components/AdaptiveIconRenderer/AdaptiveIconRenderer.tsx, packages/vkui/src/components/Group/Group.tsx, packages/vkui/src/components/LocaleProvider/LocaleProvider.tsx, packages/vkui/src/components/PlatformProvider/PlatformProvider.tsx, packages/vkui/src/components/UsersStack/UsersStack.tsx
- заменила `@version` на `@since`, потому что мы указываем не _версию_ компонента/пропса, а _с какой версии_ VKUI компонент/пропс стал доступен
- добавила пару потерявшихся `@see`
- поправила пару мелких опечаток.
=> docs: jsdoc fixes

packages/vkui/src/testing/e2e/screenshotWithClipToContent.ts
Ускоряем e2e 356.17s -> 208.23s
--- 
- related #4652
=> test(e2e): rm waitForLoadState networkidle

packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/AppRoot/AppRootPortal.tsx, packages/vkui/src/components/AppRoot/ScrollContext.tsx, packages/vkui/src/components/Epic/ScrollSaver.tsx, packages/vkui/src/components/Group/Group.tsx, packages/vkui/src/components/IconButton/IconButton.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.stories.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/ModalRoot/ModalRootAdaptive.tsx, packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx, packages/vkui/src/components/ModalRoot/types.ts, packages/vkui/src/components/ModalRoot/useModalManager.tsx, packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx, packages/vkui/src/components/Removable/Removable.tsx, packages/vkui/src/components/SelectTypography/SelectTypography.tsx, packages/vkui/src/components/Spacing/Spacing.tsx, packages/vkui/src/components/Tabs/Tabs.e2e-playground.tsx, packages/vkui/src/components/Tappable/Tappable.tsx, packages/vkui/src/components/Typography/Typography.stories.tsx, packages/vkui/src/index.ts
- переправила везде `children?: React.ReactNode` на импорт типа `HasChildren`
- `ModalRoot`: глобально поправила типы, чтобы не было дублирования
- `RemovableOwnProps`: заменила экстенд на более точный `React.HTMLAttributes<HTMLDivElement>`
- `SelectTypographyProps` (помимо `HasChildren`): добавила `extends React.HTMLAttributes<HTMLSpanElement>` и выпилила ставший ненужным благодаря этоему `className`
=> chore(types): use `HasChildren` 

packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e.tsx, packages/vkui/src/testing/e2e/index.playwright.ts
Вынес сброс позиции мыши в единое место. В рамках https://github.com/microsoft/playwright/issues/22432#issuecomment-1512307007 подсказали, что в целом перед каждым тестом стоит сбрасывать позицию мыши. Добавил **UPD** в PR по Playwright https://github.com/VKCOM/VKUI/pull/4652#firefox-bottleneck.
---
- related to #4652
=> tech(playwright): reset mouse pos for every tests

packages/vkui/src/components/ModalPage/ModalPage.module.css
Перестал работать нижний отступ из-за height: 100%
- related #4625
=> fix(ModalPage): bottom safe area

.github/actions/patch/src/main.ts
Из-за `--depth=1` черри-пик проходит с конфликтами
_https://github.com/VKCOM/VKUI/actions/runs/4784365452/jobs/8505771574_
---
- caused by #4853
=> fix(@actions-internal/patch): rm `--depth=1` flag

packages/vkui/jest.config.js
Тесты, название которых оканчивались на `a` или `y`, не работали
(например `Textarea.test.tsx`)
- related #4768
=> test(unit): fix testRegex

packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
Перетасовала jsdoc-описание, чтобы пофиксить отображение [документации](https://vkcom.github.io/VKUI/#/VisuallyHidden).
=> docs(VisuallyHidden): show docs

packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx, packages/vkui/src/components/PanelHeader/PanelHeader.tsx
> см. https://github.com/VKCOM/VKUI/issues/4963#issuecomment-1533140117
В данном случае можно было решить задачу через пропс вместо подкомпонента.
Кто-то мог уже завязаться на `PanelHeader.Content`, поэтому отметил его как `@deprecated` и добавил TODO на v6.
---
- fix #4963
- caused by #4808
=> fix(PanelHeader): replace sub-component with props

.github/dependabot.yml, .github/file-filters.yml, package.json
1. Удалил из `file-filters.yml` и `package.json` несуществующие ныне папки.
2. Изменения #4883 в `dependabot.yml` не увенчались успехом – PR по Storybook продолжают сыпаться в течение недели. Из следующего issue https://github.com/dependabot/dependabot-core/issues/5226#issuecomment-1179434437 узнал, что для монорепы достаточно указать `directory: /` и далее он сам выкупит что обновить, поэтому:
1. удалил точечные объявления пакетов
2. в `ignore` добавил зависимости `@storybook/*`, чтобы мы ориентировались только на `storybook`
3. также советуют установить `versioning-strategy: increase`, чтобы локфайлы всегда обновлялись – скорей всего в настройках репы он и указан, но на всякий захардкодил;
4. ⚠️ заменил частоту проверки обновления на `weekly`
=> tech: cleanup project configurations

packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css
**Версия:** >= 5.1.0
Из-за `isolation: isolate` в ситуациях, когда всплывающее элемента рендерится без портала, перекрывается `z-index` этого элемента вне `FormLayoutGroup`.
_**Рис. 1** с `isolation: isolate`_
_**Рис. 2** без `isolation: isolate`_
Ссылка на воспроизведение https://codesandbox.io/s/pr5089-formlayoutgroup-isolation-problem-c0zher
<details><summary>backup кода из Codesandbox</summary>
<p>
```tsx
import {
ConfigProvider,
AdaptivityProvider,
AppRoot,
Group,
Panel,
PanelHeader,
SimpleCell,
View,
FormLayoutGroup,
FormItem,
Textarea,
unstable_ChipsSelect as ChipsSelect
} from "@vkontakte/vkui";
import { useState } from "react";
export default function App() {
const colors = [
{ value: "red", label: "Красный" },
{ value: "blue", label: "Синий" },
{ value: "navarin", label: …
```
=> fix(FormLayoutGroup): rm `isolation` prop

packages/vkui/src/components/Banner/Banner.module.css, packages/vkui/src/components/Banner/Banner.tsx, packages/vkui/src/components/InfoRow/InfoRow.tsx, packages/vkui/src/components/TabsItem/TabsItem.tsx, packages/vkui/src/components/Typography/Typography.module.css, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.module.css
В некоторых браузерах NVDA не добавляет автоматически пробелы между двумя span.
Что сделала, чтобы это исправить:
----- 
- Изменения в `Header` вынесла в отдельный пулл https://github.com/VKCOM/VKUI/pull/5019
=> fix(a11y): Расставляем пробелы для скринридеров

packages/vkui/src/components/AppRoot/AppRootPortal.tsx, packages/vkui/src/components/Popper/Popper.tsx, packages/vkui/src/components/Popper/Readme.md
fix #4454 
- Добавляем кастомный проп `rootPortal` в `Popper` для того, чтобы дать возможность переопределить элемент в котором будет отрисован портал.
- в `AppRootPortal` также добавлен такой же проп, так как `Popper` использует `AppRootPortal` у себя внутри.
- При передаче `rootPortal` и `forcePortal=true` в `Popper` или `AppRootPortal` игнорируется флаг `disablePortal` из контекста `AppRootContext`.
Тестов нет, так как планируется избавиться от Popper в пользу `useFloating()` хука.
=> feat(Popper): add custom rootPortal prop for Popper

package.json, yarn.lock
Из-за апгрейда зависимости с **1.0.1** до **1.0.3** были проблемы со сборкой. Что **styleguide**, что **storybook** по долгу запускались и не могли закончить компиляцию.
В репозитории issue не нашёл ([ссылка на issues по **postcss-global-data**](https://github.com/csstools/postcss-plugins/issues?q=is%3Aopen+is%3Aissue+label%3Aplugins%2Fpostcss-global-data)) – _создаю issue_.
---
- caused by #5066
=> deps(@csstools/postcss-global-data): fix to 1.0.1

packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
Исправляем логику фокуса в ChipsSelect
- fixes #5051
=> fix(ChipsSelect): fix focusedOptionIndex logic

packages/vkui/src/components/ButtonGroup/ButtonGroup.e2e-playground.tsx, packages/vkui/src/components/ButtonGroup/ButtonGroup.e2e.tsx, packages/vkui/src/components/ButtonGroup/ButtonGroup.module.css, packages/vkui/src/components/ButtonGroup/ButtonGroup.tsx, packages/vkui/src/components/ButtonGroup/Readme.md, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-android-chromium-dark-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-android-chromium-light-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-ios-webkit-light-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-vkcom-webkit-light-1-snap.png
fix #4651 
- добавлена возможность выравнивания по правому/левому краю в режиме mode="horizontal".
- по умолчанию в `mode="horizontal"` `align-items` теперь `"center"`. Неявно оно было `"flex-start"` если `align` проп не передан, так как умолчанию он устанавливался в значение "left", или `"flex-end"` если `align="right"`.
- обновлен пример в документации.
=> feat(ButtonGroup): align button group buttons in horizontal mode

packages/vkui/src/components/NativeSelect/NativeSelect.test.tsx, packages/vkui/src/components/NativeSelect/NativeSelect.tsx
=> fix(a11y/NativeSelect): hide duplication of selected option from screen reader

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- добавил логику чтобы для показа `clearButton` проверять значение `props.value` если компонент контролируемый или  `nativeSelectValue` если копмонент не контролируемый.
Если `CustomSelect` контролируемый, но при клике на опцию мы не меняем значение `props.value` и значение `props.value = ''` и включен флаг `allowClearButton`, то при клике на любую опцию из дропдауна мы показываем кнопку очистки, хотя значение самого селекта остается пустым.
Это происходит из-за того, что `Select` реализован так, что при клике на опцию мы всегда меням значение внутреннего состояния селекта (`nativeSelectValue`). При этом для того чтобы показать `clearButton` сейчас мы смотрим именно на значение `nativeSelectValue`. Хотя если селект контролируемый, то мы должны смотреть на значение props.value.
Шаги для …
=> fix(CustomSelect): Don't show clear button with empty props.value

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- fix #5010 
- программно вызываем событие `change` у Select когда пользователь кликает на уже выбранную опцию, то есть когда value у селекта не меняется.
Мы вынуждены программно вызывать `change` у селекта в обработчике клика на опцию, потому что функция `onNativeSelectChange`, которая  висит на `onChange` нативного селекта, вызывается только когда `value` меняется у селекта. А наша задача также поддержать вариант когда value не меняется при клике.
https://github.com/VKCOM/VKUI/blob/017fa68c9f687e3a337c15d482be9c8b9622965b/packages/vkui/src/components/CustomSelect/CustomSelect.tsx#L747-L750
https://github.com/VKCOM/VKUI/blob/017fa68c9f687e3a337c15d482be9c8b9622965b/packages/vkui/src/components/CustomSelect/CustomSelect.tsx#L483-L497
Для того, чтобы `onChange` prop  `CustomSelect` …
=> fix(CustomSelect): click on already selected option triggers onChange

packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx, packages/vkui/src/components/Select/Readme.md
Добавлен запрет на использование `disabled` пропа прямо на `CustomSelectOption` если он рендерится внутри `Select` или `CustomSelect` через  `renderOption`.
Иначе Select не знает о состоянии опции и может позволить выбрать disabled элемент с клавиатуры.
<details>
<summary>Пример неправильного использования.</summary>
```jsx
const [value, setValue] = React.useState('');
const options = React.useMemo(
() => [
{ label: 'Мужской', value: 'm' },
{ label: 'Женский', value: 'f' },
],
[],
);
<View activePanel="select">
<Panel id="select">
<PanelHeader>Select</PanelHeader>
<Group>
<Button onClick={() => setValue('')}>reset</Button>
<FormItem top="Администратор">
<CustomSelect
value={value}
placeholder="Не задан"
options={options}
onChange={(event) => {
console.log('TEST', event.target.value); …
```
=> doc(CustomSelectOption): Don't allow to use disabled directly on CustomSelectOption inside Select

packages/vkui/src/components/NativeSelect/NativeSelect.tsx
Убираем свойство `multiple` из типов
=> fix(NativeSelect): omit `multiple`

packages/vkui/src/components/TabbarItem/TabbarItem.tsx
**Версия:** 5.5.1
Из-за того, что не пробрасывается `getRooRef` в атрибут `ref`, не работает, например, `TextTooltip`.
Пример кода, который не работает в https://vkcom.github.io/VKUI/5.5.1/#/TabbarItem
```jsx
const [simple, setSimple] = React.useState('one');
<Tabbar style={{ position: 'static', margin: '0 0 10px' }}>
<TextTooltip text="Новости" placement="top" appearance="accent">
<TabbarItem selected={simple === 'one'} onClick={() => setSimple('one')} aria-label="Новости">
<Icon28NewsfeedOutline />
</TabbarItem>
</TextTooltip>
<TextTooltip text="Профиль" placement="top" appearance="accent">
<TabbarItem selected={simple === 'two'} onClick={() => setSimple('two')} aria-label="Профиль">
<Icon28UserCircleOutline />
</TabbarItem>
</TextTooltip>
</Tabbar>
```
=> fix(TabbarItem): use getRootRef prop in ref

packages/vkui/src/testing/e2e/index.playwright.ts
Удаляем фикс #4891, т.к. проблема была исправлена на уровне библиотеки Playwright (см. https://github.com/microsoft/playwright/issues/22432)
=> tech(playwright): rm mouse pos reset

.github/dependabot.yml, .github/workflows/schedule_cargo_update.yml
Чтобы комплексно обновлять зависимости Rust, добавляем отдельный
воркфлоу, который по крону будет проверять обновления, и если они есть,
то обновлять и создавать один PR. Проверять будет по ПН в 05:00.
В Dependabot увеличили лимиты на PR до 20, а также отложили обновления
на 10 часов относительно расписания по крону, чтобы не было лишних PR.
Конечно, Dependabot автоматически закрывает PR, если зависимость была
обновлена. Этот сценарий возможен в двух случаях: если PR с
обновлениями всех возможных зависимсотей смержили позже расписания
Dependabot; если к моменту запуску Dependabot появились ещё обновления.
=> tech(deps): add schedule for complex cargo update

packages/vkui/src/components/Select/Select.tsx
Вынес свойства которые не используются в NativeSelect
Не уверен что можно что-то сейчас сделать на уровне типизации,
https://github.com/Microsoft/TypeScript/issues/12936
- Fixes #4378
=> fix(Select): nativeProps

packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
Была возможность добавлять в `ChipsSelect` значения не из списка (`creatable=false`)
=> Discard adding creatable value without flag

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
CustomSelect умирает на андроиде при использовании [нового рендера](https://reactjs.org/link/switch-to-createroot). Это происходит из-за завязки на фокус при выборе опции(фокус ставится позднее чем выполняется selectFocus)
Решение: Отвязал выбор опции от фокуса
- Fixes #2432
=> fix(CustomSelect):  add selectOption

packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Group/Group.module.css, packages/vkui/src/components/Group/Group.tsx
- исправил адаптивность(вынес определение mode на js)
- исправил разделители между группами
---
- related to #5344
=> fix(Group): spacing adaptivity

packages/vkui/src/components/Group/Group.module.css, packages/vkui/src/components/Group/Group.tsx
Сломались отступы `Group` в модалках, возвращаем, как было
---
- caused by #5364
=> Fix Group padding for modal

packages/vkui/src/components/ImageBase/validators.ts
`parseIconSizeByDisplayName('Icon20TextHeading1Outline')` возвращает 201
=> fix: Icon20TextHeading1Outline is 20 size

.github/actions/complete_playwright_update.yml, .github/actions/complete_storybook_update.yml, .github/dependabot.yml, .github/workflows/pull_request_common.yml
1. Dependabot не умеет делать групповое обновление зависимостей Playwright и Storybook. Приходится обновлять их вручную и создавать отдельный PR.
2. Если бы Dependabot и умел делать групповое обновление, то всё-равно для Playwright нужно будет вручную обновлять версии Docker контейнеров.
До-обновляем зависимости с помощью GitHub Workflows.
1. В `pull_request_common.yml` создаём джобу, которая проверяет не обновился ли Playwright или Storybook.
2. Если да, то запускаем процесс обновления зависимостей этих библиотек и создаём новый коммит в PR от Dependabot.
Когда Dependabot  ребейзит себе мастер, то `pull_request_common.yml` запускается заново. А это значит, что и джоба по обновлению будет запускаться заново. Риска дублирования коммита быть не должно, т.к. из мастер вряд ли прилетят …
=> ci: complete Playwright and Storybook update

styleguide/Components/Heading/Heading.css, styleguide/Components/StyleGuide/StyleGuideDesktop.css, styleguide/Components/StyleGuide/StyleGuideDesktop.js, styleguide/Components/StyleGuide/StyleGuideHeader.css, styleguide/Components/StyleGuide/StyleGuideRenderer.css
**Версия:** >= 5
Шапка и сайдбар прыгают при открытии модалки с версиями.
1. Перейти, например, на https://vkcom.github.io/VKUI/5.5.5/#/Button
2. Немного проскролить страницу.
3. Вызвать из шапки модалку со всеми версиями.
<details><summary>Видео</summary>
<p>
https://github.com/VKCOM/VKUI/assets/5850354/5d0c4f5e-43be-4840-9e1a-282500c22d29
</p>
</details> 
1. Основная причина была в том, что в компонент `SplitCol` для сайдбар
не передавалось св-во `fixed` – теперь передаётся.
1. После указания `fixed`,  переписал стили под лэйаут документации
styleguide, чтобы починить скролл. Получилось убрать перебивание VKUI
стилей, которые нами не приветствуются.
1. У `styleguide/Components/Heading` заменил `margin` на `padding`,
чтобы исправить проблему со "схлопыванием `margin`".
=> fix(docs): refactor styleguide layout

tools/swc-transform-css-modules/Cargo.lock
Снова не сработал воркфлоу [.github/workflows/schedule_cargo_update.yml](https://github.com/VKCOM/VKUI/blob/v5.5.5/.github/workflows/schedule_cargo_update.yml), до этого была проблема, что экшен `peter-evans/create-pull-request@v5` не был в разрешенном списке, поэтому создали вручную PR #5363, а сейчас воркфлоу запускается в рутовой директории, а не в `tools/swc-plugin-transform-css-modules/` (поправил в PR #5408).
=> build(deps): cargo update

.github/workflows/pull_request_dependabot.yml
При использования события `pull_request_target` ссылка `github.ref` соответствует целевой ветке.
Поэтому используем:
- `refs/pull/${{ github.event.pull_request.number }}/merge` для чекаута
- `github.head.ref` для пуша в ветку.
- caused by #5413
=> ci(pr_dependabot): use correct branch ref

docs/CONTRIBUTING.md, packages/vkui/cssm/postcss.config.js, packages/vkui/package.json, packages/vkui/scripts/generateCSSCustomMedias.js, packages/vkui/shared.config.js, packages/vkui/src/styles/customMedias.generated.css, packages/vkui/tsconfig.json, postcss.config.js, shared.js, stylelint.config.js
После мажорного обновления плагина postcss-global-data (см. #5412) вернулась проблема с вечной компиляцией dev-сборки styleguide и storybook (см. #5127).
После очередного изучения проблемы выяснилось, что проблема в создании `/tmp/customMedias.generated.css` в `postcss.config.js` ([ссылка на код](https://github.com/VKCOM/VKUI/blob/bb226ff2edbf0b7954fca56e8e181ee575486306/postcss.config.js#L25-L39)).
Из-за того, что `postcss-loader` вызывает `postcss.config.js` для каждого CSS файла, функция создания `/tmp/customMedias.generated.css` вызывается каждый раз. Начиная с версии `postcss-global-data@1.0.2` эта проблема всплыла.
Храним сгенерированный `customMedias.generated.css` в Git. И пересобираем при необходимости. Для этого была создана команда:
```sh
yarn workspace @vkontakte/vkui run …
```
=> tech: generate customMedias.generated.css once

styleguide/Components/Heading/Heading.css, styleguide/Components/Logo/Logo.js, styleguide/Components/StyleGuide/StyleGuideDesktop.js, styleguide/Components/StyleGuide/StyleGuideHeader.css, styleguide/Components/StyleGuide/StyleGuideHeader.js, styleguide/Components/StyleGuide/StyleGuideRenderer.css
В #5398 пропустили рефактор шапки доки.
Также получилось убрать перебивание VKUI стилей, которые нами
не приветствуются.
Вернул `margin`'ы. А то возникла проблему (см. скрины ниже).
_До #5398. ✅ С отступами всё ок._
_После #5398. ❌  Появились большие отступы._
Поправил схлопывание через `border-top: 0.5px` на
`StyleGuide__contentIn`.
---
- caused by #5398
=> fix(docs): edit header and desktop layout

.github/workflows/reusable_workflow_test_e2e.yml
Убрал `continue-on-error: true` из e2e workflow. 
С этим параметром не видно, что скриншотные тесты упали, и очень легко упустить этот файкт из виду.
Этот параметр был нужен в прошлом workflow, когда скриншоты сравнивались с master и тесты падали при обновлении скриншотов в рамках PR.
Больше не актуально.
Вот тестовый [PR](https://github.com/VKCOM/VKUI/pull/5457) где e2e тесты упали и workflow помечен как failed.
P.S.
В этом PR есть [комментарий](https://github.com/VKCOM/VKUI/pull/5456#issuecomment-1630874866) от github-actions по поводу e2e тестов, но он устаревший, с прошлого состояния PR где тут были изменения в PullToRefresh компонете, с тех пор я форспушнул.
=> Mark e2e workflow as failed on error

packages/vkui/src/helpers/math.test.ts, packages/vkui/src/helpers/math.ts
=> fix(Math.ts): updated `decimatedClamp` implementation

packages/vkui/src/components/Switch/Switch.module.css
=> fix(Switch): user-select: none;

packages/vkui/src/components/Switch/Switch.module.css
=> patch: pr5465

packages/vkui/src/components/Alert/Alert.tsx
Исправляем неуникальные id внутри `Alert`. Может выстрелить в ногу, если у нас окажется несколько Alert на странице. Ситуация почти нереальная, но вот в тестах у нас воспроизводится, например. 😄 
(Заодно проверяем CI, который должен показать, что количество a11y-ошибок уменьшилось.)
-----
- relates to #5276
=> fix(Alert): remove duplicate ids

packages/vkui/src/components/ActionSheet/ActionSheet.e2e-playground.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.stories.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ActionSheet/Readme.md, packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx
Делаем проп `iosCloseItem` необязательным и по дефолту проставляем `ActionSheetDefaultIosCloseItem`, чтобы не нужно было прокидывать вручную.
=> feat(ActionSheet): add default iOS close item

styleguide/Components/Section/SectionRenderer.js, styleguide/Components/Section/index.js
Не использовался созданный `styleguide/Components/Section/SectionRenderer.js`, а бралась из либы `@rsg-components/*`. Из-за чего для заголовка страницы применялся `name` (текст, который используется как имя страницы), а не `title` (текст, который отображается в слева в меню)
_Было_
_Стало_
Заодно добавил новый параметр, который позволит задавать свой заголовок страницы.
Полезно когда хотим отметить принадлежность страницы к какой-либо группе.
_Пример из https://github.com/VKCOM/VKUI/pull/5496. Отмечаем, что эта страницы является подразделом._
=> docs(styleguide): fix configuration

packages/vkui/src/components/Button/Button.e2e-playground.tsx, packages/vkui/src/components/Button/Button.e2e.tsx, packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Button/__image_snapshots__/button-counter-android-chromium-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-android-chromium-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-ios-webkit-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-webkit-light-1-snap.png
- исправляем `background-color` для `Counter` в `Button (mode:primary)`
- добавила e2e-тесты, чтобы быстрее отлавливать баги
=> fix(Button): Fix counter bg color in buttons

.github/dependabot.yml
Каждую неделю **Dependabot** пытается обновить **React** до 18 версии (например, https://github.com/VKCOM/VKUI/pull/5553). В рамках разработки v5 мы используем 17 версию, поэтому игнорируем 18 версию.
=> tech(dependabot): ignore react 18.x

.github/dependabot.yml
- caused by https://github.com/VKCOM/VKUI/pull/5563
=> chore: fix dependabot ignore version type

.github/dependabot.yml
С версии [v13.0.0](https://github.com/testing-library/react-testing-library/releases/tag/v13.0.0) больше не поддерживается React 17.
Как и в случае с https://github.com/VKCOM/VKUI/pull/5573, запрещаем мажорные обновления зависимости.
=> tech(dependabot): freeze @testing-library/react

styleguide/pages/migration_v5.md
Не удалили блок про `vkui__root` в PR https://github.com/VKCOM/VKUI/pull/4180
=> docs(migration_v5): rm info about vkui__root

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
fixes: #5568 
Для рендеринга стрелок наведения мы используем стейт.
Надо или не надо их рендерить мы определяем каждый раз при скролле, чтобы спрятать стрелку вправо, если пользователь доскролил вправо до конца.
Также мы определяем это при первом рендеринге.
Но может быть так, что `HorizontalScroll` был обернут в `useMemo` и отрендерен изначально в компоненте с `display: none`. В таком случае в `useMemo` будет храниться `HorizontalScroll` с состоянием без стрелок, так как он был отрендерен внутри компонента c `display: none` и при вычислении свойства размеров были нулевые . Если родительский компонент поменяет `display` на `block`, то `HorizontalScroll` покажется, но стрелок у него не будет при наведении.
Добавить вычисление показа стрелок при наведении (`onMouseEnter`).
=> fix(HorizontalScroll): Show arrows on hover even though element is memorized

packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ActionSheet/ActionSheetContext.ts, packages/vkui/src/components/ActionSheet/ActionSheetDefaultIosCloseItem.tsx, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx, packages/vkui/src/index.ts
resolves: #5458
В `ActionSheet.onClose` добавляем информацию об инициаторе закрытия. Это может быть пункт меню с пропом `autoClose`, может быть кнопка отмены на iOS, может быть клик вне зоны меню или нажатие `Esc`.
Добавляем в `onClose` колбэк объект со свойством `closedBy`, которое имеет одно из значений: `actionItem`, `cancelItem`, `others`. 
В `ActionSheet` нету сильной разницы между пунктом меню `cancel` и  обычным пунктом меню. Оба пункта сделаны с помощью `ActionSheetItem` и разным значением `mode`. Для того чтобы разделить их добавил проп `isCancelItem` проп `ActionSheetItem`.
Хотелось использовать mode=`cancel`, но он скорее для внешнего вида, так как `ActionItem mode='cancel'` может быть частью меню с каким-то значение и просто иметь mode=`cancel` для вида.
=> feature(ActionSheet): add information about close initiator

packages/vkui/src/components/FormItem/FormItem.module.css, packages/vkui/src/components/FormItem/FormItem.tsx
=> feature(FormItem): Add noPaddings prop to allow to disable paddings

packages/vkui/src/components/Input/Input.module.css
Отключаем нативные элементы для `<input type="number" />` при передаче `type="number"` в [Input](https://vkcom.github.io/VKUI/5.7.1/#/Input).
Иначе приходится использовать кастомный `<input type="number" />` внутри [FormField](https://vkcom.github.io/VKUI/5.7.1/#/FormField) и сбрасывать ему стили.
=> feat(Input): disable controls for type="number"

packages/vkui/src/components/PanelHeader/PanelHeader.module.css, packages/vkui/src/styles/constants.css
Заодно переименовал `--vkui_internal--z_index_panel_header_fixed` в `--vkui_internal--z_index_panel_header`, т.к.  используется не только для `fixed`.
---
- fix #5571
=> fix(PanelHeader): add z-index for visor={false}

packages/vkui/src/hooks/useIsClient.ts
Используем `React.useLayoutEffect` для обновления состояния, чтобы до отрисовки интерфейса в браузере у нас вернулось состояние `true`.
Иначе, при первом рендере, можем иметь неправильные размеры геометрии.
---
- fix #5584
- caused by #3761
=> fix(useIsClient): use useIsomorphicLayoutEffect

packages/vkui/src/components/Tappable/Tappable.module.css, packages/vkui/src/components/Tappable/Tappable.tsx
Новый проп `borderRadiusMode` позволяет оборачивать `Tappable`-элементы в какие-нибудь кастомные компоненты с собственным `border-radius`
=> feat(Tappable): add borderRadiusMode

.eslintignore, .github/workflows/pull_request_packages.yml, .github/workflows/reusable_workflow_test_e2e.yml, .gitignore, .prettierignore, package.json, packages/vkui/playwright-ct.config.ts
Изменения в `reusable_workflow_test_e2e.yml`:
- Используем `strategy.matrix` и `--shard` для распараллеливания джоб.
- Объединяем отчёты через `npx playwright merge-reports` см. https://playwright.dev/docs/test-sharding#github-actions-example
- Удалили загрузку артефакта `e2e-output` за ненадобностью.
- Удалили `TODO Playwright реализовать покрытие`, т.к. покрытие мы уже собираем jest'ом.
Изменения в `playwright-ct.config.ts`:
- Так как в CI мы распараллеливаем тесты через `--shard`, то ставим `workers` на 1.
- Пробуем выставить `maxFailures: 10` в CI, чтобы в лишний раз не гонять все тесты, если 10 из них упали.
- Используем для CI blob для отчёта, чтобы потом можно было смержить.
Стало в ~3.5 раза быстрее 🎉 
_До изменений_
_После изменений_
Пробовал использовать `@actions/cache` для …
=> ci(e2e): use playwright shard feature

packages/vkui/src/components/Group/Group.module.css, packages/vkui/src/components/Group/Group.tsx
fixes: #5603
Так как в `separator="force"` мы добавляли класс `Group__separator--force` и для компонента `Spacing` и для компонента `Separator` то оба компонента могут быть видны ( а значит слишком большой отступ добавляется после Group), если Group последний своего типа в родителе.
Нам же надо, чтобы видно было только `Separator`.
Поэтому добавляем модификатор только этому компоненту.
=> fix(Group): Show only separator--separator (not space) in the separator force mode

packages/vkui/src/components/ImageBase/ImageBase.test.tsx, packages/vkui/src/components/ImageBase/ImageBase.tsx
resolves: #5599 
При SSR изображение может загрузится раньше чем скрипт проинициализируется и повесит обработчик события `load` на img.
В таком случае нам обработчик не будет вызван и компонет останется в состоянии как будто изображение не згружено.
При маунте компонента проверить не было ли изображение уже загружено через `img.complete`. Если уже было, то вручную вызвать событие `load`, чтобы обработать загрузку изображеня как задумано.
=> fix(Avatar/BaseImage): Dispatch load img event if resource is already loaded but onload was not fired

.github/workflows/pr_close.yml
При закрытии PR через воркфлоу [inactive_contributions.yml](https://github.com/VKCOM/VKUI/blob/master/.github/workflows/inactive_contributions.yml), не вызывается событие `closed`. Тем самым не очищается S3 от артефактов (stylegude, storybook, playwrgiht) загруженных в рамках PR.
Для таких случаев вызываем воркфлоу вручную.
Можно завязаться на `pull_request_target`, но мы недавно отказались от этого события в связи с рисками pwn-атак (см. https://github.com/orgs/community/discussions/26657).
=> ci(pr_close): add workflow_dispatch

packages/vkui/src/components/ConfigProvider/ConfigProvider.test.tsx, packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx, packages/vkui/src/lib/utils.test.ts, packages/vkui/src/lib/utils.ts
resolves: #5518 
Для того чтобы независимые приложения не удаляли класс главного приложений из body при размонтировании мы позволяем каждому приложению на странице добавить свой класс в body с помощью `ConfigProvider`, даже если такой класс уже есть.
Работа с классами `body` ведётся с помощь `className` а не `classList` (который не допускает дубликатов).
=> fix(ConfigProvider) Allow duplicated classes in the body created by ConfigProvider

.github/workflows/pull_request_dependabot.yml
После https://github.com/VKCOM/VKUI/pull/5561 `.github/workflows/pull_request_dependabot.yml` теперь падает, т.к. не может запушить изменения.
В доке [Changing GITHUB_TOKEN permissions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions) сказано, что можно дать разрешение на запись для **Dependabot**, тем самым у бота появится возможность пушить.
=> ci(pull_request_dependabot): add write permissions

.github/workflows/pull_request_packages.yml
`test_e2e_prepare_report` должен выполняться всегда после `test_e2e`. В #5624 условие `if: always()` было выставлено не там где надо.
---
- caused by #5624
=> ci: use always() for test_e2e_prepare_report job

packages/vkui/.eslintrc.js, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/ImageBase/ImageBase.tsx, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx
Запрещаем использовать classNames с одним свойством
=> fix: Do not use classNames with one argument

packages/vkui/src/hooks/useFocusWithin.test.tsx, packages/vkui/src/hooks/useFocusWithin.ts
Если в компонент прокинут autoFocus, то useFocusWithin мог
этого не заметить
=> fix(useFocusWithin): check autofocus

packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx, packages/vkui/src/hooks/useAutoFocus.test.tsx, packages/vkui/src/hooks/useAutoFocus.ts
React в свойстве `autoFocus` обрабатывает только button, input, textarea и select
Добавляем хук для авто фокусировки элементов
=> fix(SelectMimicry): useAutoFocus

.github/workflows/pull_request_dependabot.yml
`secrets.DEVTOOLS_GITHUB_TOKEN` недоступен для **Dependabot**, поэтому используем `secrets.GITHUB_TOKEN`
---
- related to #5638
=> ci(pull_request_dependabot): use GITHUB_TOKEN

packages/vkui/src/components/PopoutRoot/PopoutRoot.module.css, packages/vkui/src/components/PopoutRoot/PopoutRoot.tsx
resolves: #5463 
В ситуации с m.vk.com/video из-за большого кол-ва компонентов на странице, если проскролить контент, и вызвать ActionSheet то получается, что абсолютно позиционированный `PopoutRoot` появлялся где-то наверху, в результате чего событие клика вне области `ActionSheet` может не всплыть до `body`, где у `ActionSheet` добавлен обработчик закрытия, особенно если клик был по контенту вне body.
Вне body в m.vk.com/video можно кликнуть потому, что контент на странице позиционирован через fixed/absolute, в результате чего, если чуть проскролить, то область где контента нету это область `html`, не `body`, потому что `body` на столько не растянут.
В этом изменении не должно быть проблем потому что мы уже давно такое используем для мобильных устройств. (см. …
=> fix(ActionSheet/SplitLayout): Make PopoutRoot fixed on desktop

packages/vkui/src/hooks/useAdaptivityHasHover.test.tsx, packages/vkui/src/hooks/useAdaptivityHasHover.ts, packages/vkui/src/hooks/useAdaptivityHasPointer.ts
Не используем двойной рендер если
значение было проброшено через контекст
Поправили условие из PR #5666
- caused by #5666
=> fix(useAdaptivityHasHover): two pass rendering

packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/hooks/useChipsSelect.ts
fixes: #5677 
По какой-то причине мы вообще не использовали этот проп.
- при включенном пропе `showSelected` выбранные опции не отфильтровываются.
- поправил логику закрытия по клику мимо селекта. Оказалось, оттого, что дропдаунт рендерится через портал, click outside логика срабатывает при клике по опции и селект закрывается. Раньше это не было заметно, потому без правильно работающего showSelected пропа выбранные опции всегда удалялись из dropdown и событие клика по опции никак не обрабатывалось и не всплывало до body. А по какой опции был сделан клик мы определяли по `onMouseDown`.
=> fix(ChipsSelect): Use showSelected prop

packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/styles/common.css
Перенёс `translate3d(0, 0, 0)` из CSS в компонент.
---
- close #3475
=> feat(AppRoot): add disableParentTransformForPositionFixedElements prop

.github/workflows/branch_test_coverage.yml, .github/workflows/pr_close.yml, .github/workflows/pr_close_undeploy.yml, .github/workflows/pull_request_common.yml, .github/workflows/pull_request_packages.yml, .github/workflows/pull_request_packages_deploy.yml, .github/workflows/reusable_workflow_pr_worfklow_payload.yml, .github/workflows/reusable_workflow_test.yml
После #5561 потеряли возможность создавать отчёты для PR из форк-репозиторий.
Поэтому по мотивам статьи [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), создаём новый воркфлоу, который срабатывает на `worflow_run`. В таком воркфлоу будет доступ к кредам.
- Вынес из `.github/workflows/pull_request_packages.yml` и из `.github/workflows/reusable_workflow_test.yml` шаги, где нужны креды, в отдельный воркфлоу `.github/workflows/pull_request_packages_deploy.yml`.
Тем самым у `.github/workflows/branch_test_coverage.yml` появился шаг с выгрузкой отчёта в Codecov.
- Вынес из `.github/workflows/pr_close.yml` шаг, где нужны креды, в отдельный воркфлоу …
=> fix(ci): create new workflow for report CI results

packages/vkui/src/components/Placeholder/Placeholder.tsx, packages/vkui/src/components/Placeholder/Readme.md, packages/vkui/src/index.ts
Добавляем подкомпоненты для Placeholder
- see #4696
- see #4699
=> feat(Placeholder): add subcomponents

packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/components/AppRoot/AppRootContext.ts, packages/vkui/src/components/Group/Group.module.css, packages/vkui/src/components/Group/Group.tsx, packages/vkui/src/components/Group/Readme.md, packages/vkui/src/components/Panel/Panel.module.css, packages/vkui/src/components/Panel/Panel.tsx, packages/vkui/src/components/SplitLayout/Readme.md, packages/vkui/src/styles/common.css, styleguide/Components/Playground/PlaygroundRenderer.js, styleguide/Components/Preview.js, styleguide/Components/Setting/Setting.js, styleguide/Components/Settings/LayoutSelect.js, styleguide/Components/Settings/Settings.js, styleguide/Components/StyleGuide/StyleGuideRenderer.js
Добавляем новое свойство `layout: 'plain' | 'card'`
Изменяем вид Group при mode="card" и sizeX="compact"
- closed #3018
=> feat(AppRoot): add `layout`

package.json
Связяна с: https://github.com/VKCOM/VKUI/pull/5717
Для обновления yarn до v3 надо удалить пустой `yarn.lock` файл из `/packages/vkui/`, потому что этот файл мешает yarn 3 без ошибок установить зависимости.
Этот пустой файл нужен для того, чтобы помочь экшену `andresz1/size-limit-action` правильно понять какой пакетный мереджер использовать.
https://github.com/andresz1/size-limit-action/blob/v1.7.0/src/Term.ts#L18-L22
Чтобы продолжить пользоваться экшеном без ошибок придётся удалить `packages/vkui/yarn.lock` и отказаться от свойства `directory`, потому что
именно по нему экшен попадает в `packages/vkui` и пытается найти `yarn.lock` чтобы определить пакетный менеджер. Если `yarn.lock` нет, то переключившись на ветку master и перейдя в папку `packages/vkui` он пытается установить зависимости …
=> tech: Добавляем команду `size:ci` в package.json монорепы

packages/vkui/src/components/AppRoot/AppRoot.tsx
Добавляем условие, чтобы не аффектило отличные от `embedded` режимы подключения
=> Fix AppRoot mode

packages/vkui/src/components/MiniInfoCell/Readme.md
=> docs(MiniInfoCell): rm textLevel

packages/vkui/src/components/NavIdContext/NavIdContext.tsx, packages/vkui/src/components/NavIdContext/useNavId.test.tsx, packages/vkui/src/components/NavIdContext/useNavId.ts, packages/vkui/src/components/Panel/Panel.tsx, packages/vkui/src/components/View/View.tsx, packages/vkui/src/components/View/ViewInfinite.tsx, packages/vkui/src/index.ts
=> feat: add useNavId

packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx, packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx, packages/vkui/types/env.d.ts
Сломалась сборка в vite из-за переменной.
Переименовываем `NODE_ENVIRONMENT` в `NODE_ENV` и фиксируем в типах
- fixed #5767
=> fix: bad env NODE_ENVIRONMENT

.github/dependabot.yml
- related to #5723
По умолчанию выставляем метку `v5` для PR от Dependabot, чтобы не приходилось это делать вручную. Договорились обновление зависимостей пока тоже мержить в ветку **v5**.
> **Note**
>
> Указание `labels` перебивает метки, который выставляет Dependabot по умолчанию в зависимости от `package-ecosystem`, поэтому вручную указал их.
=> tech(dependabot): add v5 label

.github/workflows/publish.yml, .github/workflows/publish_prerelease.yml
True by default.
Ингда при релизе может не быть майлстоуна, например во время теста `publish` workflow, или при публикации тестовой кастомной версии. Хочется, чтобы этот шаг можно было пропустить.
=> tech: Skip close milestone if needed with flag close_milestone

packages/vkui/src/components/ModalDismissButton/Readme.md
Кнопка пропала из документации https://vkcom.github.io/VKUI/#/ModalDismissButton
Пропажа связана с 
https://github.com/VKCOM/VKUI/commit/b5aa644c1d5a45d28a8c9240110829e4e7ca4a59
потому что мы стали полагаться на `position: relative` `PopoutWrapper__content`, но в примере он имеет ширину на всю страницу.
Вернул position: relative в пример.
До
После
=> Fix ModalDismissButton appearance in the doc

packages/vkui/playwright/index.css, packages/vkui/scripts/postcss.js, packages/vkui/shared.config.js, packages/vkui/src/components/Banner/Banner.module.css, packages/vkui/src/components/Card/Card.module.css, packages/vkui/src/components/Chip/Chip.module.css, packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.module.css, packages/vkui/src/components/FocusVisible/FocusVisible.module.css, packages/vkui/src/components/FormField/FormField.module.css, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css, packages/vkui/src/components/Group/Group.module.css, packages/vkui/src/components/HorizontalCell/Readme.md, packages/vkui/src/components/HorizontalCellShowMore/Readme.md, packages/vkui/src/components/ImageBase/ImageBase.module.css, packages/vkui/src/components/PanelHeader/PanelHeader.module.css, packages/vkui/src/components/PromoBanner/PromoBanner.module.css, packages/vkui/src/components/Separator/Separator.module.css, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css, packages/vkui/src/components/Tabbar/Tabbar.module.css, packages/vkui/src/components/TabsItem/TabsItem.module.css, packages/vkui/src/components/WriteBar/WriteBar.module.css, packages/vkui/src/index.ts, packages/vkui/src/styles/constants.css, packages/vkui/src/styles/dynamicTokens.css, stylelint.config.js
=> feat: dynamic tokens

packages/vkui/package.json, packages/vkui/tsconfig.dist.json
=> tech: turn on declaration map for vkui package

packages/vkui/src/styles/dynamicTokens.css
- ~[ ] Unit-тесты~ визуальное исправление
- ~[ ] e2e-тесты~ нет инфры под разный dpi
- ~[ ] Дизайн-ревью~ визуальное исправление
Делаем color_separator_primary в зависимости от dpi
=> feat: color_separator_primary dpi

.github/workflows/publish.yml, .github/workflows/publish_prerelease.yml
Добавила в параметры запуска `publish`'a булик, который отвечает за проставление тега `latest` при паблише пакета в `npm` и `release notes`.
При деплое сторибука и стайлгайда оставляем только файлики по пути версии (чтобы не затирались актуальные)
Если `latest=false`, то в `npm` сейчас будет запаблишена версия с тегом `legacy` (`npm` требует всегда пушить с каким-нибудь тегом). Пока кажется, что мы  хотим паблишить без `latest` только версии прошлого мажора, поэтому тег более-менее подходящий. Раньше мы паблишили с тегом мажора (например, `v4`), но `npm` так делать не [рекомендует](https://docs.npmjs.com/adding-dist-tags-to-packages#:~:text=Note%3A%20Since%20dist%2Dtags%20share%20a%20namespace%20with%20semantic%20versions%2C%2 …
=> chore(ci): add latest tag support

packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx
---
- fix #5740
---
- ~[ ] e2e-тесты~ 
Для случая, когда модальные окна сменяются (`modal1 - null - modal2`) достаточно быстро (в пределах длительности анимации закрытия), теряли подложку у модального окна (она оставалась в `opacity: 0`, а при появлении нового окна (из состояния `null`) мы всегда полагались на то, что компонент с подложкой будет замаунчен заново).
Теперь в `entering`-фазе всегда проставляем подложке `opacity: 1`. 
Для десктопной версии завернула изменение стилей в `requestAnimationFrame`, чтобы сохранить очередность событий
=> fix(ModalRoot): fix modal overlay 

packages/vkui/src/components/Avatar/Readme.md, packages/vkui/src/components/Gradient/Readme.md, packages/vkui/src/components/Group/Group.e2e-playground.tsx, packages/vkui/src/components/Group/Group.e2e.tsx, packages/vkui/src/components/Group/Group.module.css, packages/vkui/src/components/Group/Group.tsx, packages/vkui/src/components/Group/__image_snapshots__/group-android-chromium-dark-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-android-chromium-light-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-ios-webkit-light-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Image/Readme.md, packages/vkui/src/components/InfoRow/InfoRow.stories.tsx, packages/vkui/src/components/InfoRow/Readme.md, packages/vkui/src/components/SimpleCell/Readme.md
- ~[ ] Unit-тесты~ (css)
- ~[ ] Дизайн-ревью~ (визуальное исправление)
Делаем для свойства header правильное расположение
Все что передается в header будет визуально смещено вверх в зависимости от логики(карточка или не первая плашка)
=> fix(Group): header margin

packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/ModalPage/ModalPage.test.tsx, packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/ModalPageHeader/ModalPageHeader.test.tsx, packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx, packages/vkui/src/components/PanelHeader/PanelHeader.tsx
Основано на вопросах по поводу того как писать наиболее стабильные E2E тесты используя vkui.
Мотивация:
- как можно меньше зависеть от внутренней реализации VKUI и уйти от селекторов в тестах.
- не всегда удобно завязываться на текст, хоть и может быть предпочтительнее.
В подкомпонентном подходе это, конечно, будет легче сделать, но мы всё равно оставим для пользователей возможность использовать уже собранный вариант компонента по умолчанию и хотелось бы поддержать возможность для пользователей прокидывать внутрь `data-testid`.
В https://github.com/VKCOM/VKUI/issues/2342 мы окончательно смогли бы решить эту проблему.
На данный момент просто хотелось бы дать возможность уже сейчас подготовиться пользователем к изменениям в css и отвязаться от классов в тестах.
- добавил проп …
=> feature(ModalPage/Alert) Allow to pass testid to inner components

packages/vkui/src/components/Clickable/Clickable.module.css, packages/vkui/src/components/Clickable/Clickable.test.tsx, packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/ImageBase/ImageBase.tsx
- ~[ ] e2e-тесты~ (функциональное поведение)
- ~[ ] Дизайн-ревью~ (функциональное поведение)
Даем возможность кликабельности изображение
Добавил новый внутренний компонент Clickable для правильной работы a11y. В будущем он должен заменить Tappable (#3599 #1443)
=> feat(ImageBase): Clickable

packages/vkui/src/components/ActionSheet/ActionSheet.e2e.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.module.css, packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-dark-1-snap.png, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-light-1-snap.png, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-light-1-snap.png, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
- close #3866
---
~- [ ] Дизайн-ревью~ (не требуется, ничего не поменялось)
Тень имеет лишний отступ потому что ActionSheet имеет паддинг при прозрачном фоне.
Плюс ко всему этот отступ заметен не только сверху но и между списком опций и кнопкой "Отмена".
Пришлось разделить и обернуть список опций и кнопку отмена в отдельные обертки
- добавляется отдельная обертка вокруг списка опций и кнопки отмена в iOS
- обертки отвечают за тень.
- убраны стили `ActionSheetItem` отвечающие за border-radius, потому что за это теперь отвечают обертки в  `ActionSheet`.
- отступ в Android и iOS задается теперь задаётся только через паддинг. 
- увеличили точность алгоритма в скриншотном тестировании в ActionSheet e2e тестах. По причине того, что точность по умолчанию не позволяла заметить изменения в тени …
=> fix(ActionSheet): iOS Remove extra shadow padding

packages/vkui/src/components/Popper/Popper.tsx
- fix #5759 
Т.к. `useIsClient` теперь обновляет состояние через `useLayoutEffect`, в **React 18** начало неправильно пересчитываться положение `Popper` при первом открытии.
Сначала думал это связано с двойным вызовом `useEffect` в **development** при оборачивание в `StrictMode`, но ни удаление этой обёртки, ни сборка в **production** не помогли.
Попробовал заменить `useEffect` также на `useLayoutEffect`, что помогло.
- caused by #5606
=> fix(Popper): mv to useLayoutEffect

packages/vkui/src/components/ActionSheet/ActionSheet.module.css, packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ActionSheet/ActionSheetContext.ts, packages/vkui/src/components/ActionSheet/ActionSheetDropdownMenu.tsx, packages/vkui/src/components/ActionSheet/ActionSheetDropdownSheet.tsx, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
- closed #906
---
Добавляем свойство `mode` для форсированного включения меню или щита 
Внутри заменил `isDesktop` на `mode`. Добавил форсирование свойства `mode`
=> feat(ActionSheet): add `mode`

packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx, packages/vkui/src/components/ActionSheetItem/subcomponents/Radio/Radio.module.css, packages/vkui/src/components/ActionSheetItem/subcomponents/Radio/Radio.tsx
- closed #2017
---
Добавлено свойство `after` для ActionSheetItem
Была вынесена Radio иконка как отдельный компонент, слегка пофиксил a11y.
Прокинул свойство `after` в нужное место
=> feat(ActionSheetItem): add `after`

packages/vkui/src/components/Tappable/Tappable.e2e-playground.tsx, packages/vkui/src/components/Tappable/Tappable.e2e.tsx, packages/vkui/src/components/Tappable/Tappable.tsx, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-android-chromium-dark-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-android-chromium-light-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-ios-webkit-light-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-webkit-light-1-snap.png
- closed #5798
---
- ~[ ] Unit-тесты~ визуальное
- ~[ ] Дизайн-ревью~ переключатель
Новое свойство для Tappable `activated` для переключения состояния
=> feat(Tappable): add `activated`

packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/ModalRoot/Readme.md
- close #5712 
----
Добавляем возможность устанавливать фиксированную высоту для ModalPage.
- добавлен новый проп `height`, который можно использовать как в мобильной версии так и в десктопной.
- при использовании в мобильной версии `settlingHeight` будет высчитываться относительно  заданного `height`.
=> feature(ModalPage): Add height prop to ModalPage

packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx, packages/vkui/src/components/PanelHeaderClose/PanelHeaderClose.tsx, packages/vkui/src/components/PanelHeaderEdit/PanelHeaderEdit.tsx, packages/vkui/src/components/PanelHeaderSubmit/PanelHeaderSubmit.tsx
- fix #5850 
---
- caused by to #5694 
Добавляем в компоненты ссылку на актуальную документацию
=> fix(PanelHeaderButton): fix preset links

packages/vkui/src/components/WriteBar/WriteBar.e2e-playground.tsx, packages/vkui/src/components/WriteBar/WriteBar.e2e.tsx, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-icons-ios-webkit-dark-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-icons-ios-webkit-light-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-dark-1-snap.png, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css
~- [ ] Unit-тесты~
~- [ ] Дизайн-ревью~
В `iOS` "прыгала" `after` часть в случае, когда иконка и кнопка располагались вместе, а должны оставаться на своих местах
https://github.com/VKCOM/VKUI/assets/7431217/a655f037-2e2f-49bf-a95f-286e5d3b431d
https://github.com/VKCOM/VKUI/assets/7431217/7fd6fb87-693d-456a-b839-3fbfbf3c0817
Добавила компенсацию отступа для случая, когда в `after` части находится и кнопка, и иконки вместе.
И исправила обводку в `IOS` компонента `Counter`, чтобы она совпадала с фоном (пришлось ещё потрогать threshold, чтобы изменения на скриншотах появились)
=> fix(WriteBar): icons shift

packages/vkui/src/components/AspectRatio/AspectRatio.tsx
После fd4948219b59c41d1a61c2e629ac0a773c1dff54 мы перестали передавать `children` в `RootComponent`.
Проверил все изменения из того коммита - это единственное место.
В результате чего на странице [AspectRatio](https://vkcom.github.io/VKUI/5.8.0/#/AspectRatio) начиная с версии 5.8.0 мы не видим картинок.
=> fix(AspectRatio): children prop passing

packages/vkui/src/components/Avatar/Avatar.stories.tsx, packages/vkui/src/components/GridAvatar/GridAvatar.stories.tsx, tools/storybook-addon-cartesian/src/withCartesian.tsx
Не подхватывались переопределения пропов через механизм [mapping](https://storybook.js.org/docs/react/essentials/controls#dealing-with-complex-values)
Поменяла отображения баджика в сторях компонентов `Avatar`/`GridAvatar`
=> chore: Add prop mapping support for Storybook cartesian

packages/vkui/src/components/CellButton/CellButton.module.css, packages/vkui/src/components/CellButton/CellButton.tsx, packages/vkui/src/components/ImageBase/ImageBase.module.css, packages/vkui/src/components/Removable/Removable.module.css, packages/vkui/src/components/SimpleCell/SimpleCell.module.css, packages/vkui/src/components/SimpleCell/SimpleCell.tsx
- related to #5794  [SimpleCell.module.css](https://github.com/VKCOM/VKUI/pull/5794/files#diff-cde505330a0123c800ac2efb02f954a76b39dfafaa0c5250dfb355bafddb7596)
Выставление `color` явно в `.SimpleCell__before` перебивает цвет заданный в вышестоящем компоненте, таком как `CellButton`. В итоге влияет иконку без класса `.vkuiIcon`.
https://github.com/VKCOM/VKUI/blob/e560f5306928f680ce8f060520edefae4fa7de83/packages/vkui/src/components/CellButton/CellButton.module.css#L51-L57
- избавляемся от зависимости цвета от селекторов с .vkuiIcon классом
- используем css-переменную `--vkui_internal--icon_color` которую задаём в `CellButton` и использем в `.SimpleCell__before` и `.SimpleCell__after` с фоллбэком на цвета SimpleCell.
- это позволило также избавится от селекторов в `ImageBase` в случае …
=> fix(SimpleCell): Get rid of selector complexity to define icon color

packages/vkui/src/components/Button/Button.module.css
- close #5846
Поправили font-family в компоненте Button в зависимости от режима и платформы, согласно [дизайн-системе](https://www.figma.com/file/jvJUbY10EFMYTkbxNIIPqd/%F0%9F%92%A0-VKUI-iOS-Library?type=design&node-id=17380-81012&mode=design&t=ft7pwyJK7IA9XKEa-4),
=> fix(Button): Specify correct font-family for the Button in different modes

packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css, packages/vkui/src/components/HorizontalCell/HorizontalCell.test.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx
- close #5883 
Убираем блок с `.HorizontaCell__content` если в нём нечего рендерить, чтобы не занимал места.
=> fix(HorizontalCell): Don't render HorizontalCell__content if it's empty

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
- close #5793
related to #4625, #4689, #5402
Иногда, если достаточно быстро свайпнуть вниз `ModalPage`, то состояние `collapsed` останется `false`, что в 
свою очередь означает, что сработает 
https://github.com/VKCOM/VKUI/blob/9309f383d991ac81469a4b4cf81450085fd10d84/packages/vkui/src/components/ModalRoot/ModalRoot.tsx#L606-L607
и у контента модалки высота будет выставлена как `height: 100%`.
https://github.com/VKCOM/VKUI/blob/9309f383d991ac81469a4b4cf81450085fd10d84/packages/vkui/src/components/ModalPage/ModalPage.module.css#L118-L124
В таком случае при следующем открытии модалки высота контента `.ModalPage__content-in` будет равна высоте родителя `.ModalPage__content` и проверка состояния expanded вернёт false, что в свою очередь заставит модалку открыться на всю высоту. …
=> fix(ModalRoot/ModalPage): Fix flacky expanding and scrolling

packages/vkui/src/components/Panel/Panel.tsx, packages/vkui/src/components/View/Readme.md, packages/vkui/src/components/View/View.module.css, packages/vkui/src/components/View/View.tsx
closes: #5194 
Добавляем затемнение при swipeBack на iOS на появляющейся панели, при этом убираем тень сбоку у текущей панели.
- во `View` добавлен `div`, отвечающий за затемнение панели, рендерящейся внутри `View`.
- такой же div, используемый для затемнения панели при переходах между панелями был удалён из Panel, потому что теперь мы используем его во `View`.   
Удалил, так как мы всё равно стили для него задавали во `View`, а теперь мы должны иметь доступ к нему напрямую для того, чтобы высчитать и присвоить значение `opacity` при `swipeBack`.
- затемнение сделано через div рендерящийся только для при `swipeBack` только для следующей панели.   
- Изначально он имеет частично прозрачный фон, после чего во время swipeBack мы высчитываем opacity для всего div относительно того, на сколько …
=> fix(View): Fix shadow on iOS swipe back

packages/vkui/src/components/Panel/Panel.module.css, packages/vkui/src/components/Panel/Panel.tsx
- ~[ ] Unit-тесты~ визуал
- ~[ ] e2e-тест~ сложно отловить
Не учел переходы между панелями при layout=card
- related #5642
При layout=card у Panel будет фон
=> fix(Panel): background color layout=card

packages/vkui/src/styles/common.css
Известно, что при `overflow-x: hidden` на `body` события скролла не всплывают до `window`. И библиотеки (реализующие виртуальные списки), которые слушают события скролла `window` ломаются.
Рекоммендуем пользователям библиотеки самим выставлять `overflow-x: hidden` на `body`, если это действительно нужно по какой-то причине.
Возможно, что выставим это же на `AppRoot`, если в этом будет необходимость, как в `embedded` режиме.
=> Remove overflow-x: hidden from body

packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/ConfigProvider/ConfigProvider.test.tsx, packages/vkui/src/components/CustomScrollView/CustomScrollView.test.tsx, packages/vkui/src/components/CustomScrollView/CustomScrollView.tsx, packages/vkui/src/components/FormLayout/FormLayout.tsx, packages/vkui/src/components/LocaleProvider/LocaleProvider.test.tsx, packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx, packages/vkui/src/components/Tooltip/Tooltip.test.tsx, packages/vkui/src/components/VisuallyHiddenInput/VisuallyHiddenInput.tsx, packages/vkui/src/testing/utils.tsx
- related to #5651
Из-за проверки только на `null` в `getRootRefTest` ловили ложно-положительные результаты тестов
Там, где проверка не нужна, она была убрана
В некоторых компонентах на рутовые компоненты по ошибке прокидывается `getRoot`, оставила комменты, что в `v6` нужно это убрать
В `CustomScrollViewProps` поправлены типы
=> fix: change getRootRefTest check for null

.yarnrc.yml, package.json, packages/vkui/package.json, packages/vkui/src/lib/floating/adapters.ts, packages/vkui/src/lib/floating/index.ts, packages/vkui/src/lib/floating/types.ts, yarn.lock
Стало известно, что в старых барузерах, типа Firefox 52 приложения на VKUI падают, потому что в коде не преобразуются [spread syntax in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax).
Выяснилось, что проблема в том, что начиная с версии [v5.2.0](https://github.com/VKCOM/VKUI/releases/tag/v5.2.0) мы [перешли](https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2FVKCOM%2FVKUI%2Fcommit%2F0d05eb958c8f1e3c981a462da2ff7988f6c10aae&utf=1) с popperjs на floating-ui. Оказалось, что floating-ui [поддерживают более новые браузеры](https://github.com/floating-ui/floating-ui/commit/ee5d9dd22655cf52de9a7ab337e4cf7c6415b025) чем мы и теперь в нашу сборку попадает код, нарушающий контракт нашего …
=> fix(lib/floating): Use compatible with old browsers version of floating-ui/react-dom using @vkontakte/floating-ui-react-dom

packages/vkui/src/components/Avatar/Avatar.tsx
Экспортируем функцию `getInitialsFontSize`
=> feat(Avatar): export getInitialsFontSize

package.json, packages/vkui/scripts/postcss.js, yarn.lock
Удаляем postcss-custom-properties, поскольку теперь мы попадаем в браузерную [поддержку CSS Custom Properties](https://caniuse.com/css-variables)
Больше не будет фолбэков на CSS Custom Properties
=> BREAKING CHANGE: rm postcss-custom-properties

packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalRoot/ModalRoot.tsx
- close #5901 
----
В идеале, в состоянии `collapsed` (когда модульное окно не до конца раскрыто) скроллить контент невозможно.
Но, если перевести модальное окно из состояния `expanded` (полностью раскрыто) в состояние `collapsed` коротким, лёгким движением вниз, то визуально модальное окно будет в состоянии collapsed, но внутреннее состояние модалки будет `collapsed=false`, а значит скролл будет разрешен.
То же будет если из состоянии collapsed чуть поднять модальное окно за "челку" и отпустить. Скролл также снова будет доступен, хотя визуально модальное окно осталось в состоянии `collapsed`, но внутреннее состояние будет `collapsed=false`.
Особенно легко воспроизвести, если у `ConfigProvider` `hasCustomPanelHeaderAfter=true`.
Проблема тут в логике определяющей внутреннее состояние …
=> fix(ModalPage): Fix scrolling behaviour in the collapsed state of ModalPage

packages/vkui/src/components/Button/Button.e2e-playground.tsx, packages/vkui/src/components/Button/Button.e2e.tsx, packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Button/__image_snapshots__/button-paddings-android-chromium-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-paddings-ios-webkit-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-paddings-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-paddings-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-paddings-vkcom-webkit-light-1-snap.png
- fix #4049
---
В режиме `stretched` у кнопок только с `after` или `before` сохранялись ненужные отступы 
Добавили класс для обнуления отступов + накинули `e2e`-тестов
=> fix(Button): after/before padding for stretched

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- ~[ ] Unit-тесты~ (Фикс типизации)
- ~[ ] e2e-тесты~ (Фикс типизации)
- ~[ ] Дизайн-ревью~ (Фикс типизации)
- ~[ ] Документация фичи~ (Фикс типизации)
Исправляем типизацию для функции `renderOption`, так как свойство `CustomSelectOption['option']` является deprecated
=> fix(CustomSelect): CustomSelectRenderOption

packages/vkui/src/components/Avatar/Avatar.tsx, packages/vkui/src/components/Image/Image.e2e-playground.tsx, packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/ImageBase/ImageBase.tsx, packages/vkui/src/components/ImageBase/helpers.ts, packages/vkui/src/lib/comparing.test.ts, packages/vkui/src/lib/comparing.ts
=> feat(Image): width & height

packages/vkui/src/components/Gallery/Gallery.tsx, packages/vkui/src/components/Gallery/hooks.ts
- fix #5951
---
При уходе с активной вкладки копились колбэки по проигрыванию анимации
Подписываемся на событие `visibilitychange`, чтобы отключать автоматическое пролистывание слайдов, когда пользователь уходит с вкладки
=> fix(Gallery): timeout inactive tab issue

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
Скрывает стрелки навигации в компоненте `HorizontalScroll` от screen reader (например, NVDA). Данная утилита позволяет устанавливать фокус на любой элемент внутри прокручиваемого содержимого, что в свою очередь избавляет такого пользователя от необходимости управлять кнопками прокрутки.
Добавлен атрибут `aria-hidden` на кнопки стрелок навигации.
=> feat(HorizontalScroll): disable scroll arrows for screen readers

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
`option` всегда передается в `renderOption`
=> fix(CustomSelectRenderOption): option is request

.github/workflows/pull_request_common.yml
Не накладываем лейбл <kbd>v5</kbd> на PR-ы названия которых начинаются с `patch`
=> ci(labels): ignore patch

packages/vkui/src/components/Header/Header.test.tsx, packages/vkui/src/components/Header/Header.tsx
Повышение доступности.
Есть компонент `Header`, широко используемый везде. Внутри компонента зашито несколько комбинаций `Title`, `Headline`, `Footnote`. Это все завернуто во внутренний компонент `HeaderContent`.
Для доступности, быстрой навигации по h-заголовкам, таким пользователям необходимо иметь возможность навигироваться по реальным h-заголовкам, вместо span-ов.
Планируется ли такая поддержка h-заголовков внутри `Header`? Варианты по обратной совместимости значение по умолчанию / от режима `mode` / полностью опциональный вариант (т.е. по месту использования руками передавать)?
Другие мысли из чата:
Пару мыслей о доступности Header:
1. Правильно ли впихивать индикатор в h-заголовок (Счетчик всегда должен попадать на ссылку, на кнопку и на заголовок.)
2. Увидел Component="header", …
=> Header a11y

packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
- close #5670
---
Иногда, вместе с pull to refresh в мобильном iOS также может тригерится нативный pull to refresh который обновляет всю страницу.
Происходит это при довольно быстром жесте. 
Проблема в том, что внутренние состояния компонента устанавливаются с небольшой задержкой, потому что мы сначала определяем направление, потом уже начинаем проверять сдвиг по оси Y для отрисовки смещения спинера. И всё это через состояния, которые зависят одно от другого и устанавливаются при разных вызовах рендер функции.
Пока внутренние состояния устанавливаются браузер успевает обработать событие `touchmove` и принять решение о том, что началcя нативный pull to refresh. 
То есть для решения этой проблемы мы должный как можно раньше отменять `touchmove` событие на `document.body`.
Причём сразу …
=> fix(PullToRefresh): Detect pull to refresh gesture in the document's touchmove

.github/workflows/branch_test_coverage.yml, .github/workflows/update_screens.yml
Т.к. при мердже в `stable`-ветки у нас не дублируются скриншоты, то создаем дополнительные `workflow` для синхронизации изменений
Т.к. используем `sharding`, то дополнительно создаем архивы с измененными скриншотами (с сохранением структуры папок) и уже после изменения одним коммитом доставляем в нужную ветку (или создаем PR)
Убрала вызов `e2e`-тестов в `branch_test_coverage.yml`, потому что их запуск ни на что не влияет 
Вызов `update_screens.yml` вручную теперь тоже использует [sharding](https://playwright.dev/docs/test-sharding)
Добавила триггер на `push` в `stable`-ветки, чтобы держать скриншоты в актуальном состоянии
=> chore: add stable branch screenshots

packages/vkui/src/components/Gradient/Gradient.e2e-playground.tsx, packages/vkui/src/components/Gradient/Gradient.e2e.tsx, packages/vkui/src/components/Gradient/Gradient.module.css, packages/vkui/src/components/Gradient/Gradient.tsx, packages/vkui/src/components/Gradient/Readme.md, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-light-1-snap.png
- resolve #5218
---
~- [ ] Unit-тесты~
Добавили новый `mode=default` для случая, когда в светлой теме используется `white` градиент, а в тёмной - оттенок серого (`background_content`)
Добавила `deprecated` ненужных свойств, исправила немного стили, чтобы не было лишнего класса
=> feat(Gradient): add new default mode

packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx, packages/vkui/src/styles/common.css
- close #2806 
- related #5670 и #5967
---
Ещё одна попытка победить нативный pull-to-refresh который периодически появляется при закрытии модалки или в PullToRefresh компоненте.
В целом событие `touchmove` на window уже игнорируется, но этого недостаточно, потому что для pull-to-refresh в мобильном Safari хватит и одного обработанного браузером`touchstart`. 
Используется css свойство [`overscroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) на `html` элементе.
Перепробывал кучу других вариантов с `touchstart/touchmove` событиями, но единственный действенный это превентить `touchstart`. Но тогда перестаёт работать скролл внутри PullToRefresh, а через JS имитировать скролл браузера неблагодарная задача.
добавил глобальный класс, которые в последствии …
=> fix(ModalRoot/ModalPage/PullToRefresh): Disable native pull-to-refresh

packages/vkui-floating-ui/index.mjs
Из-за ошибки в регулярке (группа обёрнута в одинарные кавычки) импорт `@floating/core` не заменялся на ту, что собрана под ES5.
- related to #5958
=> fix(build): rm single quote from floating-ui regex

packages/vkui/.env.development.local, packages/vkui/package.json
Добавил возможность задавать порт для девсервера Storybook через файлик `.env`, чтобы не приходилось менять в `package.json`.
- Для скрипта `yarn run storybook` в `packages/vkui` добавил импорт переменных окружения `.env` с последующим прокидыванием порта в команду `storybook dev -p`.
- _Почему `bash -c`?_ в `@yarnpkg/shell` нет команды `source`, поэтому нужно запускать через `bash -c` (см. https://github.com/yarnpkg/berry/issues/2088#issuecomment-723953394).
- _Что за равно в `${STORYBOOK_DEV_PORT:=6006}`?_ здесь мы задаём значение по умолчанию, если в `.env` вдруг не будет нужной переменной.
> **Note**
> Хотел сделать так, чтобы файл `.env` был не обязателен, но из-за проблемы в `yarn` не смог это реализовать (https://github.com/yarnpkg/berry/issues/4033). Поэтому локально надо себе …
=> tech: provide custom port to storybook dev server

packages/vkui/src/components/ConfigProvider/ConfigProvider.test.tsx, packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx, packages/vkui/src/lib/utils.test.ts, packages/vkui/src/lib/utils.ts
**Версия VKUI:** >= 5.0.1
---
При передаче `<ConfigProvider platform={undefined}>` перебивается значения по умолчанию, из-за чего в контекст приходит `undefined`, а в тэг `body` добавляется класс `vkui--undefined--light`/`vkui--undefined--dark`.
- related to #3574
Создал утилиту `excludeKeysWithUndefined`, через которую прогоняю `props` в `ConfigProvider`.
=> fix(ConfigProvider): exclude prop with undefined value

packages/vkui/src/components/Radio/Radio.test.tsx, packages/vkui/src/components/Radio/Radio.tsx
Довольно сложно тестировать `Radio` элемент в e2e тестах с помощью `data-testid`. Из-за того, что мы передаём data-testid в input, реализованный с использованием [VisuallyHidden](https://vkcom.github.io/VKUI/#/VisuallyHidden). Известно, по крайне мере, о проблемах WebdriverIO, который не может нормально взаимодействовать с таким элементом.
Добавили возможность передавать `data-*` аттрибуты в `label` компонента `Radio` c помощью пропа `labelProps`.
На текущий момент ограничили типы `labelProps` до data-* аттрибутов, чтобы не было конфликтов с `Tappable` и не возникало желания переопределять пропы `Tappable`.
=> feat(Radio): Allow to pass data-* attributes to label element

packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx, packages/vkui/src/components/ModalRoot/types.ts
Добавляем `modalOverlayTestId` для ModalRoot
=> feat(ModalRoot): add modalOverlayTestId

styleguide/Components/Playground/PlaygroundRenderer.js, styleguide/Components/Preview.js
Делаем по дефолту `layout=undefined`, чтобы изменение `layout` там, где он задан в настройках, не аффектило примеры без него
=> docs: fix default layout for examples

packages/vkui/src/components/ModalCard/ModalCard.test.tsx, packages/vkui/src/components/ModalCard/ModalCard.tsx, packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx, packages/vkui/src/components/ModalPage/ModalPage.test.tsx, packages/vkui/src/components/ModalPage/ModalPage.tsx
Добавляем свойство `modalDismissButtonTestId` для ModalCard и ModalPage
Новое свойство `modalDismissButtonTestId` для ModalCard и ModalPage которое прокидывается в кнопку закрытия
=> feat(modal): add modalDismissButtonTestId

packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.e2e-playground.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.e2e.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-android-chromium-light-1-snap.png, packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-ios-webkit-light-1-snap.png, packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.module.css, packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
- resolve #5915 
---
Иногда требуется показать контент без скролла
Добавлен проп `noMaxHeight`, позволяющий отключить задание максимальной высоты
=> feat(CustomSelect,ChipsSelect): add noMaxHeight prop

packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/hoc/withInsets.tsx, styleguide/pages/migration_v6.md
=> patch: pr6071

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/Select/Select.tsx, packages/vkui/src/index.ts, packages/vkui/src/lib/select.ts
- close #6072
---
Мы вроде бы позволяем использовать опции любых типов, которые бы имели у себя обязательные свойста Select, 
https://github.com/VKCOM/VKUI/blob/3a844db48dea7a4d83d2b9020c2bf21ba18a3344/packages/vkui/src/components/CustomSelect/CustomSelect.tsx#L107-L112
но сейчас TS ругается если мы пытаемся использовать в `renderOption` опции со свойствами, которых нету в `CustomSelectOptionInterface`. 
Добавили дженерик для типа опций с constraint, чтобы можно было использовать расширинный тип опции с обязательными полями.
=> fix(Select/CustomSelect): Allow to use custom options in renderOption prop

packages/vkui/src/components/ModalCard/ModalCard.e2e-playground.tsx, packages/vkui/src/components/ModalCard/ModalCard.module.css, packages/vkui/src/components/ModalCard/ModalCard.test.tsx, packages/vkui/src/components/ModalCard/ModalCard.tsx, packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx, packages/vkui/src/components/ModalRoot/types.ts
- close #5646
---
При открытии, фокусируемся на контейнер `ModalPage`/`ModalCard` если внутри модалки нет элемента, на котором уже есть фокус (проверяем через `document.activeElement`).
- Для контейнера `ModalPage`/`ModalCard` добавлены `tabIndex={-1}`, чтобы была возможность фокусироваться на него, но при этом по Tab'у на него пользователь больше не попадал.
- Добавил параметр `noFocusToDialog`, чтобы была возможность отключить фичу (понадобилось в e2e тестах `ModalCard`, см. коммент в тестах).
- Добавил отключение `outline` на фокус в CSS для `ModalPage` и `ModalCard`.
- Для `ModalCard` добавил недостающие для a11y атрибуты.
=> feat(Modal): focus to modal container if controllable element doesn't focused
