src/components/ChipsSelect/ChipsSelect.tsx, src/components/CustomScrollView/CustomScrollView.tsx, src/components/Search/Search.tsx
=> [v4] бэкпорт фиксов из v5

src/components/Checkbox/Checkbox.tsx
=> [v4] feat(Checkbox): расшрияет параметры от `Tappable`

packages/vkui/shared.config.js, packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx, packages/vkui/src/shared/breakpoints.js
Используем not для исправления проблем с дробными пикселями.
Исправляет часть проблем в стайлгайде связанным с определением адаптивности в хроме и масштабом 90%
=> fix(Adaptivity): use `not` in media rule

packages/vkui/src/components/PanelHeader/PanelHeader.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
Добавляем android класс, если platform отличается от ios и vkcom
- link #3415
=> fix(PanelHeader): android className default

packages/vkui/src/components/Slider/Slider.e2e.tsx, packages/vkui/src/components/Slider/Slider.tsx, packages/vkui/src/components/Slider/__image_snapshots__/slider-android-chromium-dark-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-android-chromium-light-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-ios-webkit-light-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-webkit-light-1-snap.png
- Вернул потерявшийся `isControlled` в предикате для первого аргумента `clamp()`.
- Добавил e2e на этот кейс
---
- fix #4044
- caused by #3686
=> fix(Slider): fix behavior for zero `value` and negative `min`

packages/vkui/src/components/Footer/Readme.md, packages/vkui/src/components/Panel/Readme.md, packages/vkui/src/components/Popper/Readme.md, packages/vkui/src/components/Touch/Readme.md
- fix cell prop in footer
- fix cell prop in header
- fix theme change in Popper
- fix Touch example
=> chore(doc): Fix docs minor bugs

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
=> fix(CustomSelect): invalid value not call onChange

postcss.config.js
Возвращаем фолбеки для css properties и vkui-tokens
=> fix: fallback css properties

.github/dependabot.yml
=> ci(dependabot): fix swc-transform-css-modules path

tools/swc-transform-css-modules/Cargo.lock, tools/swc-transform-css-modules/src/lib.rs
=> build(deps): cargo update

packages/vkui/src/components/Button/Button.module.css
=> fix(Button): Fix width for single icon buttons

src/components/Button/Button.css
=> [v4] fix(Button): fix width for single icon buttons

.github/workflows/publish.yml
Фиксаем деплой версий v4 как latest для gh-pages
=> Fix styleguide deploying v4

packages/vkui/src/components/Progress/Progress.tsx
Вытаскиваю лишнее из https://github.com/VKCOM/VKUI/pull/3803, часть вторая.
Добавила дефолтный `title` нашему кастомному `Progress`.
=> fix(Progress): add title

packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.module.css, packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.tsx
Вытаскиваю лишнее из https://github.com/VKCOM/VKUI/pull/3803, часть первая.
Перевела `CellCheckbox` на `VisuallyHiddenInput`.
=> refactor(CellCheckbox): use VisuallyHiddenInput

packages/vkui/src/components/Card/Card.module.css
=> fix(Card): outline add `pointer-events: none`

packages/vkui/src/components/Card/Card.module.css
=> patch: pr4150

packages/vkui/src/components/Search/Search.module.css
=> fix(Search): fix padding token

packages/vkui/src/components/Touch/Touch.test.tsx, packages/vkui/src/components/Touch/Touch.tsx
=> patch: pr3932

src/components/HorizontalScroll/HorizontalScroll.css, src/components/TabsItem/TabsItem.css
=> [v4] feat(Tabs): use vkui-tokens for x-gaps

packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-ios-webkit-dark-w_2-1-snap.png, packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-ios-webkit-light-w_2-1-snap.png, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
=> fix(ActionSheetItem): Fix accent color for item on iOS

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.module.css, packages/vkui/src/components/Tabs/Tabs.module.css, packages/vkui/src/components/Tabs/Tabs.tsx, packages/vkui/src/components/TabsItem/TabsItem.module.css
=> patch: pr4155

packages/vkui/src/components/Checkbox/Checkbox.tsx
=> feat(Checkbox): provide states props of Tappable

.github/actions/patch/action.yml, .github/actions/patch/src/main.ts, .github/actions/stable-branch/action.yml, .github/actions/stable-branch/src/main.ts, .github/workflows/pr_close.yml, .github/workflows/publish.yml
=> patch: 4018

yarn.lock
=> build(deps): update @sideway/formula

packages/vkui/src/components/FormField/FormField.tsx
Вытаскиваю лишнее из https://github.com/VKCOM/VKUI/pull/3803, часть пятая.
Подправила верстку `FormField`, чтобы улучшить доступность компонента (и выкинуть лишнее).
=> refactor(FormField): change markup for better a11y

packages/vkui/src/components/ContentCard/ContentCard.tsx, packages/vkui/src/components/ContentCard/Readme.md
Это я вдруг подумала и поняла, что слишком сильно все усложняю.
-----
- Отпочковалось от #4111
- Относится к https://github.com/VKCOM/VKUI/issues/4186
=> fix(ContentCard): add default `alt=""`

packages/vkui/src/components/ModalCard/ModalCard.tsx, packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx, packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalPage/ModalPage.tsx
Добавляем возможность указывать size для модальных окон
- closed #3637
=> feat(Modal): add `size: number`

postcss.config.js, tools/postcss-restructure-variable/index.js
Используем `Once` при реструктуризации vkui-tokens
- see #4219
=> fix(postcss-restructure-variable): use Once

styleguide/.eslintrc.json, styleguide/Components/Modals/Platforms.js, styleguide/Components/Modals/Versions.js, styleguide/Components/Preview.js, styleguide/Components/ReactComponent/ReactComponent.js, styleguide/Components/StyleGuide/StyleGuideDesktop.js, styleguide/Components/StyleGuide/StyleGuideMobile.js, styleguide/Components/TableOfContents/TableOfContents.js
Потихоньку отказываемся от бабеля
---
- related to #4080
=> style: use @typescript-eslint/parser

package.json, yarn.lock
=> Revert "build(deps-dev): Bump @csstools/postcss-global-data from 1.0.1 to 1.0.2"

packages/vkui/shared.config.js, packages/vkui/src/shared/breakpoints.js
Отрицание отдельной функции с помощью `(not (...))` имеет плохую поддержку и запутано
---
- caused by #4037
=> fix(Adaptivity): using hack-width in media queries

packages/vkui/src/lib/date.test.ts, packages/vkui/src/lib/date.ts
Добавляем больше тестов для date.ts
codecov - https://app.codecov.io/gh/VKCOM/VKUI/pull/3999
=> test(date): add more

index.html
Надо хоть какую то иконку использовать для сайта с докой, а то на данный момент нет никакой. Когда много вкладок открыто не можешь найти сайт с докой. Можно эту картинку что в static лежит.
=> Add icon for doc site

styleguide/config.js
https://github.com/VKCOM/VKUI/pull/4258#issuecomment-1433421916
=> Add favicon into config for gh-pages doc site

packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx
=> fix(SegmentedControl): fix animation on initial render

packages/vkui/src/components/Typography/Caption/Caption.a11y.test.tsx
(Заодно и CI проверим еще раз)
- https://github.com/VKCOM/VKUI/pull/4154
=> test(Caption): add a11y test

styleguide/pages/migration_v5.md
Добавил в доку по миграции про удаление **VK Sans Display**.
---
- https://github.com/VKCOM/VKUI/discussions/4201
- caused by #2977
=> docs(migration_v5.md): add info about VK Sans Display

packages/vkui/src/components/Header/Header.module.css
=> fix(Header): add margin Group > Tappable > Header

src/components/Header/Header.css
=> [v4] fix(Header): add margin Group > Tappable > Header

packages/vkui/src/components/Counter/Counter.module.css, packages/vkui/src/components/WriteBar/Readme.md, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx, packages/vkui/src/components/WriteBarIcon/WriteBarIconRenderer.tsx, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-android-chromium-dark-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-android-chromium-light-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-dark-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-light-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-webkit-light-1-snap.png
=> fix(WriteBar): fix design review notes

packages/vkui/src/components/Snackbar/Readme.md, packages/vkui/src/components/Snackbar/Snackbar.module.css, packages/vkui/src/components/Snackbar/Snackbar.tsx
=> fix(Snackbar): fix design review notes

docs/TESTING.md, packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.tsx, packages/vkui/src/components/Cell/CellDragger/CellDragger.tsx, packages/vkui/src/components/File/File.tsx, packages/vkui/src/components/ModalCard/ModalCard.tsx, packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx, packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx, packages/vkui/src/components/NativeSelect/NativeSelect.tsx, packages/vkui/src/components/PanelHeader/PanelHeader.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx, packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.tsx, packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx, packages/vkui/src/components/SelectTypography/SelectTypography.tsx, packages/vkui/src/components/SimpleCell/SimpleCell.tsx, packages/vkui/src/components/Switch/Switch.tsx, packages/vkui/src/components/View/ViewInfinite.tsx, packages/vkui/src/helpers/getPlatformClassName.ts, styleguide/pages/migration_v5.md, styleguide/pages/utils.md
=> tech(css modules): deprecate getPlatformClassName()

packages/vkui/src/components/Pagination/Pagination.tsx, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-android-chromium-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-android-chromium-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-ios-webkit-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-webkit-light-1-snap.png
Используем знак многоточия вместо трех точек, для правильного прочтения скринридерами
=> fix(Pagination): a11y use ellipsis

packages/vkui/src/components/Input/Input.tsx
- fix https://github.com/VKCOM/VKUI/issues/3995
=> fix(Input): throw up mode param to form-field

packages/vkui/src/components/Input/Input.tsx, packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
=> patch: pr4347 pr4348

packages/vkui/src/components/Snackbar/Readme.md, packages/vkui/src/components/Snackbar/Snackbar.module.css, packages/vkui/src/components/Snackbar/Snackbar.tsx
(cherry picked from commit 379a42bf237cf6c8650df5d661ab743bc2a49367)
=> [patch] fix(Snackbar): fix design review notes (#4286)

packages/vkui/src/components/PanelHeader/PanelHeader.module.css, packages/vkui/src/components/PanelHeader/PanelHeader.tsx
=> patch: pr4334

packages/vkui/src/components/RichCell/Readme.md, packages/vkui/src/components/RichCell/RichCell.e2e.tsx, packages/vkui/src/components/RichCell/RichCell.module.css, packages/vkui/src/components/RichCell/RichCell.tsx, packages/vkui/src/components/RichCell/RichCellIcon/RichCellIcon.module.css, packages/vkui/src/components/RichCell/RichCellIcon/RichCellIcon.tsx, packages/vkui/src/components/RichTooltip/Readme.md
=> fix(RichCell): fix design review notes

packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Button/Button.test.tsx, packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/IconButton/IconButton.test.tsx, packages/vkui/src/components/IconButton/IconButton.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.test.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
=> patch: pr4379

packages/vkui/src/components/Touch/Touch.tsx
=> fix(Touch): сбрасываем состояние для тач-устройств при touchmove

packages/vkui/src/components/UsersStack/UsersStack.tsx
=> fix(UsersStack): hide if count > 99

packages/vkui/src/index.ts
=> feature: export HasRef & HasRootRef

packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css
=> fix(WriteBarIcon): cleanup browser styles

packages/vkui/src/components/Group/Group.module.css, packages/vkui/src/components/Group/Group.tsx, packages/vkui/src/components/Header/Header.module.css, packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Tabs/Tabs.module.css
=> fix: remove Group__inner

packages/vkui/src/components/List/Readme.md
=> patch: pr4482

package.json, yarn.lock
Второй коммит – это изменение `yarn.lock` после запуска команды.
---
- close #3924
=> tech: добавляет `yarn-deduplicate`

src/components/Group/Group.css, src/components/Group/Group.tsx, src/components/Header/Header.css, src/components/Tabs/Tabs.css
=> v4 fix: rm Group__inner

.github/file-filters.yml
=> patch: pr4492

packages/vkui/src/components/Accordion/Accordion.a11y.test.tsx, packages/vkui/src/components/Accordion/Accordion.e2e.tsx, packages/vkui/src/components/Accordion/Accordion.stories.tsx, packages/vkui/src/components/Accordion/Accordion.test.tsx, packages/vkui/src/components/Accordion/Accordion.tsx, packages/vkui/src/components/Accordion/AccordionSummary.module.css, packages/vkui/src/components/Accordion/AccordionSummary.tsx, packages/vkui/src/components/Accordion/Readme.md, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-android-chromium-dark-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-android-chromium-light-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-ios-webkit-light-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-webkit-light-1-snap.png, packages/vkui/src/index.ts, styleguide/config.js
=> feat: add Accordion

packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Counter/Counter.module.css, packages/vkui/src/components/Counter/__image_snapshots__/counter-android-chromium-dark-1-snap.png, packages/vkui/src/components/Counter/__image_snapshots__/counter-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css
Удаляем "CMP" код, используем css переменные
=> fix(Counter): secondary color

e2e/generateWebpackConfig.ts
Удаляем из покрытия `src/testing`
=> test(e2e): rm src/testing from coverage

packages/vkui/src/components/Input/Input.module.css, packages/vkui/src/components/Input/Input.tsx
=> patch: pr4515

packages/vkui/src/components/AppRoot/AppRoot.module.css, packages/vkui/src/styles/common.css
- Удаляем лишние global
- Убираем из AppRoot глобальные селекторы(NextJS ругается)
=> fix(AppRoot): remove global selectors

tools/swc-transform-css-modules/Cargo.lock
=> bump(swc-transform-css-modules): cargo update

packages/vkui/src/components/ModalPage/ModalPage.module.css
=> fix(ModalPage): header:empty + content radius

packages/vkui/src/components/Tappable/Tappable.module.css, packages/vkui/src/components/Tappable/Tappable.tsx
=> fix(Tappable): hasHover cursor

packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-android-chromium-dark-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-android-chromium-light-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-ios-webkit-dark-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-ios-webkit-light-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/SimpleCheckbox/__image_snapshots__/simplecheckbox-vkcom-webkit-light-1-snap.png
=> chore: rm SimpleCheckbox screenshots

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
=> fix(CustomSelect): getRef

packages/vkui/src/components/TabbarItem/Readme.md, packages/vkui/src/components/TabbarItem/TabbarItem.tsx
- fixes https://github.com/VKCOM/VKUI/issues/4595
=> docs(TabbarItem): add aria-label

packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.module.css, packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.tsx, packages/vkui/src/components/PanelHeaderContext/Readme.md
=> fix(PanelHeaderContext): remove List

packages/vkui/src/components/AdaptiveIconRenderer/AdaptiveIconRenderer.tsx, packages/vkui/src/components/AdaptiveIconRenderer/Readme.md, packages/vkui/src/components/WriteBar/Readme.md, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx, packages/vkui/src/index.ts, styleguide/config.js
Новый компонент для возможности отрисовать иконки для разных экранов
=> feat(AdaptiveIconRenderer): add component for adaptive icon rendering

packages/vkui/src/components/ModalPage/ModalPage.module.css
=> fix(ModalPage): expandable content-in height: 100%

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
=> fix(CustomSelect): callback deps

packages/vkui/src/components/ChipsInput/ChipsInput.tsx
Позволяет прокинуть `mode` для `FormField`
=> fix(ChipsInput): add mode prop

packages/vkui/src/components/Banner/Banner.tsx, packages/vkui/src/components/FormStatus/FormStatus.tsx
=> fix(Banner, FormStatus): add root ref

packages/vkui/src/components/PromoBanner/PromoBanner.tsx
=> chore(PromoBanner): deprecated

e2e/generateWebpackConfig.ts
Исключаем `e2e.tsx` из покрытия
=> test(e2e): exclude e2e.tsx from coverage

styleguide/pages/platforms_and_themes.md
`ConfigProvider` умеет сам определять тему из [vk-bridge](https://www.npmjs.com/package/@vkontakte/vk-bridge)
=> docs: ConfigProvider appearance from vk-bridge

packages/vkui/src/components/WriteBar/WriteBar.e2e.tsx, packages/vkui/src/components/WriteBar/WriteBar.module.css, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-dark-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-light-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-dark-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-light-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-light-1-snap.png
=> fix(WriteBar): fix border token + add e2e tests

packages/vkui/src/helpers/avatar.test.ts
Добавляем тестов для calcInitialsAvatarColor
=> test(calcInitialsAvatarColor): add cases

packages/vkui/package.json, packages/vkui/src/lib/SSR.test.ts, yarn.lock
Добавляем тестовых кейсов для SSRWrapper
- см также VKCOM/vkjs#209
=> test(SSRWrapper): add cases

.github/actions/s3/.eslintrc.js, .github/actions/s3/action.yml, .github/actions/s3/package.json, .github/actions/s3/src/main.ts, .github/actions/s3/tsconfig.json, .github/workflows/pr_close.yml, .github/workflows/pull_request_packages.yml, yarn.lock
Деплоим документацию в PR-ах на s3
=> ci: deploy docs s3

packages/vkui/src/components/Popover/Popover.stories.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.stories.tsx, packages/vkui/src/components/RichTooltip/RichTooltip.stories.tsx, packages/vkui/src/components/TextTooltip/TextTooltip.stories.tsx, packages/vkui/src/components/Tooltip/Tooltip.stories.tsx, packages/vkui/src/storybook/constants.ts
Докидываем стори, которых не хватало
=> chore: Add more storybook stories

.github/dependabot.yml
Добавляем .github/actions/s3 в dependabot
=> ci(dependabot): add .github/actions/s3

.github/workflows/pull_request_packages.yml
Не обновляется комментарий на документацию
=> ci(docs_comment): update comment

packages/vkui/src/components/Card/Card.module.css, packages/vkui/src/components/Card/Card.tsx
=> fix(Card): rm Card__in

packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/NativeSelect/NativeSelect.tsx, packages/vkui/src/components/Select/Select.module.css, packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
- Добавляем свойство icon
- Убираем after
- Исправляем before для NativeSelect
| Компонент | before             | after | icon                     |
|--------|--------|--------|--------|
| Select | сломано                  | сломано      | сломано      |
| CustomSelect | ок                | сломано      | ок                 | 
| NativeSelect | отсутствует | отсутствует | отсутствует |
| SelectMimicry | ок               | дропдаун     | after             |
| ChipsSelect | ок                   | отсутствует | отсутствует |
=> feat(Select): add icon

styleguide/config.js, styleguide/pages/css_modules.md
- closed #1676
- closed #2349
- closed #4061
=> docs: add cssm

packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx, packages/vkui/src/components/ModalRoot/useModalManager.test.tsx, packages/vkui/src/components/ModalRoot/useModalManager.tsx, packages/vkui/src/hooks/useWaitTransitionFinish.ts
=> refactor(ModalRootDesktop): rewrite to FC

.eslintrc.json, .github/workflows/publish.yml, package.json, packages/vkui/.eslintrc.js, packages/vkui/src/components/ActionSheet/types.ts, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx, packages/vkui/src/components/FixedLayout/FixedLayout.tsx, packages/vkui/src/components/Footer/Footer.module.css, packages/vkui/src/components/ModalCardBase/ModalCardBase.module.css, packages/vkui/src/components/PromoBanner/PromoBanner.tsx, packages/vkui/src/components/SplitCol/SplitCol.tsx, packages/vkui/src/components/UsersStack/UsersStack.tsx, packages/vkui/src/helpers/getPlatformClassName.ts, packages/vkui/src/hooks/useId.ts, styleguide/.eslintrc.json, styleguide/Components/Name/NameRenderer.js, styleguide/Components/Preview.js, styleguide/Components/ReactComponent/ReactComponent.js, styleguide/Components/Table/TableRenderer.js, styleguide/Components/TableOfContents/TableOfContents.js, tools/eslint-plugin-vkui/package.json, yarn.lock
- Обновляем eslint до v8
- Обновляем @vkontakte/eslint-plugin
- Добавляем [unicorn/expiring-todo-comments](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v46.0.0/docs/rules/expiring-todo-comments.md)
=> style(eslint): update v8

packages/vkui/.env.development.local, packages/vkui/playwright-ct.config.ts
Изменил тип на массив, чтобы можно было несколько проектов зашивать
---
- related #4652
=> tech(e2e): change type of PLAYWRIGHT_FORCE_PROJECT env var

.github/actions/patch/src/main.ts, .github/actions/patch/src/message.ts
=> tech(@actions-internal/patch): refactor exclude png logic

packages/vkui/src/components/SimpleCell/SimpleCell.module.css, packages/vkui/src/components/SimpleCell/SimpleCell.tsx
Удаляем SimpleCell__typography
=> refactor(SimpleCell): rm SimpleCell__typography

packages/vkui/src/components/Counter/Counter.module.css, packages/vkui/src/components/Counter/Counter.tsx
=> fix(Counter): rm Counter__in

packages/vkui/src/components/Panel/Panel.module.css, packages/vkui/src/components/View/View.module.css, packages/vkui/src/components/View/View.tsx, packages/vkui/src/components/View/ViewInfinite.tsx
Исправляем порядок паддингнов для Panel__in
=> fix(Panel): padding css order

packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.tsx, packages/vkui/src/components/Checkbox/Checkbox.tsx, packages/vkui/src/components/File/File.tsx, packages/vkui/src/components/Radio/Radio.tsx, packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx, packages/vkui/src/components/Switch/Switch.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.a11y.test.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.module.css, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.stories.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.test.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx, packages/vkui/src/components/VisuallyHiddenInput/VisuallyHiddenInput.tsx, packages/vkui/src/index.ts, styleguide/config.js
Добавляю новый компонент `VisuallyHidden`:
-----
- fixes https://github.com/VKCOM/VKUI/issues/4639
=> feat(a11y): компонент `VisuallyHidden`

packages/vkui/src/components/ModalPage/ModalPage.module.css
=> patch: pr4897

packages/vkui/src/components/Search/Search.tsx
Используем компонент типографики
=> fix(Search): use Headline

packages/vkui/src/components/RichCell/RichCell.module.css
=> fix(RichCell): add word-break

packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Button/Button.tsx
=> fix(Button): rm --android

.github/workflows/publish.yml, .github/workflows/publish_prerelease.yml
Добавляем публикацию сторибука
=> ci(publish): add build storybook

.github/workflows/publish.yml
Исправляем установку реквизитов для гита
- related #4767
=> ci(publish): fix git credentials

postcss.config.js
css собирается без префиксов
- related #4652
=> fix(build): VKUI_PACKAGE_BUILD

packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
В #2353 не обновили маску даты
- fixes #4949
=> fix(DateRangeInput): bad date mask

packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.module.css, packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.tsx, packages/vkui/src/components/Typography/Headline/Headline.module.css, packages/vkui/src/components/Typography/Text/Text.module.css
=> refactor: rm global PanelHeaderContent__children

packages/vkui/src/components/Input/Input.module.css, packages/vkui/src/components/Input/Input.tsx, packages/vkui/src/components/Textarea/Textarea.module.css, packages/vkui/src/components/Textarea/Textarea.tsx
=> refactor(Textarea|Input): use Text component

.github/workflows/reusable_workflow_test.yml, .github/workflows/reusable_workflow_test_a11y.yml, .github/workflows/reusable_workflow_test_e2e.yml
Добавляем CODECOV_TOKEN для правильной работы codecov
=> ci: add  CODECOV_TOKEN

.github/file-filters.yml
Изменение postcss тоже надо считать изменением, который может затронуть пакет `vkui`.
---
- related to #4197
- caused by #4964
=> tech(file-filters.yml): add postcss to package_vkui

packages/vkui/package.json, packages/vkui/src/lib/floating/functions.test.ts, packages/vkui/src/lib/floating/functions.ts, yarn.lock
> Default x and y coordinates to 0 instead of null
_Инфа из [changelog](https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Freact-dom%402.0.0)'а_
---
- caused by #4966
- caused by #4974
=> build(deps): Bump @floating-ui/react-dom from 1.3.0 to 2.0.0

packages/vkui/src/components/Link/Link.stories.tsx
**Из аудита невизуальной доступности:**
> Скринридер видит в примере кнопку.
=> docs(Link): fix Link story

packages/vkui/src/components/SplitLayout/Readme.md, packages/vkui/src/components/Tappable/Tappable.tsx, styleguide/Components/TableOfContents/TableOfContents.css, styleguide/Components/TableOfContents/TableOfContents.js
- resolve #4626 
По информации от дизайна свойств `hovered` и `disabled` одновременно быть не должно
=> feat(Tappable): add hovered prop

.github/workflows/pull_request_packages.yml
Удаляем ненужный checkout и установку nodejs
=> ci(pr): reporter remove checkout

packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx, packages/vkui/src/components/PanelHeader/PanelHeader.tsx
=> path: pr4990

packages/vkui/src/components/MiniInfoCell/MiniInfoCell.module.css
=> fix(MiniInfoCell): add word-break

packages/vkui/src/components/Cell/Cell.tsx, packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.module.css, packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.stories.tsx, packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.tsx, packages/vkui/src/components/Cell/Readme.md, packages/vkui/src/components/Cell/__image_snapshots__/cell-android-chromium-dark-1-snap.png, packages/vkui/src/components/Cell/__image_snapshots__/cell-android-chromium-light-1-snap.png, packages/vkui/src/index.ts
Добавляем новый компонент `Cell.Checkbox`
=> feat: add `Cell.Checkbox`

packages/vkui/src/components/PullToRefresh/PullToRefresh.module.css, packages/vkui/src/styles/constants.css
- closes https://github.com/VKCOM/VKUI/issues/3644
=> fix(PullToRefresh): исправляем моргание на iOS

packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css, packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx, packages/vkui/src/components/HorizontalCell/Readme.md, packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-does-not-have-arrows-without-mouse-ios-webkit-dark-1-snap.png, packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-does-not-have-arrows-without-mouse-ios-webkit-light-1-snap.png, packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-has-arrows-on-mouse-hover-ios-webkit-dark-1-snap.png, packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-has-arrows-on-mouse-hover-ios-webkit-light-1-snap.png, packages/vkui/src/components/ImageBase/ImageBase.module.css, packages/vkui/src/components/ImageBase/ImageBase.tsx, packages/vkui/src/styles/constants.css
- fix #4168 
- fix #4332
+ добавление возможности использовать прямоугольные `Image` пойдет отдельной фичой
=> fix(HorizontalCell): fix design review notes

packages/vkui/src/components/ButtonGroup/ButtonGroup.module.css, packages/vkui/src/components/FormField/FormField.module.css, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css, packages/vkui/src/components/Link/Link.module.css, packages/vkui/src/components/Tappable/Tappable.module.css
=> tech(stylelint): fix atomic disable comments

packages/vkui/src/components/ActionSheet/ActionSheet.e2e-playground.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.module.css, packages/vkui/src/components/ActionSheet/ActionSheetDefaultIosCloseItem.tsx, packages/vkui/src/components/ActionSheet/Readme.md, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
- patch #4678
---------
(cherry picked from commit 1cdad2d340e59cc10ec9227cab577da823ed212e)
=> fix(ActionSheet, ActionSheetItem): fix design notes (#4678)

packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/ModalRoot/types.ts, packages/vkui/src/components/ModalRoot/useModalManager.tsx
При открытии клавиатуры меняется размер окна, поэтому всегда отслеживаем изменение окна 
- fixed #5011
=> fix(ModalRoot): always check resize

packages/vkui/src/components/Cell/CellDragger/CellDragger.tsx, packages/vkui/src/components/Cell/useDraggable.tsx
- Добавил `stopPropagation` и `preventDefault` на все события дрэга.
- Дополнительно поправил в `CellDragger` поправил, чтобы `onClick` из параметров вызывался. До этого просто перебивался.
---
- fix #3368
=> fix(Cell): stop propagation drag events

packages/vkui/src/components/Header/Header.module.css, packages/vkui/src/components/Header/Header.tsx, packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-light-1-snap.png
=> feat(Header): rm vkcom styles

packages/vkui/src/components/CustomScrollView/CustomScrollView.tsx
=> feat(CustomScrollView): Add onScroll prop

packages/vkui/src/components/Panel/Panel.tsx
Перемещаем тень ниже контента
- fix #4623
=> fix(View): fade after content

packages/vkui/src/hooks/useTodayDate.ts
fix(useTodayDate): add visibilitychange eventlistener to prevent skipped state update after tab freeze
=> CLND-9207: В календаре в сайдбаре  подчеркнут вчерашний день, до перезагрузки страницы

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
- fix https://github.com/VKCOM/VKUI/issues/3683
=> fix(ModalRoot): drop state after close modal

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
=> patch: pr4380

packages/vkui/src/hooks/useTodayDate.ts
=> patch: pr5151

packages/vkui/src/components/Progress/Progress.e2e-playground.tsx, packages/vkui/src/components/Progress/Progress.e2e.tsx, packages/vkui/src/components/Progress/Progress.module.css, packages/vkui/src/components/Progress/Progress.tsx, packages/vkui/src/components/Progress/Readme.md, packages/vkui/src/components/Progress/__image_snapshots__/progress-android-chromium-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-android-chromium-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-ios-webkit-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-webkit-light-1-snap.png
=> feat(Progress): add `appearance`

packages/vkui/src/components/Placeholder/Placeholder.module.css, packages/vkui/src/components/Placeholder/Placeholder.tsx
Добавляем `withPadding` для отступов.
Избавляемся от `Placeholder__in`
=> feat(Placeholder): add `withPadding`

packages/vkui/src/components/AspectRatio/AspectRatio.module.css, packages/vkui/src/components/AspectRatio/AspectRatio.stories.tsx, packages/vkui/src/components/AspectRatio/AspectRatio.test.tsx, packages/vkui/src/components/AspectRatio/AspectRatio.tsx, packages/vkui/src/components/AspectRatio/Readme.md, packages/vkui/src/index.ts, packages/vkui/src/types.ts, styleguide/config.js
Добавляем компонент для встраивания медиа (картинок, видео, карт) в заданных пропорциях
=> Add AspectRatio component

packages/vkui/src/components/Badge/Badge.module.css, packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-android-chromium-dark-1-snap.png, packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-android-chromium-light-1-snap.png, packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-ios-webkit-light-1-snap.png, packages/vkui/src/components/TabbarItem/TabbarItem.module.css
=> fix(Tabbar): change padding

packages/vkui/src/components/View/View.module.css, packages/vkui/src/styles/constants.css
=> fix(Panel): Add z-index to fade element

packages/vkui/src/components/Gallery/Readme.md
=> docs(Gallery): use placebear

packages/vkui/src/components/TabbarItem/TabbarItem.module.css
=> patch: pr5196

packages/vkui/src/components/PanelHeader/LegacyPanelHeaderContent.tsx, packages/vkui/src/components/PanelHeader/PanelHeader.tsx
Вынес LegacyPanelHeaderContent, чтобы правильно подтягивался PanelHeader
=> docs: fix PanelHeader name

styleguide/package.json
=> chore: cross env for `yarn docs:styleguide:props`

.github/workflows/reusable_workflow_test_e2e.yml, .github/workflows/update_screens.yml, package.json, packages/vkui/docker-compose.yml, packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-dark-1-snap.png, packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-light-1-snap.png, packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Input/__image_snapshots__/input-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Input/__image_snapshots__/input-ios-webkit-light-1-snap.png, packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png, yarn.lock
https://github.com/microsoft/playwright/releases/tag/v1.35.0
=> build(deps-dev): Bump playwright to 1.35.0

packages/vkui/src/components/Chip/Readme.md, packages/vkui/src/components/ChipsInput/Readme.md, packages/vkui/src/components/FormItem/FormItem.stories.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/FormItem/Readme.md, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.e2e-playground.tsx, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.stories.tsx, packages/vkui/src/components/Input/Readme.md, packages/vkui/src/components/Popover/Popover.stories.tsx, packages/vkui/src/components/View/Readme.md, packages/vkui/src/components/View/View.stories.tsx
=> patch: pr5211

packages/vkui/src/components/Banner/Banner.module.css, packages/vkui/src/components/Banner/Banner.tsx
=> feat(Banner): add `noPadding`

packages/vkui/src/components/ModalCard/ModalCard.tsx
=> fix(ModalCard): add getRootRef

.github/workflows/reusable_workflow_test_e2e.yml, .github/workflows/update_screens.yml, package.json, packages/vkui/docker-compose.yml, yarn.lock
Bump playwright from 1.35.0 to 1.35.1
=> build(deps-dev): Bump playwright from 1.35.0 to 1.35.1

packages/vkui/src/components/FixedLayout/Readme.md
=> doc(FixedLayout): add filled

package.json, packages/vkui/playwright-ct.config.ts, packages/vkui/src/components/Button/Button.e2e-playground.tsx, packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/Button/__image_snapshots__/button-android-chromium-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-android-chromium-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-ios-webkit-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Button/__image_snapshots__/button-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Spinner/Spinner.tsx, yarn.lock
vite не умеет убирать process.env самостоятельно.
Заменил process.env на свойство
=> feat(Spinner): add `disableAnimation`

packages/vkui/src/components/FixedLayout/FixedLayout.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
=> patch: pr5279

packages/vkui/src/components/ImageBase/ImageBase.tsx, packages/vkui/src/components/Tappable/Tappable.tsx, packages/vkui/src/lib/platform.ts, packages/vkui/src/types.ts
Добавляем LiteralUnion для работы автозаполнения
https://togithub.com/microsoft/TypeScript/issues/29729
=> doc(types): add LiteralUnion

packages/vkui/src/hooks/useAutoDetectAppearance.tsx
Автоопределение appearance через bridge работает неверно:
1. Пользователь с темной темой открывает приложение
2. Идет асинхронный запрос `VKWebAppGetConfig`
3. initialAppearance еще не существует, поэтому в
useAutoDetectAppearance ставиться светлая тема
4.  `VKWebAppGetConfig` обновляет переменную initialAppearance
5. Происходит подписка в autoDetectAppearanceByBridge
ФР: пользователь видит светлую тему
Переносим запрос `VKWebAppGetConfig` после подписки на событие
=> fix(autoDetectAppearanceByBridge): bridge async

packages/vkui/src/components/Group/Group.tsx, packages/vkui/src/components/Header/Header.module.css, packages/vkui/src/components/Header/Header.tsx
- потерялся стиль для `multiline` у `subtitle`
- исправились отступы для  вложения в `Group`
=> fix(Header): add multiline style + fix paddings

packages/vkui/package.json, yarn.lock
Используем каретку для прямых зависимостей
=> fix(deps): use caret range

.github/actions/complete_playwright_update/action.yml, .github/actions/complete_storybook_update/action.yml
=> fix(github actions): set git creds before push

packages/vkui/package.json, yarn.lock
=> patch: pr5374

packages/vkui/src/components/Epic/Epic.tsx, packages/vkui/src/components/ModalRoot/types.ts, packages/vkui/src/components/Root/Root.test.tsx, packages/vkui/src/components/Root/Root.tsx, packages/vkui/src/components/View/View.test.tsx, packages/vkui/src/components/View/View.tsx, packages/vkui/src/storybook/ModalWrapper.tsx
=> fix(Routing): update children type

packages/vkui/src/components/Epic/Epic.tsx, packages/vkui/src/components/ModalRoot/types.ts, packages/vkui/src/components/Root/Root.test.tsx, packages/vkui/src/components/Root/Root.tsx, packages/vkui/src/components/View/View.test.tsx, packages/vkui/src/components/View/View.tsx, packages/vkui/src/storybook/ModalWrapper.tsx
=> patch: pr5395

.github/workflows/schedule_cargo_update.yml
=> fix(ci): set working dir to schedule cargo update

packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
=> Add addOnBlur prop for ChipsInputBase

packages/vkui/src/components/Tappable/Tappable.module.css
=> fix(Tappable): reset outline

packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalRoot/ModalRoot.tsx
=> Fix modal height

tools/swc-transform-css-modules/Cargo.lock
=> Cargo update

packages/vkui/src/components/WriteBar/Readme.md
Потерялось заполнение FixedLayout
=> doc(WriteBar): FixedLayout filled

packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-dark-1-snap.png, packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-light-1-snap.png, packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-light-1-snap.png, packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx
Шрифт оказался маленьким, хардкодим 14px
=> fix(ModalCardBase): Subhead regular

packages/vkui/src/index.ts
=> Add ChipOption and RenderChip types

yarn.lock
=> feat: yarn upgrade

packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/FormItem/Readme.md, packages/vkui/src/helpers/math.test.ts, packages/vkui/src/helpers/math.ts
=> patch: pr5284 and pr5422

packages/vkui/src/components/Progress/Progress.e2e-playground.tsx, packages/vkui/src/components/Progress/Progress.test.tsx, packages/vkui/src/components/Progress/Progress.tsx, packages/vkui/src/components/Progress/__image_snapshots__/progress-android-chromium-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-android-chromium-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-ios-webkit-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-webkit-light-1-snap.png
Добавляем свойство `height` для возможности задать свою высоту
=> feat(Progress): add height

packages/vkui/src/components/Search/Search.tsx
Вызывает memory leaks в реакте
=> Remove onCancel call from Search

packages/vkui/src/components/ChipsSelect/Readme.md, packages/vkui/src/components/FormItem/FormItem.e2e-playground.tsx, packages/vkui/src/components/FormItem/Readme.md, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.e2e-playground.tsx, packages/vkui/src/components/FormLayoutGroup/Readme.md, packages/vkui/src/components/FormStatus/Readme.md, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.module.css, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css
=> patch: pr5225 pr5459

packages/vkui/src/components/Epic/Readme.md
=> feat(doc-epic): move active story styles to object

packages/vkui/src/components/Epic/Readme.md
=> patch: pr5474

.github/actions/complete_playwright_update/action.yml
В #5366 пропустили обновление версии Docker контейнера в `update_screens.yml`.
- caused by #5366
=> ci: fix playwright Docker container update

packages/vkui/src/components/Search/Search.module.css, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-webkit-light-1-snap.png
`placeholder` должен быть цветом `--vkui--color_text_secondary` по дизайн-системе
=> Fix search placeholder

.github/workflows/pull_request_common.yml, .github/workflows/pull_request_packages.yml
После того, как с PRа снимается флажок `draft`, необходимо запускать все чеки заново
=> Add gh action trigger event on PRs

packages/vkui/src/components/Search/Search.module.css, packages/vkui/src/components/Search/Search.tsx
=> patch: pr5490

packages/vkui/src/components/Link/Link.module.css
line-height может быть выставлен браузерными стилями button
=> fix(Link): line-height inherit

styleguide/config.js
Устанавливаем русский язык для документации, чтобы не мешал переводчик
=> docs(styleguide): lang ru

packages/vkui/src/components/Search/Search.tsx
=> fix(Search): add onCancel on touch devices

packages/vkui/src/components/Tooltip/Tooltip.module.css, packages/vkui/src/components/Tooltip/Tooltip.test.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx
Используем overlay для закрытия
- fixes #536
=> fix(Tooltip): use overlay for close

packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ActionSheet/ActionSheetDropdown.tsx, packages/vkui/src/components/ActionSheet/ActionSheetDropdownDesktop.tsx, packages/vkui/src/components/ActionSheet/Readme.md, packages/vkui/src/components/ActionSheet/types.ts
=> feat(ActionSheet): add placement prop

packages/vkui/src/components/Alert/Alert.module.css
- relates to https://github.com/VKCOM/VKUI/pull/5530
=> fix(Alert): suggest css update

packages/vkui/src/components/ActionSheet/ActionSheet.module.css, packages/vkui/src/components/ModalDismissButton/Readme.md, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.module.css, packages/vkui/src/components/Popover/Popover.module.css, packages/vkui/src/components/Popover/Popover.tsx
Добавляем position: relative для правильного наложения элементов
=> fix(PopoutWrapper): add position

packages/vkui/src/components/Alert/Alert.module.css, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Alert/AlertAction.tsx, packages/vkui/src/components/Alert/AlertActions.tsx, packages/vkui/src/components/Alert/AlertTypography.tsx, packages/vkui/src/components/Alert/Readme.md, packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-android-chromium-dark-1-snap.png
Добавляем свойство `renderAction` и `actionsAlign`
Немного декомпозировал код
- closed #5471
=> feat(Alert): add renderAction

packages/vkui/src/index.ts
=> feat: export `defaultFilterFn` as `filterFnForSelect`

packages/vkui/src/components/Typography/Typography.module.css, packages/vkui/src/components/Typography/Typography.tsx
Добавляем жирности для b внутри типографики
=> feat(Typography): b weight

packages/vkui/.eslintrc.js, packages/vkui/src/components/Badge/Badge.tsx, packages/vkui/src/components/Banner/Banner.tsx, packages/vkui/src/components/BaseGallery/BaseGallery.tsx, packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/ButtonGroup/ButtonGroup.tsx, packages/vkui/src/components/CardGrid/CardGrid.tsx, packages/vkui/src/components/CardScroll/CardScroll.tsx, packages/vkui/src/components/FixedLayout/FixedLayout.tsx, packages/vkui/src/components/FocusVisible/FocusVisible.tsx, packages/vkui/src/components/FormField/FormField.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/Gradient/Gradient.tsx, packages/vkui/src/components/Group/Group.tsx, packages/vkui/src/components/Header/Header.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx, packages/vkui/src/components/MiniInfoCell/MiniInfoCell.tsx, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.tsx, packages/vkui/src/components/Progress/Progress.tsx, packages/vkui/src/components/RichTooltip/RichTooltip.tsx, packages/vkui/src/components/ScrollArrow/ScrollArrow.tsx, packages/vkui/src/components/Snackbar/Snackbar.tsx, packages/vkui/src/components/TabsItem/TabsItem.tsx, packages/vkui/src/components/Tappable/Tappable.tsx, packages/vkui/src/components/TextTooltip/TextTooltip.tsx, packages/vkui/src/components/Typography/Caption/Caption.tsx, packages/vkui/src/components/Typography/Headline/Headline.tsx, packages/vkui/src/components/Typography/Title/Title.tsx, packages/vkui/src/components/Typography/Typography.tsx, packages/vkui/src/components/UsersStack/UsersStack.tsx
Добавляем линтер для выноса всех объектов из classNames
=> refactor(eslint): add no-object-in-class-names

packages/vkui/playwright/index.css, packages/vkui/src/components/Checkbox/Checkbox.e2e-playground.tsx, packages/vkui/src/components/Checkbox/Checkbox.module.css, packages/vkui/src/components/Checkbox/Checkbox.tsx, packages/vkui/src/testing/e2e/constants.ts
=> patch: pr5691

packages/vkui/src/components/MiniInfoCell/MiniInfoCell.e2e-playground.tsx, packages/vkui/src/components/MiniInfoCell/MiniInfoCell.tsx, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-chromium-dark-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-chromium-light-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-webkit-dark-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-webkit-light-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-webkit-light-1-snap.png
Добавляем возможность убрать иконку слева
=> fix(MiniInfoCell): check before

packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/components/TooltipBase/TooltipBase.module.css, packages/vkui/src/components/TooltipBase/TooltipBase.tsx
=> feat(TooltipBase): add maxWidth prop

.github/workflows/pr_close.yml
Добавляем патч на ветку v5
- close #3298
=> ci: add v5 patch

packages/vkui/src/components/Checkbox/Checkbox.tsx, packages/vkui/src/components/Root/Root.tsx
=> fix: css modules classes

packages/vkui/src/components/CardGrid/CardGrid.module.css
=> fix(CardGrid): remove useless style

packages/vkui/src/styles/common.css
=> fix: rm font-smoothing

packages/vkui/src/components/Alert/Alert.module.css, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Alert/Readme.md, packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-ios-webkit-light-1-snap.png, packages/vkui/src/components/IconButton/IconButton.module.css
- resolve #5486 
`ModalPage` поедет отдельно, нужны комменты от дизайнеров
=> feat(Alert): add inside close button (part 1)

packages/vkui/src/components/Tabbar/Tabbar.e2e.tsx, packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-android-chromium-dark-1-snap.png, packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-ios-webkit-dark-1-snap.png, packages/vkui/src/components/TabbarItem/TabbarItem.module.css, packages/vkui/src/testing/e2e/index.playwright.ts, packages/vkui/src/testing/e2e/types.ts
- fix #5689 
info: Добавила свойство `threshold` для теста, потому что без него цвета не различались в скриншотных тестах
=> fix(TabbarItem): change text color token

package.json, packages/token-translator/package.json, packages/vkui/package.json, yarn.lock
PR, смерженные без label v5
- patch https://github.com/VKCOM/VKUI/pull/5769
- patch https://github.com/VKCOM/VKUI/pull/5776
- patch https://github.com/VKCOM/VKUI/pull/5774
- patch https://github.com/VKCOM/VKUI/pull/5773
- patch https://github.com/VKCOM/VKUI/pull/5770
=> tech: sync `v5` with `master`

yarn.lock
В изменениях результат запуска `yarn dedupe`.
=> tech: deduplication dependencies

packages/vkui/src/styles/dynamicTokens.css
=> patch: pr5791

.browserslistrc, packages/vkui/package.swcrc, styleguide/pages/migration_v6.md
Устанавливаем таргет на es2015 (es6)
https://caniuse.com/es6
- Измененный список поддерживаемых браузеров
- Уменьшение размера бандла
=> BREAKING CHANGE: target es2015

packages/vkui/src/components/PanelHeader/Readme.md
=> docs(PanelHeader): if after is Banner

tsconfig.json
Добавлены в игнор `dist` файлы `storybook`
=> chore: add storybook dist to ts ignore

packages/vkui/src/hooks/useAdaptivityConditionalRender/index.ts, packages/vkui/src/index.ts
- close #5699 
Экспортируем из VKUI типы необходимые по #5699
=> feat: Export useful types from vkui library

packages/vkui/src/components/MiniInfoCell/Readme.md
- Fixes #5825
Убрал сепаратор из документации
=> docs(MiniInfoCell): rm separator

packages/vkui/src/components/FixedLayout/Readme.md
Фиксируем PanelHeader для всех платформ
=> docs(FixedLayout): PanelHeader fixed

packages/vkui/src/components/HorizontalCellShowMore/Readme.md
Исправляем отсутствующую шапку
Добавлен `PanelHeader`
=> Add PanelHeader to HorizontalCellShowMore doc

.github/file-filters.yml, .github/workflows/pull_request_packages.yml
В #5886 не сработала сборка сторибука
Добавляем отдельный фильтр по файликам, которые актуальны только для сторибука, и по ним делаем вывод о необходимости его сборки
=> feat(chore): expand file-filters.yml for storybook

packages/vkui/src/components/AspectRatio/AspectRatio.e2e-playground.tsx, packages/vkui/src/components/AspectRatio/AspectRatio.e2e.tsx, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-android-chromium-dark-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-android-chromium-light-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-ios-webkit-dark-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-ios-webkit-light-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/AspectRatio/__image_snapshots__/aspectratio-vkcom-webkit-light-1-snap.png
Добавил e2e тестов для AspectRatio
- See #5864
=> test(e2e): AspectRatio

packages/vkui/.storybook/preview.ts
В сторибуке исчезли `Separator`'ы
Добавлен нужный `css`-файл
=> fix(storybook): add dynamicTokens.css file

yarn.lock
Дедуплицируем пакеты после обновления зависимостей через dependabot
=> chore: dedupe packages

packages/vkui/src/components/Link/Link.module.css
Пробрасываем жирность шрифта в Link
=> fix(Link): add font-weight: inherit

packages/vkui/package.json
Поднимаем версию в мастере для правильной работы патчей. Сейчас патчи будут автоматом улетать в 5.8-stable
=> chore: update master version 5.9.0

packages/vkui/src/components/Group/Group.module.css
- ~[ ] Unit-тесты~ визуальное исправление
- ~[ ] Дизайн-ревью~ визуальное исправление
Исправляем отступ в заголовке в Group
=> fix(Group): plain header margin

.github/workflows/publish_vkui_floating_ui_react_dom.yml, packages/vkui-floating-ui-react-dom/LICENSE, packages/vkui-floating-ui-react-dom/README.md, packages/vkui-floating-ui-react-dom/index.mjs, packages/vkui-floating-ui-react-dom/package.json, packages/vkui-floating-ui-react-dom/types.d.ts, packages/vkui/package.json, yarn.lock
Добавляем новый пакет @vkontakte/vkui-floating-ui-react-dom. Это @floating-ui/react-dom которая скомпилирована под es5
=> feat: add vkui-floating-ui-react-dom

.github/workflows/publish_vkui_floating_ui_react_dom.yml, .yarnrc.yml, package.json, packages/vkui-floating-ui-react-dom/LICENSE, packages/vkui-floating-ui-react-dom/README.md, packages/vkui-floating-ui-react-dom/index.mjs, packages/vkui-floating-ui-react-dom/package.json, packages/vkui-floating-ui-react-dom/types.d.ts, packages/vkui/package.json, packages/vkui/src/lib/floating/adapters.ts, packages/vkui/src/lib/floating/index.ts, packages/vkui/src/lib/floating/types.ts, yarn.lock
- patch #5905
- patch #5913
Конфликт был на почве yarn.lock. Перезаписал с помощью `yarn install`.
=> Patch/pr5905 Patch/pr5913 in V5

.github/workflows/publish_vkui_floating_ui_react_dom.yml, .yarnrc.yml, package.json, packages/vkui-floating-ui-react-dom/LICENSE, packages/vkui-floating-ui-react-dom/README.md, packages/vkui-floating-ui-react-dom/index.mjs, packages/vkui-floating-ui-react-dom/package.json, packages/vkui-floating-ui-react-dom/types.d.ts, packages/vkui/package.json, packages/vkui/src/lib/floating/adapters.ts, packages/vkui/src/lib/floating/index.ts, packages/vkui/src/lib/floating/types.ts, yarn.lock
- patch #5905
- patch #5913
Конфликт был на почве yarn.lock. Перезаписал с помощью `yarn install`.
=> Patch/pr5905/pr5913 in 5.9-stable

package.json, yarn.lock
Поднимаем версию `@vkontakte/vkui-tokens`
=> build(deps-dev): Bump @vkontakte/vkui-tokens from 4.40.0 to 4.41.0

packages/vkui-floating-ui-react-dom/index.mjs
Неверные кавычки
- related to https://github.com/VKCOM/VKUI/pull/5905
=> fix(vkui-floating-ui-react-dom): regex quotes

packages/vkui/src/components/Snackbar/Snackbar.module.css
- Fixes #5931
---
- ~[ ] e2e-тесты~ (see #5932)
Изменен border-radius для Snackbar
=> fix(Snackbar): set size_card_border_radius

package.json, packages/token-translator/package.json, packages/vkui-floating-ui-react-dom/package.json, yarn.lock
=> patch: pr5939

packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-desktop-ios-only-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-desktop-ios-only-ios-webkit-light-1-snap.png, packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-mobile-ios-only-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-mobile-ios-only-ios-webkit-light-1-snap.png, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.module.css
=> patch: #5878

packages/vkui/src/components/CustomSelectOption/CustomSelectOption.module.css, packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-android-chromium-dark-1-snap.png, packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-android-chromium-light-1-snap.png, packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-ios-webkit-dark-1-snap.png, packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-ios-webkit-light-1-snap.png
- closed #5949
---
В дизайне текст переходит на новую строку
Убрал троеточие и nowrap для CustomSelectOption
=> fix(CustomSelectOption): wrap text

.github/workflows/pull_request_common.yml
Добавляем лейблы автоматом, в зависимости от названия PR-а
Пример прямо в этом PR-е
=> ci(pr): add labels

packages/vkui/package.json, yarn.lock
Используем каретку для @vkontakte/vkui-floating-ui-react-dom
=> fix: vkui-floating-ui-react-dom caret version

.github/workflows/deprecate.yml, .github/workflows/unpublish.yml
Добавляем возможность прокидывать название пакета в `.github/workflows/deprecate.yml`.
> **Note**
> В рамках этого PR добавил новый воркфлоу `Unpublish package`, который должен удалить [@vkontakte/vkui-floating-ui-react-dom](https://www.npmjs.com/package/@vkontakte/vkui-floating-ui-react-dom) из NPM. После удаления, воркфлоу будет удалён.
=> tech(workflow/deprecate): add package_name input

packages/vkui/src/components/Typography/Caption/Caption.tsx, packages/vkui/src/components/Typography/Footnote/Footnote.tsx, packages/vkui/src/components/Typography/Headline/Headline.tsx, packages/vkui/src/components/Typography/Paragraph/Paragraph.tsx, packages/vkui/src/components/Typography/Subhead/Subhead.tsx, packages/vkui/src/components/Typography/Text/Text.tsx, packages/vkui/src/components/Typography/Title/Readme.md, packages/vkui/src/components/Typography/Title/Title.tsx
Добавляем минимальное описание для типографики
=> docs(typography): add description

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
=> test(HorizontalScroll): fix arrow on hover

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
=> patch(v5): pr5969

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
=> patch(5.9-stable): pr5969

packages/vkui/src/components/ActionSheet/ActionSheet.tsx
header в ActionSheet имеет роль [banner](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role), который является глобальным заголовком для страницы
- see also #3044
=> fix(ActionSheet): rm header

package.json, yarn.lock
=> patch: pr5981

package.json, yarn.lock
=> patch: pr5982

package.json, packages/token-translator/package.json, packages/vkui-floating-ui/package.json, yarn.lock
=> patch: pr5988

packages/vkui/src/components/Header/Header.test.tsx, packages/vkui/src/components/Header/Header.tsx
=> patch: pr5996

packages/vkui/src/components/Alert/Alert.e2e-playground.tsx, packages/vkui/src/components/Alert/Alert.e2e.tsx, packages/vkui/src/components/Alert/Alert.module.css, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-android-chromium-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-ios-webkit-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-webkit-light-1-snap.png
- fix #5999
---
Добавили `word-break: break-word`
=> fix(Alert): add word-break

.github/workflows/dedupe_deps.yml
Чтобы не создавать ветку вручную
=> chore: Add deps deduplication

package.json, yarn.lock
Обновляем транзитивные зависимости
=> bump: update transitive deps

packages/vkui-floating-ui/package.json
=> patch(5.9-stable): bump @vkontakte/vkui-floating-ui from 0.1.0 to 0.1.1

packages/vkui-floating-ui/package.json
=> patch(v5): bump @vkontakte/vkui-floating-ui from 0.1.0 to 0.1.1

packages/vkui/src/components/Touch/Readme.md
Добавляем в пример `touch-action: none` для отключения взаимодействием тачем(прокрутка, действий назад и т.п.)
=> docs: Touch add touch-action: none

.browserslistrc, package.json, packages/vkui/scripts/postcss.js, yarn.lock
Поднимаем browserslistrc, добавляем [postcss-gap-properties](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-gap-properties)
=> BREAKING CHANGE: up browserslistrc && grid gap

.codesandbox/ci.json, .github/workflows/dedupe_deps.yml, .github/workflows/deprecate.yml, .github/workflows/pr_close.yml, .github/workflows/publish.yml, .github/workflows/publish_prerelease.yml, .github/workflows/publish_token_translator.yml, .github/workflows/publish_vkui_floating_ui_react_dom.yml, .github/workflows/pull_request_common.yml, .github/workflows/pull_request_dependabot.yml, .github/workflows/pull_request_packages.yml, .github/workflows/reusable_workflow_test.yml, .github/workflows/reusable_workflow_test_e2e.yml, .github/workflows/update_screens.yml
=> ci: use node v20

styleguide/Components/Modals/Versions.js
После использования `Object.keys` менялся порядок версий:
Добавила `SemVer.rcompare` для сравнения версий
=> docs: Add versions sorting

packages/vkui/src/components/ModalCard/ModalCard.e2e-playground.tsx, packages/vkui/src/components/ModalCard/ModalCard.module.css, packages/vkui/src/components/ModalCard/ModalCard.test.tsx, packages/vkui/src/components/ModalCard/ModalCard.tsx, packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx, packages/vkui/src/components/ModalRoot/types.ts
=> patch: pr6054

package.json, yarn.lock
=> build(deps-dev): Bump @vkontakte/vkui-tokens from 4.41.0 to 4.41.1

package.json, yarn.lock
=> build: remove @types/css-font-loading-module

.eslintrc.json, packages/vkui/playwright-ct.config.ts, packages/vkui/scripts/generateCSSCustomMedias.js, packages/vkui/src/components/MiniInfoCell/MiniInfoCell.e2e-playground.tsx, packages/vkui/src/hooks/useAdaptivityWithJSMediaQueries.ts, packages/vkui/src/hooks/useAutoDetectAppearance.tsx, packages/vkui/src/hooks/useBridgeAdaptivity.ts, packages/vkui/src/lib/platform.ts, packages/vkui/src/lib/warnOnce.test.ts, packages/vkui/src/lib/warnOnce.ts
Избавляемся от [подобных](https://github.com/VKCOM/VKUI/pull/6145#discussion_r1407664958) артефактов
Включаем `no-console` правило, часть файлов, где сейчас проставлен игнор правила - удалятся в #5868
=> chore(eslint): turn on no-console rule

packages/vkui/src/components/ModalCardBase/ModalCardBase.stories.tsx, packages/vkui/src/components/ModalCardBase/Readme.md
=> docs(ModalCardBase): rm key

packages/vkui/src/components/Card/Card.module.css, packages/vkui/src/components/CardScroll/CardScroll.module.css, packages/vkui/src/components/PanelHeader/PanelHeader.module.css, packages/vkui/src/components/SplitCol/SplitCol.module.css, packages/vkui/src/components/SplitCol/SplitCol.tsx, styleguide/pages/migration_v6.md
- resolve #6154
---
~~- [ ] Гайд миграции~~
- related to #5868
Удаляем
=> BREAKING CHANGE(SplitCol): remove spaced prop

packages/vkui/src/index.ts
Забыл удалить префикс `unstable_` 😅 
---
- caused by #6185
=> fix(Popper): rm unstable prefix

packages/codemods/package.json
=> chore: fix provenance

packages/codemods/package.json
=> chore: add public acces to codemod package

packages/codemods/package.json
- related to #6234
Возвращаем подписание пакета
=> chore: add provenance to vkui-codemods

README.md, packages/vkui/src/components/ModalCard/ModalCard.stories.tsx
Поправила версию React'a в Readme.md, исправила выравнивание в сторе по `ModalCard`
=> chore: Fix Readme.md & story for ModalCard

packages/vkui/src/components/MiniInfoCell/MiniInfoCell.tsx
- close #6261 
---
Делаем проп необязательным
=> fix(MiniInfoCell): make before prop not required

packages/vkui/src/components/View/Readme.md
Страница с докой по `View` не открывается (падает с ошибкой)
- переделала ссылки на те, которые переварит `LinkRenderer`
- добавила `key` для элементов массива, чтобы в консоли не было ошибок
=> fix(View): fix readme.md links

styleguide/pages/migration_v6.md
- related to https://github.com/VKCOM/VKUI/pull/6273#pullrequestreview-1779414671
Добавляем заголовки третьего уровня также в содержание (кроме заголовков интеграции на vk-bridge)
=> chore(migration_v6): add subheaders to sublist of page list

.github/workflows/pull_request_packages.yml, .github/workflows/reusable_workflow_test_e2e.yml
Фиксим обновление на `actions/*-artifact@v4`.
- relates to https://github.com/VKCOM/VKUI/pull/6282
=> ci: update artifact names (to account for actions/upload-artifact@v4 breaking change)

packages/codemods/src/codemod-helpers.ts, packages/codemods/src/report.ts, packages/codemods/src/transforms/__testfixtures__/form-layout/basic.input.tsx, packages/codemods/src/transforms/__tests__/__snapshots__/form-layout.ts.snap, packages/codemods/src/transforms/__tests__/__snapshots__/rich-tooltip.ts.snap, packages/codemods/src/transforms/__tests__/form-layout.ts, packages/codemods/src/transforms/__tests__/rich-tooltip.ts, packages/codemods/src/transforms/form-layout.ts, packages/codemods/src/transforms/modal-card.ts, packages/codemods/src/transforms/popout-wrapper.ts
- Добавила кодмоды для `FormLayout`, `ModalCard/ModalCardBase` и `PopoutWrapper` + нагенерила новых снапшотов
- Функцию `report` обернула в `try/catch`, чтобы не падало в `jest`
=> chore: Add new codemods

packages/vkui/src/components/Clickable/Clickable.module.css, packages/vkui/src/components/Tappable/Tappable.module.css, packages/vkui/src/components/Tappable/Tappable.tsx
Переносим стили Tappable из Clickable
- see #6287
=> fix(Tappable): fix position

README.md
Забыли поправить ссылку перед релизом.
=> fix(README.md): mv 6.0.0-beta.3 to 6.0.0 in links

.github/workflows/pull_request_common.yml
Возвращаем работу джобы `labels`.
- related to #6134
=> tech(pull_request_common): rm disabled labels job

packages/codemods/src/report.ts
Исправляем линку на правильный путь до гайда миграции (спасибо, @scffs)
=> codemod: Fix migration guide link

packages/vkui/src/components/Textarea/Textarea.e2e-playground.tsx, packages/vkui/src/components/Textarea/Textarea.module.css, packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-android-chromium-dark-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-android-chromium-light-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-ios-webkit-light-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-webkit-light-1-snap.png
- closed #6363
---
Добавляем для Textarea свойство `align`
=> feat(Textarea): add `align`

.github/dependabot.yml
Группируем обновление swc с плагинами
=> ci(dependabot): add swc group

packages/vkui/src/lib/dom.test.ts, packages/vkui/src/lib/dom.tsx
=> patch(v5): pr6456

packages/vkui/src/index.ts
- close #6475
---
Экспортируем тип `ImageBaseProps` для `ImageBase`
=> fix(ImageBase): export ImageBaseProps

packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.tsx
- closed #6492
Добавляем более широкой типизации для `ImageBase.Badge`
=> feat(ImageBase.Badge): use HTMLAttributesWithRootRef

yarn.lock
Automated dependencies deduplication
=> chore: Deduplicate dependencies on master

packages/vkui/src/styles/dynamicTokens.css
Удаляем универсальный селектор из-за проблем с памятью. Выпиливаем переопределение цвета обводки
=> fix(dynamicTokens): rm universal selector

packages/vkui/src/components/PullToRefresh/PullToRefresh.stories.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx, packages/vkui/src/styles/common.css
=> patch: pr6540

packages/vkui/src/components/NativeSelect/NativeSelect.test.tsx, packages/vkui/src/components/NativeSelect/NativeSelect.tsx, packages/vkui/src/components/Search/Search.test.tsx, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/Textarea/Textarea.test.tsx, packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/components/WriteBar/WriteBar.test.tsx, packages/vkui/src/components/WriteBar/WriteBar.tsx
- fixes #6560
---
Убираем useEnsuredControl для честной работы неконтролируемых компонентов в формах
=> fix: rm useEnsuredControl

packages/vkui/src/components/NativeSelect/NativeSelect.test.tsx, packages/vkui/src/components/NativeSelect/NativeSelect.tsx, packages/vkui/src/components/Search/Search.test.tsx, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/Textarea/Textarea.test.tsx, packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/components/WriteBar/WriteBar.test.tsx, packages/vkui/src/components/WriteBar/WriteBar.tsx
=> patch: pr6561

yarn.lock
=> build(deps-dev): Bump ip from 2.0.0 to 2.0.1

packages/vkui/src/components/FormItem/FormItem.e2e-playground.tsx, packages/vkui/src/components/FormItem/FormItem.module.css, packages/vkui/src/components/FormItem/FormItem.stories.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-android-chromium-dark-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-android-chromium-light-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-ios-webkit-dark-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-ios-webkit-light-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-webkit-light-1-snap.png
- close #6579
---
Поддержка многострочного вывода для текста `top`
Добавлен prop `topMultiline`
=> feat(FormItem): support multiline for top (#6579)

packages/vkui/src/components/DateInput/DateInput.tsx
=> patch(v5): pr6446

packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/AppRoot/ScrollContext.tsx
=> patch(v5): pr6614

packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.module.css, packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-webkit-light-1-snap.png
=> patch(v5):  pr6613

packages/vkui/src/components/Banner/Banner.tsx
- close #6616
---
Изменены теги с `p` на более универсальные `div`.
=> fix(Banner): fix nesting issue

.github/workflows/pull_request_common.yml
Проверяем при запуске прикреплении лейблов, что это не форк и первое открытие PR-а
=> ci(labels): check not fork and action

packages/vkui/src/components/DatePicker/DatePicker.tsx, packages/vkui/src/components/Select/Select.tsx, packages/vkui/src/types.ts
=> patch(v5): pr6663

packages/vkui/src/components/Banner/Banner.tsx
=> patch: pr6675

styleguide/Components/Table/TableRenderer.js, styleguide/propsParser.config.js
- see #6686
Удаляем излишнюю информацию из описания свойств компонентов. Уменьшаем бандл стайлгайда с 18.1MB до 12.7MB (чистыми)
=> docs: rm declarations & parent  from props

styleguide/Components/Preview.js, styleguide/setup.js, styleguide/utils/index.js, styleguide/webpack.config.js
- see #6686
Удаляем профайлинг, так как им никто не пользуется, при этом он может влиять на производительность документации
=> docs: rm profiling

packages/vkui/src/components/CustomSelectOption/CustomSelectOption.stories.tsx
- closed #5021
Добавляем `listbox` для примера
=> docs(CustomSelectOption): add withListBox

packages/vkui/src/components/Tappable/Tappable.stories.tsx
- closed #5014
> Не понимаю, как должен работать этот элемент. Как простая кнопка?
Изменяем надпись на более понятную
=> docs(Tappable): change inscription

packages/vkui/src/components/Panel/Panel.module.css
=> patch: pr6736

packages/vkui/src/components/Snackbar/Snackbar.test.tsx, packages/vkui/src/components/Snackbar/Snackbar.tsx, packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
=> patch: pr6731

packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/hooks/useDateInput.ts
В `onChange`  передается `undefined`
=> fix: revert #6664

.gitignore, .prettierignore, .vscode/extensions.json
Добавляем рекомендованные расширения для `VS Code`
=> chore: add recommended extensions 

.github/workflows/pull_request_packages.yml
=> Revert "build(deps): Bump andresz1/size-limit-action from 1.7.0 to 1.8.0"

docs/TESTING.md
Больше не требуется обновлять версию Playwright в данных файлах
=> docs(TESTING): playwright update info

packages/vkui/.storybook/addons/storybook-theme/StorybookTheme.tsx, packages/vkui/src/storybook/VKUIDecorators.tsx
Тоггл темы самого сторибука не оказывал влияние на тему `vkui`-компонентов
**Было:**
https://github.com/VKCOM/VKUI/assets/7431217/ce37360b-1d10-4344-b5b3-9571fcdb2d27      
**Стало:**
https://github.com/VKCOM/VKUI/assets/7431217/483ad1a6-fddf-422b-a7c4-4a4ba097fd28
=> fix: fix storybook global theme switch

package.json, yarn.lock
- caused #6791
Документации падают
ревертим css-loader
=> revert: css-loader to 6.10.0

packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.module.css, packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
При таче на SegmentedControlOption состояние hover застревает
Используем Clickable
=> fix: SegmentedControlOption hover

packages/vkui/src/components/DropZone/DropZone.tsx
Добавляем since
- related to #6807
=> docs(DropZone): add since 6.1.0

packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.e2e-playground.tsx, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.e2e.tsx, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.module.css, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.stories.tsx, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.test.tsx, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.tsx, packages/vkui/src/components/Typography/EllipsisText/Readme.md, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-android-chromium-dark-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-android-chromium-light-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-ios-webkit-light-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Typography/Typography.stories.tsx, packages/vkui/src/index.ts, styleguide/config.js
- close #6662
---
Компонент EllipsisText 
Задача компонента, через CSS, убирать текст не помещающийся в ширину контейнера в многоточие.
Реализовал подкомпонент EllipsisText , добавил документацию и примеры
=> feat: add ellipsistext

packages/vkui/src/components/ActionSheet/Readme.md, packages/vkui/src/components/Input/Readme.md, packages/vkui/src/components/Popper/Readme.md, packages/vkui/src/components/Touch/Readme.md, packages/vkui/src/components/WriteBar/Readme.md, styleguide/Components/Setting/Setting.js, styleguide/Components/Table/TableRenderer.js
=> fix: useRef need args

packages/vkui/src/components/Button/Button.module.css
- close #6586
---
Возвращаем CSS св-во `transition`.
- related to #6132
=> fix(Button): add transition property for background-color and color

packages/vkui/src/index.ts
Добавляем экспорт `AppearanceType`
=> feat: add AppearanceType export

packages/vkui/src/components/ModalPageHeader/Readme.md
=> docs: change link to PanelHeaderButton

packages/vkui/src/components/ActionSheet/ActionSheet.stories.tsx, packages/vkui/src/components/Alert/Alert.stories.tsx, packages/vkui/src/components/Epic/Epic.stories.tsx, packages/vkui/src/components/Epic/Readme.md, packages/vkui/src/components/PanelHeaderContext/Readme.md, packages/vkui/src/components/SplitCol/SplitCol.stories.tsx, packages/vkui/src/components/SplitLayout/Readme.md, packages/vkui/src/components/SplitLayout/SplitLayout.module.css, packages/vkui/src/components/SplitLayout/SplitLayout.stories.tsx, packages/vkui/src/components/SplitLayout/SplitLayout.tsx
- closed #6587
---
Добавляем централизацию для SplitLayout
=> feat(SplitLayout): add center

packages/vkui/src/components/Badge/Badge.tsx
- Fixes #6946
---
Свойство mode в Badge является обязательным
Делаем опциональным
=> fix(Badge): mode is optional

packages/vkui/src/components/Button/Readme.md
Есть проблемы в доке `Button` при переключении тогглов:
https://github.com/VKCOM/VKUI/assets/7431217/f00d2d45-3ce4-4c24-986b-7c46b786ed5d
Пока делаем компоненты контролируемыми
=> fix(doc): fix Button doc toggles

.github/actions/publish-workflow-4-complete/action.yml, .github/workflows/publish_prerelease.yml
- related to #6559 
Потерялся шаг с созданием стабильной ветки. Поэтому не прошел патч в #6968.
Добавляем шаг для пакета `@vkontakte/vkui`
=> fix(ci): bring back stable branch step

packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Добавляем свойство `dropdownOffsetDistance` как у CustomSelect
=> feat(ChipsSelect): add dropdownOffsetDistance

packages/vkui/src/components/SplitLayout/SplitLayout.e2e-playground.tsx, packages/vkui/src/components/SplitLayout/SplitLayout.e2e.tsx, packages/vkui/src/components/SplitLayout/SplitLayout.module.css, packages/vkui/src/components/SplitLayout/SplitLayout.tsx, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-android-chromium-dark-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-android-chromium-light-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-ios-webkit-dark-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-ios-webkit-light-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-webkit-light-1-snap.png
Центрирование в SplitLayout неверно работало
- caused #6951
=> fix(SplitLayout): center on inner

packages/vkui/src/index.ts
Экспортируем AccordionContentProps
=> feat: export AccordionContentProps

packages/vkui/src/lib/utils.ts
Используем для проверки версию `React`
=> fix: fix warning of React.use usage

packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.e2e-playground.tsx, packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.e2e.tsx, packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.module.css, packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.stories.tsx, packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.test.tsx, packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.tsx, packages/vkui/src/components/Typography/DisplayTitle/Readme.md, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-android-chromium-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-android-chromium-light-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-ios-webkit-light-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-webkit-light-1-snap.png, packages/vkui/src/index.ts, styleguide/config.js
Добавляем новый типографический компонент DisplayTitle
=> feat: add DisplayTitle

packages/vkui/src/components/ModalRoot/Readme.md
Прописано неправильное свойство
=> docs(ModalRoot): ButtonGroup gap

packages/vkui/src/components/DatePicker/DatePicker.tsx
- fixes #2697
---
Депрекейтим компонент DatePicker
=> chore(DatePicker): deprecated

yarn.lock
Обновляем все зависимости в yarn.lock файле
=> chore: yarn.lock update

packages/vkui/src/hooks/useMediaQueries.ts
- see #6920
---
React компилятор не разрешает писать в переменные за пределами хука
> Writing to a variable defined outside a component or hook is not allowed.
Используем WeakMap
=> fix(useMediaQueries): use WeakMap

packages/vkui/.eslintrc.js, packages/vkui/jest.config.js, packages/vkui/jest.setup.ts, packages/vkui/scripts/postcss.d.ts, packages/vkui/src/lib/accessibility.test.tsx, packages/vkui/src/shared/breakpoints.d.ts, packages/vkui/tsconfig.eslint.json, packages/vkui/tsconfig.json, tsconfig.json
Отключаем allowJs. Нужно для поддержки isolatedDeclarations
=> chore(tsconfig): disallow JS

packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/components/Textarea/useResizeTextarea.ts, packages/vkui/src/components/WriteBar/WriteBar.tsx
- see #6920
---
Линтер компилятора ругается на мутации внутри Textarea, WriteBar
> Mutating a value returned from a function whose return value should not be mutated
Вынес общий хук useResizeTextarea
=> fix: add useResizeTextarea

packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/ChipsSelect/useChipsSelect.ts
- close #6815
---
Добавляем `onOpen`/`onClose` коллбэки
=> fix(ChipsSelect): add onOpen & onClose callbacks

packages/vkui/src/components/CustomScrollView/CustomScrollView.module.css
- related to https://github.com/VKCOM/VKUI/pull/7060#discussion_r1656965151
Добавил необходимые стили для блока box-content
=> fix(CustomScrollView): add size styles to box-content

packages/vkui/src/components/GridAvatar/GridAvatar.tsx
В компоненте `GridAvatar` использовали в качестве `key` проп `url`, при передаче одинаковой картинки генерируется ворнинг от реакта об одинаковых ключах
Используем в качестве `key` индекс элемента в массиве
=> fix(GridAvatar): fix key prop

packages/vkui/src/hooks/useEnsuredControl.ts
=> chirry-pick: 7099

packages/vkui/src/hooks/useEventListener.ts
- see #6920
---
Линтер компилятора ругается на внутренности хука useEventListener
Избавился от хуков, написал отдельный класс реализующий EventListenerHandle
=> fix(useEventListener): rm hooks

packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-scroll-to-option-android-chromium-light-1-snap.png
Обновил скриншот в мастере
---
- related to #7131
=> fix: update screenshot

packages/vkui/src/components/Checkbox/Checkbox.tsx
- see #6920
---
> Mutating a value returned from a function whose return value should not be mutated
Скрываем мутацию от компилятора
=> fix(Checkbox): remove mutating ref

packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.tsx, packages/vkui/src/components/ImageBase/ImageBaseOverlay/ImageBaseOverlay.tsx
- see #6920
---
Выносим проверки в деве, чтобы не нарушать правило хуков
=> fix(ImageBase): add DevelopmentCheck

packages/vkui/src/components/View/View.tsx, packages/vkui/src/components/View/useLayoutEffectCall.tsx
- see #6920
---
> This mutates a variable that React considers immutable
Компилятор ругается на мутацию afterTransition
=> fix(View): add useLayoutEffectCall

packages/vkui/src/components/Snackbar/Snackbar.module.css, packages/vkui/src/components/Snackbar/Snackbar.test.tsx, packages/vkui/src/components/Snackbar/Snackbar.tsx, packages/vkui/src/components/Snackbar/types.ts, packages/vkui/src/components/Snackbar/utils.ts, packages/vkui/src/components/Spinner/Spinner.test.tsx, packages/vkui/src/testing/utils.tsx
=> patch: pr7135

packages/vkui/src/components/ModalRoot/Readme.md, packages/vkui/src/components/Search/Readme.md
Меняем indexOf != -1 на includes
=> docs: indexOf to includes

packages/vkui/src/components/Search/Readme.md, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/index.ts
- close #6851 
---
Доработал возможность прокидывания иконки в компонент Search. Теперь можно прокинуть в качестве иконки функцию. С помощью этого кейс issue решается(в документации добавил пример)
=> feat(Search): update prop icon. update documentation

packages/vkui/src/components/DateRangeInput/Readme.md
- caused by #6226
---
Из-за того, чо ребейзилась очень древняя ветка - в доку прокрался компонент, который больше не существует
Убираем ненужную больше обертку
=> doc(DateRangeInput): remove wrapper

packages/vkui/src/components/AppRoot/ScrollContext.tsx, packages/vkui/src/components/View/View.tsx, packages/vkui/src/components/View/ViewInfinite.tsx
- close #6909
---
Отключаем высчитывание высоты скролла без учёта клавиатуры (см. #3292) для кейса, когда переходим на следующую панель.
<details><summary>Код для View.stories.tsx, с помощью которого проверял</summary>
<p>
```tsx
import { useCallback, useState } from 'react';
import { Meta, StoryObj } from '@storybook/react';
import { CanvasFullLayout, DisableCartesianParam } from '../../storybook/constants';
import { Button } from '../Button/Button';
import { ConfigProviderOverride } from '../ConfigProvider/ConfigProviderOverride';
import { Div } from '../Div/Div';
import { FormItem } from '../FormItem/FormItem';
import { Group } from '../Group/Group';
import { Input } from '../Input/Input';
import { ModalCard } from '../ModalCard/ModalCard';
import { ModalRoot } from …
```
=> fix(View): exclude keyboard height only for current active panel

packages/vkui/src/components/TabsItem/TabsItem.e2e-playground.tsx, packages/vkui/src/components/TabsItem/TabsItem.e2e.tsx, packages/vkui/src/components/TabsItem/TabsItem.module.css, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-android-chromium-dark-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-android-chromium-light-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-ios-webkit-dark-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-ios-webkit-light-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-webkit-light-1-snap.png
- Fixes #7229
---
При наведении плохо видно наведение
Изменили токен
=> fix(TabsItem): hover background

packages/vkui/src/components/Gradient/Gradient.e2e-playground.tsx, packages/vkui/src/components/Gradient/Gradient.module.css, packages/vkui/src/components/Gradient/Gradient.tsx, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-light-1-snap.png
Добавляем новый режим для градиента `overlay`
=> feat(Gradient): mode overlay

packages/vkui/src/components/Flex/FlexItem/FlexItem.tsx
flexBasis перебивает style. Должно быть наоборот
=> fix(Flex): flexBasis in style

packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/lib/utils.ts
Удаляем функцию debounce, используем из @vkontakte/vkjs
=> refactor: rm debounce

.husky/pre-commit, package.json
С husky@^9.1.1  появилась возможность запускать команду напрямую, что должно быть немного быстрее
=> chore(husky): run command directly

tools/storybook-addon-cartesian/package.json, yarn.lock
Обновляем, чтобы задедуплицировать swc/core
=> build(dev-deps): Bump @storybook/addon-webpack5-compiler-swc to 1.0.5

packages/vkui/src/components/FixedLayout/FixedLayout.tsx, packages/vkui/src/components/FixedLayout/Readme.md, packages/vkui/src/components/OnboardingTooltip/OnboardingTooltipContainer.tsx
- close #5714 
---
Добавил prop `Component` для `FixedLayout` и для `OnboardingTooltipContainer`
=> feat(FixedLayout): add Component prop to FixedLayout

packages/vkui/src/index.ts
Экспортируем хук, чтобы его не брали из папки `/dist`
=> feat(useOrientationChange): export hook

packages/vkui/src/components/Flex/FlexItem/FlexItem.tsx
Делаем пропы `FormItem` необязательными + расширяем тип `flexBasis` строковым типом
=> feat(FlexItem): make props optional + extend flexBasis types

packages/vkui/src/components/Cell/Cell.test.tsx, packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.test.tsx, packages/vkui/src/components/CellButton/CellButton.test.tsx, packages/vkui/src/components/SimpleCell/SimpleCell.test.tsx
Улучшил покрытие тестами компонента `Cell` и сопутствующие ему `CellButton` и `SimpleCell`, `CellCheckbox`
=> test(Cell): improve unit-tests coverage

packages/vkui/src/components/FixedLayout/FixedLayout.test.tsx
Улучшил покрытие тестами компонента FixedLayout
=> test(FixedLayout): improve unit-tests coverage

packages/vkui/src/components/Skeleton/Skeleton.test.tsx
Улучшил покрытие тестами компонента Skeleton
=> test(Skeleton): improve unit-tests coverage

packages/vkui/src/components/Pagination/Pagination.test.tsx, packages/vkui/src/components/Pagination/PaginationNavigationButton/PaginationNavigationButton.tsx, packages/vkui/src/components/Pagination/PaginationPage/PaginationPageButton.tsx
Улучшил покрытие тестами компонента `Pagination`
=> test(Pagination): improve tests coverage

packages/vkui/src/components/Avatar/Avatar.test.tsx, packages/vkui/src/components/GridAvatar/GridAvatar.test.tsx
Улучшил покрытие тестами компонента Avatar и сопутствующие ему GridAvatar
=> test(Avatar): improve tests coverage

packages/vkui/src/components/Image/Image.test.tsx, packages/vkui/src/components/ImageBase/ImageBase.test.tsx
Улучшил покрытие тестами компонента `Image` и сопутствующий ему `ImageBase`
=> test(Image): improve tests coverage

packages/vkui/src/components/Calendar/Calendar.test.tsx, packages/vkui/src/components/CalendarDay/CalendarDay.test.tsx, packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx
Улучшил покрытие тестами компоненты Calendar и CalendarRange и сопутствующие им CalendarDay, CalendarHeader, CalendarTime
=> test(Calendar): improve tests coverage

packages/vkui/src/components/DropZone/DropZone.test.tsx
Улучшил покрытие тестами компонента `DropZone`
=> test(DropZone): improve tests coverage

packages/vkui/src/components/ChipsInput/ChipsInput.test.tsx
Улучшил покрытие тестами компонента ChipsInput
=> test(ChipsInput): improve tests coverage

packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx
Улучшил покрытие тестами компонента `DateRangeInput`
=> test(DateRangeInput): improve tests coverage

packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx
Произошел конфликт между влитым ранее переездом на date-fns (#7320) и в улучшении покрытия тестами (#7312)
Поправил импорт функций в файле с тестами.
=> fix(CalendarTimes): Fix functions import from date-fns in test file

.github/actions/node-setup/action.yml, .github/workflows/dedupe_deps.yml, .github/workflows/deploy_docs_on_branch_push.yml, .github/workflows/pull_request_common.yml, .github/workflows/pull_request_packages.yml, .github/workflows/reusable_workflow_test.yml, .github/workflows/reusable_workflow_test_e2e.yml, .github/workflows/update_screens.yml
Выделяем проверки yarn в отдельный воркфлоу, для ускорения установки зависимостей в CI на 10 секунд
https://yarnpkg.com/features/security#hardened-mode
---
**до**
```
Resolution step
➤ YN0000: └ Completed in 10s 320ms
```
**после**
```
Resolution step
➤ YN0000: └ Completed in 0s 318ms
```
=> ci: YARN_ENABLE_HARDENED_MODE=0

packages/vkui/src/components/Alert/Alert.test.tsx
Улучшил покрытие тестами компонента Alert
=> test(Alert): improve unit-tests coverage

packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
- close #7274 
---
Добавил prop `renderDropdown` для компонента ChipsSelect
Добавил тест для компонента
=> feat(ChipsSelect): add prop renderDropdown

packages/vkui/src/components/Flex/Flex.test.tsx, packages/vkui/src/components/Group/Group.test.tsx, packages/vkui/src/components/SimpleGrid/SimpleGrid.test.tsx
Улучшил покрытие тестами компонента Flex, Group, SimpleGrid
=> test: improve unit-tests coverage in Flex, Group, SimpleGrid

packages/vkui/src/components/Tabs/Tabs.test.tsx, packages/vkui/src/components/TabsItem/TabsItem.test.tsx
Улучшил покрытие тестами компонента Tabs и сопутствующие ему TabsItem
=> test(Tabs): improve unit-tests coverage

packages/vkui/src/components/DateInput/DateInput.test.tsx
Улучшил покрытие тестами компонента `DateInput`
=> test(DateInput): improve tests coverage

packages/vkui/src/components/Search/Search.test.tsx
Улучшил покрытие тестами компонента `Search`
=> test(Search): improve unit-tests coverage

packages/vkui/src/components/Checkbox/Checkbox.test.tsx
Улучшил покрытие тестами компонента Checkbox
=> test(Checkbox): improve unit-tests coverage

packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/Cell/Cell.tsx, packages/vkui/src/components/ChipsInputBase/Chip/Chip.tsx, packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx, packages/vkui/src/components/Link/Link.tsx, packages/vkui/src/components/Removable/Removable.tsx, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/Snackbar/Snackbar.tsx, packages/vkui/src/components/ToolButton/ToolButton.tsx
Добавляем больше компонентов в проверке кликабельности
Убираем лишние `onClick = noop`
=> fix(Clickable): more Components in checkClickable

packages/vkui/src/components/Placeholder/Placeholder.test.tsx
Улучшил покрытие тестами компонента `Placeholder`
=> test(Placeholder): improve unit-tests coverage

packages/vkui/src/components/Image/Readme.md, packages/vkui/src/components/ImageBase/ImageBase.module.css, packages/vkui/src/styles/constants.css
=> cherry-pick: #7342

.github/workflows/update_screens.yml
[Падает](https://github.com/VKCOM/VKUI/actions/runs/10503590862) экшен с обновлением скриншотов в ветке с патч-изменениями
=> ci(update_screens): add pull request write permission

.github/workflows/update_screens.yml
=> ci(update_screens): add pull request write permission (#7427)

packages/vkui/src/components/ChipsInputBase/Chip/Readme.md, styleguide/config.js
Из-за опечатки не было доки по `Chips`
=> docs(Chip): add docs page

packages/vkui/src/components/Footer/Footer.stories.tsx, packages/vkui/src/components/Footer/Footer.test.tsx, packages/vkui/src/components/Footer/Footer.tsx, packages/vkui/src/components/Footer/Readme.md
=> patch: pr7378

packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
=> patch: pr7419

packages/vkui/src/components/RootComponent/RootComponent.e2e-playground.tsx, packages/vkui/src/components/RootComponent/RootComponent.e2e.tsx, packages/vkui/src/components/RootComponent/RootComponent.module.css, packages/vkui/src/components/RootComponent/RootComponent.tsx, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-android-chromium-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-android-chromium-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-ios-webkit-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-ios-webkit-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-webkit-light-1-snap.png
- fixes #7412
---
Браузерные стили свойства `hidden` перебивались нашими стилями
Добавили на уровне RootComponent обработку глобального свойства `hidden`
=> fix(RootComponent): support hidden

packages/vkui/src/components/RootComponent/RootComponent.e2e-playground.tsx, packages/vkui/src/components/RootComponent/RootComponent.e2e.tsx, packages/vkui/src/components/RootComponent/RootComponent.module.css, packages/vkui/src/components/RootComponent/RootComponent.tsx, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-android-chromium-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-android-chromium-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-ios-webkit-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-ios-webkit-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/RootComponent/__image_snapshots__/rootcomponent-vkcom-webkit-light-1-snap.png
=> patch: pr7430

packages/vkui/src/hooks/useIsClient.ts, styleguide/pages/quick_start.md, styleguide/pages/utils.md
Изменил в документации ссылки на новый сайт [react.dev](https://react.dev/). Также в хуках изменил одну ссылку на описание в апи.
=> fix(links): updated the website of React

.github/workflows/update_screens.yml
This reverts commit 750f34396a2324e9b4a33e2867976c7fd38ef8f1.
=> Revert "ci(update_screens): use DEVTOOLS_GITHUB_TOKEN (#7437)"

packages/vkui/src/hooks/useIsClient.ts, styleguide/pages/quick_start.md, styleguide/pages/utils.md
=> patch: pr7447

packages/vkui/src/components/VisuallyHidden/VisuallyHidden.module.css
- Fixes #7467
Скрытый текст выделяется и его можно копировать
Отключаем выделение скрытого текста
=> fix(VisualHidden): user-select: none

packages/vkui/src/components/CardScroll/CardScroll.test.tsx
- caused by #7343
---
Поправил import в файле
=> fix(CardsScroll): fix import

packages/vkui/src/components/TabbarItem/TabbarItem.e2e-playground.tsx, packages/vkui/src/components/TabbarItem/TabbarItem.e2e.tsx, packages/vkui/src/components/TabbarItem/__image_snapshots__/tabbaritem-android-chromium-dark-1-snap.png, packages/vkui/src/components/TabbarItem/__image_snapshots__/tabbaritem-android-chromium-light-1-snap.png, packages/vkui/src/components/TabbarItem/__image_snapshots__/tabbaritem-ios-webkit-dark-1-snap.png, packages/vkui/src/components/TabbarItem/__image_snapshots__/tabbaritem-ios-webkit-light-1-snap.png
Нужно добавить скриншотные тесты для компонента TabbarItem
=> test(TabbarItem): add screenshots tests to component

packages/vkui/src/components/DatePicker/DatePicker.tsx
- see #6920
---
> Mutating component props or hook arguments is not allowed
Убираем мутации пропов, так как это не поддерживается реакт компилятором
=> fix(DatePicker): rm mutation props

packages/vkui/src/components/Spacing/Spacing.tsx
- see #6920
---
> Mutating component props or hook arguments is not allowed
Убираем мутации пропов, так как это не поддерживается реакт компилятором
=> fix(Spacing): rm mutation props

packages/vkui/src/components/Epic/Epic.e2e-playground.tsx, packages/vkui/src/components/Epic/Epic.e2e.tsx, packages/vkui/src/components/Epic/__image_snapshots__/epic-android-chromium-dark-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-android-chromium-light-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-ios-webkit-light-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Epic/__image_snapshots__/epic-vkcom-webkit-light-1-snap.png
Необходимо добавить скриншоты для компонента `Epic`
=> test(Epic): add screenshots tests to component

packages/vkui/src/components/FormField/FormField.e2e-playground.tsx, packages/vkui/src/components/FormField/FormField.e2e.tsx, packages/vkui/src/components/FormField/FormField.tsx, packages/vkui/src/components/FormField/__image_snapshots__/formfield-android-chromium-dark-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-android-chromium-light-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-ios-webkit-dark-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-ios-webkit-light-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/FormField/__image_snapshots__/formfield-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/FormStatus/FormStatus.e2e-playground.tsx, packages/vkui/src/components/FormStatus/FormStatus.e2e.tsx, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-android-chromium-dark-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-android-chromium-light-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-ios-webkit-dark-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-ios-webkit-light-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/FormStatus/__image_snapshots__/formstatus-vkcom-webkit-light-1-snap.png
Нужно добавить скриншотные тесты для компонентов FormStatus, FormField
=> test: add screenshots tests to components FormStatus, FormField

packages/vkui/src/components/Tooltip/Tooltip.tsx
- see #6920
---
> Mutating a value returned from a function whose return value should not be mutated
Убираем мутации пропов, так как реакт компилятор ругается
=> fix(Tooltip): rm mutation value

.github/workflows/pull_request_common.yml
- caused by #7474 
---
В шаге `dependencies` job-ы `check-dependabot-pr` проверки на directory не срабатывали так как получение outputs было реализовано не правильно. Нужно поправить этот момент
=> tech: fix condition in step dependencies

packages/vkui/src/components/Gallery/Gallery.e2e-playground.tsx, packages/vkui/src/components/Gallery/Gallery.e2e.tsx, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-android-chromium-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-android-chromium-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-ios-webkit-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-webkit-light-1-snap.png
Необходимо добавить скриншотные тесты для компонента Gallery
=> test(Gallery): add screenshot tests to component

packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/Popover/Popover.tsx
- related to #7302
Наследуем проп `autoFocus` из `FocusTrapProps` там, где у нас есть возможность переопределить `autoFocus`
=> fix(Popover, ActionSheet): get autoFocus prop from FocusTrapProps

yarn.lock
- see GHSA-9wv6-86v2-598j
Обновляем express до последней версии
=> build(deps-dev): update express

.github/actions/lfs/action.yml, .github/workflows/branch_test_coverage.yml, .github/workflows/reusable_workflow_test_e2e.yml, .github/workflows/update_screens.yml
Кэшируем в мастере LFS, чтобы не заходит за лимиты GitHub
=> ci: cache LFS on master

.github/actions/lfs/action.yml
Проверяем что git lfs установлен или же устанавливаем его
=> ci(lfs): fix check git lfs install

packages/vkui/src/components/Typography/Subhead/Subhead.module.css
- related #7283 
---
Добавили использование compact токенов в compact режиме, если такие токены есть.
- Subhead: добавлена поддержка compact режима для токенов fontWeight и fontFamily
=> feat(Subhead): Add fontWeight and fontFamily to compact mode

packages/vkui/src/components/Typography/Caption/Caption.module.css, packages/vkui/src/components/Typography/Caption/Caption.tsx, packages/vkui/src/components/Typography/Typography.module.css
- related #7283 
---
Добавили использование compact токенов в `compact` режиме, если такие токены есть.
Пришлось увеличить специфичность селекторов компонента Typography для установки кастомного значения жирности, чтобы перебить селектор Caption в режиме `caps`.
- Caption:  добавлена поддержка compact режима
=> feat(Caption): Add adaptivity

packages/vkui/src/components/Typography/Footnote/Footnote.module.css, packages/vkui/src/components/Typography/Footnote/Footnote.tsx
- related #7283
---
Добавили использование compact токенов в compact режиме, если такие токены есть.
- Footnote: добавлена поддержка compact режима
=> feat(Footnote): add adaptivity

packages/vkui/src/components/Typography/Title/Title.module.css, packages/vkui/src/components/Typography/Title/Title.tsx
- related #7283
---
Добавили использование compact токенов в compact режиме, если такие токены есть.
- Title: добавлена поддержка compact режима
=> feat(Title): Add adaptivity

.github/workflows/pr_close.yml, .github/workflows/pull_request_common.yml
Добавляем автоматизацию дублирования изменений в ветку `v6`
- добавляем скрипт на дублирование изменений в v6
- временно отключила автоматизацию метки `patch`, потому что по умолчанию будем лить все изменения в `master`
-
=> chore: add v6 cherry-pick automation

benchmark/package.json, yarn.lock
- see GHSA-m6fv-jmcg-4jfg
Обновляем зависимости для обновления send
=> build(dev-deps): update send to 0.19.0

packages/codemods/_templates/codemod-test/new/input-testfixture.ejs.t, packages/codemods/_templates/codemod-test/new/test.ejs.t, packages/codemods/_templates/codemod-test/new/transformer.ejs.t
Немного модернизируем шаблоны для создания кодмодов, чтобы учитывалась версию `v6` или `v7`
-
=> feat: improve codemod templates

package.json, prettier.config.mjs
Удаляем prettier.config.mjs, прописываем конфиг в package.json
- распил #7574
-
=> chore: rm prettier.config.mjs

packages/vkui/jest.config.ts, packages/vkui/package.json, packages/vkui/tsconfig.json, yarn.lock
Используем ts для jest config
- распил #7574
-
=> chore(vkui): jest config use ts

.github/workflows/update_screens.yml
В ветке v6 не обновляются скриншоты автоматические
Добавляем автоматическое обновление скриншотов для ветки v6
-
=> cI: add update screenshots for v6

packages/vkui/package.json
Т.к. при выполнении `yarn:build` не очищается папка `dist`, в ней могут сохраниться файлы, которые будут мешать сборке зависимых пакетов. 
-
=> chore: add clean script before build

packages/vkui/package.json
=> fix: revert typings deleting

packages/vkui/src/components/Spacing/Spacing.e2e-playground.tsx, packages/vkui/src/components/Spacing/Spacing.module.css, packages/vkui/src/components/Spacing/Spacing.test.tsx, packages/vkui/src/components/Spacing/Spacing.tsx, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-webkit-light-1-snap.png
=> patch: pr7632

yarn.lock
=> build(dev-deps): update express to 4.21.1

packages/vkui/src/components/Button/Button.tsx
=> patch: pr7734

packages/codemods/src/transforms/v7/__testfixtures__/alert/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/alert.ts.snap, packages/codemods/src/transforms/v7/__tests__/alert.ts, packages/codemods/src/transforms/v7/alert.ts, packages/vkui/src/components/Alert/Alert.e2e-playground.tsx, packages/vkui/src/components/Alert/Alert.module.css, packages/vkui/src/components/Alert/Alert.stories.tsx, packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Alert/AlertTypography.tsx, packages/vkui/src/components/Alert/Readme.md, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-android-chromium-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-ios-webkit-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/SplitLayout/Readme.md, packages/vkui/src/components/SplitLayout/SplitLayout.stories.tsx, packages/vkui/src/components/View/Readme.md, packages/vkui/src/components/View/View.stories.tsx
- close #7768
---
В компоненте `Alert` переименовал свойства `header` -> `title`, `text` -> `description`
- Alert:
- свойство `header` переименовано на`title`
- свойство `text` переименовано на `description`
```diff
<Alert
- header="Подтвердите действие"
+ title="Подтвердите действие"
- text="Вы уверены, что хотите лишить пользователя права на модерацию контента?"
+ description="Вы уверены, что хотите лишить пользователя права на модерацию контента?"
actionsAlign="left"
actionsLayout="horizontal"
/>
```
=> feat(Alert): rename typography props

packages/codemods/src/transforms/v7/__testfixtures__/subnavigation-bar/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/subnavigation-bar.ts.snap, packages/codemods/src/transforms/v7/__tests__/subnavigation-bar.ts, packages/codemods/src/transforms/v7/subnavigation-bar.ts, packages/vkui/src/components/SubnavigationBar/Readme.md, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.test.tsx, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx
- close #7791
---
В компоненте `SubnavigationBar` заменил свойство `mode` на флаг `fixed`
- SubnavigationBar: свойство `mode` заменено на флаг `fixed`
```diff
<SubnavigationBar
- mode={"fixed"}
+ fixed
/>
<SubnavigationBar
- mode={"overflow"}
/>
```
=> feat(SubnavigationBar): replace prop `mode` to `fixed` flag

packages/vkui/src/components/Banner/Readme.md
- cause #7773
---
Потерялось свойство
-
=> docs(Banner): extraSubhead to extraSubtitle

packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/AppRoot/ScrollContext.tsx, packages/vkui/src/hooks/useCounter.ts, packages/vkui/src/testing/utils.tsx
Используя несколько компонентов с useScrollLock, при демонтировании одного могло происходить разблокирование прокрутки.
Переходим на использование счетчика
- При использовании нескольних компонентов блокирующих прокрутку, на демонтировании одного из них могло происходить разблокирование прокрутки
=> fix(useScrollLock): use counter

packages/vkui/src/components/CustomSelect/Readme.md
- caused by #7703
---
Убрал лишнее прокидывание пропа autoHideScrollBar в документации CustomSelect, из-за которого падала ошибка в консоль.
-
=> doc(CustomSelect): remove props autoHideScrollbar

packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.e2e-playground.tsx, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css
=> patch: pr7819

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
=> patch: pr7816

packages/vkui/src/components/BaseGallery/BaseGallery.module.css, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-chromium-light-1-snap.png
- close #6272
---
Исправляем мерцание слоев в галерее при пролистывании
- Gallery: исправлено мерцание при переключении слайдов
=> fix(Gallery): fix flickery slides

.github/dependabot.yml
Добавляем в dependabot группировку для rspack зависимостей
-
=> ci(dependabot): add rspack pattern

packages/vkui/src/components/Touch/Touch.tsx
Убрал TODO в компоненте Touch связанные с заменой событий. Обсудили с @inomdzhon  и решили, что для однообразия с другими событиями лучше оставить как есть
-
=> fix(Touch): rm todo of events

packages/vkui/package.swcrc, packages/vkui/rspack.styles.config.ts, packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.test.tsx, shared.js
Пользователи завязываются на VKUI классы, чем нарушают инкапсуляцию
Хэшируем классы
- css классам добавлен хэш
=> fix: hash classes

packages/vkui/src/components/Gallery/Gallery.test.tsx
=> patch: pr7862 in v6

packages/codemods/src/transforms/v7/__testfixtures__/cell-button/basic.input.tsx, packages/codemods/src/transforms/v7/__testfixtures__/panel-spinner/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/cell-button.ts.snap, packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-spinner.ts.snap, packages/codemods/src/transforms/v7/__tests__/panel-spinner.ts, packages/codemods/src/transforms/v7/banner.ts, packages/codemods/src/transforms/v7/cell-button.ts, packages/codemods/src/transforms/v7/panel-spinner.ts, packages/codemods/src/transforms/v7/subnavigation-bar.ts
Добавляем недостающие `codemods`:
- `size` проп для `PanelSpinner`
- `chevron` проп для `CellButton`
-
=> feat: enhance codemods

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
=> patch: pr7882

packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/hooks/useDateInput.ts
=> patch: pr7878

packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
=> patch: pr7882 in v6

packages/vkui/src/components/Typography/EllipsisText/EllipsisText.test.tsx, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.tsx
Компонент наследует типы `RootComponent`, но сам `RootComponent` не использует из-за чего не работает параметр `Component`.
- caused by #6692
Заодно покрыл тестами параметр `disableNativeTitle`.
- EllipsisText: не срабатывал параметр `Component`
=> fix(EllipsisText): use RootComponent for host

packages/vkui/src/components/DateInput/DateInput.test.tsx
В рамках #7705 изменилось `API` по тестам, и `PR` вмерджился раньше, чем #7872
-
=> fix(DateInput): fix test after merge

packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/lib/floating/customResizeObserver.ts
=> patch: pr7933

packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/DateInput/DateInput.test.tsx
=> patch: pr7928

packages/vkui/package.swcrc, packages/vkui/rspack.styles.config.ts, shared.js
- caused by #7857
---
Необходимо перенести добавление хешей на следующую мажорную версию.
В релиз ноутах **v7.0.0** нужно сделать анонс, что на классы больше не получится завязываться.
-
=> tech: revert hash classes

packages/vkui/src/components/Spacing/Spacing.tsx
- caused by #7720
---
Опечатка в `@deprecated`
-
=> fix(Spacing): fix jsdoc typo

packages/vkui/.eslintrc.cjs, packages/vkui/src/components/BaseGallery/BaseGallery.tsx, packages/vkui/src/components/Gallery/Gallery.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, yarn.lock
Обновляем зависимости в yarn.lock
-
=> build(deps-dev): update yarn.lock

.codesandbox/ci.json
Codesandbox падает из-за использования фич из 20 ноды
Обновляем ноду до 20
-
=> ci(codesandbox): node 20

styleguide/Components/Setting/Setting.js, styleguide/Components/Settings/ThemeName.js
- caused by #7957
---
После #7957 нужно поправить использование компонента Link в styleguide
-
=> fix: fix Link with icon in styleguide

packages/vkui/package.json
jest требует дефолтного экспорта
Добавил в `exports` поля `default`
- В package.json добавлены exports.default поля
=> fix(vkui): add default export

packages/vkui/src/index.ts
- добавлен экспорт `AppRootPortal`
=> feat(AppRootPortal): add export

packages/vkui/src/components/FloatingArrow/DefaultIcon.tsx, packages/vkui/src/components/FloatingArrow/FloatingArrow.module.css, packages/vkui/src/components/FloatingArrow/FloatingArrow.test.tsx, packages/vkui/src/components/FloatingArrow/FloatingArrow.tsx, packages/vkui/src/index.ts
Для возможности пользователям создавать свои всплывающие окна.
- Добавлен экспорт `FloatingArrow`, использующийся компонентами `Popover`, `Tooltip`, `Popper`
=> feat(FloatingArrow): reexport

styleguide/Components/StyleGuide/StyleGuideHeader.js
- caused by #7957
---
_Не поправили в шапке_
-
=> docs: fix button with version

packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx
- HorizontalCell: добавлено новое свойство `titleComponent`, для изменения типографического элемента `title`
=> feat(HorizontalCell): add titleComponent

packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/Clickable/RealClickable.tsx
На все компоненты внутри Clickable.tsx повешана декларация `use client`, хотя для многих компонентов она не требуется
Выносим компонент RealClickable с `use client` кодом отдельно
-
=> refactor(Clickable): mv use client code

packages/vkui/src/components/Button/Button.module.css
`.host` излишен для модификаторов
Удаляем
-
=> refactor(Button): rm host in selectors

packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
- related to #7526
Не успели в v7
-
=> chore(PanelHeaderButton): mv TODO from v7 to v8

.github/workflows/pull_request_common.yml
=> chore: revert patch label on PRs

packages/vkui/src/components/Header/Readme.md
- caused by #7957
Забыли поменять API в доке
-
- Header: исправлено расположение ссылки с иконкой в теме `vkcom`
=> fix: link and icon position on header doc page

packages/vkui/src/components/ChipsInput/ChipsInput.tsx
- close #7978 
---
Нужно в пропсы `ChipsInput` добавить свойство `maxHeight`
- ChipsInput: добавлено свойство `maxHeight`, которое позволяет ограничить высоту компонента
=> feat(ChipsInput): add prop maxHeight

packages/vkui/src/components/CustomScrollView/CustomScrollView.module.css, packages/vkui/src/components/CustomScrollView/CustomScrollView.test.tsx, packages/vkui/src/components/CustomScrollView/CustomScrollView.tsx
- close #7932 
---
Нужно добавить свойство `scrollBehavior`, которое отвечает за стиль `scroll-behavior` в компонента CustomScrollView
- CustomScrollView: добавлено свойство `scrollBehavior`, которое отвечает за настройку стиля `scroll-behavior`
=> feat(CustomScrollView): add prop scrollBehavior

packages/vkui/src/components/Slider/Slider.test.tsx, packages/vkui/src/components/Slider/Slider.tsx
- related https://github.com/VKCOM/VKUI/issues/6219
---
Добавлены пропы для задания testid у slider thumb.
- Slider: добавлена возможность прокинуть test-id на ползунки с помощью свойств `startThumbTestId`, `endThumbTestId`.
=> feat(Slider): add testid for slider thumbs

packages/vkui/src/components/ContentCard/ContentCard.module.css
- close #7900 
---
Сейчас контент карточки не всегда растягивается на всю высоту самой карточки, поэтому ховер на карточку выглядит некорректно
Добавил растягивание на 100% контента карточки
- ContentCard: поправлен баг с растягиванием контента карточки на всю высоту карточки
=> fix(ContentCard): fix height of ContentCard content

packages/vkui/src/components/CardScroll/CardScroll.test.tsx, packages/vkui/src/components/CardScroll/CardScroll.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
- related https://github.com/VKCOM/VKUI/issues/6219
---
Добавляем свойства для прокидывания data-testid на стрелки.
Убираем старые, зашитые в код testId. 
- HorizontalScroll: добавлена возможность передать `data-testid` в стрелки навигации с помощью новых свойств `startArrowTestId` и `endArrowTestId`.
- CardScroll: добавлена возможность передать `data-testid` в стрелки навигации с помощью новых свойств `startArrowTestId` и `endArrowTestId`.
=> feat(HorizontalScroll, CardScroll): Add testid props for arrows

packages/vkui/src/index.ts
Экспортируем полезные функции и компоненты
- экспортирован `AccordionContext`
- экспортирован `DOMContext`
- экспортирован `unstable_useCSSKeyframesAnimationController`
=> feat: add more export

.github/workflows/monday.yml
- https://github.com/VKCOM/gh-actions/pull/519
Добавляем экшон для создания PR-а обновления версии Node.js в понедельник
-
=> ci(monday): add nvmrc-up-pr

packages/vkui/src/components/Popper/Popper.tsx
- caused by #8178 
---
в #8178 в `Popper` было добавлено свойство `strategy`, которое по умолчанию было сделано `'fixed'`, это неправильно, так как, судя по документации, раньше по умолчанию использовалось `absolute`. Нужно просто убрать значение по умолчанию
-
=> fix(Popper): remove strategy by default

packages/vkui/src/components/Tabs/Tabs.tsx
=> patch: pr8203

packages/vkui/src/components/FormItem/FormItem.module.css
- close #8146 
---
Используем токены расстояний в FormItem. 
В том числе и в режиме `removable`, так как логика отрицательных марджинов основана на значениях отступов элемента.
- FormItem: отступы привязаны к токенам.
=> fix(FormItem): Use spacing size tokens

packages/vkui-docs-theme/src/components/Head.tsx, packages/vkui-docs-theme/src/mdx/Main/Main.tsx, packages/vkui/src/testing/e2e/ComponentPlayground.tsx, yarn.lock
Обновляем типы для реакта. React.FC теперь может возвращать промис
Поправлены использования React.FC
-
=> build(dev-deps): update @types/react

packages/vkui/src/components/FormItem/FormItem.e2e-playground.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/Removable/Removable.module.css, packages/vkui/src/components/Removable/Removable.tsx
=> patch: pr8232

packages/vkui/src/components/Accordion/Accordion.tsx
Улучшаем документацию для `onChange`
- [Accordion](https://vkcom.github.io/VKUI/${version}/#/Accordion): поправлена документация свойства `onChange`
=> docs(Accordion): onChange

.github/actions/publish-workflow-1-setup/action.yml
Не используем кэш для публикации, дополнительно проверяем зависимости
-
=> ci(publish): rm github cache

packages/vkui/src/components/Card/Card.stories.tsx, packages/vkui/src/components/CardGrid/CardGrid.stories.tsx, packages/vkui/src/components/CardScroll/CardScroll.stories.tsx, packages/vkui/src/components/Checkbox/Checkbox.stories.tsx, packages/vkui/src/components/Flex/Flex.stories.tsx, packages/vkui/src/components/FormField/FormField.stories.tsx, packages/vkui/src/components/FormField/Readme.md, packages/vkui/src/components/Input/Input.stories.tsx, packages/vkui/src/components/Switch/Switch.stories.tsx, packages/vkui/src/components/Textarea/Textarea.stories.tsx
- close #4930
- close #4931
---
- Исправляем Flex пример из storybook. Раньше мы растягивали пример по высоте, чтобы Banner хорошо смотрелся, но из-за того, что компонент `Banner` был когда-то отрефакторен и потерял одну из обёрток, пример Flex стал излишне растягиваться по высоте и ломать компонент Banner с нишим кастомным стилем. Убрал растягивание по высоте.
- во время ревью примеров сторибука с точки зрения доступности было не понятно что за примеры лежат в `Card` и `CardGrid` и есть ли что там проверять. Добавил текст в контейнеры. Чтобы было понятно, что это просто визульные примеры. Обсудил это с тестировщиком по доступности и сошлись на том, что этого для примеров будет достаточно. Текст спрятал, потому что примеры должны быть похожи на то, что у нас в дизайне.
- Из примера Card …
=> doc(Card): add labels to Card and CardScroll storybook examples

packages/vkui/src/components/ModalPage/ModalPageBase.tsx, packages/vkui/src/components/ModalPage/ModalPageInternal.tsx
- relates to #8291 
---
Для pr #8291 нужно добавить компонент, чтобы отображать только сам контент модалки `ModalPage` 
-
=> tech(ModalPage): add ModalPageBase component with implementation of modal

packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Alert/AlertBase.tsx
- relates #8291
---
Для pr #8291 нужно добавить компонент, чтобы отображать только сам контент модалки `Alert`
-
=> tech(Alert): add AlertBase component with implementation of alert modal

packages/vkui/src/components/Clickable/Clickable.test.tsx, packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/TabsItem/TabsItem.module.css, packages/vkui/src/hooks/useTabsNavigation.ts
Тег `a` без `href` не является ссылкой
- Для отключенных ссылок добавляем `role="link"`
- Не прокидывам `disabled` для `a` и `div`
- Фиксим проверку для табов на `disabled`
- Исправлена доступность для `disabled` ссылок
=> fix(Clickable): add role=link for <a>

packages/vkui/src/components/Search/Search.test.tsx, packages/vkui/src/components/Search/Search.tsx
Добавляем data-testId для кнопки очистки Search.
Убрал `it.skip` из некоторых тестов Search. Падающие тесты снова проходят. Один тест подправил в соответствии с описанием (убрал `onChange`):
https://github.com/VKCOM/VKUI/blob/ba3c303dc44287ec9b567ce20651b3c13ce54493/packages/vkui/src/components/Search/Search.test.tsx#L142-L148
- Search: добавляем новое свойство `celarButtonTestId` для передачи data-testid кнопке очистки
=> feat(Search): Add testId to clear button

packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.e2e-playground.tsx, packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.module.css, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-android-chromium-dark-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-android-chromium-light-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-ios-webkit-light-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-webkit-light-1-snap.png
Текст в снекбаре может выходить за его пределы
Добавляем `break-word`
- [Snackbar](https://vkcom.github.io/VKUI/${version}/#/Snackbar): длинный текст выходил за пределы компонента
=> fix(Snackbar): break-word

packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx, packages/vkui/src/components/OnboardingTooltip/OnboardingTooltipContainer.tsx, packages/vkui/src/components/OnboardingTooltip/OnboardingTooltipContext.tsx
Сейчас в `OnboardingTooltip` поиск `OnboardingTooltipContainer` происходит с помощью функции `.closest`, что не очень оптимально по производительности. Предложение: передавать `ref` на `OnboardingTooltipContainer` через context api.
- Добавил контекст `OnboardingTooltipContext` и в `OnboardingTooltipContainer` прокинул в него ref на контейнер
- В `OnboardingTooltip` сделал получение контейнера через контекст
- В `OnboardingTooltipContainer` не стал удалять дата атрибут, так как возможно кто-то мог на него завязаться
-
=> feat(OnboardingTooltipContainer): tooltip container from context

packages/vkui/src/components/ContentCard/ContentCard.test.tsx, packages/vkui/src/components/ContentCard/ContentCard.tsx
- close #8384 
---
Нужно добавить свойство `imageObjectFit` для изменения свойства `object-fit` у картинки
- ContentCard: Добавлено свойство `imageObjectFit`, для изменения `object-fit` у картинки
=> feat(ContentCard): add prop `imageObjectFit`

packages/vkui/rspack.styles.config.mjs
Добавляем проверку цикличных зависимости
- see #8354
-
=> chore: add rspack.CircularDependencyRspackPlugin

styleguide/Components/Frame/Frame.js
- related to #8383
Дока перестала открываться, потому что требует svg sprite
-
=> fix: remove svg sprite

packages/vkui/src/components/Avatar/__image_snapshots__/avatar-android-chromium-dark-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-android-chromium-light-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-ios-webkit-light-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-state-focus-visible-overlay-android-chromium-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-light-1-snap.png, packages/vkui/src/styles/constants.css
- close #7669 
---
Сейчас `Overlay` у `Image` располагается ниже бордера из-за меньшего `z-index`. Нужно чтобы было наоборот
- Image: Обводка картинки теперь располагается ниже `Overlay`
=> fix(ImageBase): fix border `z-index`

packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsInputBase/helpers.ts
- close #8434 
---
Если у `option` свойство `value` является числом, то на этот `option` не срабатывает удаление через кнопку `Backspace`/`Delete`.
- Добавил для чипа атрибут `data-value-type` - со значениями `number`/`string`, чтобы можно было определить тип и сделать нужное преобразование
- ChipsSelect: Поправлен баг с удалением чипа, если у него в `value` было значение типа `number`
=> fix(ChipsSelect,ChipsInput): fix remove option with number value

packages/vkui/src/components/FormItem/FormItem.module.css
---
Перенос текста не нужен, если включен проп topMultiline
- FormItem: перенос текста не нужен, если включен проп `topMultiline`
=> fix(FormItem): Disable overflow in label with multiline prop

.codesandbox/ci.json
codesandbox для каждого PR-а создавал npm пакет который можно использовать для тестирования. При этом он имеет свой ci который клонирует репозиторий. Из-за этого он может влиять на LFS лимиты
-
=> ci: rm codesandbox

packages/vkui/src/components/Tappable/Tappable.module.css
- caused by #6132
---
Заметил, что волна в компоненте `Tappable` позиционируется неправильно относительно места нажатия. Покопался и нашел в истории pr #6132, в котором была сделана случайная правка:
```diff
.wave {
...
margin-block: -12px 0;
- margin-inline: -12px 0;
+ margin-inline: 0 -12px;
content: '';
...
}
```
Нужно вернуть как было
- Tappable: Поправлено отображение эффекта волны относительно места нажатия
=> fix(Tappable): fix wave positioning

packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
=> patch: pr8457

packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
=> patch: pr8454

packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/CalendarDays/CalendarDays.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateInput/hooks.test.ts, packages/vkui/src/components/DateInput/hooks.ts, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/hooks/useCalendar.ts, packages/vkui/src/hooks/useDateInput.ts, packages/vkui/src/lib/date.ts
=> patch: pr8470

packages/vkui/src/components/Touch/Touch.test.tsx, packages/vkui/src/components/Touch/Touch.tsx, packages/vkui/src/lib/dom.tsx
svg элементы не обрабатывались когда включался touch режим
https://github.com/user-attachments/assets/aad5ba6a-fb0a-4498-bd2f-6c7427efbe21
Добавлена проверка на isSVGElement
- [Touch](https://vkcom.github.io/VKUI/${version}/#/Touch): svg элементы не обрабатывались при touch событиях
=> fix(Touch): is svg element

packages/vkui/src/components/ModalRoot/Readme.md, packages/vkui/src/components/ModalRoot/types.ts, packages/vkui/src/components/ModalRoot/useModalRootContext.ts
=> patch: pr8481

.github/workflows/pull_request_packages.yml, .github/workflows/pull_request_packages_deploy.yml
Добавляем в ci публикацию npm пакета на s3 собранный из изменений в PR-е. Данный пайплайн сделан на замену codesandbox-ci
-
=> ci: add deploy package

.yarn/patches/@storybook-addon-webpack5-compiler-swc-npm-1.0.5-dbab81c473.patch, tools/storybook-addon-cartesian/package.json, yarn.lock
Обновляем `@storybook/addon-webpack5-compiler-swc` до 3.0.0
-
=> build(deps-dev): Bump @storybook/addon-webpack5-compiler-swc to 3.0.0

packages/vkui/src/hooks/usePlatform.test.tsx
Удаляем дубликат теста (выше есть `"handles ConfigProvider's without platform"`)
-
=> chore: remove duplicate test

packages/vkui/src/components/Progress/Progress.tsx
Исправляем тип для покраски токеном
- [Progress](https://vkcom.github.io/VKUI/${version}/#/Progress): исправлен тип поля `appearance` для использования с токеном
=> fix(Progress): appearance token type

packages/vkui/src/components/Progress/Progress.tsx
=> patch: pr8504

packages/vkui/src/components/Link/Link.module.css, packages/vkui/src/components/Link/Link.test.tsx, packages/vkui/src/components/Link/Link.tsx
=> patch: pr8503

packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/lib/floating/index.ts, packages/vkui/src/lib/floating/types/common.ts
- close #8529
---
При использовании свойства `dropdownAutoWidth ` в `CustomSelect` дропдаун отображается всегда по центру относительно поля ввода. Иногда нужно, чтобы выравнивание было по левому или правому краю. Нужно добавить возможность установки выравнивания.
- Расширил типа `popupDirection` - добавил `top-start`, `top-end`, `bottom-start`, `bottom-end`
- CustomSelect: Тип свойства `popupDirection` расширен новыми значениями: `top-start`, `top-end`, `bottom-start`, `bottom-end`
=> feat(CustomSelect): extend popupDirection type

packages/vkui/playwright-ct.config.mjs
Правим TODO в `playwright-ct.config.mjs`
-
=> chore(playwright-ct.config.mjs): resolve TODO

packages/vkui/src/components/CarouselBase/types.ts
Добавляем описание для `slideWidth`
-
=> docs(Gallery): slideWidth description

packages/vkui-date-fns-tz/package.json
> npm error 402 Payment Required - PUT https://registry.npmjs.org/@vkontakte%2fvkui-date-fns-tz - You must sign up for private packages
-
=> ci(vkui-date-fns-tz): publishConfig access public

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- close #8564
---
Сейчас при прокидывании в `CustomSelect` свойство `readonly` поле все еще можно изменять, открывать дропдаун и тд. Нужно поправить
- Сделал корректное прокидывание `readOnly` свойства до input
- Также при прокидывании `readOnly` отключил обработку действий, которые могли бы открыть дропдаун
- Решил, что при прокидывании `readOnly` не должны показывать иконки открытия(шеврон) и кнопка удаления.
- CustomSelect: Исправлено поведение компонента при прокидывании `readOnly`
=> fix(CustomSelect): fix readonly mode

packages/vkui-date-fns-tz/.gitignore, packages/vkui-date-fns-tz/build.ts, packages/vkui-date-fns-tz/package.json
- related to #8581
- caused by #8588
Добавляем cjs для решения проблем jest-а
-
=> fix(vkui-date-fns-tz): cjs

packages/vkui-date-fns-tz/package.json
- caused by #8591
- related to #8581
Потерялся index.cjs файл
-
=> fix(vkui-date-fns-tz): add index.cjs files

yarn.lock
В yarn.lock затерялись зависимости
-
=> build(deps-dev): fix @swc core

packages/vkui/src/components/Banner/Banner.tsx, packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/Checkbox/Checkbox.tsx, packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/Clickable/RealClickable.tsx, packages/vkui/src/components/ContentCard/ContentCard.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.tsx, packages/vkui/src/components/IconButton/IconButton.tsx, packages/vkui/src/components/Link/Link.tsx, packages/vkui/src/components/ModalOutsideButton/ModalOutsideButton.tsx, packages/vkui/src/components/Pagination/PaginationPage/PaginationPageButton.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx, packages/vkui/src/components/Radio/Radio.tsx, packages/vkui/src/components/RichCell/RichCell.tsx, packages/vkui/src/components/SelectionControl/SelectionControl.tsx, packages/vkui/src/components/SimpleCell/SimpleCell.tsx, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx, packages/vkui/src/components/TabsItem/TabsItem.tsx, packages/vkui/src/components/Tappable/Tappable.tsx, packages/vkui/src/components/ToolButton/ToolButton.tsx
Добавляем возможность Clickable менять `div` тег.
Для Link меняем тег `div` на `span`
- [Link](https://vkcom.github.io/VKUI/${version}/#/Link): тег `div` изменен на `span`
=> feat(Clickable): add DefaultComponent

packages/vkui/src/components/MiniInfoCell/MiniInfoCell.tsx
Tappable уже внутри себя имеет логику кликабельности
-
=> refactor(MiniInfoCell): use Tappable

styleguide/Components/ReactComponent/ReactComponent.js, styleguide/Components/StyleGuide/StyleGuideHeader.js
Ссылаемся на сторибук конкретных версий, потому что всё равно его собираем
- Исправлены ссылки на конкретные версии **Storybook** из основной документации
=> fix(docs): url storybook to its own version

packages/vkui/src/components/Flex/Flex.test.tsx, packages/vkui/src/lib/layouts/gaps.ts
---
У вложенного Flex gap наследуется от родительского, если у дочернего не выставлен никакой gap
- Flex: У вложенного `Flex` при `gap=undefined` gap наследовался от родительского `Flex`
=> fix(Flex): fix nested Flex gap reset

.github/workflows/publish_deploy.yml, website/next.config.mjs
При паблише новой версии пушим новую документацию (и сторибук) в отдельный репозиторий, который деплоится на vkui.io.
Приходится билдать дважды в случае релиза - сначала для доки, которая хостится с корневого пути, затем для пути `/{version}`
-
=> chore: add new docs to CI

packages/vkui/docs/common/hooks/useGetConfigByQuery.ts, packages/vkui/docs/components-overview/ComponentsOverview.tsx, packages/vkui/docs/icons-overview/IconsOverview.tsx
Доработал поиск на странице `overview` в `storybook`, так чтобы при вводе русских символов поиск происходил по английским
-
=> feat(storybook): improve search by query on overview page

packages/vkui/src/components/ImageBase/ImageBase.module.css, packages/vkui/src/lib/floating/functions.test.ts, packages/vkui/src/lib/floating/functions.ts
- close #8699
---
Сейчас при использовании флага `hideWhenReferenceHidden` при скрытии `reference`  для popover задается стиль `visibility: hidden`. Но если внутри этого popover будет элемент с `visibility: visible`, то его будет видно. Нужно сделать скрытие по другому
Поменял стиль `visibility: hidden` на `opacity: 0`.
Решили пока что оставить логику скрытия как есть и поправить конкретно кейс с `Image`. Немного поменял стили `Image`, чтобы visibility: visible не выставлялось явно
- Popover: Поправлена проблема с тем, что при использовании флага `hideWhenReferenceHidden` не все содержимое всплывающего элемента могло скрываться
=> fix(Popover): fix hide popover when reference hidden

tools/postcss-restructure-variable/package.json, tools/postcss-restructure-variable/postcss-restructure-variable.test.js, tools/postcss-restructure-variable/postcss-restructure-variable.test.js.snapshot
- link #8704
Переводим postcss-restructure-variable c jest на node
-
=> test(postcss-restructure-variable): use node test

.github/workflows/pr_close.yml
- related to #7404
---
Экшен, который должен автоматически обновлять `@vkui-floating-ui`, когда обновляется `@floating-ui/react-dom`, падает на шаге, когда должен запустить workflow публикации пакета. Скорее всего у него не хватает прав на запуск. Добавил в `permissions` `actions: write`
-
=> fix: add actions permission to workflow

packages/vkui/package.json, yarn.lock
Обновление @vkontakte/vkui-date-fns-tz и  @vkontakte/vkui-floating-ui
-
=> build(deps): update @vkontakte

packages/vkui/src/components/ContentCard/ContentCard.tsx, yarn.lock
Полностью обновляем yarn.lock
Размер уменьшился из-за реакта
-
=> build(deps-dev): update yarn lock

packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/components/Skeleton/Skeleton.tsx, packages/vkui/src/components/View/View.tsx, packages/vkui/src/components/View/ViewInfinite.tsx, packages/vkui/src/lib/date.ts, packages/vkui/src/lib/touch/UIPanGestureRecognizer.ts
- link #8640
---
Добавляем константу `millisecondsInSecond`, удаляем импорт date-fns/constants
-
=> refactor: millisecondsInSecond

packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/CalendarDays/CalendarDays.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/CalendarRange/utils.ts, packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/hooks/useCalendar.ts, packages/vkui/src/hooks/useTodayDate.ts, packages/vkui/src/lib/calendar.ts, packages/vkui/src/lib/date.test.ts, packages/vkui/src/lib/date.ts
- link #8640
---
Переписываем `is*` функции
-
=> refactor: rm is function from date-fns

packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.tsx
=> patch: #8872

packages/vkui/package.json, packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/CalendarRange/Readme.md, packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/DateRangeInput/Readme.md, packages/vkui/src/hooks/useCalendar.ts, packages/vkui/src/hooks/useTodayDate.ts, packages/vkui/src/lib/calendar.ts, packages/vkui/src/lib/date.test.ts, packages/vkui/src/lib/date.ts, yarn.lock
- fix #8640
---
Удаляем зависимость date-fns
- [date-fns](https://www.npmjs.com/package/date-fns) заменён на внутреннее решение
=> feat: rm date-fns

.github/workflows/pr_close.yml, .github/workflows/publish_complete.yml
- relates to #7404
---
Сейчас при обновлении `@floating-ui/react-dom` публикуется новая версия "@vkontakte/vkui-floating-ui" на шаге "Publish new version" джобы "autopublish-vkui-floating-ui". Но следующий шаг выполняется, не дожидаясь завершения воркфлоу публикации.
Перенес код обновления `@vkontakte/vkui-floating-ui` в `vkui` в форкфлоу `publish_complete.yml`
-
=> fix: move update vkui-floating-ui after complete publish new version

.github/workflows/pull_request_packages_deploy.yml
- caused by #8863
---
Экшен генерации дифа бандла опять упал - теперь на шаге с поиском комментария. Упал он из-за того, что в шаге `diff_comment` в needs не был указан шаг `pr_workflow_payload`
-
=> fix: fix find comment with diff

packages/vkui/src/components/MiniInfoCell/MiniInfoCell.tsx, packages/vkui/src/components/Tappable/Tappable.tsx
- close #8814
---
Нужно расширить свойства `MiniInfoCell`, чтобы они наследовались от `Tappable`
- MiniInfoCell: Свойства теперь наследуют свойства `'hoverMode' | 'activeMode' | 'hovered' | 'activated' | 'hasHover' | 'hasActive'` от `Tappable`
=> fix(MiniInfoCell): extend tappable props

website/app/[[...mdxPath]]/page.tsx, website/app/layout.tsx
- link #8924
---
В новой документации нужно указать rel="canoncial", чтобы улучшить индексацию при использовании кастомного домена в GH Pages (https://stackoverflow.com/questions/15389370/how-to-make-google-index-my-custom-domain-instead-of-the-github-pages-domain)
-
=> tech: add canonical url to documentation page

.gitignore, examples/vkui-nextjs-ts/.gitignore, examples/vkui-nextjs-ts/next-env.d.ts, website/next-env.d.ts
Файлик динамически генерируется на каждом билде, добавляем в `.gitignore`
-
=> feat: add next-env.d.ts to gitignore

package.json, yarn.lock
- caused by #8958
---
В #8958 была добавлена devDependencies jsdom, но видимо эта зависимость используется внутри vitest, поэтому она не нужна как отдельная зависимость. Ее можно удалить.
-
=> tech: remove jsdom dependency

packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx, packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
=> patch: pr9009

packages/vkui/src/testing/utils.tsx
Некоторые тесты падают в baseline. Немного подправил установку фейковых таймеров
-
=> fix: fix baseline tests
