VKCOM/VKUI

packages/vkui/package.json, yarn.lock
Обновляем `@vkontakte/vkui-floating-ui` до свеженькой версии, чтобы обновиться на [@floating-ui/react-dom](https://github.com/floating-ui/floating-ui/tree/HEAD/packages/react-dom) v2.0.4
- related to https://github.com/VKCOM/VKUI/pull/6097
=> build(deps): bump @vkontakte/vkui-floating-ui to v0.1.2

.github/workflows/publish.yml, .github/workflows/publish_prerelease.yml, .github/workflows/publish_token_translator.yml, .github/workflows/publish_vkui_floating_ui_react_dom.yml, packages/token-translator/package.json, packages/vkui-floating-ui/package.json, packages/vkui/package.json
Добавляем подпись от ci для npm пакетов
- [блог](https://github.blog/2023-04-19-introducing-npm-package-provenance/)
- [документация](https://docs.npmjs.com/generating-provenance-statements)
На пакетах появится подпись от GitHub Actions с ссылкой на коммит, процесс ci и т.д.
UPD: сейчас не заработает, нужно чтобы yarn завез себе
- blocked by  [yarnpkg/berry#5430](https://togithub.com/yarnpkg/berry/issues/5430)
UPD 2: переписал на npm
=> feat: add provenance

packages/vkui/src/components/Search/Readme.md, packages/vkui/src/components/Search/Search.e2e-playground.tsx, packages/vkui/src/components/Search/Search.module.css, packages/vkui/src/components/Search/Search.test.tsx, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-light-1-snap.png
- resolve #5521
Добавляем кнопку "Найти" в соответствии с требованиями дизайн-системы
=> feat(Search): add Find button

.github/workflows/pull_request_common.yml
Зарелизили последнею минорную версию по **v5** [v5.10.0](https://github.com/VKCOM/VKUI/releases/tag/v5.10.0). Т.к. дальше пойдут только хотфиксы, то удаляем автодобавление метки `v5`, а также временно удаляем метку `patch`.
- related to #5953
=> ci(pr-auto-add-label): rm v5; a.i. disable patch

packages/vkui/src/components/HoverPopper/HoverPopper.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/helpers/getMergedSameEventsByProps.test.ts, packages/vkui/src/helpers/getMergedSameEventsByProps.ts, packages/vkui/src/hooks/usePatchChildren.test.tsx, packages/vkui/src/hooks/usePatchChildren.ts, packages/vkui/src/hooks/usePatchChildrenRef.test.tsx, packages/vkui/src/hooks/usePatchChildrenRef.ts, packages/vkui/src/lib/utils.ts, packages/vkui/src/types.ts
Добавил два новых аргумента:
1. возможность прокидывать параметры помимо `ref`/`getRootRef`;
1. возможность прокинуть дополнительный обработчик `ref`.
- block #2523
- переименовал из `usePatchChildrenRef()` на `usePatchChildren()` (см. https://github.com/VKCOM/VKUI/pull/6135#discussion_r1405759461)
- `getMergedSameEventsByProps()` – функция, которая объединяет две схожие функции в одну из двух входных
параметров.
- в `lib/utils` добавились новые валидаторы `isDOMTypeElement()` и `isValidNotReactFragmentElement()`;
=> feat(usePatchChildren): opportunity to provide props

packages/vkui/src/hooks/useGlobalOnClickOutside.test.tsx, packages/vkui/src/hooks/useGlobalOnClickOutside.ts, packages/vkui/src/hooks/useStableCallback.test.ts, packages/vkui/src/hooks/useStableCallback.ts, packages/vkui/src/lib/createPortal.test.tsx, packages/vkui/src/lib/createPortal.ts, packages/vkui/src/lib/dom.test.ts, packages/vkui/src/lib/dom.tsx
- `useGlobalOnClickOutside()` – функция для отслеживания клика на обалсть вне целевых элементов.
- `useStableCallback()` – подобие `React.useCallback()`, но без второго аргумента с `deps`.
- `createPortal()` – внутри сразу фолбечит на `document.body`. Использую в `useFloatingWithIteractions()`.
> **Note**
>
> Из-за особенности работы `iframe` в Styleguide, `document.body`, полученный даже через `document` из `getDOM()`, соответствует корневому элементу, а не тому, что в `iframe`. Создал функцию `getDocumentBody()`, с помощью которой нужно получать `document.body` и передавать в `createPortal()`.
- block #2523
=> feat: create utilities functions

packages/vkui/src/hooks/useEnsuredControl.test.tsx, packages/vkui/src/hooks/useEnsuredControl.ts
Добавляем возможность менять состояние через функцию, как в `React.useState()`.
В `preservedControlledValueRef` запоминаем текущее значение для случая когда состояние управляется пользователем. В этом случае мы вызываем функцию передав туда `preservedControlledValueRef`.
- related to #2523
=> feat(useEnsuredControl): opportunity to use dispatch fn for change state

packages/vkui/src/components/AppRoot/AppRootPortal.tsx, packages/vkui/src/components/AppearanceProvider/AppearanceProvider.tsx, packages/vkui/src/components/Textarea/Textarea.e2e-playground.tsx, styleguide/Components/Preview.js, styleguide/config.js, styleguide/pages/migration_v6.md, styleguide/pages/platforms_and_themes.md
В остальные провайдеры (`PlatformProvider`, `LocaleProvider`) прокидываем `value`, для консистентность нужно сделать также для  `AppearanceProvider`
Заменила проп + добавила ссылку на гайд миграции в стайлгайде
=> BREAKING CHANGE(AppearanceProvider): replace appearance with value

packages/vkui/src/components/ActionSheet/ActionSheet.stories.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx, packages/vkui/src/components/ActionSheet/ActionSheetDefaultIosCloseItem.tsx, packages/vkui/src/components/ActionSheet/Readme.md, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx, packages/vkui/src/components/ActionSheetItem/Readme.md, packages/vkui/src/components/Alert/Alert.stories.tsx, packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Alert/AlertActions.tsx, packages/vkui/src/components/Alert/Readme.md, packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx, styleguide/Components/Setting/Setting.js, styleguide/pages/migration_v6.md
Сейчас в айтемы `ActionSheet` и `Alert` необходимо каждый раз пробрасывать `autoClose=true`, чтобы при клике на айтем элемент скрывался, кажется, логичнее будет сделать это поведением по-умолчанию.
Добавлен проп `autoCloseDisabled`, который наоборот позволяет отключить автоматический вызов `onClose` у родительского элемента
=> BREAKING CHANGE(ActionSheet, Alert): remove autoClose

packages/vkui/src/components/FocusTrap/FocusTrap.tsx, packages/vkui/src/lib/dom.test.ts, packages/vkui/src/lib/dom.tsx, packages/vkui/src/lib/floating/adapters.ts, packages/vkui/src/lib/floating/index.ts, packages/vkui/src/lib/floating/types.ts, packages/vkui/src/lib/floating/useFloatingMiddlewaresBootstrap/index.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/__snapshots__/useFloatingWithInteractions.test.tsx.snap, packages/vkui/src/lib/floating/useFloatingWithInteractions/constants.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/index.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/useResolveTriggerType.test.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/useResolveTriggerType.ts, packages/vkui/src/testing/utils.tsx
- В `lib/floating` создал хук `useFloatingMiddlewaresBootstrap`, где вынес сборку миддлваров для `useFloating()` в единое место.
- В `lib/floating` создал хук `useFloatingWithInteractions()`, который реализует интерактивное поведение для всплывающих элементов. А именно открытие/скрытие на `focus`, `click` и `hover`. Можно комбинировать. Также добавил `manual`, который позволит полностью самому управлять показом/скрытием.
Заложил логику для обработки CSS анимаций
> **Note**
> Учитываю, что у пользователя анимация может быть системна отключена. Проверяю через событие `onAnimationStart` была ли анимация при открытии.
Изменения нужны для issue:
- block #2523 
По ходу дела пошатал `FocusTrap`, получилось сделать его полегче, из изменений:
- Добавил параметр `autoFocus`.
- Параметр …
=> feat: extend lib/floating

README.md, package.json, packages/vkui/package.json, packages/vkui/src/components/View/Readme.md, packages/vkui/src/components/View/View.stories.tsx, packages/vkui/src/index.ts, packages/vkui/src/types.ts, styleguide/pages/migration_v6.md, styleguide/pages/platforms_and_themes.md, styleguide/pages/quick_start.md, yarn.lock
- close #6169
---
Удаляем зависимость и его упоминания везде, кроме `integrations_vk_mini_apps.md`.
Также удалил `@vkontakte/icons` из инструкции по установке (см. #5718).
=> feat: rm legacy vk-bridge

packages/vkui/src/components/Header/Header.stories.tsx, packages/vkui/src/components/Header/Header.test.tsx, packages/vkui/src/components/Header/Header.tsx, packages/vkui/src/components/Header/Readme.md, styleguide/pages/migration_v6.md
- related #4696
---
Компонент `Header` позволяет задать текст `subtitle`, но не позволяет поменять тип элемента в котором этот текст будет отрендерен.
Добавляем новый проп `subtitleComponent`.
Надо ли менять значение по умолчанию свойства `Component` у `Header` с `h2` на `span`? 
~Этот компонент не используется внутри других компонентов у нас. Может быть и лишнее.~
Ответ: 
Лучше не трогать значение по умолчанию.
=> feat(Header): Allow to change subtitle component

packages/vkui/src/components/FormItem/FormItem.test.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, styleguide/pages/migration_v6.md
- related #4696 
---
Так как использование `h5` как тега по умолчанию может повредить доступности мы меняем значение тега по умолчанию для свойства `top`. Теперь это `span`, если не задан `htmlFor` или `topComponent`. 
Добавили новое свойство `topComponent`, чтобы дать возможность менять `тэг` `top`.
=> feat(FormItem): Allow to change default tag for top prop

packages/vkui/src/components/Popover/Popover.module.css, packages/vkui/src/components/Popover/Popover.stories.tsx, packages/vkui/src/components/Popover/Popover.test.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/components/Popover/Readme.md, packages/vkui/src/index.ts, packages/vkui/src/lib/accessibility.test.ts, packages/vkui/src/lib/accessibility.ts, packages/vkui/src/lib/cssAnimation/fades.ts, packages/vkui/src/lib/cssAnimation/index.ts, packages/vkui/src/lib/cssAnimation/transformOrigin.ts, packages/vkui/src/styles/animationFades.module.css, packages/vkui/src/styles/transformOriginByPlacement.module.css
- close #2523
---
- пошатал API
- `action` -> `trigger`
- `showDelay`/`hideDelay` -> `hoverDelay`
- `content` – теперь может быть функцией
- `offsetDistance` -> `offsetByMainAxis`
- `offsetSkidding` ->  `offsetByCrossAxis`
- новый API
- `autoFocus`
- `noStyling`
- `usePortal`
- поправил доку
- добавил информацию про доступность
- вынес анимации из стилей в `lib/animation`.
> В ней создал мапу с базовыми анимациями. Сами анимации описываю в `styles/*.module.css`.
<details><summary>Видео Popover</summary>
<p>
https://github.com/VKCOM/VKUI/assets/5850354/0372b7b4-f6dd-4242-a61e-168b63cbca67
</p>
</details> 
- Создал функцию `injectAriaExpandedPropByRole`, который добавляет в пропы `aria-expanded` с тоглом значения
=> [BREAKING CHANGE] feat(Popover): mv to stable

packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/hooks/useKeyboardInputTracker.test.ts, packages/vkui/src/hooks/useKeyboardInputTracker.ts, packages/vkui/src/lib/accessibility.ts
- Заменил `useState` на `useRef`, чтобы оптимизировать рендер. В `AppRoot` использую getter, чтобы по коду не пришлось менять на `keyboardInput.current`.
- Оптимизируем подписку на события: вместо нескольких `useGlobalEventListener`, которые порождают по два эффекта внутри, используем один и разом подписываем/отписываемся. Обработчики переносим в этот эффект.
- Рефактор `lib/accessibility`: массив с ожидаемыми кодами кнопок переделал на `Map`, тем самым упростилась `pressedKey()`. Создал `isKeyboardFocusingStarted()`, которую использую в `useKeyboardInputTracker()`.
---
- block #2518
=> refactor: useKeyboardInputTracker()

packages/vkui/src/hooks/useDraggableWithDomApi/useDraggableWithDomApi.ts, packages/vkui/src/hooks/useDraggableWithDomApi/utils.ts
В **React 18** периодически, по-крайней мере у меня, `onDragMove` вызывается дважды при начале перетаскивания, из-за чего дважды срабатывает `initializeItems()`, в конечном итоге и функция `setInitialPlaceholderItemStyles()`.
У @BlackySoul каждый раз `onDragMove` срабатывает джажды.
<details><summary>Видео с воспроизведением от @BlackySoul</summary>
<p>
https://github.com/VKCOM/VKUI/assets/5850354/8d010f2c-a4f4-4497-9a79-69a866dc362d
</p>
</details> 
- related to #5833
- related to #6010
- `dragging` в `true` теперь выставляем через функцию в `setDragging()`, в аргументы которого мы можем получить следующую транзакцию состояния и проверять не `true` ли уже.
- В `setInitialPlaceholderItemStyles()` дополнительно проверяем нет вставлен ли уже элемент.
=> fix(useDraggableWithDomApi): placeholder double render (React 18)

packages/vkui/src/components/ChipsInput/Readme.md, packages/vkui/src/components/ChipsInputBase/Chip/Chip.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsInputBase/constants.tsx, packages/vkui/src/components/ChipsInputBase/types.ts, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
- relates to https://github.com/VKCOM/VKUI/pull/6139
- relates to https://github.com/VKCOM/VKUI/pull/6206
Несу Иному часть, связанную с чипами, из задачи про `aria-label`.
=> fix(ChipsSelect): aria-label fixes for #6206

styleguide/Components/Modals/Versions.js
В запросе в NPM для получения информации о пакете, починили сжатие для запроса с заголовком `application/vnd.npm.install-v1+json`. По этому заголовку возвращается более урезанная информация по пакету.
По размеру на **~100 kb** запрос стал легче:
```diff
- 441 kb
+ 339 kb
```
- related to #5500
- https://github.com/npm/feedback/discussions/749
=> docs(styleguide): use gzipped https://registry.npmjs.org/@vkontakte/vkui req

packages/vkui/src/components/Clickable/Clickable.tsx
Убираем свойства, которые не требуются для DOM
=> fix(NonClickable): props not for dom

packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx
- close #6175 
---
Добавили свойство `dismissButtonTestId` для передачи `testId` в `dismissButton`.
=> feat(Alert): Add prop to pass data-test-id to Alert dismiss button

packages/vkui/src/components/CalendarRange/CalendarRange.stories.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.stories.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
- close #6214 
---
- Правим пример в сторибуке, чтобы DateRangeInput реагировал на изменения дат.
- исправляем поведение при выборе даты, если value={[null, null]}. В этом случае onChange возвращал всегда [null, null], что бы мы не выбрали в DateRangeInput.
Временное решение без этого фикса это передавать `undefined`. Будет актуально для v5, если не выпустим там патч.
- Меняем тип value c Array на Tuple, так как value может содержать только два элемента.
=> fix(DateRangeInput): Treat array of nulls as empty value to set start date on click

packages/vkui/src/hooks/useAutoDetectAppearance.test.ts, packages/vkui/src/hooks/useAutoDetectAppearance.ts
- close #6240
---
Не учёл, что `useState()` вызывается и на сервере. Первое, что может придти в голову – это проверять в `useState` существует ли `window`, но так сделать не можем, т.к. на клиенте, если пользователь не передал `appearance`, то условие отработает удовлетворительно и в первый мы получим автоматическое определение `appearance`, тем самым у нас уже будет разница между клиентом и сервером.
В `useState` теперь возвращаем либо пользовательский `appearance`, либо `'light'` по умолчанию.
В самом эффекте добавил условие для `window`, чтобы убрать неочевидный **Non-null Assertion Operator** (`!`).
---
- caused by #5868
=> fix(useAutoDetectAppearance): rm window from useState

packages/vkui/src/components/PopoutWrapper/PopoutWrapper.test.tsx, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.tsx, packages/vkui/src/components/PopoutWrapper/Readme.md, styleguide/pages/migration_v6.md
- close #4314
---
Теперь, при использовании `PopoutWrapper` напрямую, необходимо самостоятельно импортировать и вызывать `useScrollLock()` (см. https://github.com/VKCOM/VKUI/issues/4314).
- related to #4531
=> fix(PopoutWrapper): fix scroll blocked 

packages/vkui/src/components/PopoutRoot/PopoutRoot.test.tsx, packages/vkui/src/components/PopoutRoot/PopoutRoot.tsx
Из-за того, что `PopoutRootPopout` и `PopoutRootModal` не резолвили `className`, `TokensClassProvider` затирал их `className`.
Можно воспроизвести на странице https://vkcom.github.io/VKUI/6.0.0-beta.1/#/Group:
1. Прокручиваем до самого конца.
2. Нажимаем "Открыть Group в модальном окне".
=> fix(PopoutRoot): use className by props in Popout and Modal sub-cmp

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
- close #6268
---
Зануляем предыдущий стейт, чтобы модалка не разворачивалась в некоторых случаях на всю высоту
=> fix(ModalRoot): clean up stale state

packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/components/Slider/__image_snapshots__/slider-with-tooltip-slider-with-tooltip-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-with-tooltip-slider-with-tooltip-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Slider/__image_snapshots__/slider-with-tooltip-slider-with-tooltip-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Tappable/Tappable.tsx, styleguide/setup.js
https://github.com/VKCOM/VKUI/assets/7431217/e462c3cc-4612-40c3-9b8d-88f7459649e3
---
- caused by #6263
---
- Почему изменились скриншоты:
Для тогглика задаем обводку `outline: var(--vkui_internal--outline);`, но `--vkui_internal--outline` определена в `:root` у [constants.css](https://github.com/VKCOM/VKUI/blob/6b1683cf63c259598db487eb93c69e72803c45a8/packages/vkui/src/styles/constants.css), поэтому токен раньше скатывался в дефолтовый андроидовский, сейчас починился
- Почему добавили `import '../Clickable/Clickable.module.css'; // Reorder css`:
На `codesandbox`'e словила, что стили `Clickable` перебивали `Tappable`, не работал ховер, например
=> fix(AppRoot): bring back setting color-scheme

packages/vkui/src/components/FormLayout/FormLayout.tsx, packages/vkui/src/components/RootComponent/RootComponent.tsx, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.module.css, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css, styleguide/pages/migration_v6.md
- related #6160 
Не зацепили ещё пару TODOшек
`FormLayout` - просто удалили `getRef`
`SubnavigationBar` - немного изменили верстку, избавились от глобального класса
`RootComponent` - позволяю в `baseClassName` прокидывать `false` булик, чтобы не форсить прокидывание `undefined` при навешивании класса по условию (?)
_Кодмод под изменения завезу в следующем PRе_
=> fix: rest of TODO (FormLayout & SubnavigationButton)

.github/workflows/publish_prerelease.yml
Убираем майлстоун-галочку из пререлизного экшена, т.к. решили вместо майлстоунов использовать метки для пререлизов.
=> ci(publish_prerelease): remove close_milestone

packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
При `<HorizontalCell size="m" />` зашивалась ширина, в отличии от `<HorizontalCell size="s" />`.
- related to #1316 – в этом PR добавили `max-width` только для `size="s"`
=> fix(HorizontalCell): use max-width for size="m"

packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/hooks/useDateInput.ts
- close #6244
---
Немного поменял логику сброса программного фокуса. 
Функция для сброса вызывается при клике снаружи или при выборе даты, если используется свойство `closeOnChange`.
Но функция сброса внутри проверяет состояние календаря`open` и только если оно true, то фокус сбрасывается.
В #6244 как раз ситуация, когда по клику на кнопку "Готово", мы закрываем попап календаря, но фокус не убираем. Потом кликаем по другой кнопке, это как раз "click outside", но фокус не сбрасывается, потому что `open` ужe `false`.
Переделал проверку с `open` на `focusedElement`.
Работать будет аналогично, но и фокус сбрасываться будет более предсказуемо и всегда при вызове `resetFocusFormField` если фокус установлен.
=> fix(DateInput): Clear DateInput focus when click Done button

packages/vkui/src/components/View/View.test.tsx, packages/vkui/src/components/View/View.tsx
- close #6320
---
Мы очень хитро восстанавливаем позицию скролла, надеясь на то, что это всегда будет работать в useEffect, который сработает перед обработкой события transition (перед завершением анимации), где окончательно сбросятся все состояния.
Но в случае, если пользователь вернул панель назад, мы просто сбрасываем состояние компонента, отвечающее, за свайп. Логика, отвечающая за восстановление скролла не срабатывает, потому что это не считается как `failure`.
Вот тут мы решаем `swipeBack` был успешным (`success`), был отменён (`fail`), то есть свайп не закончен, либо это вообще не считается свайпом, потому что панель по завершении жеста осталась на той же позиции.
https://github.com/VKCOM/VKUI/blob/a4719b49f887c2584eec6655d72e373e62409c59/packages/vkui/src/components/View/View.tsx#L …
=> fix(View): Restore scroll position on swipe back cancel

package.json, stylelint.config.js, tools/stylelint-bad-multiplication/index.js, tools/stylelint-bad-multiplication/jest.config.js, tools/stylelint-bad-multiplication/jest.setup.js, tools/stylelint-bad-multiplication/package.json, yarn.lock
- blocked by https://github.com/VKCOM/stylelint-config/pull/238
- caused by #6303, #6304
Сейчас обновление до **Stylelint v16** затруднено из-за плагинов, которые ещё не поддерживают эту версию:
- `stylelint-value-no-unknown-custom-properties` (https://github.com/csstools/stylelint-value-no-unknown-custom-properties/issues/39)
- `stylelint-use-logical` (https://github.com/csstools/stylelint-use-logical/pull/22)
Следующие плагины поддерживают **Stylelint v16**, но обратно несовместимы со **Stylelint v15**:
- `stylelint-config-standard`
- `stylelint-media-use-custom-media`
Обновил их и `stylelint` до последних версий, но в `"resolutions"` сбрасываю под **Stylelint v15**:
```json
"resolutions": {
"stylelint": "15.11.0",
"stylelint-config-standard": "34.0.0", …
```
=> bump(deps): prepare for Stylelint v16

packages/vkui/src/components/Input/Readme.md
В `ExampleWithIcon`, для полноты картины, не хватало `textInput.current.focus();`.
=> docs(Input): textInputRef.focus() when clear()

README.md
В https://www.npmjs.com/package/@vkontakte/vkui/v/beta сейчас не релевантные ссылки.
Перед релизом `v6` надо будет удалить пути до `v6.0.0-beta.*` (оставил **TODO**).
Также заменил `ВКонтакте` на `VK`.
---
- related to #6257
=> fix(README.md): update doc links to v6.0.0-beta.3

packages/vkui/src/components/Switch/Switch.module.css, packages/vkui/src/components/Switch/Switch.stories.tsx, packages/vkui/src/components/Switch/Switch.test.tsx, packages/vkui/src/components/Switch/Switch.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.module.css, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.test.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
- close #3046 
---
Действительно на Android в Talkback не видно фокуса при фокусировании на инпуте, потому что мы прячем этот инпут с помощью `VisuallyHidden` компонента.
Как вариант можно убрать использование VisuallyHidden и спрятать компонент позади визульной части.
- Добавил модификатор для VisuallyHidden, когда речь идет о `Component=input`. Явно задал размер равный размеру родительского элемента, чтобы выделение визуально было подобно размеру switch. Но изменение затронуло не только Switch, но и другие компоненты, в которых `<VisuallyHidden Component="input" \>`.
- добавил `role='switch'`
- добавил `aria-checked`. Так как значение этого аттрибута должно соответствовать значению инпута, то добавил переменную состояния.
- обновил пример в Storybook, добавив историю с испольованием …
=> fix(Switch): show focus in android talkback

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- close #6371 
---
В старой реализации CustomSelect (v5.9.3) мы передавали required на div, тем самым он вообще не был задействован в обработке формы.
В v5.10.0 мы поломали это поведение и `required` стал передаваться на input, используемый для поиска. 
Исправляем это передавая `required` на спрятанный нативный селект.
=> fix[CustomSelect]: Pass required prop to native select instead of search input

packages/vkui/src/components/Tappable/Tappable.tsx
Добавляем type="button" по умолчанию для `<button>` компонентов
- fix #6370
- caused by #6132
=> fix: defaultButtonComponentProps

packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/Link/Link.tsx
Добавляем onClick=noop по умолчанию для Button и Link чтобы компонент был кликабельным
- caused by https://github.com/VKCOM/VKUI/pull/6132
- related to https://github.com/VKCOM/VKUI/issues/3599
=> fix: button add onClick = noop

packages/vkui/src/components/Image/Readme.md, packages/vkui/src/components/ImageBase/ImageBaseOverlay/ImageBaseOverlay.tsx, packages/vkui/src/components/RichCell/Readme.md
- close #6284 
- caused by https://github.com/VKCOM/VKUI/pull/6132
Убираем из примеров `RichCell` проп `disabled`, потому что без `onClick` компонент и так неактивный
В `ImageBaseOverlay` устанавливаем по умолчанию `onClick=noop` в режиме `on-hover`, потому что хотим, чтобы он реагировал на наведение.
=> fix(RichCell, ImageBaseOverlay): add noop default + remove disabled prop

packages/vkui/src/components/ChipsInput/ChipsInput.stories.tsx, packages/vkui/src/components/ChipsInput/useChipsInput.ts, packages/vkui/src/components/ChipsInputBase/Chip/Chip.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.module.css, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsInputBase/constants.tsx, packages/vkui/src/components/ChipsInputBase/helpers.ts, packages/vkui/src/components/ChipsInputBase/types.ts, packages/vkui/src/components/ChipsSelect/ChipsSelect.module.css, packages/vkui/src/components/ChipsSelect/ChipsSelect.stories.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/ChipsSelect/constants.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx, packages/vkui/src/lib/accessibility.ts, packages/vkui/src/lib/dom.tsx, packages/vkui/src/testing/utils.tsx
- close #4143
---
- ~[ ] Unit-тесты~ – снова отдельным PR, оставил `it.todo`.
- ~[ ] Гайд миграции~ – отдельным PR:
- добавить про удаление `inputLabel` (нужно использовать `FormItem`)
- добавить про удаление `getIconLabel`
> [!NOTE]
> см. https://github.com/VKCOM/VKUI/issues/4143#issuecomment-1884598384
>
> Добавил логику работы `ChipsInput`/`ChipsSelect` в описание задачи https://github.com/VKCOM/VKUI/issues/4143#user-content-logic.
Проверил `ChipsSelect` и `ChipsInput` в **NVDA** и нашёл причину почему он не видит компоненты – причиной был скрытый текст для визуальной доступности, который располагался прямо перед полем ввода. Оно осталось со старой реализации, думал так и надо. Я удалил этот скрытый текст, т.к. его содержание должно быть в атрибуте `placeholder`, который есть у …
=> fix(a11y): `ChipsSelect` and `ChipsInput`

packages/vkui/src/components/DatePicker/DatePicker.tsx
Eсли смотреть компонент `DatePicker` с переданным `monthNames` на тач устройствах, то cвойство `monthNames` встает html-аттрибутом. В режиме локальной разработки есть реакт-варнинг.
Не передаем `monthNames` в компоненты ниже `NativeDatePicker`.
=> fix(NativeDatePicker): Exclude monthNames prop from passed props

packages/vkui/src/components/WriteBarIcon/WriteBarIcon.test.tsx, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
- close #6383 
---
Предупреждение о том, что у WriteBarIcon отсутствует текстовое описание выводится даже если текстовое описание есть.
В v6 эта проблема решена.
- Поправил проверку пропсов
- добавил тестов
У PR базовая ветка v5.
=> fix(WriteBarIcon):  [v5] update missing label warning logic

packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx
Переносим из v6 в v5.
PR: #6222
=> feat(Alert): Add prop to pass data-test-id to Alert dismiss button (cherry-picked from #6222)

packages/vkui/src/components/View/View.test.tsx, packages/vkui/src/components/View/View.tsx
Cherry-picked в v5 из v6. #6325
related: https://github.com/VKCOM/VKUI/issues/6320
=> fix(View): Restore scroll position on swipe back cancel (cherry-picked from #6325)

packages/vkui/src/hooks/useDraggableWithDomApi/useDraggableWithDomApi.ts, packages/vkui/src/hooks/useDraggableWithDomApi/utils.ts
Это cherry-pick из #6187, из v6 в v5.
В **React 18** периодически, по-крайней мере у меня, `onDragMove` вызывается дважды при начале перетаскивания, из-за чего дважды срабатывает `initializeItems()`, в конечном итоге и функция `setInitialPlaceholderItemStyles()`.
У @BlackySoul каждый раз `onDragMove` срабатывает джажды.
<details><summary>Видео с воспроизведением от @BlackySoul</summary> <p>
https://github.com/VKCOM/VKUI/assets/5850354/8d010f2c-a4f4-4497-9a79-69a866dc362d
</p>
</details> 
- `dragging` в `true` теперь выставляем через функцию в `setDragging()`, в аргументы которого мы можем получить следующую транзакцию состояния и проверять не `true` ли уже.
- В `setInitialPlaceholderItemStyles()` дополнительно проверяем нет вставлен ли уже элемент.
=> fix(useDraggableWithDomApi): placeholder double render (React 18) (cherry-picked from #6187)

packages/vkui/src/hooks/useDateInput.ts
Это cherry-pick из #6312, из v6 в v5.
Немного поменял логику сброса программного фокуса.  Функция для сброса вызывается при клике снаружи или при выборе даты, если используется свойство `closeOnChange`. Но функция сброса внутри проверяет состояние календаря`open` и только если оно true, то фокус сбрасывается. В #6244 как раз ситуация, когда по клику на кнопку "Готово", мы закрываем попап календаря, но фокус не убираем. Потом кликаем по другой кнопке, это как раз "click outside", но фокус не сбрасывается, потому что `open` ужe `false`.
Переделал проверку с `open` на `focusedElement`.
Работать будет аналогично, но и фокус сбрасываться будет более предсказуемо и всегда при вызове `resetFocusFormField` если фокус установлен.
=> fix(DateInput): Clear DateInput focus when click Done button (#6312)

packages/codemods/src/transforms/__tests__/__snapshots__/chips-input.ts.snap, packages/codemods/src/transforms/chips-input.ts
После #6367 `inputLabel` (a.k.a `inputAriaLabel`) был удалён. Вместо него нужно использовать либо `placeholder`, либо оборачивать в `FormItem`.
- caused by #6367
=> codemode(chips-input): mv inputAriaLabel to placeholder

packages/vkui/src/components/Switch/Switch.stories.tsx, packages/vkui/src/components/Switch/Switch.test.tsx, packages/vkui/src/components/Switch/Switch.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.module.css, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.test.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
Это cherry-pick из #6365, из v6 в v5.
Действительно, на Android в Talkback не видно фокуса при фокусировании на инпуте, потому что мы прячем этот инпут с помощью `VisuallyHidden` компонента. Как вариант можно убрать использование VisuallyHidden и спрятать компонент позади визульной части.
- Добавил модификатор для VisuallyHidden, когда речь идет о `Component=input`. Явно задал размер равный размеру родительского элемента, чтобы выделение визуально было подобно размеру switch. Но изменение затронуло не только Switch, но и другие компоненты, в которых `<VisuallyHidden Component="input" \>`.
- добавил `role='switch'`
- добавил `aria-checked`. Так как значение этого аттрибута должно соответствовать значению инпута, то добавил переменную состояния.
- обновил пример в Storybook, добавив историю …
=> fix(Switch): Show focus in android talkback (#6365)

packages/vkui/src/components/CalendarRange/CalendarRange.stories.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.stories.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
Это cherry-pick из #6215, из v6 в v5.
- Правим пример в сторибуке, чтобы DateRangeInput реагировал на изменения дат.
- исправляем поведение при выборе даты, если value={[null, null]}. В этом случае onChange возвращал всегда [null, null], что бы мы не выбрали в DateRangeInput. Временное решение без этого фикса это передавать `undefined`. Будет актуально для v5, если не выпустим там патч.
- Меняем тип value c Array на Tuple, так как value может содержать только два элемента.
=> fix(DateRangeInput): Treat array of nulls as empty value to set start date on click (#6215)

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Это cherry-pick из #6373, из v6 в v5.
В старой реализации CustomSelect (v5.9.3) мы передавали required на div, тем самым он вообще не был задействован в обработке формы. В v5.10.0 мы поломали это поведение и `required` стал передаваться на input, используемый для поиска. 
Исправляем это передавая `required` на спрятанный нативный селект.
=> [CustomSelect]: Pass required prop to native select instead of search input (#6373)

packages/vkui/src/components/DatePicker/DatePicker.tsx
Это cherry-pick из #6386, из v6 в v5.
Eсли смотреть компонент `DatePicker` с переданным `monthNames` на тач устройствах, то cвойство `monthNames` встает html-аттрибутом. В режиме локальной разработки есть реакт-варнинг.
Не передаем `monthNames` в компоненты ниже `NativeDatePicker`.
=> [DatePicker]: Exclude monthNames prop from passed props to NativeDatePicker (#6386)

packages/vkui/src/components/DatePicker/DatePicker.tsx
базовая ветка v5.10-stable. В прошлом [PR](https://github.com/VKCOM/VKUI/pull/6409#issuecomment-1900109291) ошибся с тэгами и v5.10-stable не обновилась.
Eсли смотреть компонент `DatePicker` с переданным `monthNames` на тач устройствах, то cвойство `monthNames` встает html-аттрибутом. В режиме локальной разработки есть реакт-варнинг.
Не передаем `monthNames` в компоненты ниже `NativeDatePicker`.
=> Exclude monthNames prop from passed props to NativeDatePicker (#6386) (#6409)

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
базовая ветка v5.10-stable. В прошлом [PR](https://github.com/VKCOM/VKUI/pull/6408#issuecomment-1900109015) ошибся с тэгами и v5.10-stable не обновилась.
В старой реализации CustomSelect (v5.9.3) мы передавали required на div, тем самым он вообще не был задействован в обработке формы. В v5.10.0 мы поломали это поведение и `required` стал передаваться на input, используемый для поиска. 
Исправляем это передавая `required` на спрятанный нативный селект.
=> [CustomSelect]: Pass required prop to native select instead of search input (#6373) (#6408)

packages/vkui/src/components/Accordion/Accordion.module.css, packages/vkui/src/components/Accordion/AccordionContent.tsx
- Fixes #6414
---
~- [ ] Unit-тесты~
~- [ ] Дизайн-ревью~
~- [ ] Документация фичи~
margin-top при выставлении процентов берет значение от ширины, а не высоты
Для фикса бага используем max-height, вместо margin-top
=> fix(Accordion): use  max-height

packages/vkui/src/components/ChipsInput/Readme.md, packages/vkui/src/components/ChipsInput/useChipsInput.ts, packages/vkui/src/components/ChipsInputBase/Chip/Chip.test.tsx, packages/vkui/src/components/ChipsInputBase/Chip/Chip.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.module.css, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsInputBase/helpers.ts, packages/vkui/src/components/ChipsInputBase/types.ts, packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
- Добавил цикличную навигацию стрелками между чипами.
https://github.com/VKCOM/VKUI/assets/5850354/a849e56c-9912-4cd3-802a-97f224d9f03b
- Покрыл тестами `ChipsSelect`, `ChipsInputBase`, `Chip`.
- `Chip`
- теперь принимает `readOnly`. При его передаче, скрывается кнопка удаления чипа;
- для корректного произношения скринридером, добавил `&nbsp;` перед скрытым текстом `"Удалить <children>"`.
---
- related to #6367
=> feat(ChipsInputBase): add cycle navigates between chips

packages/vkui/src/components/SubnavigationBar/SubnavigationBar.test.tsx, packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx
- close #6111
---
Используем `hasReactNode(child)`, чтобы отфильтровать все пустые ноды
=> fix(SubnavigationBar): ignore falsy children

packages/vkui/src/components/TabsItem/TabsItem.module.css, packages/vkui/src/components/TabsItem/TabsItem.tsx
- closed #5879
---
Добавляем возможность прокидывать ссылку в TabsItem
=> feat(TabsItem): add anchor attributes

styleguide/Components/Editor/Editor.css
- close #3791
---
Исправляем такую работу подсветки в хроме:
https://user-images.githubusercontent.com/7431217/208252677-d69efc40-6d0b-4f16-8bb5-98d5b85dd06f.mov
Установка любого цвета, кроме `black` исправляет подсветку  ¯\ _(ツ)_/¯
=> docs: fix selection in chrome

packages/vkui/src/components/Radio/Radio.tsx
Иногда нужна возможность управлять `hover/active` состоянием компонента (например, при размещении его в ячейке таблицы)
Дает возможность пробросить свойства `'hoverMode' | 'activeMode' | 'hasHover' | 'hasActive' | 'focusVisibleMode'`
=> feat(Radio): extend by Tappablep props

packages/vkui/src/lib/dom.test.ts, packages/vkui/src/lib/dom.tsx
> [!NOTE]
>
> Также будет патч в `5.10.1`.
- close #6338
---
- ~e2e-тесты~
- ~Дизайн-ревью~
- ~Документация фичи~
Перебиваем `height` из `document.documentElement.getBoundingClientRect` на `document.documentElement.clientHeight`.
=> fix(Cell): patch client height of html (see `draggable` mode)

package.json, packages/vkui/src/components/Mark/Mark.e2e-playground.tsx, packages/vkui/src/components/Mark/Mark.e2e.tsx, packages/vkui/src/components/Mark/Mark.module.css, packages/vkui/src/components/Mark/Mark.stories.tsx, packages/vkui/src/components/Mark/Mark.test.tsx, packages/vkui/src/components/Mark/Mark.tsx, packages/vkui/src/components/Mark/Readme.md, packages/vkui/src/components/Mark/__image_snapshots__/mark-android-chromium-dark-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-android-chromium-light-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-ios-webkit-light-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-webkit-light-1-snap.png, packages/vkui/src/index.ts, styleguide/config.js, yarn.lock
Добавляем новый компонент Mark для выделений контекста
=> feat: add Mark

packages/vkui/src/components/AppRoot/AppRootPortal.test.tsx, packages/vkui/src/components/AppRoot/AppRootPortal.tsx
- close #6380 
---
В рефакторинге AppRootPortal в c7e4c410eaf9877f236d5d7e1cfda49352197daa мы инверсировали логику использования портала и там закралась ошибка в значении по умолчанию. До рефакторинга мы использовали портал если `mode !== 'full'`, 
https://github.com/VKCOM/VKUI/blob/7f1888d54ca8fb08a0a8d8d3697f0a19ccab6d19/packages/vkui/src/components/AppRoot/AppRootPortal.tsx#L35-L42
а теперь выключаем портал если `mode !== 'full'`.
https://github.com/VKCOM/VKUI/blob/959611e24e6168643ff409d8db08a585825d030f/packages/vkui/src/components/AppRoot/AppRootPortal.tsx#L38-L51
Эта ошибка повлекла за собой по крайней мере неверное позиционирование Snackbar, когда речь идёт о Snackbar + Tabbar у Epic в режиме миниапов (`mode="full"`). Snackbar рендерился используя портал, тем самым выпадая из …
=> fix(Snackbar/AppRootPortal): fix default shouldDisablePortalLogic in AppRootPortal

packages/codemods/src/transforms/__testfixtures__/tooltip-container/basic.input.tsx, packages/codemods/src/transforms/__testfixtures__/tooltip/basic.input.tsx, packages/codemods/src/transforms/__tests__/__snapshots__/tooltip-container.ts.snap, packages/codemods/src/transforms/__tests__/__snapshots__/tooltip.ts.snap, packages/codemods/src/transforms/__tests__/tooltip-container.ts, packages/codemods/src/transforms/tooltip-container.ts, packages/codemods/src/transforms/tooltip.ts, packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.test.tsx, packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx, packages/vkui/src/components/Popover/Popover.test.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/components/Popper/Popper.tsx, packages/vkui/src/components/Tooltip/Tooltip.test.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/lib/floating/index.ts, packages/vkui/src/lib/floating/types/common.ts, packages/vkui/src/lib/floating/types/component.ts, packages/vkui/src/lib/floating/usePlacementChangeCallback.ts, styleguide/pages/migration_v6.md
Принесли фидбэк по гайду миграции и codemod:
- У компонента Tooltip был проп arrow, в 6 версии у OnboardingTooltip его убрали. В гайде по миграции об этом не сказано, codemods тоже никак об этом не сообщает
- У Popover был проп onPlacementChange, в 6 версии его убрали. В гайде по миграции об этом не сказано, codemods тоже никак об этом не сообщает
- codemods не переименовывает TooltipContainer. В гайде не упоминается о переименовании TooltipContainer в OnboardingTooltipContainer
- Добавлен проп `disableArrow` у `OnboardingTooltip`, взамен `arrow` 
- у всех всплывающих элементов добавлен `onPlacementChange`, какой был в `v5`
- Добавлен `codemod` для переименовывания `TooltipContainer` в `OnboardingTooltipContainer` и замена пропа `arrow` на `disableArrow` в `Tooltip`
=> fix: Add popper changes for v6

packages/vkui/src/components/Tooltip/Tooltip.test.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx
- close #6216 
---
Мы действительно не использовали переданный `getRootRef` в компоненте, перетирая его значеним, необходимым для позиционирования тултипа.
В v6 такой проблемы нет. Поэтому этот фикс только для v5. Раз уж мы готовим для v5 релиз.
=> fix(Tooltip)[v5]: Merge getRootRef prop with floating ref and pass to BaseTooltip getRootRef

packages/vkui-floating-ui/index.mjs, packages/vkui-floating-ui/package.json
Поправил в `package.json` пути в `"exports"`.
После [@floating-ui/utils@0.2.0](https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Futils%400.2.0), изменилась структура папки `node_modules/@floating-ui/utils/`, из-за чего падает `swc.transformFile`, т.к. путь до нужного файла уже другой, а конкретно до `/node_modules/@floating-ui/utils/dom/dist/floating-ui.utils.dom.esm.js`. Теперь это `/node_modules/@floating-ui/utils/dom/floating-ui.utils.dom.esm.js`, либо `/node_modules/@floating-ui/utils/dist/floating-ui.utils.dom.esm.js` (в коде теперь использую именно этот).
```sh
node:internal/process/esm_loader:40
internalBinding('errors').triggerUncaughtException(
^
[Error: failed to load file
Caused by:
No such file or directory (os error 2)] {
code: 'GenericFailure'
} …
```
=> build(vkui-floating-ui): fix exports path

packages/codemods/package.json, packages/codemods/src/getAvailableCodemods.ts, packages/codemods/src/testHelpers/testHelper.ts, packages/codemods/src/transforms/__tests__/__snapshots__/text-tooltip.ts.snap, packages/codemods/src/transforms/__tests__/text-tooltip.ts
Исправляет порядок срабатывания трансформации `transforms/tooltip` и `transforms/text-tooltip` при использовании флага `--all`. До этого сначала срабатывал `transforms/text-tooltip` и заменял `unstable_TextTooltip` на `Tooltip` из-за чего `transforms/tooltip` перетирал `Tooltip` на `OnboardingTooltip`.
Под unit-тесты были сделано следующее:
- Вынес получение пути до **fixtures** в фукнцию `getTestFixturesInputPath`.
- Экспортирую `applyTransform` из `jscodeshift/dist/testUtils`.
- В `getAvailableCodemods` добавил фильтрацию и по `'.ts'` расширению.
=> fix(codemode): wait tooltip transform first before text-tooltip

styleguide/Components/Editor/Editor.css
- caused by #6447
На светлой теме исправилась подсветка, но на темной теме курсор терялся, подобрала более подходящий токен: 
https://github.com/VKCOM/VKUI/assets/7431217/3d5034fa-df17-409a-953c-6a67cb9ca6f2
https://github.com/VKCOM/VKUI/assets/7431217/189b0547-00f5-4fdd-9b35-fcef32132ed3
=> fix: Change editor color in doc

.github/workflows/pull_request_common.yml
Проверяем на `github.event.pull_request.state == 'open'`, чтобы `patch` добавлялся только при открытии PR. Бывает случае, что нам не нужен этот лейбел, мы его удаляем, но как только стоит запушить в ветку, то лейбел заново добавляется.
- caused by #5495
=> ci(pull_request_common): check to open state before add patch label

.github/workflows/dedupe_deps.yml
Сейчас PR от лица `github-action` не триггерит CI 
Заменяем гитхабовский токен на наш сервисный (как сказано в [этой дискуссии](https://github.com/orgs/community/discussions/65321))
=> chore: fix token for dedupe action

packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.module.css
- Fixes #6491
Тень ImageBase.Badge перекрывает события для компонентов внутри
добавлено pointer-events none
=> fix(ImageBase.Badge): shadow pointer-events none

packages/vkui/src/styles/dynamicTokens.css
Удаляем универсальный селектор из-за проблем с памятью. Выпиливаем переопределение цвета обводки
=> fix(dynamicTokens): rm universal selector

packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx, packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx, packages/vkui/src/lib/adaptivity/functions.ts
- close #6476 
---
- переделаны условия вычисления sizeY. 
- использованы идентичные с `useAdaptivityWithJSMediaQueries` функции из `lib/adoptivity/functions`.
Если `viewWidth` и `hasPointer` переданы, то мы вычисляем `sizeY`. Раньше мы вычисляли sizeY только если заданы оба пропа: `viewWidth` и `viewHeight`.
-`hasPointer`, передаваемый в контекст из `AdoptiveProvider` теперь используется в вычислении sizeY. Раньше мы этот проп не использовали, а брали hasPointer из библиотеки vkjs.
- переработаны тесты, чтобы сравнить результат `AdoptiveProvider` и `useAdaptivityWithJSMediaQueries`. Может и не очень честно так сравнивать, ведь `useAdaptivityWithJSMediaQueries` использует контекст `AdoptiveProvider`, но мы должны быть уверены, что результаты идентичны.
=> fix(AdaptivityProvider): calculate size y when viewWidth is provided

.github/actions/publish-workflow-1-setup/action.yml, .github/actions/publish-workflow-2-bump-version/action.yml, .github/actions/publish-workflow-3-validation/action.yml, .github/actions/publish-workflow-4-complete/action.yml, .github/actions/setup/action.yml, .github/workflows/publish_deploy.yml, .github/workflows/publish_prerelease.yml
Унифицируем воркфлоу под остальные пакеты.
Такое же решение применял в [vk-bridge/.github/workflows/publish_prerelease.yml](https://github.com/VKCOM/vk-bridge/blob/13d54fca1e5a5424da15c0bb91415cd9e78f17cd/.github/workflows/publish_prerelease.yml).
Вынес шаги с созданием документации в отдельный вокрфлоу, чтобы была возможность отдельно контролировать выпуск документации.
Сейчас, если в процессе паблиша упадёт сборка доки, то нельзя безопасно перезапустить её.
По умолчанию, запускается на успешное окончание `publish_prerelease.yml` (в дальнейшем и на `publish_release.yml`). В крайнем случае можно будет запустить вручную передав название пакета и версию.
Выносим некоторые общие шаги в отдельные пользовательские экшены. В дальнейшем будет шарится между `publish_prerelease.yml` и …
=> ci(publish_prerelease): unify the workflow for all packages; separates deploy part

.github/actions/publish-workflow-4-complete/action.yml, .github/workflows/publish_deploy.yml
1. Не добавил `shell: bash`:
> ❌ [publish](https://github.com/VKCOM/VKUI/actions/runs/7830906758/job/21366046530#step:6:1) /home/runner/work/VKUI/VKUI/./.github/actions/publish-workflow-4-complete/action.yml (Line: 69, Col: 7): Required property is missing: shell
2. Заменил в `publish_deploy.yml` переменную на статичный текст `@vkontakte/vkui`
---
- caused by https://github.com/VKCOM/VKUI/pull/6526
=> fix(.github/actions/publish-workflow-4-complete): add missed `shell: bash`

packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx, packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx, packages/vkui/src/lib/adaptivity/functions.ts
Это черри пик merge коммита bf26ee0145f26a1ea622d079b6349f06dc474812 из #6489 
Попытка перенести исправления в подсчёте `sizeY` у `AdoptivityProvider`.
Готов закрыть этот PR, если в изменениях нету большого смысла. Хотя [баг](https://github.com/VKCOM/VKUI/issues/6476) был именно для v5.
- в целом мы полностью переносим логику затрагивающую работу `AdoptivityProvider` без `bridge`.
В то же время логику c `bridge` мы не трогаем. В том числе оставляем *неявное* использование `_hasPointer` из `vkjs` и игнорирование `hasPointer` свойства `AdoptivityProvider`. Сделано специально, чтобы никак не затронуть пользователей bridge, ведь на них баг не распространяется.
https://github.com/VKCOM/VKUI/blob/f361335092b365360b3b8ee65c145fb6b621a414/packages/vkui/src/components/AdaptivityProvider/AdaptivityP …
=> patch(v5): pr6489

.github/actions/publish-workflow-4-complete/action.yml, .github/workflows/publish_deploy.yml, .github/workflows/publish_prerelease.yml
Упал `publish_deploy.yml` из-за ошибки в [actions/download-artifact@v4](https://github.com/actions/download-artifact/tree/v4/).
_https://github.com/VKCOM/VKUI/actions/runs/7831306942_
@mendrew подсказал причину – в экшон, помимо `run-id`, надо передать ещё и `github-token`.
- `.github/workflows/publish_deploy.yml`
- передаём `github-token` в `actions/download-artifact`;
- создаём новое поле `publish_type`, чтобы при ручном запуске можно было указать какой-то типа релиз (до этого была бы бага, что ни одна из джоб сборки док не сработала бы);
- в `run-name` учитываем, что воркфлоу может вызываться вручную.
- `.github/actions/publish-workflow-4-complete/action.yml`
- удалил несуществующий ключ `outputs` у `inputs`.
- `.github/workflows/publish_prerelease.yml`
- поднял поле `run-name` выше …
=> ci(publish_release, publish_deploy): fix workflows issues

styleguide/lib/theme/useLoadThemeTokens.js
Из-за завязки на `pending` внутри `useLoadThemeTokens` попадали на бесконечный цикл
https://github.com/VKCOM/VKUI/assets/7431217/597ec65b-0347-446b-9555-e392f45b9697
- caused by #6313
Убираем завязку на `pending`, кажется, что в случае чего `promiseRef.current !== null` будет достаточно
=> fix(docs): remove param from hook in useLoadThemeTokens

packages/vkui/src/components/PullToRefresh/PullToRefresh.stories.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx, packages/vkui/src/styles/common.css
- close #6530
---
Глобальный обработчик на `touchmove` влиял на поведение элементов с горизонтальным скроллом (например, `HorizontalScroll`) – нужно было проводить пальцем ровно по оси X, чтобы проскроллить по горизонтали.
<details><summary>Видео 1. Поправленный пример из issue6530</summary>
<p>
https://github.com/VKCOM/VKUI/assets/5850354/d3aa291f-6274-470b-9ccb-3e9e19e544ab
</p>
</details> 
После удаления проблемы, из-за которой был добавлен этот обработчик (#5967), не смог воспроизвести. Даже если такая проблема и есть, то думаю она не критичней, в отличие от блокировки горизонтального скролла. Удалил тест, который проверял глобальный обработчик, т.к. он больше не проходит.
Заодно поправил проблему, когда при работе спиннера можно было бы потянуть сверху вниз и вызвать нативный …
=> fix(PullToRefresh): rm global touchmove listener

packages/vkui/src/components/ChipsInput/useChipsInput.ts, packages/vkui/src/hooks/useNativeFormResetListener.test.tsx, packages/vkui/src/hooks/useNativeFormResetListener.ts
- related to #6561, #6560
- Создал хук `useNativeFormResetListener()`.
- Применил хук в `useChipsInput()`.
=> feat(ChipsInput/ChipsSelect): reset state after `form.reset()`

packages/vkui/src/lib/floating/adapters.ts
- close #5039 
---
Убираем лишнюю оптимизацию из логики обновления позиции плавающего элемента.
У нас была дополнительная проверка на вызов коллбэка `MutationObserver`, с помощью которой мы пропускали обновление попапа при первом вызове коллбэка.
На сколько мы обсудили с @inomdzhon эта проверка была добавлена как оптимизация, чтобы не допустить лишнего ререндера при маунте.
Судя по результатам исследования у нас нету такой проблемы с ререндером из-за `MutationObserver` и эту проверку мы можем просто убрать.
А убрать нам её нужно, потому что она не даёт правильно спозиционировать опции `ChipsSelect`, если селект находится внизу окна, тем самым опции рендерятся сверху селекта. Если пользователь сразу после фокуса на селекте вводит текст, который оставляет одну-две опции в списке, то …
=> fix(ChipsSelect): Remove initialUpdate logic from floating Mutation observer callback

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
- close #6242
Проблема лишнего места при изменении ориентации экрана в том, что это происходит когда модальное окно в режиме `expandable`. В этом режиме у `.ModalPage__content-in` `height` задано `100%` (изначально добавлено [тут](https://github.com/VKCOM/VKUI/pull/4625))
https://github.com/VKCOM/VKUI/blob/e935a7b8dfd2c9d9dbbb5937bd1decba859d45d1/packages/vkui/src/components/ModalPage/ModalPage.module.css#L121-L126
Из-за этих стилей высота контейнера контента становится равна высоте родительского элемента.
При этом, если высота контента в вертикальной ориентации экрана меньше чем высота экрана, то высота контейнера контента будет больше чем высота контента, что как раз и добавляет лишнее место снизу.
При изменении ориентации мы пересчитываем высоту, но селектор всё ещё работает и …
=> fix(ModalPage): Properly calculate content height in expanded mode

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
=> patch(v5): pr6538

.github/workflows/branch_test_coverage.yml, .github/workflows/pull_request_packages_deploy.yml
После обновления до **v4**, перестало выгружаться покрытие. Сбрасываем до **v3**.
- caused by #6500
- related to https://github.com/codecov/codecov-action/issues/1284
=> build(deps): Downgrade codecov/codecov-action from 4 to 3

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Забыл вовремя добавить label patch в https://github.com/VKCOM/VKUI/pull/6573
=> patch(v5.10-stable): pr6538

packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx, packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx, packages/vkui/src/lib/adaptivity/functions.ts
Забыл поставить `patch` в #6536
=> patch(5.10-stable): pr6489G

packages/vkui/src/components/ChipsInputBase/types.ts, packages/vkui/src/components/ChipsSelect/ChipsSelect.stories.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/ChipsSelect/Readme.md, packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
- close #6629 
---
Потерялся проп `disabled` для опции
Добавляем возможность указать `disabled` + накладываем такие же ограничения, как и в `Select`/`CustomSelect`, чтобы значение всегда было актуальным
=> fix(ChipsSelect): add disabled prop

packages/vkui/.eslintrc.js, packages/vkui/src/components/ContentCard/ContentCard.tsx, packages/vkui/src/components/ImageBase/ImageBase.tsx
- see https://togithub.com/facebook/react/issues/25682
---
Атрибут fetchPriority был добавлен в типизацию реакта, однако не вышло новой версии реакта, которая бы полноценно поддерживала данное свойство. В данный момент fetchPriority генерирует ворнинги.
Временно прокидываем `fetchpriority` как html свойство
=> fix: fetchPriority warning

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
- close #6635
---
Смотрим на предыдущее значение `expandable` для принятия решения по разворачиванию модалки - если изначально модалку нельзя было открыть на всю высоту, то оставляем её в свернутом состоянии
=> fix(ModalPage): account for prev expandable value

packages/vkui/src/components/ModalRoot/ModalRoot.tsx
=> patch(v5): pr6637

packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/AppRoot/ScrollContext.tsx
- close #6604
---
Если проскролить панель, открыть `ModalPage`, а затем из него `ActionSheet`, то скролл панели сбросится и мы увидим верхний контент страницы (за оверлеем).
Оказалось, что и `ModalPage` и `ActionSheet` используют один и тот же контекст при открытии для запрета скролла.
Но фукция, запрещающая скролл не проверяет, были ли он уже запрещён или нет.
Если он уже был запрещён, значит нужные отступы у body уже выставлены, и повторный запуск логики по запрету скролла неправильно перебивает отступы.
=> fix(ScrollContext): Fix scroll position after opening ActionSheet from ModalPage

packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.module.css, packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-webkit-light-1-snap.png
Растягиваем PullToRefresh по высоте, чтобы контент мог занимать всю высоту панели.
Одна из проблем была с `Placeholder` в режиме `stretched`, который переставал выравниваться по центру, если был обернут в `PullToRefresh`. Без жесткого кастома нельзя отцентрировать по вертикали `Placeholder` `stretched` при наличии `PullToRefresh`
Пример где `PullToRefresh` ломал поведение `Placeholder` https://codesandbox.io/p/sandbox/bold-feather-hfjx23
Раньше мы уже исправляли это в https://github.com/VKCOM/VKUI/commit/4a0f71301c110b86c5a1c0910726a98d534ab37c, но в какой-то момент поведение сломалось.
В v5 это тоже нужно занести.
=> fix(PullToRefresh): Stretch PullToRefresh horizontally

packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx, packages/vkui/src/components/TabsItem/TabsItem.tsx
- close #6330
---
- caused by #6009 
По умолчанию начинаем проставлять `hasHover=true`, поэтому ловим артефакты из issue #6330
"Обнуляем" `hover`-эффекты на `iOS`
=> fix(PanelHeaderButton, TabsItem): fix hover effect

styleguide/Components/Preview.js
- fix #4619
---
В мобильном представлении мы форсим скрытие параметров адаптивности (в частности `hasPointer`), поэтому просто запоминается последнее значение из контекста (по умолчанию `hasPointer=true`). Из-за этого на мобилках параметры адаптивности невалидные.  
В мобильном представлении убираем задание адаптивности (оно будет определяться автоматически)
=> docs: Auto detect hasPointer on mobile

packages/vkui/.storybook/addons/source-tab/SourceTab.tsx, packages/vkui/.storybook/addons/source-tab/constants.ts, packages/vkui/.storybook/addons/source-tab/register.tsx, packages/vkui/.storybook/main.ts, packages/vkui/.storybook/preview.ts, packages/vkui/src/components/Accordion/Accordion.tsx, packages/vkui/src/components/Accordion/AccordionContent.tsx, packages/vkui/src/components/Accordion/AccordionSummary.tsx, packages/vkui/src/components/Avatar/Avatar.tsx, packages/vkui/src/components/Avatar/AvatarBadge/AvatarBadge.tsx, packages/vkui/src/components/Avatar/AvatarBadge/AvatarBadgeWithPreset.tsx, packages/vkui/src/components/Image/Image.tsx, packages/vkui/src/components/Image/ImageBadge/ImageBadge.tsx, packages/vkui/src/components/ImageBase/ImageBase.tsx, packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.tsx, packages/vkui/src/components/ImageBase/ImageBaseOverlay/ImageBaseOverlay.tsx
Добавляем самописный аддон для отображения кода сториса компонента.
> [!NOTE]
> Аддон [Storysource](https://storybook.js.org/addons/@storybook/addon-storysource) не подошёл, т.к. он рендерит весь файл `*.stories.tsx` и не показывает выбранные в панели **Controls** параметры.
<details><summary>Пример работы с **Controls**</summary>
<p>
https://github.com/VKCOM/VKUI/assets/5850354/048103dd-c321-4592-9aac-85ed0cf59312
</p>
</details> 
- Выставил `Source`, по умолчанию.
- Для подкомпонентов добавил `displayName` – без этого они показывается не как св-во родительского компонента.
- В `.storybook/preview.ts` устанавливаем `parameters.docs.source.type` в `'dynamic'`, чтобы отображались сторис, `render()` которых без аргументов (см. [доку](https://storybook.js.org/docs/api/doc-block-source#type)). …
=> docs(storybook): add Source tab

packages/vkui/src/components/Select/Select.tsx
Исключаем передачу неиспользуемых `Select` пропсов в `NativeSelect`.
Вот бы это как-нибудь автоматически ловить.
=> fix(NativeSelect): Don't pass unused props to NativeSelect

packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
В `onChange` не передается `undefined`
=> fix(CalendarRange): onChange value is not undefined

packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
В `onChange` не передается `undefined`
---
- Это черипик из #6664 в v5
=> fix(CalendarRange): onChange value is not undefined (v5)

packages/vkui/src/components/DatePicker/DatePicker.tsx, packages/vkui/src/components/Select/Select.tsx, packages/vkui/src/types.ts
В тех местах, где при определённых условиях под капотом используется нативный компонент, мы, бывает, забываем исключать новые свойства необходимые только в кастомных компонентах. В итоге неспользуемые свойства оказываются в DOM. (https://github.com/VKCOM/VKUI/pull/6663, https://github.com/VKCOM/VKUI/pull/6386).
Добавил тип, как посоветовал @inomdzhon в https://github.com/VKCOM/VKUI/pull/6663#issuecomment-1983200842, чтобы при добавлении нового свойства линтер ругался если для нативного компонента это свойство не нужно.
=> Feat(Select, DatePicker): add type to catch unsupported props

packages/vkui/.storybook/preview.ts
В #6658 переносил св-во `expanded` из аддона `controls` в `docs`, думаю что параметр отвечает за приоритет открытия, а оказывается он совсем о другом =)
_из-за этого пропала описание во вкладке **Controls**_
В PR возвращаю как было.
- caused by #6658
=> docs(storybook): revert expanded prop for controls addon

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
- close #6661
---
Передаём `tabIndex={-1}` в `ScrollArrow`.
=> fix(HorizontalScroll): disable navigation to arrow by keyboard

packages/vkui/src/components/FocusTrap/FocusTrap.tsx
В сафари в открытой модалке при нажатии на <kbd>Esc</kbd> браузер переходит из развернутого в оконный режим
Вызываем `preventDefault` при нажатии на <kbd>Esc</kbd>
=> fix(FocusTrap): preventDefault on Escape

styleguide/Components/Frame/Frame.js, styleguide/setup.js
- closed #6686
Сейчас в стайлгайде иконки монтируются сразу при открытии страницы. Это было сделано для копирования иконок в Frame. Данный способ серьезно замедляет открытие страницы и также монтирует очень большое количество DOM нод
Избавился от монтирование иконок на старте и добавил обсервер на спрайт
LCP (замедление cpu x6, M1) 13 сек -> 5.5 сек
=> docs: don't mount icons on start

packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
Cкринридер читает заголовок с описанием слитно
Добавляем пробел для доступности
=> fix(CustomSelectOption): add nbsp

packages/vkui/src/components/File/File.tsx
- fixes #2562
Браузер для input type="file" пишет свой текст("Выберите файл"). Из-за этого скринридер прочитает сначала что написано в label, а потом что написано в title
Добавляем пустой title
=> fix(File): add empty title

packages/vkui/src/components/ButtonGroup/ButtonGroup.stories.tsx, packages/vkui/src/components/ButtonGroup/Readme.md, packages/vkui/src/components/Popover/Readme.md
=> docs: Button with icon add label

packages/vkui/src/components/FormStatus/FormStatus.tsx
- closed #4934
При появлении или изменении FormStatus, текст в нем не озвучивается
Добавляем роль `status` или `alert` в зависимости от `mode`
=> fix(FormStatus): add role=status or alert

styleguide/Components/TableOfContents/TableOfContents.js
Убираем `leading`/`trailing`-пробелы, чтобы поиск работал и при их наличии
=> fix(docs): trim search input

packages/vkui/.storybook/preview.ts, packages/vkui/scripts/postcss.js, packages/vkui/src/components/AppRoot/AppRoot.module.css, packages/vkui/src/storybook/VKUIDecorators.tsx
Добавляем для сторибука возможность переключать направление текста
https://github.com/VKCOM/VKUI/assets/14944123/e06f053b-057f-4a11-ba14-16c0729f68be
=> docs: add dir and writing mode

packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
- close #6715
---
На iOS мы вызываем `runRefreshing` внутри `onTouchMove` обработчика, который может вызываеться чаще чем обновляется состояние refreshing в стейте компонента.
https://github.com/VKCOM/VKUI/blob/78e4cb5a5fe44fda8bbe87d079156566b2aa6ce9/packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx#L222-L224
Это в свою очередь влечет за собой двойной вызов `onRefresh`.
- добавляем состояние вызова `runRefreshing()` через ref, чтобы избежать повторного вызова `runRefreshing`. Cбрасываем состояние в обработчике onTouchEnd().
Это локальная проблема конкретного условия, что runRefreshing() на iOS вызывается в определённый момент ещё до конца жеста, поэтому и ref используем только в одном месте.
=> fix(PullToRefresh): Prevent multiple calls of runRefreshing on iOS

packages/vkui/src/components/Input/Input.module.css, packages/vkui/src/components/Input/Input.tsx, packages/vkui/src/components/Textarea/Textarea.module.css, packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/components/UnstyledTextField/UnstyledTextField.module.css, packages/vkui/src/components/UnstyledTextField/UnstyledTextField.stories.mdx, packages/vkui/src/components/UnstyledTextField/UnstyledTextField.test.tsx, packages/vkui/src/components/UnstyledTextField/UnstyledTextField.tsx, packages/vkui/src/index.ts
- close #6496
---
- Не стал сбрасывать стили `color`, `font`, `box-sizing`, `display`, во избежание проблем с порядком загрузки стилей, ибо большая вероятность, что эти св-ва будут использованы пользователем (в нашем случае задаются в `Input` и `Textarea`). Свойство `padding` под тем же причинам вынес в `noPadding`, который по умолчанию `false`.
- Целенаправлено документацию создал только в сторибук, т.к. это сервисный компонент чисто для разработки.
=> feat: create `UnstyledTextField` component

packages/vkui/src/components/Search/Search.module.css, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png
- close #6719
---
На `iOS` кнопка в `after` выезжает если есть текст или фокус у инпута.
Но пока эта кнопка не видна, она всё ещё влияет на верстку `Search`, за счёт своих марджинов.
Задаём `margin` только когда кнопка видна. 
На анимацию появления это никак не повлияло.
Diff из Playwright для демонстрации до и после:
=> fix(Search): correct side margins of `after` element on iOS

.github/workflows/dedupe_deps.yml
Иногда требуется запустить дедупликацию зависимостей непосредственно в ветке (например, при обновлении зависимостей от `dependabot`)
Добавляем флажок `push_directly` для возможности запушить дедупликацию прямов выбранную ветку + шаги по коммиту и пушу
=> chore: dedupe on branch directly

packages/vkui/src/components/Panel/Panel.module.css
- close #6327 
---
- Чтобы была возможность применить градиент к фону `Panel` через токен используем свойство `background` вместо `background-color`.
- Убираем `Panel::before`, так как не несет за собой никакой функции. Описывая фон, её полностью перекрывает `Panel__in`, в том числе не видно разницы в режиме нескольких колонок, со скролом на странице, с разным значением `aria-inset`.
=> feat(Panel): Allow to use gradient in Panel background

packages/vkui/src/components/Panel/Readme.md
- caused by #6678
Из-за того, что перестали оборачивать пример с `Panel` в обертку, получали вот такую поехавшую верстку (ширина рассчитывалась относительно корневого `SplitCol`):
Убираем проп, который убирает обертку 🙃
=> docs: Fix Panel layout

yarn.lock
=> build(deps-dev): Bump webpack-dev-middleware from 6.1.1 to 6.1.2

packages/vkui/src/components/Snackbar/Snackbar.test.tsx, packages/vkui/src/components/Snackbar/Snackbar.tsx, packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
- close #6733 
Из-за того, что свойство `layout` играет роль только если не выполнено одно из условий (в том числе `isDesktop`), то задать желаемый `layout` для того чтобы `action` был на десктопе горизонтально невозможно. Хотя нам ничего не мешает сохранить условие, но дать приоритет именно значению переданному через свойство `layout`.
https://github.com/VKCOM/VKUI/blob/cb0cc188b4d543062312f518102da266c56533f9/packages/vkui/src/components/Snackbar/Snackbar.tsx#L171
=> feat(Snackbar): Let layout prop to take priority

packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx
- close #6727 
---
Даём возможность закрыть Alert по клику на action, если `autoCloseDisabled: true`, передавая `close` функцию как аргумент в вызов `action`.
=> feat(Alert): Pass close callback to action

packages/vkui/src/components/Popover/Popover.module.css, packages/vkui/src/components/Popover/Popover.test.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/index.ts
- close #6634
---
- ~[ ] Дизайн-ревью~ – компонента утилитарный, его нет в Figma
На подобии `OnboardingTooltip` и `Popper`, добавил параметр `arrow`, `arrowPadding`, `arrowHeight`, `arrowProps`, `ArrowIcon`.
При `noStyling` также отключаем покраску.
_Справа пример с `noStyling`, цвет работает через **currentColor** в SVG_
=> feat(Popover): support arrow

.github/workflows/deploy_docs_on_branch_push.yml
Добавляем экшон, который собирает доки (пока `styleguide`/`storybook`) на основе актуальной ветки `master` и деплоит их на `S3` (`url` будет всегда статичный)
Используем `dorny/paths-filter@v3` и стандартный `paths-ignore` для того, чтобы пересобирать доки, когда это действительно необходимо
=> ci: deploy next release docs

packages/vkui/src/components/DateInput/DateInput.tsx
- caused by #5866
---
В #5866 забыла прокинуть пропы именно на `DateInput`, хотя изначально оно для этого компонента и запрашивалось 🙈
=> fix(DateInput): add minDateTime & maxDateTime support

styleguide/Components/Preview.css, styleguide/Components/StyleGuide/StyleGuideRenderer.js
Попауты(например списки) могут быть выше чем заголовок документации.
Отключаем портал, изолируем плейграунд
=> docs(StyleGuide): disablePortal

styleguide/pages/migration_v6.md
Попросили добавить ещё один вариант для демонстрации случая, когда `ActionSheetItem` не прокидывал параметра `autoClose`
=> fix(doc): add example ActionSheetItem without autoClose prop

packages/vkui/src/components/TabsItem/TabsItem.tsx
- close #6849
---
Добавляем возможность прокидывать некоторые пропы от `Tappable`
=> feat(TabsItem): add Tappable props

packages/vkui/src/components/Mark/Mark.tsx, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.tsx, packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
- related to #6692
- добавляем `6.1.0` для `EllipsisText`
- удаляем префикс `v` у `Mark` и `VisualHidden`
=> docs: resolve @since comments

packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Clickable/Clickable.module.css, packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/Link/Link.module.css
- close #6503
---
Сбрасываем пропущенные св-ва по умолчанию (т.н. user agent). По задаче применялся `text-align: center`
Вынес некоторые св-ва сброса из `Button.module.css` и `Link.module.css` в `Clickable.module.css`, а также добавил недостающие:
- `appearance: none` – сбрасывает системные стили
- `-webkit-tap-highlight-color: none` – удаляет оверлей на кликабельных элементах в мобильных устройствах, в частности в Safari
- `-webkit-touch-callout: none` – отключает вызов контекстного меню
- `-webkit-user-drag: none` – отключает перетаскивание
=> fix(Button/Link): reset user-agent styles

packages/vkui/docker-compose.yml, packages/vkui/package.json
- удалил поле `version` в `docker-compose.yml`, т.к. оно устарело
```sh
WARN[0000] /packages/vkui/docker-compose.yml: `version` is obsolete 
```
- поправил NPM скрипт `docker:clear-playwright-cache` под изменение из #6717
=> tech(playwright): fix docker warns

packages/vkui/src/components/Epic/Epic.module.css
next.js при cssm сборке ругается на глобальный селектор без локального
>./node_modules/@vkontakte/vkui/dist/cssm/components/Epic/Epic.module.css:8:1
> Syntax error: Selector ":global(.vkuiInternalEpic--hasTabbar)" is not pure (pure selectors must contain at least one local class or id)
Добавляем локальный селектор
=> fix: selector global vkuiInternalEpic--hasTabbar is not pure

packages/vkui/src/components/ToolButton/Readme.md, packages/vkui/src/components/ToolButton/ToolButton.e2e-playground.tsx, packages/vkui/src/components/ToolButton/ToolButton.e2e.tsx, packages/vkui/src/components/ToolButton/ToolButton.module.css, packages/vkui/src/components/ToolButton/ToolButton.stories.tsx, packages/vkui/src/components/ToolButton/ToolButton.test.tsx, packages/vkui/src/components/ToolButton/ToolButton.tsx, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-android-chromium-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-android-chromium-light-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-ios-webkit-light-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-webkit-light-1-snap.png, packages/vkui/src/index.ts, styleguide/config.js
- close #6817
---
Добавляем новый вид кнопок
=> feat: add ToolButton

packages/vkui/src/components/ContentCard/ContentCard.tsx, packages/vkui/src/components/ImageBase/ImageBase.tsx, packages/vkui/src/lib/utils.ts
Сейчас ловим ворнинг:
Ожидалось, что с версией 18.3.* это пофиксится, но не случилось 
Ориентируемся на версию реакта при выборе наименования для пропа, чтобы поддержать обе версии 🙃
=> fix: fetchPriority React@19 support

packages/vkui/src/components/ToolButton/ToolButton.e2e-playground.tsx, packages/vkui/src/components/ToolButton/ToolButton.e2e.tsx, packages/vkui/src/components/ToolButton/ToolButton.test.tsx, packages/vkui/src/components/ToolButton/ToolButton.tsx
- caused by #6837
- caused by #6873
Убираем ненужный импорт `React`
=> fix: remove react useless imports

packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx, packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx, packages/vkui/src/components/ModalRoot/useModalManager.test.tsx, packages/vkui/src/components/NavTransitionDirectionContext/NavTransitionDirectionContext.test.tsx, packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.test.tsx, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.test.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx, packages/vkui/src/components/Root/Root.test.tsx, packages/vkui/src/components/Search/Search.test.tsx, packages/vkui/src/components/Slider/Slider.test.tsx, packages/vkui/src/components/Tabs/Tabs.test.tsx, packages/vkui/src/components/Textarea/Textarea.test.tsx, packages/vkui/src/components/View/View.test.tsx, packages/vkui/src/components/View/ViewInfinite.test.tsx, packages/vkui/src/helpers/getMergedSameEventsByProps.test.ts, packages/vkui/src/hooks/useAutoDetectAppearance.test.ts, packages/vkui/src/hooks/useBooleanState.test.tsx, packages/vkui/src/hooks/useFocusVisible.test.tsx, packages/vkui/src/hooks/useFocusVisibleClassName.test.ts, packages/vkui/src/hooks/useFocusWithin.test.tsx, packages/vkui/src/hooks/useKeyboardInputTracker.test.ts, packages/vkui/src/hooks/usePatchChildren.test.tsx, packages/vkui/src/hooks/useTimeout.test.ts, packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.test.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx, packages/vkui/src/testing/utils.tsx
- `act()` из `@testing-library/react` теперь `@deprecated` – рекомендуется использовать `act()` из `react`.
- отключил React варнинги в `Textarea` и `Search`, т.к. в тестах специально передаются `value` и `defaultValue` одновременно.
- в `Search` поправил варнинг, что не хватает вызова `act()`.
=> tech: fix jest deprecation and warnings

packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx, packages/vkui/src/lib/calendar.test.tsx, packages/vkui/src/lib/calendar.ts
- close #6921
---
В `dayjs` есть [проблемы](https://github.com/iamkun/dayjs/issues/2591) с годами `< 100`, поэтому ограничиваем нижнюю границу этим числом
Верхнюю границу ограничила `9999`, потому что есть проблемы с визуальным отображением на некоторых мобильных устройствах
=> fix(Calendar): restrict min and max years

packages/vkui/src/components/Calendar/Calendar.tsx
Пришли в чатик с вопросом о неработающем `minDateTime`. Причина была в одновременном применении `disablePast` и `minDateTime`.
Добавляем в документацию пояснение порядка применения пропов.
=> fix(DateInput): add docs clarification about disabled date

packages/vkui/package.json, packages/vkui/src/components/AppearanceProvider/AppearanceProvider.tsx, packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx, yarn.lock
Поддержка растровых иконок для icons пакета, значения провайдера может использоваться компонентами иконок для отображения нужного вида иконки в зависимости от темы
https://github.com/VKCOM/icons/pull/893
https://github.com/VKCOM/icons/releases/tag/%40vkontakte%2Ficons-scripts%404.2.0
https://github.com/VKCOM/icons/releases/tag/%40vkontakte%2Ficons-sprite%402.2.0
=> feat(ConfigProvider): raster icons support

packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/components/Popper/Popper.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/lib/floating/usePlacementChangeCallback.test.ts, packages/vkui/src/lib/floating/usePlacementChangeCallback.ts
- close #6889
---
Исправляем поведение хука `usePlacementChangeCallbace`, который вызывает `onPlacemenChange` коллбэк при автоматическом изменении свойства `placement`.
Из-за того, что `onPlacementChange` не всегда вызывался когда это требовалось мы получали неправильно отрендеренные границы у `CustomSelect`, потому что `CustomSelect` мог считать что `placement = "bottom"` когда на самом деле дропдаун уже отрисовывался сверху.
- Исправляем вызов коллбэка при первом рендере.
Для этого учитываем значение пропа `placement` переданного библиотеке `floating-ui`. Раньше мы его игнорировали и могло быть так, что при первом рендере `CustomSelect` ожидает, что `placement="bottom"`, а `floating-ui` уже решил, что `resolvedPlacement="top"`, но так как это первый рендер, то коллбэк не вызывается и …
=> fix(DatePicker, Popper, Popout): extend usePlacementChangeCallback logic

packages/vkui/src/components/Spacing/Spacing.e2e-playground.tsx, packages/vkui/src/components/Spacing/Spacing.e2e.tsx, packages/vkui/src/components/Spacing/Spacing.tsx, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-webkit-light-1-snap.png
- related https://github.com/VKCOM/VKUI/issues/6684
---
Добавляем к свойству size возможность передавать строковые значния размеров, соответствующие размерам из системы расстояний (#6684)
=> feat(Spacing): Use vkui-tokens in the Spacing component

packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/components/Popper/Popper.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/lib/floating/useFloatingMiddlewaresBootstrap/index.ts
- close #6917
---
Иногда требуется отключить автоматический расчет наиболее удачного расположения
Добавляем `disablePlacementFlip`, чтобы форсировать `placement`, отключая применение плагинов `flipMiddleware` и `autoPlacementMiddleware`
=> feat(Popover): add disablePlacementFlip prop

packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.module.css
- close #6857
Уменьшаем иконку "назад" в заголовке модалок на платформе vkcom.
=> feat(PanelHeaderBack): Change icon and icon color on vkcom

packages/vkui/src/components/Search/Search.test.tsx, packages/vkui/src/components/Search/Search.tsx
- close #6944 
---
Иконка крестика хранила предыдущий стейт, если изменение поля было "извне" + нашла, что так же не работает очистка через `form.reset`
Для `controlled`-варианта используем useIsomorphicLayoutEffect, чтобы засинкать значение, для `uncontrolled`-варианты используем хук `useNativeFormResetListener`
=> fix(Search): hides clear button with external changes

packages/vkui/src/hooks/useDraggableWithDomApi/autoScroll.test.ts, packages/vkui/src/hooks/useDraggableWithDomApi/autoScroll.ts
- caused by #5833
---
Удаляем проверку на OUTBOX_OFFSET, т.к. из-за неё не срабаывает автоскролл при уводе элемента за область видимости.
=> fix(Cell): rm OUTBOX_OFFSET

packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/index.ts
Добавляем экспорт `CustomSelectClearButtonProps`, нужный для кастомного компонента кнопки очистки.
=> feat(CustomSelect): export CustomSelectClearButtonProps

package.json, stylelint.config.js, tools/stylelint-plugin-vkui/.eslintrc.mjs, tools/stylelint-plugin-vkui/index.js, tools/stylelint-plugin-vkui/jest.config.js, tools/stylelint-plugin-vkui/jest.setup.js, tools/stylelint-plugin-vkui/package.json, tools/stylelint-plugin-vkui/rules/bad-multiplication/index.js, tools/stylelint-plugin-vkui/rules/bad-multiplication/index.test.js, tools/stylelint-plugin-vkui/rules/index.js, tools/stylelint-plugin-vkui/tsconfig.json, yarn.lock
Теперь все внутренние правила нужно писать в папке `tools/stylelint-plugin-vkui/rules`.
Используем `.eslintrc.mjs`, т.к. в `package.json` установлено `"type": "module"`.
---
В рамках PR #6979 начал добавлять новое правило и пришёл к такой структуре. Решил перенести в отдельный PR.
=> refactor(stylelint): mv to `tools/stylelint-plugin-vkui`

packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
- close #6915
---
Одновременное указание в качестве триггера `click` и `focus` приводило к проблеме, что всплывающее окно показывалось и сразу же скрывалось.
Игнорируем клик на элемент, если ранее был вызов события `focus`
=> fix(Popover): fix multiple trigger behavior

packages/vkui/src/components/Slider/Slider.test.tsx, packages/vkui/src/components/Slider/Slider.tsx, packages/vkui/src/components/Slider/SliderThumb/SliderThumb.module.css, packages/vkui/src/components/Slider/SliderThumb/SliderThumb.tsx
- close #5050
---
Добавляем состояние hover и active для Slider.
`active` состояние специально берётся и устанавливается на уровне `Slider`, а не в самих `SliderThumb`, потому что это даёт возможность установить активное состояние даже когда пользователь нажимает не на сам `Thumb` а на часть `Slider`.
https://github.com/VKCOM/VKUI/assets/5443359/e5b84f9e-0131-44c5-af98-d5c6f6ca0968
=> feat(Slider): Add active/hover states for Slider Thumb

packages/vkui/src/components/Select/Select.test.tsx, packages/vkui/src/components/Select/Select.tsx, packages/vkui/src/styles/adaptivity.module.css
Select рендерит сразу два поля
Используем `useAdaptivityConditionalRender` для скрытия лишнего поля
=> fix(Select): use conditional render

yarn.lock
=> build(deps-dev): Bump socks to 2.8.3

packages/vkui/src/components/AppRoot/AppRoot.module.css, packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/AppRoot/AppRoot.tsx, packages/vkui/src/components/AppRoot/helpers.ts, packages/vkui/src/components/AppRoot/types.ts, packages/vkui/src/components/Header/Header.module.css
- closes #3507, 
- closes #5216,
-  closes #6835
---
Добавляем возможность выставлять режим выделения текста с помощью свойства userSelectMode у AppRoot: 
- `disabled-in-webview` режим для приложений, которые встраиваются в webview, где нужен запрет на выделение, в то же время в мобильных браузерах выделение следует оставить. Теперь по умолчанию.
Если у приложения `isWebView=true` в ConfigProvider, то выделять текст будет запрещено.
- `enabled-with-pointer` режим в котором текст разрешается выделять только при наличии мыши. (То, что сейчас)
- `enabled` режим где выделять текст разрешено.
- `disabled` режим в котором выделать текст запрещается.
- убираем принудительно разрешение выделения Header. для #3507
- добавляем новое свойство `userSelectMode` для `AppRoot`.
- логику для работы …
=> feat(AppRoot): add userSelectMode

packages/vkui/src/components/Clickable/useState.tsx, packages/vkui/src/components/Tappable/Tappable.test.tsx
- fixes #6322
---
`lockState` блокировал обработку всех событий, из-за чего состояния не сбрасывались
Пробрасываем в хуки `lockState`  и не влияем на `hasHover` и `hasActive`
=> fix(Clickable): lockState block events

package.json, packages/vkui/scripts/postcss.js, packages/vkui/webpack.styles.config.js, yarn.lock
**PostCSS** >= 8.4.38 при импорте файлов со стилями из `@vkontakte/vkui`
```css
@import 'node_modules/@vkontakte/vkui/dist/components.css';
/* или */
@import 'node_modules/@vkontakte/vkui/dist/vkui.css';
```
пишет в консоль предупреждения
```
original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
```
Ругается на некорректный **source-map**. Вот пути до них:
```
node_modules/@vkontakte/vkui/dist/components.css.map
node_modules/@vkontakte/vkui/dist/vkui.css.map
```
Мы собираем выше упомянутые стили через **Webpack**. Но есть несколько нюансов:
- в **mode** используется значение `none`;
- CSS минифицируется через …
=> build(css): fix source-map generated by webpack

packages/vkui/src/components/Spacing/Spacing.e2e-playground.tsx, packages/vkui/src/components/Spacing/Spacing.module.css, packages/vkui/src/components/Spacing/Spacing.test.tsx, packages/vkui/src/components/Spacing/Spacing.tsx
Не применялся padding из-за невалидного `calc()`. Но так как в `calc()` было деление на `2px`, это не срабатывало. Также к числу `sizeValue` не добавлялась единица измерения (`px`), что тоже считается не валидным. 
❌ `calc(16 / 2px)`
❌ `calc(16px / 2px)`
✅ `calc(16px / 2)`
> [!NOTE]
> **React**, перед тем как применить стили, высчитывает `calc()` перед ставкой если можно.
> `calc(16px / 2)` → `calc(8px)`
Решил сразу перенести всё в CSS, потому что:
- можно использовать CSS logical с последующим фоллбеком;
- более явно видим какие **vkui-tokens** применяются;
- убираем логику пересчёта из JS.
В JS модифицируем входящие `className` и `style`, дабы не создавать дополнительные переменные. В случае такого простого компонента `Spacing` лишние операции ни к чему.
---
- caused by #6925
=> fix(Spacing): padding style wasn't applied

packages/vkui/scripts/generate_env_docker.sh
Утилита [jq](https://formulae.brew.sh/formula/jq) не является базовой утилитой, поэтому заменил на [cut](https://www.manpagez.com/man/1/cut/).
---
- caused by #6717
=> tech(generate_env_docker): mv `jq` to `cut`

packages/vkui/src/components/ToolButton/ToolButton.module.css, packages/vkui/src/components/ToolButton/ToolButton.tsx
При ширине >= 768px включается десктопный режим, в этот момент показывается иконка для десктопа. Для этой иконки применяется отступ справа – это создаёт визуальный баг когда не передан `children`.
Переносим отступ на контейнер для `children`, т.к. отступ нужен только тогда, когда он передан.
- добавил JSDoc для параметра `rounded`;
- убрал динамический ключ в объекте `sizeYClassNames`.
---
- caused by #6837
=> fix(ToolButton): mv gap to wrapper of children prop

packages/codemods/package.json, yarn.lock
- revert #7053
- see facebook/jscodeshift#589
=> revert: Bump jscodeshift from 0.15.2 to 0.16.0

packages/vkui/src/styles/focusVisible.module.css
В #6979 для теста менял на `2s` и случайно закоммитил.
Вернул `0.1s`.
#6979 ждёт релиза **v6.2.0**, поэтому фикс без майлстоун.
---
- caused by #6979
=> fix(focusVisible): revert animation duration

packages/vkui/src/components/ConfigProvider/ConfigProvider.test.tsx, packages/vkui/src/components/LocaleProvider/LocaleProvider.test.tsx, packages/vkui/src/components/PlatformProvider/PlatformProvider.test.tsx, packages/vkui/src/components/Popover/Popover.test.tsx, packages/vkui/src/hooks/useExternRef.test.tsx, packages/vkui/src/hooks/useFocusWithin.test.tsx
- see #6920
---
Используем  [`use no memo`](https://react.dev/learn/react-compiler#use-no-memo) для отключения компилятора в тестах
=> test: use no memo

packages/vkui/src/components/Popper/Readme.md
Компонент уже давно принимает `usePortal` а в доке всё ещё forcePortal.
=> docs: Replace forcePortal with usePortal

packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Tappable/Tappable.module.css
Убираем хак для Tappable с использованием `will-change: transform`. 
1. Это создаёт дополнительные композитные слои и нагружает браузер.
2. Это приводит к тому, что при переходе на страницу с большом количестве элементов с `Tappable` внутри, например, `SimpleCell`, наблюдаются блики элементов, видно как браузер старается снова перерисовать эти элементы. Отсутствие `will-change: transform` убирает такой эффект.
3. Этот хак был добавлен не для оптимизации анимации, а для того, чтобы исправить `border-radius: inherit` у `stateLayer` в iOS. В iOS скругление не работает. К сожаление и с этим хаком в последних версиях iOS, в том числе и в симуляторе, наблюдаются прямые углы у `Tappable` при наведении или при тапе, хотя они должны быть скругленными. …
=> fix(Tappable): Remove will-change hack from ripple effect layer

packages/vkui/src/components/Accordion/Accordion.module.css, packages/vkui/src/components/Accordion/Accordion.test.tsx, packages/vkui/src/components/Accordion/AccordionContent.tsx, packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.test.ts, packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.ts
- close #7045
---
Чтобы не зашивать `max-height`, устанавливаем его тогда, когда нужно (с переходом с `transition` на `animation` заменил на использование `height`). Сделал для удобства, через CSS переменную, которую добавляем/удалям в `useLayoutEffect()` относительно `animationState`. По умолчанию, переменная со значением `initial`.
Для `@media (--reduce-motion)` заменяем анимацию на `opacity`.
- related to #6429
=> fix(AccordionContent): refactor for useCSSKeyframesAnimationController()

packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx
- close #6897 
---
Если раскрыть календарь DateRangeInput и менять месяц через дропдаун в правой половине календаря, то выбраный в дропдауне месяц может появится в левой пловине, хотя ожидается, что где месяц был выбран, там он появится.
То же относится и к CalendarRange
Доработал обработку выбора месяца и года в header-е календаря в правой части
=> fix(CalendarRange): fix select view date in right part calendar

packages/vkui/src/components/FixedLayout/FixedLayout.tsx, packages/vkui/src/hooks/useResizeObserver.ts
- close #2429 
---
Добавил подписку на изменения размеров родителя (или колонки) и пересчет размеров FixedLayout
=> fix(FixedLayout): add resize observer for resize component

packages/vkui/src/components/FloatingArrow/FloatingArrow.tsx, packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.e2e-playground.tsx, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-android-chromium-dark-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-android-chromium-light-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-ios-webkit-dark-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-ios-webkit-light-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-webkit-light-1-snap.png
Добавляем возможность при передаче пропа для статичного позиционирования `isStaticOffset` применять отступ `offset` от противоположного края, если в placement есть `Align` часть с `-end`, то есть `top-end`, `right-end`, `bottom-end`, `left-end`.
Это позволит более гибко настраивать положение стрелочки.
Наш элемент прибит к правому краю и мы над ним хотим показать попап, да так, чтобы стрелочка было близко к краю. Для этого мы передаем `placement: "top-end"`, а в `arrowProps`: {{ isStaticOffset, offset: 20}}
Раньше, чтобы это сделать надо было знать ширину всего попапа, чтобы задать `offset` практически равный этой ширине, потому что отсчёт позиции стрелочки был от левого края.
Теперь, если в placement `top-end`, то отсчёт при `isStaticOffset` будет от правого края.
=> feat(FloatingArrow): Apply offset according to the placement Align

packages/vkui/src/components/Link/Link.tsx
- close #7086
---
Из-за того, что у компонентов Link всегда рендерится часть Tappable для ripple-эффекта, спозиционированная абсолютно, Link не прячется в Safari вместе с контентом если контент переполнил родительский элемент.
Это, конечно, странное поведение Safari, но и у нас довольно странно в DOM вставлять Ripple компонент, который для Link совсем не нужен.
Руководствуясь условием в `Tappable`, по которому мы рендерим Ripple компонент
https://github.com/VKCOM/VKUI/blob/92d8c0867892d718d6dfadcfbf3f78122d870583/packages/vkui/src/components/Tappable/Tappable.tsx#L74-L76
мы убираем hoverMode="none" у `Link`.
Это безопасно, потому что hoverMode="background" у `Tappable` есть по умолчанию и управляет он фоном, которого у Link нету. Так что на Link это никак не повлияет. …
=> fix(Link): Remove ripple part of Link by disabling Tappable hoverMode

packages/vkui/src/components/CustomSelectOption/CustomSelectOption.module.css
- close #7062 
---
Добавил для текста в CustomSelectOption свойство `word-break: break-word`
Свойство `word-break: break-word` не поддерживается в старых версиях Firefox, но поскольку у нас есть несколько мест, где уже используется, решил заиспользовать
=> fix(CustomSelectOption): add word-break: break-word

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/Select/Select.tsx
- close #7115 
---
Добавил пропс `getSelectInputRef` для получения ссылки на элемент input внутри `CustomSelect`
=> feat(CustomSelect): add prop getSelectInputRef

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Наведение в CustomSelect зависит от расположения элемента в DOM. Из-за того что первым элементом выставлялся iframe, то наведение слетало на один элемент
Не завязываемся на расположение элемента в DOM
----
- caused by #7060
=> fix(CustomSelect): focus index

packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx, packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsInputBase/constants.tsx
Бывает, что хочется некоторые chips уже сразу сделать выбранными по умолчанию, не давая их убрать. Например, с помощью disabled и readOnly свойств.
Оказалось, что для ChipsInput мы позволяем задать `disabled` или `readOnly` только для всех chips разом.
Используем значение `disabled`/`readOnly` из `option` при рендере chips.
=> fix(ChipsSelect/ChipsInput): Pass option disabled and readonly to renderChip

packages/vkui/src/hooks/useEnsuredControl.ts
Мы получили репорт об ошибке от пользователей:
> TypeError: Uncaught TypeError: Cannot read properties of undefined (reading 'shown')
shown в объекте используется только в `useFloatingWithInteractions`, который управляется с помощью хука `useCustomEnsuredControl`.
Единственный момент когда бы состояние могло быть `undefined` это момент когда вызывается callback 
https://github.com/VKCOM/VKUI/blob/406784aa5bfa1d1dd0dd40f24f031faca8de5eca/packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts#L93-L102
Тут мы вызываем `setShownLocalState` с функцией, у которой в аргументах может лежать предыдущее состояние стейта.
В этот момент у `useCustomEnsuredControl`, если компонент контролируемый и вызывает `onChange` с коллбэком, мы обращаемся к переменной …
=> fix(useCustomEnsuredControl/useFloatingWithInteractions): Initialize preservedControlledValueRef with value

packages/vkui/src/components/Popover/Popover.tsx
- close #7117
---
Возвращаем параметр, который удалили в v6.0.0.
---
- caused by #6212
=> fix(Popover): revert `customMiddlewares` prop

packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.module.css, packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.tsx
- close #6387 
---
Нужно добавить возможность выравнивания по центру для компонента `HorizontalCellShowMore`
Добавил проп `centered`. При передаче которого, компонент выравнивается по центру по вертикали относительно родителя
=> feat(HorizontalCellShowMore): add prop `centered`

packages/vkui/src/components/CustomSelect/CustomSelect.e2e-playground.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.e2e.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-scroll-to-option-android-chromium-light-1-snap.png
- caused by #7060 
Т.к. изменилась внутренняя структура `CustomScrollView`, в `CustomSelect` сломалось получение ссылки на конкретный айтем и не работал подскролл к нужному элементу при открытии дропдауна.
Получаем верную ссылку на элемент, покрываем тестом данный кейс.
=> fix(CustomSelect): fix scroll to element

packages/vkui/src/hooks/useExternRef.ts
- see #6920
---
Для компилятора требуется знать точные зависимости в useMemo
Избавился от useMemo, написал отдельный класс реализующий MutableRefObject
=> fix(useExternRef): rm useMemo

packages/vkui/src/hooks/useExternRef.ts
> Unexpected ref object provided for %s. Use either a ref-setter function or React.createRef().
React проверяет наличие свойства current у объектов через hasOwnProperty и генерирует ошибки
Исправляем реализацией hasOwnProperty
- cause #7077
=> fix(useExternRef): add hasOwnProperty

packages/vkui/src/components/CustomSelect/CustomSelect.e2e-playground.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.e2e.tsx, packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-scroll-to-option-android-chromium-light-1-snap.png
- caused by #7131
---
Из-за того, что использовалось `platform` вместо `onlyForPlatforms`, иногда тесты исполнялись и для `vkcom`-платформы
Добавляем исправленный `e2e`-тест
=> fix(CustomSelect): bring back (not)flacky test

packages/vkui/src/components/AspectRatio/AspectRatio.tsx
- close #7145
---
Расширяем компонент всеми пропами от `RootComponent`
=> feat(AspectRatio): extend props from RootComponent

packages/vkui/src/components/CustomSelect/Readme.md
В примере для текста выставлен токен фона, вместо текста
color_background_accent -> color_text_accent
=> docs(CustomSelect): fix token

packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.test.tsx, packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.tsx
- caused by #6979
---
Если контекст был изначально скрыт - видели блинкуюущую менюшку:
| Было  | Стало |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/dc5eafab-a38c-45cd-8344-3b4141e6ef0f">  | <video src="https://github.com/user-attachments/assets/9fc720a4-02af-4309-9614-3a5c9d167cfe">|
Передаем флажок `disableInitAnimation` и исправляем тест
=> fix(PanelHeaderContext): remove init animation

styleguide/pages/customize.md
Был указан неправильный импорт CSS файла с темой.
---
- caused by #6313
=> docs(customize.md): fix imports and add additional comments

packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
- close #7195
---
Игнорируем события наведения мыши (`onMouseOver`/`onMouseLeave`) на всплывающем окне в момент `willBeHide`.
С `onMouseLeave` проблемы нет, но на всякий тоже отключаю.
Затрагивает `Popover` и `Tooltip`.
---
- caused by #6150
=> fix(useFloatingWithInteractions): prevent mouse events when `willBeHide` is `true`

packages/vkui/src/components/Search/Search.module.css, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-firefox-light-1-snap.png
- close #6833 
---
Поправить анимацию кнопки в компоненте Search на ios
Поправил css анимации появления и скрытия кнопки на ios
=> fix(Search): fix ios button animation

packages/vkui/src/components/FormField/FormField.module.css, packages/vkui/src/components/FormField/FormField.test.tsx, packages/vkui/src/components/FormField/FormField.tsx, packages/vkui/src/components/Select/Select.tsx, packages/vkui/src/components/Textarea/Readme.md, packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/index.ts
- close #6307 
---
Добавить пропс after для компонента `TextArea`
- Добавил пропсы `after` и `before` для компонента TextArea
- Добавил пропсы `afterAlign` и `beforeAlign` для компонента `FormField` для выравнивания компонентов по вертикали
- Дописал тесты для компонента `FormField`
- Добавил пример в документацию с компонентом `after` в `TextField`
=> feat(TextArea): add possibility to add after and before props. Add props to align after and before items in FormField

packages/vkui/src/components/Accordion/Accordion.module.css, packages/vkui/src/components/ModalRoot/ModalRoot.module.css
Перестала работать анимация подложки в ModalRoot
Оказалось что в #7083 добавилась анимация для аккордиона с названием `animation-fade-in`, и оно перебило анимацию в модалках
Переименовал анимации
Для решения проблемы пересечения имен в будущем будем хэшировать названия классов и кейфремов. В текущий момент требуется называть кейфреймы с префиксом компонента
=> fix: double animation-fade-in

packages/vkui/src/components/Cell/Cell.test.tsx, packages/vkui/src/components/Cell/Cell.tsx
Из-за того, что мы явно устанавливали значение свойства `Component` в `simpleCellProps`, то оно становилось явным и переопределяло значение Component позже в Clickable.
https://github.com/VKCOM/VKUI/blob/7f0a1694094434c2676af8969ab4ce964cd8972a/packages/vkui/src/components/Cell/Cell.tsx#L79
https://github.com/VKCOM/VKUI/blob/7f0a1694094434c2676af8969ab4ce964cd8972a/packages/vkui/src/components/Cell/Cell.tsx#L128
https://github.com/VKCOM/VKUI/blob/7f0a1694094434c2676af8969ab4ce964cd8972a/packages/vkui/src/components/Clickable/Clickable.tsx#L192-L193
=> fix(Cell): Ignore falsy explicit undefined Component value with href

packages/vkui/src/components/ModalDismissButton/ModalDismissButton.module.css, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-android-chromium-dark-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-android-chromium-light-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-ios-webkit-light-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-webkit-light-1-snap.png
При наведении на крестик навешивался токен --vkui--opacity--disable. Заменил на ховерные и активные варианты токена и починил анимацию, привязав её к :before.
Изменение состояния стало менее заметным визуально, отполируем её чуть позже через токены.
=> fix(ModalDismissButton): Changed transition from opacity to background

packages/vkui/shared.config.js, packages/vkui/src/vkui.js, webpack.common.config.js
Удаляем vkui.js. Он не используется уже 5 лет 
- see #360
=> chore: rm vkui.js

packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
- close #7173
---
С v6 у Popover появилась анимация закрытия и `onShownChange` не учитывает это и вызывается сразу. Для решения проблемы создал колбек `onShownChanged`, который ждёт завершения анимации.
---
- caused by #6150
- related to #7175
=> feat(Popover): add onShownChanged prop

packages/vkui/src/components/Tooltip/Tooltip.tsx
Добавляем новое свойство disableTriggerOnFocus, чтобы запретить появление при фокусе.
Иногда, если `Tooltip` на элементе внутри модалки, при открытии модалки появляется `Tooltip`, что не желательно.
В то же время лучше избегать использования такого свойство чтобы следовать паттерну [Tooltip](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/)
=> feat(Tooltip): disable trigger on focus with disableTriggerOnFocus prop

packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.test.ts, packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.ts
Состояние `entered` выставлялось с ре-рендером при инициализации.
---
- caused by #6806
=> feat(useCSSKeyframesAnimationController): exclude first rerender

packages/vkui/src/components/Snackbar/Snackbar.module.css, packages/vkui/src/components/Snackbar/Snackbar.tsx, packages/vkui/src/components/Snackbar/types.ts, packages/vkui/src/components/Snackbar/utils.ts
- close #7212
---
В мобильном режиме `"bottom-end"` больше не перебивается на  `"bottom-start"`. Также теперь можно закрыть Snackbar свайпом в любое из направлений по горизонтали.
=> feat(Snackbar): support close with swipe in any direction in mobile

benchmark/docker-compose.yml
Пропустили флаг в `benchmark/docker-compose.yml`
---
- caused by #7165
=> tech(docker-compose.yml): add corepack enable; rm unused flag

packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ActionSheet/ActionSheetContext.ts, packages/vkui/src/components/ActionSheet/Readme.md, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.test.tsx, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx, packages/vkui/src/components/ActionSheetItem/helpers.ts
- close #6954 
---
При навигации с помощью стрелочек по  `ActionSheetItems` с `selectable` флагом закрывается `ActionSheet`
- Поисследовал проблему с тригером события `click` при навигации по элементам. Нашел вариант как можно ее обойти https://github.com/facebook/react/issues/7407. С помощью проверки можно отличить реальное событие клика. 
- Добавил обработку нажатия кнопки `Enter`, при котором происходит закрытие `ActionSheet`
- Добавил тесты для нового функционала
=> fix(ActionSheetItem): fix navigation by arrows in selectable ActionSheetItem

packages/vkui/src/components/List/List.e2e-playground.tsx, packages/vkui/src/components/List/List.e2e.tsx, packages/vkui/src/components/List/List.module.css, packages/vkui/src/components/List/__image_snapshots__/list-android-chromium-dark-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-android-chromium-light-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-ios-webkit-dark-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-ios-webkit-light-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/List/__image_snapshots__/list-vkcom-webkit-light-1-snap.png
По умолчанию grid item имеет ширину минимум равную минимальной ширине контента (`minmax(auto, 1fr)`). 
По этой причине контент может вылезать за пределы родителя, если контента много.
- меняем правила для grid колонки на `minmax(0, 1fr)`
- добавляем скриншотные тесты именно для этой проблемы.
| До | После |
|----|--------|
| <img width="1034" alt="Screenshot 2024-07-31 at 18 44 19" src="https://github.com/user-attachments/assets/fc35c832-1bca-4f40-bd7e-50ea6ab3eae3"> |<img width="1034" alt="Screenshot 2024-07-31 at 18 44 23" src="https://github.com/user-attachments/assets/2810dcb7-ef63-4258-a3ea-a5610a4fa68f">|
=> fix(List): avoid Cell content to overflow parent

packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
В момент когда делали ChipsSelect стабильным (https://github.com/VKCOM/VKUI/pull/6206), мы поменяли key на использование `option.label` вместо `option.value`. Это не совсем правильно, так как текстовое представление `label` может совпадать, в то время как `value` должно быть уникальным.
Пример с воспроизведением: https://codesandbox.io/p/sandbox/muddy-water-4jxc78?file=/src/App.tsx:13,1
Поменял key в `ChipsInput` при рендере `Chips` и в `ChipsSelect` при рендере options.
Обновил key в `CustomSelect` для единообразия по аналогии с ChipsSelect.
=> fix(ChipsSelect/CustomSelect): Change key back to option.value

packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Avatar/Avatar.tsx, packages/vkui/src/components/Avatar/AvatarBadge/icons.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/ChipsInput/ChipsInput.tsx, packages/vkui/src/components/ChipsInputBase/helpers.ts, packages/vkui/src/components/ChipsInputBase/types.ts, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/Clickable/useState.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/FixedLayout/FixedLayout.tsx, packages/vkui/src/components/GridAvatar/GridAvatar.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx, packages/vkui/src/components/Image/Image.tsx, packages/vkui/src/components/ImageBase/validators.ts
---
Данный PR сделан, чтобы вынести изменения по компонентам из задач по улучшению покрытия тестами #7244, #7263, #7277. Сделано это, чтобы в тех PR были изменения касающиеся только тестов. Теперь по каждому файлу
- `Alert`. Убрано значение `actions` по умолчанию, так как нет мест, где `actions` не прокидывается
- `icons.tsx`. В иконках убраны значения по умолчанию для `width` и `height`, чтобы не покрывать кейсы, когда `width` и `height` не прокинуты
- `Avatar`. Убрал экспорт константы, так как она нигде за пределами не используется
- `CalendarRange`. Поменял способ получения `start` и `end` через деструктуризацию 
- `ChipsInput`. Убрал значения по умолчанию для `getOptionValue`, `getOptionLabel`, `getNewOptionData`. Так как эти пропы не используются на уровне этого компонента
- …
=> feat: prepare components to tests coverage

packages/vkui/package.json, yarn.lock
После переписывания Tappable пакет mitt больше не использовался
=> fix(deps): rm mitt

packages/vkui/src/components/Group/Group.test.tsx, packages/vkui/src/components/Group/Group.tsx
Класс `Group--sizeX-regular` должен был быть ещё в PR #7284, но видимо случайно ревертнул когда пушил. Без него не будет автоопределения для `mode="card"`, когда `mode === "none"` и `sizeX === "regular"`.
Также исправляем тест из под #7333 – падал из-за того, что в PR был старый мастер без #7284.
---
- caused by #7284, #7333
=> fix(Group): add missed CSS class for `sizeX="regular"`

packages/vkui/src/components/ModalRoot/Readme.md
- close #7347
---
Ошибочно был указан несуществующий `gap="l"`. Меняем везде на значения из дизайн-системы.
=> docs(ModalRoot): ButtonGroup gap

styleguide/Components/SectionSubheading/SectionSubheading.css, styleguide/Components/SectionSubheading/SectionSubheading.js
- close #7349
---
Переносим якорную иконку вправо, чтобы было видно на мобилках
=> docs: move anchor links to the right

package.json, packages/vkui/scripts/postcss.js, packages/vkui/webpack.styles.config.js, yarn.lock
Перенос изменений беты [v5.10.1-beta.1](https://www.npmjs.com/package/@vkontakte/vkui/v/5.10.1-beta.1) (см. [comparing changes](https://github.com/VKCOM/VKUI/compare/5.10-stable...imirdzhamolov/tech/v5.10.1-beta.1/fix-css-source-map)).
> [!NOTE]
>
> `v5.10.1-beta.1` публиковал из ветки `imirdzhamolov/tech/v5.10.1-beta.1/fix-css-source-map`
---
- related to #7034
=> build: fix CSS source-map for postcss >= 8.4.33

packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx, packages/vkui/src/components/FocusTrap/FocusTrap.tsx
- close #7268 
---
Нужно добавить возможность фокуса на контейнер FocusTrap при первой отрисовке
Добавил в пропс `autoFocus` значение 'root' и использовал его при первой отрисовке, чтобы сфокусироваться на контейнере. Добавил тест проверяющий новый функционал
=> feat(FocusTrap): add autoFocus to root possibility

package.json, packages/vkui-floating-ui/package.json, packages/vkui/package.json, tools/storybook-addon-cartesian/package.json, yarn.lock
Исправляем ворнинги от yarn
```diff
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ prettier is listed by your project with version 3.3.2 (p8eea9), which doesn't satisfy what @vkontakte/prettier-config and other dependencies request (but they have non-overlapping ranges!).
- ➤ YN0002: │ @project-tools/storybook-addon-cartesian@workspace:tools/storybook-addon-cartesian doesn't provide typescript (p400c4), requested by @storybook/react-webpack5 and other dependencies.
- ➤ YN0002: │ @vkontakte/vkui-floating-ui@workspace:packages/vkui-floating-ui doesn't provide react (pc9b97), requested by @floating-ui/react-dom.
- ➤ YN0002: │ @vkontakte/vkui-floating-ui@workspace:packages/vkui-floating-ui doesn't provide react-dom (pf7e9e), requested by @floating-ui/react-dom.
- ➤ YN0002: │ …
```
=> chore: yarn clean more warning

.github/dependabot.yml
`playwright`, который был транзитивной завивимостью вместе с `@playwright/experimental-ct-react` и обновлялся вместе с ним, теперь есть в вокрспейсе `benchmark/`, поэтому нужно, чтобы **Dependabot** обновлял и `playwright`.
---
- caused by #7128
=> tech(dependabot.yml): extend playwright patterns

packages/vkui/src/components/WriteBar/WriteBar.stories.tsx, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.stories.tsx
- close #5013 
---
Нужно сделать кнопки в Writebar в Storybook  интерактивными
Добавил прокидывание `noop` колбэка в `onClick` для кнопок
=> a11y(WriteBar): add onClick to add interactivity

packages/vkui/src/components/Image/Readme.md, packages/vkui/src/components/ImageBase/ImageBase.module.css, packages/vkui/src/styles/constants.css
Сейчас `keepAspectRatio` у `Image` требует явного задания ширины/высоты родителя, потому что непосредственно сама картинка имеет `position: absolute` (соответственно, без явных указаний размеров картинка будет схлапываться или переполнять родительский контейнер). Также есть проблемы с обводкой - она не растягивается на размерам картинки.
Убираем `position: absolute` у `img`
=> feat(ImageBase): remove position: absolute & update docs example

packages/vkui/src/components/Flex/FlexItem/FlexItem.tsx
У `content` было неправильно указано CSS значение.
Хаодно добавил про значение `fixed`.
---
- caused by #6226
=> fix(FlexItem): edit flex prop description

styleguide/Components/Setting/Setting.css, styleguide/Components/Setting/Setting.js
- close #7357 
---
Hint у настройки в документации тоже перенимает на себя `opacity` когда настройка задизаблена
Подумав над решением проблемы пришел к выводу, что тултип не должен вообще показываться когда настройка заблокирована. Поэтому добавил проверку `disabled` прежде чем показывать тултип. А также поправил отображение курсора при наведении на настройку в заблокированном состоянии
=> doc(Settings): don't show hint when setting disabled

packages/vkui/src/components/CustomScrollView/Readme.md
В документации CustomScrollView не отображается заголовок в примерах использования, из-за того, что там используется FixedLayout, для отображения примера не использовался iframe. Поэтому заголовок улетал вверх
Поправил доку CustomScrollView, чтобы в примере использовался iframe
=> doc(CustomScrollView): use iframe to show documentation

packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelect/CustomSelectInput.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/components/Select/Select.tsx
Убрал проп maxHeight в компонентах DateRangeInput, DateInput и CustomSelect так как он там не нужен и только смущает пользователей
=> fix: remove maxHeight props from DateRangeInput, DateInput and CustomSelect

.github/workflows/pull_request_common.yml
Падает ошибка при попытке вызвать скрипт `@dependabot/fetch-metadata@v2`. Проблема из-за того, что `DEVTOOLS_GITHUB_TOKEN` не устанавливается в контекста `dependabot`
- Заменил `DEVTOOLS_GITHUB_TOKEN` на `GITHUB_TOKEN`
- Добавил права на создание и редактирование milestone и pull_requests
=> fix: add permissions to issues and pull requests write

.github/dependabot.yml
- caused by #7377
- related to #7399
---
Как видно в PR от **Dependabot** #7399, скорей всего в #7377 я в неправильном порядке указал `'playwright'` в поле **petterns**. По примеру группы `storybook` необходимо зависимость без `@` указать в начале.
=> tech(dependabot.yml): fix playwright patterns order

packages/vkui/src/components/Search/Search.tsx
Кнопка очистки была доступна не смотря на то, что поиск был задисайблен
Отключаем кнопку очистки при передаче `disabled` в компонент поиска
=> fix(Search): clear button not disabled

packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
- close #7413
---
Мы не отправляли внутреннее значение `placement` из `CustomSelect` в `CustomSelectDropdown` потому и в некоторых ситуациях `onPlacementChange` `callback` не вызывался, потому что при длительном взаимодейтсвии с `CustomSelect`, внутренее значение могло быть `top`, при этом в `CustomSelectDropdown` передавался постоянно prop `placement="button"`, в итоге `usePlacementChangeCallback` не вызывал `onPlacementChange` callback.
Передаем внутренне состояние `placement` в `CustomSelectDropdown`, вместо `popupDirection`.
Тут есть эффект того, что изменение пропа `placement` после первого рендера не поменяет направление дропдауна.
Но это фича, которая не особо имеет смысл. 
Контролировать `placement` через проп в `CustomSelect` не очень получится, он принимает значения `'top' | …
=> fix(CustomSelect): Fix input borders when CustomSelectDropdown is opened

.github/workflows/update_screens.yml
- related #7427
Падает уже с другой ошибкой:
По [рекомендации](https://github.com/peter-evans/create-pull-request#:~:text=GITHUB_TOKEN%20(permissions%20contents%3A%20write%20and%20pull%2Drequests%3A%20write)) добавляем ещё `contents: write`
=> ci(update_screens): add contents write permission

benchmark/README.md, packages/vkui/src/components/BaseGallery/BaseGallery.tsx, packages/vkui/src/components/BaseGallery/CarouselBase/CarouselBase.tsx, packages/vkui/src/components/BaseGallery/types.ts, packages/vkui/src/components/ModalRoot/ModalRoot.tsx, packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx, packages/vkui/src/components/Slider/Slider.test.tsx, packages/vkui/src/components/Slider/Slider.tsx, packages/vkui/src/components/Touch/Touch.stories.tsx, packages/vkui/src/components/Touch/Touch.test.tsx, packages/vkui/src/components/Touch/Touch.tsx, packages/vkui/src/components/View/View.tsx, packages/vkui/src/components/View/ViewInfinite.tsx, packages/vkui/src/components/View/utils.ts, packages/vkui/src/hooks/useDraggableWithDomApi/types.ts, packages/vkui/src/hooks/useDraggableWithDomApi/useDraggableWithDomApi.ts, packages/vkui/src/lib/touch/functions.ts
- close #7269
---
см. #7269
- `handleNativePointerUp` и `handleNativePointerMove` обернул в `useStableCallback()` – без этого терялась область видимости и коллбеки `onEnd`/`onEndX`/`onEndY` и `onMove`/`onMoveX`/`onMoveY` вызывались со старым состоянием. Особенно это было заментно в компонент `View`, в котором начало свайп срабатывало со второго раза, а сам свайп не заверашлся, т.к. `onEnd` вызывался с предыдущим состоянием;
- `handlePointerDown` теперь передаёт в `onStart`/`onStartX`/`onStartY` **React**-овское событие для правильной работы `preventDefault()` и `stopPropagation()`.
- `TouchEvent` переименован в `CustomTouchEvent` – из-за этого +14 файлов в изменениях 😅 ;
- события `pointerenter`/`pointerleave`/`mouseenter`/`mouseleave`/`touchstart`/`mousedown` теперь навешиваются через …
=> refactor(Touch): rm `useEventListener()`

packages/vkui/src/components/Flex/Flex.e2e-playground.tsx, packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-android-chromium-light-1-snap.png, packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-ios-webkit-light-1-snap.png, packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-vkcom-webkit-light-1-snap.png, packages/vkui/src/styles/constants.css
Из-за того, что по умолчанию `--vkui_internal--row_gap` и `--vkui_internal--column_gap` устанавливались в `0`, то при их участии в расчете через `calc` свойство `margin` рассчитывалось неверно (отсутствовали отступы сверху-слева)
Инициализируем значения как `0px`
=> fix(Flex): add margin auto offset

packages/vkui/src/components/Search/Readme.md
@shevchux заметил, что в документации указан неверный `type`
=> fix(Search): mv type="text" to type="search"

packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.module.css, packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx, packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
- close #7458 
---
Нужно реализовать закрытие дропдауна в компоненте ChipsSelect при  нажатии на DropdownIcon
=> fix(ChipsSelect): add close dropdown when click dropdown icon

packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx, packages/vkui/src/components/Tooltip/Tooltip.stories.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/components/TooltipBase/TooltipBase.e2e-playground.tsx, packages/vkui/src/components/TooltipBase/TooltipBase.e2e.tsx, packages/vkui/src/components/TooltipBase/TooltipBase.module.css, packages/vkui/src/components/TooltipBase/TooltipBase.tsx, packages/vkui/src/components/TooltipBase/__image_snapshots__/tooltipbase-android-chromium-dark-1-snap.png, packages/vkui/src/components/TooltipBase/__image_snapshots__/tooltipbase-android-chromium-light-1-snap.png, packages/vkui/src/index.ts
- close #6258
---
- ~[ ] Unit-тесты~ – сейчас их в целом пока нет, не стал покрывать в этом PR
- related to #6892
- для `TooltipBase` добавил параметры `closeIconLabel` и `onCloseIconClick`
- в `OnboardingTooltip` игнорируем их, т.к. там логика закрытия завязана на нажатие на оверлей;
- добавил пару скриншотов.
- в `Tooltip`:
- удалил дублирующий `TooltipBase` код;
- по аналогии с `Popover`, добавил типы и их ре-экспорт  `TooltipArrowProps` и `TooltipOnShownChange`;
- в Story файл добавит пример с `closable`.
=> feat(Tooltip): add `closable` prop

.github/workflows/pr_close.yml, .github/workflows/pull_request_common.yml
- caused by #7404
---
Не было проверки на то, что PR был создан dependabot, поэтому падал шаг dependabot/fetch-metadata. Добавил проверку перед джобой
Также поправил проблему с вызовом экшена в pull_request_common.yml/labels
=> tech: move check dependabot to job is-updated-vkui-floating-ui

packages/vkui/src/components/Checkbox/CheckboxInput/CheckboxInput.tsx
- see #6920
---
> Mutating a value returned from a function whose return value should not be mutated
Убираем мутации инпута, так как реакт компилятор ругается
=> fix(CheckboxInput): rm mutation value

packages/vkui/src/components/OnboardingTooltip/OnboardingTooltipContainer.tsx
- see #6920
---
> Mutating component props or hook arguments is not allowed
Убираем мутации пропов, так как это не поддерживается реакт компилятором
=> fix(OnboardingTooltipContainer): rm mutation props

packages/vkui/src/components/BaseGallery/CarouselBase/CarouselBase.tsx, packages/vkui/src/components/FocusTrap/FocusTrap.tsx, packages/vkui/src/hooks/useMutationObserver.test.tsx, packages/vkui/src/hooks/useMutationObserver.ts
- close #7465 
---
Сейчас есть проблема в компоненте `Gallery`. При контроллируемом переключении слайда происходит перерендер компонента и `children` меняется(поскольку это массив). Из-за этого в `CarouselBase` происходит срабатывание `useEffect`'а, у которого в `deps` есть `children`. В этом `useEffect`'е происходит вызов функции `initializeSlides`, где неправильно выставляется `transform` для слоя со слайдами(так как slideIndex изменился). Поэтому появляется на один фрейм баг описанный в задаче.
По идее при изменении ссылки на `children` не должна вызываться функция `initializeSlides`, так как содержимое не изменилось. И вообще содержимое галереи вряд ли будет меняться в рантайме(довольно редкий кейс). Но все равно надо учесть такой кейс. Как вариант - использование `MutationObserver` …
=> fix: fix rerender component when slide controlled changes

.github/actions/add-label-to-pull-request/action.yml
- caused by #7404
---
При попытке добавить label при создании PR падает ошибка. Это из-за того, что в экшене переданный label не был обернут в кавычки. Добавил кавычки
=> tech: fix add-label action

packages/vkui/src/components/AppRoot/ScrollContext.tsx
- see #6920
---
Удаляем неиспользуемый код, который мешает react компилятору
=> chore(useScrollLockEffect): rm death code

.eslintrc.json, package.json, yarn.lock
Добавляем линтер для [react компилятора](https://react.dev/learn/react-compiler)
=> style: add eslint-plugin-react-compiler

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- close #7504
---
Сейчас нельзя изменять положение курсора с помощью мыши в searchable CustomSelect-е. Проблема в том, что при обработке mousedown происходит preventDefault всегда когда input  в фокусе. Нужно доработать проверку так, что при наличии фокуса и клике в input не происходил preventDefault
Доработал проверку в обработчике mouseDown, чтобы можно было менять положение курсора мышью
Обработал кейс, чтобы при фокуса в поле просходило выделение всего текста
- CustomSelect: поправлена проблема с изменением позиции курсора с помощью мыши
=> fix(CustomSelect): fix custom select cursor updating

.github/workflows/pr_close.yml
- caused by #7431 
---
При вызове job-ы по обновлению release notes падает ошибка. Проблема в том, что в скрипте обновления нет инпута vkui_version, там используется current_vkui_version. Нужно переименовать vkui_version на current_vkui_version
=> tech: rename vkui_version to current_vkui_version in inputs

packages/vkui/src/components/Search/Search.module.css, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-android-chromium-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-android-chromium-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-ios-webkit-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-webkit-light-1-snap.png
- close #7460
- caused by #7196
---
1. обернул кнопку под `after` в отдельный `<div>`;
2. удалил анимацию `margin-inline` путём выставления отступов через `::before` и `::after` у нового `<div>`;
3. у `::after` минусуем отступ справа, который выставляется у `Search` если он есть (завязываемся на `.Search--withPadding`);
4. ~удалил `Search__afterText`, т.к. у `Button` уже есть логика обрезания текста (⚠️ правда через `ellipsis`, а не `clip`);~ см. https://github.com/VKCOM/VKUI/pull/7487#issuecomment-2325134932
5. у кнопки выставил `hoverMode` и `activeMode` на `"opacity"`;
6. обновил скриншоты, т.к. привёл отступы к соответствие с дизайном.
_У кнопки слева/справа **12px**, а вокруг обёртки над кнопкой по **4px** (справа отступ минусуем, см. **п.3**)_
- для ясности точечно применяем …
=> fix(Search): edit after transition

.github/dependabot.yml
- related to #6920
- caused by #7533
---
Игнорируем https://www.npmjs.com/package/eslint-plugin-react-compiler/v/0.0.0 (это самый первый релиз), чтобы использовать только экспериментальные версии и версии выше.
А то **Dependabot** решил удалить постфикс `-experimental`.
=> ci(dependabot): ignore eslint-plugin-react-compiler 0.0.0

packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx, packages/vkui/src/hooks/useWaitTransitionFinish.ts
- close #7525
---
За счет бабблинга событий `transitionend` на родительском элементе может вызываться несколько раз
- проверяем на целевой элемент, для которого нам интересно завершение анимации
- немного изменяем типы
- [ModalRoot](https://vkcom.github.io/VKUI/6.7.0/#/ModalRoot): исправлены повторные вызовы `onClosed` при определенных условиях
=> fix(ModalRoot): call onClosed only once

packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx
Цитата:
> Недавно столкнулся с проблемой, что в модалке основное действие не отрабатывало. В нашем компоненте мы используем компонент `Alert` и храним нужные данные в объекте, который сетим при открытии и уничтожаем при закрытии модалки, а в основном действии используем этот объект. Оказалось, что при выборе подтверждающего действия компонент `Alert` сначала вызывает `onClose`, а только потом само главное действие, из-за чего к моменту, когда нам нужен наш объект он оказывается уже удалённым. Решил проблему, отложив удаление нашего объекта в `onClose` на следующий цикл, но выглядит так, что лучше это иcправить на вашей стороне.
- Alert: `onClose` теперь вызывается после `action`
=> fix(Alert): call onClose after item's action

packages/vkui/src/components/Badge/Badge.tsx, packages/vkui/src/components/Counter/Counter.module.css, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.e2e-playground.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.module.css, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-android-chromium-dark-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-android-chromium-light-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-ios-webkit-dark-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-ios-webkit-light-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderbutton-vkcom-webkit-light-1-snap.png
- close #6612
---
Необходимо с соответствии с дизайном добавить поддержку `Badge` в `PanelHeaderButton`
**Целевое решение**: в версии `v7` (оставила коммент) необходимо будет разграничить `label` и добавить св-во `indicator`, которое позволит убрать немного лапшу в `css`
Получилась очень некрасивая портянка в `CSS`, пришлось добавить глобальный класс `vkuiInternalBadge`, потому что в дизайне сложные правила применения отступов. Попробовала попросить дизайн как-то покрутить, чтобы отступы были одинаковые, но ничего не получилось 😞 
- PanelHeaderButton: добавлена поддержка компонента `Badge` в `label`
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/14bb6d5e-2390-4766-8bdb-8e16d5166523">
</picture>
=> feat(PanelHeaderButton): add Badge support in label prop

.github/actions/lfs/action.yml
`actions/cache` для сжатия кэша использует zstd,  eсли его нет то использует gzip. Из-за этого в контейнерах кэш не может восстановиться.
Устанавливаем zstd если его нет.
=> ci(lfs): install zstd

packages/vkui/src/components/Typography/Typography.module.css, packages/vkui/src/components/Typography/Typography.stories.tsx, packages/vkui/src/components/Typography/Typography.test.tsx, packages/vkui/src/components/Typography/Typography.tsx
- related #7283 (раздел с проблемой font-weight)
---
`font-weight` в дизайн системе может выглядеть как отдельны режим.
Мы позволяем менять `font-weight `с помощью свойства `weight` компонента `Typography`, который под капотом у всех других типографических элементов.
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9e3bfa46da0d/packages/vkui/src/components/Typography/Typography.tsx#L21-L24
Но Typography поддерживает не все токены, которые могут быть использованы в дизайн-системе.
Вот все токены `fontWeight` пока что существующие в vkui-tokens. [Ссылка](https://github.com/VKCOM/vkui-tokens/blob/ecdad88decf36df7ad14f5df493ba5adbddae6a5/src/themeDescriptions/base/paradigm.ts#L14-L19) на токены темы `paradigm`
```js
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9 …
```
=> feat(Typography): Support fontWeightBase tokens

packages/vkui/src/components/Typography/Text/Text.e2e-playground.tsx, packages/vkui/src/components/Typography/Text/Text.module.css, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-android-chromium-dark-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-android-chromium-light-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-ios-webkit-light-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Typography/Text/__image_snapshots__/text-vkcom-webkit-light-1-snap.png
- related #7283 
---
Добавили токены fontWeight и fontFamily для compact режима, плюс фолббэк на regular токены.
- Text: добавлено использование compact токенов fontWeight/fontFamily в режиме compact
=> feat(Text): Add compact tokens for font-weight and font-family

packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.module.css, packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.tsx, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-webkit-light-1-snap.png
- related #7283 
---
Добавили compact режим для DisplayTitle, чтобы в теме,  где указаты токены compact режима, они применялись.
Тесты упали на платформе vkcom, потом что там применяются разные режимы адаптивности, в том числе sizeY: compact. В этом режиме теперь используются compact токены. Раньше такого не было, потому что мы compact режим не обрабатывали.
https://github.com/VKCOM/VKUI/blob/b43b961fb7c0cd94b8288fba4f88d25ea2424b3b/packages/vkui/src/testing/e2e/ComponentPlayground.tsx#L43-L44
- DisplayTitle: добавлена поддержка compact режима
=> feat(DisplayTitle): Add adaptivity to DisplayTitle

packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/Clickable/useState.tsx, packages/vkui/src/components/Clickable/useStateWithDelay.test.tsx, packages/vkui/src/components/Clickable/useStateWithDelay.tsx, packages/vkui/src/components/Tappable/Tappable.test.tsx
- close #7228
-------
Необходимо дать возможность `Tappable` компонентам или компонентам основанным на `Tappable` иметь hover-состояние при наведении на дочерние компоненты.
По умолчанию мы намеренно отключаем это поведение.
Включение необходимо реализовать через свойство.
В процессе изучения проблемы пришел к выводу, что нам мало только разрешить `hover` у родителя при наведении на дочерний элемент. Нам также нужно продолжать запрещать распространение `active` состояния с дочернего компонента на родительский.
Но тут возникли проблемы. Дело в том, что запрещение `active` работало только вместе с `hover`. Всё потому, что активное состояние включается с задержкой по `setTimeout`, что также влечёт за собой отложенное включение флага запрета для родительского компонента, и за это время …
=> feat(Tappable): allow parent to hover with children by props

.eslintrc.json, packages/vkui/src/components/AspectRatio/AspectRatio.tsx, packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/CardGrid/CardGrid.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/components/FormField/FormField.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx, packages/vkui/src/components/Input/Input.tsx, packages/vkui/src/components/NativeSelect/NativeSelect.tsx, packages/vkui/src/components/Panel/Panel.tsx, packages/vkui/src/components/RichCell/RichCell.tsx, packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx, packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx, packages/vkui/src/components/SimpleCell/SimpleCell.tsx, packages/vkui/src/components/Slider/Slider.tsx, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx, packages/vkui/src/components/TabsItem/TabsItem.tsx, packages/vkui/src/components/Textarea/Textarea.tsx, packages/vkui/src/components/Typography/Headline/Headline.tsx, packages/vkui/src/components/Typography/Subhead/Subhead.tsx, packages/vkui/src/components/Typography/Text/Text.tsx, packages/vkui/src/hooks/useAdaptivityConditionalRender/constants.ts
Добавляем в eslint правило [no-useless-computed-key](https://eslint.org/docs/latest/rules/no-useless-computed-key)
Основано на https://github.com/VKCOM/VKUI/pull/7555#discussion_r1754102951
- Вычисляемые свойства в объектах приведены к обычным там, где они были ненужны
=> tech: Apply no-useless-computed-key eslint rule

.github/CODEOWNERS
Исключаем шаблоны `pull_request_template.md` и `ISSUE_TEMPLATE/*.md`, т.к. это не sensitive-файлы и не требуют внимания @VKCOM/vk-sec.
-
=> chore(CODEOWNERS): exclude safe files

packages/vkui/src/components/Placeholder/Placeholder.module.css
- close #7530
---
Удаляем не обоснованный `padding-block: inherit` у `stretched` режима.
см. https://github.com/VKCOM/VKUI/issues/7530#issuecomment-2340337039
- Placeholder:  при `stretched` режиме больше не выставляется `padding-block: inherit`.
=> fix(Placeholder): cleanup stretched styling

packages/vkui/src/components/Link/Link.e2e-playground.tsx, packages/vkui/src/components/Link/Link.module.css, packages/vkui/src/components/Link/Link.stories.tsx, packages/vkui/src/components/Link/Readme.md, packages/vkui/src/components/Link/__image_snapshots__/link-state-focus-visible-android-chromium-light-1-snap.png
- close #6855
- related to #6895 
---
Удаляем `margin`, т.к.:
- сейчас расчёт такой, что иконка всегда после текста, а она может быть перед текстом;
- обычный пробел сам по себе и так компенсирует отступ, чтобы текст и иконка не слипались;
- по прошедшим e2e тестам видно, что `margin` не нужен.
Заменил в доках обычный пробел на `&npsp;`, т.к. логичнее использовать его, чтобы иконка не переносилась без текста.
- Link: из CSS удалён зашитый отступ справа в `4px`, который выставлялся иконке. Был расчёт, что иконка всегда справа, но она может быть и слева, в этом раскладе появлялся ненужный отступ слева. Было решено отдать пользователю управлять отступами. Поэтому, если вам требуется отступ, используйте неразрывный пробел:
либо через HTML-код `&nbsp;`,
```diff
<Link href="https://google.com" …
```
=> fix(Link): rm margin from icon

packages/vkui/src/components/Checkbox/CheckboxInput/CheckboxInput.tsx, packages/vkui/src/index.ts
Добавляет возможность прокидывать в Checkbox альтернативные иконки
- related to [#14947](https://jira.vk.team/browse/BIZ-14947)
- Checkbox: добавлена возможность прокидывать альтернативные иконки
=> feat: add custom checkbox icons

packages/vkui/package.json
- closed #7206
CJS устарел
- Была выпилена cjs сборка
- Экспорты были ограничены. Теперь никто не сможет импортировать кишки vkui
- Удалена сборка `@vkontakte/vkui/dist/cjs/index.js`
- Импортировать внутренности VKUI теперь запрещено на уровне свойства `exports` в `package.json`
=> BREAKING CHANGE: use exports

packages/vkui/src/components/Select/Select.tsx
`disabled` не прокидывается в option
Прокидываем `disabled` в option
- [Select](https://vkcom.github.io/VKUI/${version}/#/Select): `disabled` для опций  не прокидывалось в NativeSelect
=> fix(Select): disabled for options

packages/vkui/src/components/BaseGallery/CarouselBase/CarouselBase.tsx
- close #7610
---
Сейчас в компоненте `Gallery` со значением `looped` некорректно происходит переход между слайдами, когда всего два слайда
В функции `performSlideChange` происходит обработка трех кейсов:
1. Переход с последнего слайда на первый
2. Переход с первого слайда на последний
3. Обычный переход с любого слайда на следующий или предыдущий
Когда всего два слайда и мы пытаемся перейти с первого на второй, срабатывает проверка на переход с первого на последний(что в целом логично). Из-за чего и происходит неправильная "обратная" анимация.
Чтобы проверка проходила правильно, добавил при обработке нажатия на стрелочки добавление или убавления `shiftXCurrentRef.current `на минимальное для перехода к следующему/предыдущему слайду значение
- Gallery: Поправлен баг с переходом между двумя …
=> fix(CarouselBase): fix two slides transition

packages/vkui/package.json
- cause #7611
webpack 4 не поддерживает `exports`, поэтому возвращаем поле `module`
Возвращаем поле module
-
=> fix(vkui): return module

packages/vkui/cssm/cssm.swcrc, packages/vkui/jest.config.ts, packages/vkui/package.swcrc
Node.JS для esm формата требует явное указание файла из которго необходимо сделать импорт
```js
import ... from './models'          // ❌
import ... from './models/index.js' // ✅
```
Добавляем резолвинг путей в swc конфигах
```diff
- export { AppRoot } from "./components/AppRoot/AppRoot";
+ export { AppRoot } from "./components/AppRoot/AppRoot.js";
```
-
=> fix(esm): resolveFully

packages/vkui/src/components/TabsItem/TabsItem.module.css
TabsItem при использовании разных тегов(используя свойства `href` и `onClick`) могли не проставляться отступы между элементами
Используем `first-child` вместо `first-of-type`
- [TabsItem](https://vkcom.github.io/VKUI/${version}/#/TabsItem): исправлен отступ между элементами при использовании `href` и `onClick` вместе
=> fix(TabsItem): gaps use first-child

packages/codemods/src/transforms/v7/__testfixtures__/spacing/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/spacing.ts.snap, packages/codemods/src/transforms/v7/__tests__/spacing.ts, packages/codemods/src/transforms/v7/common/remapSizePropValue.ts, packages/codemods/src/transforms/v7/header.ts, packages/codemods/src/transforms/v7/spacing.ts, packages/vkui/src/components/Header/Header.module.css, packages/vkui/src/components/Spacing/Spacing.module.css, packages/vkui/src/components/Spacing/Spacing.tsx, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-webkit-light-1-snap.png
Сейчас в некоторых местах в css используется токен `--vkui--spacing_size_3xs`, но этот токен устарел и равен токену `--vkui--spacing_size_2xs`. Нужно избавиться от использования этого токена в css
- Выпилил использование этого токена в компоненте Spacing, соответственно удалил один из вариантов пропа size
- Реализовал кодмод, чтобы size: 3xs преобразовывался в 2xs в Spacing.
- Заменил использование токена `--vkui--spacing_size_3xs` на `--vkui--spacing_size_2xs` в css компонента Header
- Spacing: удален вариант значения пропа size `3xs` вместо него можно использовать `2xs`, он такой же по значению
```diff
- <Spacing size="3xs" />
+ <Spacing size="2xs" />
```
=> feat(Spacing): remove 3xs size type

packages/codemods/src/transforms/v7/__testfixtures__/typography/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/typography.ts.snap, packages/codemods/src/transforms/v7/__tests__/typography.ts, packages/codemods/src/transforms/v7/typography.ts, packages/vkui/src/components/Typography/Typography.test.tsx, packages/vkui/src/components/Typography/Typography.tsx
related: #7549
---
Делаем `useAccentWeight` по умолчанию false.
Чтобы значение соответствовало названию свойства и по умолчанию отражало суть. 
По умолчанию, если требуется переопределить жирность текста с помощью свойства `weight` - мы используем `fontWeightBase` токены жирности текста. Чтобы включить `fontWeightAccent` токены, нужно также использовать свойство `useAccentWeight`.
- useAccentWeight = false в Typography по умолчанию.
- Добавлен `codemode` `typography`, который применяется для `Typography` и всех типографических компонентов, сделанных на основе `Typography`.
Так как в VKUI раньше было зашито использование только `fontWeightAccent` токенов при использовании свойства `weight`, то  имеет смысл включить `fontWeightAccent` токены там , где используется свойство `weight`, чтобы …
=> feat(Typography): make useAccentWeight=false by default

packages/vkui/package.json
related: #7627
Сборка на [codesandbox](https://ci.codesandbox.io/status/VKCOM/VKUI/pr/7640/builds/544301) не проходит. 
Падает на шаге 
```shell
yarn run build:vkui (in /tmp/4789e560)
No matches found: "dist/*"
Error: Process rejected with status code 1
at ChildProcess.<anonymous> (/app/dist/utils/exec.js:20:27)
at ChildProcess.emit (node:events:518:28)
at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
code: 1
}
```
Ошибка возникает из-за того, что мы вызываем `yarn clear` перед сборкой, то есть вызываем `rm -rf dist/*` когда папки `dist` нету, или она пуста. В таком случае `rm` кидает ошибку.
Из-за того, что мы используем `shx` для запуска `rm`, для поддержки кросплатформенной сборки, нет возможности проверить есть ли папка `dist` и есть ли в ней файлы, перед запуском …
=> tech: fix clear command on codesandbox

packages/vkui/src/lib/layouts/gaps.ts
- related #7550
---
Забыли поменять местами элементы в описании метода
-
=> fix: update calculateGap description

packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
- close #7635
---
Есть проп `disableCloseAfterClick` у компонента Tooltip, который блокирует закрытие тултипа при клике на якорный элемент
При исследовании бага выяснил, что проблема связана с тем, что по умолчанию у тултипа trigger'ы это `['hover', 'focus']` и именно из-за наличия фокуса, при нажатии на элемент, срабатывает событие фокуса у элемент, и затем срабатывает соответствующий обработчик в котором тултип закрывается.
Чтобы поправить баг, в обработчике фокуса добавил проверку на флаг `closeAfterClick`, а также на причину текущего открытия поповера, а именно то, что поповер был открыт по ховеру. Таким образом баг не воспроизводится и старое поведение работает корректно
- Tooltip: поправлен баг с закрытием тултипа при клике на якорный элемент при прокидывании …
=> fix(UseFloatingWithInteractions): fix bug with disableAfterClickClose in Tooltip

packages/vkui/package.json, yarn.lock
- caused by #7593
- `@vkontakte/vkui-floating-ui` обновлён с 2.1.1 до 2.1.3
=> build(deps): Bump `@vkontakte/vkui-floating-ui` from 0.2.1 to 0.2.3

packages/vkui/src/components/SimpleCell/SimpleCell.tsx
Описание свойство `expandable=always` может путать, так как кажется что его необходимо ставить если ячейка кликабельна
Обновляем описание на более ясное
-
=> docs(SimpleCell): `expandable` description update

packages/vkui/src/components/AppRoot/AppRoot.tsx
Выяснилось, что если `AppRoot` по какой-то причине ререндерится, то это вызывает ререндер компонентов, основанных на `Tappable`/`Clickable` компонентах, даже если они обернуты в `React.memo`. 
Виной тому пересоздающийся объект контекста.
Когда может ререндерится `AppRoot`?
Например, когда он обернут в компонент, который слушает изменения стора, бывает нужно для того, чтобы менять тему самого `AppRoot`. Тогда получается, что каждое обновление стора вызывает ререндер `AppRoot` и компонентов `VKUI`.
Пример с вспроизведением: https://7zmxhp.csb.app/
<details>
<summary>
Нужно посмотреть что происходит в react profiler при каждом ререндере AppRoot.
</summary>
| До | После |
|---|----|
| <img width="967" alt="Screenshot 2024-09-26 at 16 17 16" …
=> fix(AppRoot): Use memo for AppRootContext value

benchmark/runtime/webpack.config.mjs, package.json, styleguide/pages/css_modules.md, webpack.common.config.js, yarn.lock
- close #6805
---
С `v7.0.0` по умолчанию используется именованный экспорт CSS-модулей, поэтому отключил это поведение через опцию `namedExport: false` (см. подробнее в релиз ноуте https://github.com/webpack-contrib/css-loader/blob/v7.1.0/CHANGELOG.md). Расширил документацию `styleguide/pages/css_modules.md` на эту тему.
Также, для подстраховки, явно выставил `modules: false` там, где не нужны CSS-модули.
- Раздел **CSS Modules** дополнен информацией про использование пакета с `'css-loader' >= 7.0.0`.
=> build(dev-deps): Bump css-loader from 6.10.0 to 7.1.2

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
В описании свойства залезло TODO. В мастере его уже нет, но есть в v6 
Удаляем TODO из описания
-
=> docs(HorizontalScroll): rm TODO from description

packages/vkui/src/components/BaseGallery/CarouselBase/CarouselBase.tsx, packages/vkui/src/components/Gallery/Gallery.test.tsx
- close #7672 
---
Помечаем галерею неинициализированной в случае, когда кол-во слайдов = `0`
- Gallery: исправлена ошибка при отсутствии слайдов в режиме `looped`
=> fix(CarouselBase): fix error when no slides

packages/codemods/src/transforms/v7/__testfixtures__/separator/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/separator.ts.snap, packages/codemods/src/transforms/v7/__tests__/separator.ts, packages/codemods/src/transforms/v7/separator.ts, packages/vkui/src/components/Separator/Readme.md, packages/vkui/src/components/Separator/Separator.module.css, packages/vkui/src/components/Separator/Separator.test.tsx, packages/vkui/src/components/Separator/Separator.tsx
`mode` не подходит для изменения цветовой палитры, используем `appearance`
- Separator: свойство `mode` заменено на `appearance` 
```diff
<Separator
-  mode="primary"
+  appearance="primary"
/>
```
=> refactor(Separator): rename mode to appearance

packages/vkui/src/components/Typography/EllipsisText/EllipsisText.module.css, packages/vkui/src/components/Typography/EllipsisText/EllipsisText.tsx
- close #7636
---
Необходимо добавить установку аттрибута `title` для компонента `EllipsisText` с полным текстом
- Добавил установку аттрибута `title` для компонента `EllipsisText` 
- Добавил проп `disableNativeTitle` для отключения отображения нативного тултипа, на случай, если пользователь захочет добавить отображение настоящего тултипа поверх `EllipsisText`
- EllipsisText: у компонента был добавлен аттрибут `title`, который отображает весь текст переданный в компонент. Его также можно отключить передав параметр `disableNativeTitle`
=> feat(EllipsisText): add title attribute

packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx
- close #7670 
---
Сейчас выбор промежутка дат в `CalendarRange` выглядит и работает очень не очевидно для пользователя. Нужно  поменять логику выбора даты на более понятную. В кратце, необходимо третьим кликом на дату сбрасывать выбранный промежуток и давать пользователю выбрать новый промежуток
- Доработал логику выбора даты в `CalendarRange` 
- Поправил и добавил unit тесты для нового поведения 
- CalendarRange: изменена логика выбора промежутка дат, теперь для сброса промежутка надо кликнуть на третью дату и можно выбрать новую дату
=> feat(CalendarRange): update calendar range select logic

packages/vkui/src/components/Flex/Flex.tsx, packages/vkui/src/components/Flex/FlexItem/FlexItem.tsx, packages/vkui/src/components/SimpleGrid/SimpleGrid.tsx
По просьбе из чата расширяем `Flex`, `Flex.Item` и `SimpleGrid` пропами из `RootComponent`
- Flex: свойства теперь наследуются из `RootComponentProps`
- SimpleGrid: свойства теперь наследуются из `RootComponentProps`
=> feat(Flex, SimpleGrid): extends from RootComponentProps

packages/vkui-floating-ui/package.json
К сожалению, текущими тестами это не отловить. Возможно, нужна тестовая сборка чисто под `mjs` на будущее.
Пытался собрать Vite + TS + React + VKUI + SSR используя дефолтный [шаблон](https://github.com/bluwy/create-vite-extra/tree/master/template-ssr-react-ts), но наткнулся на ошибку:
```sh
/Users/andrey.medvedev/src/experiment/vkui-ssr-7529/node_modules/@vkontakte/vkui-floating-ui/utils/dom/floating-ui.utils.dom.esm.js:1
import { _ as _instanceof } from "@swc/helpers/_/_instanceof";
^^^^^^
SyntaxError: Cannot use import statement outside a module
at wrapSafe (node:internal/modules/cjs/loader:1378:20)
at Module._compile (node:internal/modules/cjs/loader:1428:41)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32) …
```
=> fix(vkui-floating-ui): esm with .mjs

package.json, yarn.lock
- relates to #7709
Обновление eslint-plugin-import from 2.30.0 to 2.31.0
=> build(deps-dev): Bump eslint-plugin-import from 2.30.0 to 2.31.0

packages/vkui/src/components/Button/Button.tsx
Из-за неверного порядка css в cssm сборке `<Button loading/>` становится высоким
Добавили импорт Tappable.module.css чтобы изменить порядок css
- [Button](https://vkcom.github.io/VKUI/${version}/#/CustomSelect): loading неверно отображался в cssm сборке
=> fix(Button): import Tappable.module.css

packages/codemods/src/transforms/v7/__testfixtures__/horizontal-cell/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/horizontal-cell.ts.snap, packages/codemods/src/transforms/v7/__tests__/horizontal-cell.ts, packages/codemods/src/transforms/v7/horizontal-cell.ts, packages/vkui/src/components/HorizontalCell/HorizontalCell.e2e-playground.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.stories.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.test.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx, packages/vkui/src/components/HorizontalCell/Readme.md, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-android-chromium-dark-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-android-chromium-light-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-ios-webkit-dark-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-ios-webkit-light-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.e2e-playground.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.stories.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.e2e-playground.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.stories.tsx, packages/vkui/src/components/View/View.stories.tsx, packages/vkui/src/components/View/View.test.tsx, packages/vkui/src/components/View/ViewInfinite.test.tsx
- close #7697 
---
Переименовать свойство `header` на `title` в компоненте `HorizontalCell`
- HorizontalCell: свойство `header` переименовано на `title`
=> feat(HorizontalCell): rename prop header to title

packages/codemods/src/transforms/v7/__testfixtures__/rich-cell/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/rich-cell.ts.snap, packages/codemods/src/transforms/v7/__tests__/rich-cell.ts, packages/codemods/src/transforms/v7/rich-cell.ts, packages/vkui/src/components/RichCell/Readme.md, packages/vkui/src/components/RichCell/RichCell.e2e-playground.tsx, packages/vkui/src/components/RichCell/RichCell.module.css, packages/vkui/src/components/RichCell/RichCell.stories.tsx, packages/vkui/src/components/RichCell/RichCell.test.tsx, packages/vkui/src/components/RichCell/RichCell.tsx, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-light-1-snap.png
- close #7716 
---
Необходимо переименовать свойство `text` в `subtitle`, `caption` в `extraSubtitle`, `subhead` в `overTitle` компонента RichCell
- RichCell:
- Переименовано свойство `text` на `subtitle`
- Переименовано свойство `caption` на `extraSubtitle`
- Переименовано свойство `subhead` на `overTitle`
=> feat(RichCell): rename props header, text, caption

packages/vkui/package.json
В #7611 забыли про `package.json`, который можно импортировать.
- в поле `"exports"` добавлен `package.json`
=> fix: add package.json to "exports" field

packages/vkui/playwright-ct.config.ts, packages/vkui/src/testing/e2e/index.playwright.ts
- caused by #7728 
---
После PR #7728 скриншоты генерируются и проверяются только для `light` `colorSheme`. Так происходит из-за неправильно прокинутого значения свойства.
Поправил именование свойства `colorScheme` на `colorSchemeType`. Использовано это имя так как `colorScheme` уже есть в playwright
-
=> fix: fix generating screenshots names

packages/codemods/src/transforms/v7/__testfixtures__/screen-spinner/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/screen-spinner.ts.snap, packages/codemods/src/transforms/v7/screen-spinner.ts, packages/vkui/src/components/ScreenSpinner/Readme.md, packages/vkui/src/components/ScreenSpinner/ScreenSpinner.e2e-playground.tsx, packages/vkui/src/components/ScreenSpinner/ScreenSpinner.module.css, packages/vkui/src/components/ScreenSpinner/ScreenSpinner.tsx, packages/vkui/src/components/ScreenSpinner/ScreenSpinnerContainer.tsx, packages/vkui/src/components/ScreenSpinner/ScreenSpinnerLoader.tsx, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-android-chromium-dark-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-android-chromium-light-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-ios-webkit-light-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/ScreenSpinner/__image_snapshots__/screenspinner-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/ScreenSpinner/context.ts, packages/vkui/src/components/ScreenSpinner/types.tsx
- close #7789
---
В компоненте `ScreenSpinner` и в его подкомпоненте `ScreenSpinner.Container` переименовал свойство `caption` на `label`
- ScreenSpinner: свойство `caption` переименовано на `label`
```diff
<ScreenSpinner
state="loading"
- caption="Caption"
+ label="Caption"
/>
<ScreenSpinner.Container
- caption="Caption"
+ label="Caption"
>
<ScreenSpinner.Loader />
<ScreenSpinner.SwapIcon />
</ScreenSpinner.Container>
```
=> feat(ScreenSpinner): rename prop caption to label

packages/codemods/README.md, packages/codemods/src/cli.ts, packages/codemods/src/index.ts, packages/codemods/src/transforms/v7/__testfixtures__/spacing/basic.input.tsx, packages/codemods/src/transforms/v7/__tests__/__snapshots__/spacing.ts.snap, packages/codemods/src/transforms/v7/cell-button.ts, packages/codemods/src/transforms/v7/common/remapSizePropValue.ts, packages/codemods/src/transforms/v7/config-provider.ts, packages/codemods/src/transforms/v7/image-overlay.ts, packages/codemods/src/transforms/v7/users-stack.ts
- отредактировано README.md
- исправлены информационные сообщения
- добавлена возможность вывода информации о ручных миграциях в файл (`--log-file <file>`)
- добавлена возможность применить несколько миграций одновременно (а не только все или одну) (`[codemod-names...]`)
- добавлена возможность задать несколько путей, в которых необходимо применить миграции (`--path [paths...]`)
- добавлена возможность вместо путей указать конкретные файлы или директории через файл (`--input-file <file>`)
- в миграции по `Spacing` ограничена обработка  не-строковых нод
-
=> feat: enhance codemods

packages/vkui/src/components/Separator/Readme.md, packages/vkui/src/components/Separator/Separator.e2e-playground.tsx, packages/vkui/src/components/Separator/Separator.module.css, packages/vkui/src/components/Separator/Separator.stories.tsx, packages/vkui/src/components/Separator/Separator.tsx, packages/vkui/src/components/Separator/__image_snapshots__/separator-android-chromium-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-android-chromium-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-ios-webkit-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-webkit-light-1-snap.png
- close #7760
---
Значения Separator свойства direction переименованы с 'block'|'inline' на 'vertical'|'horizontal'
> **Release notes** см. #7720
-
=> feat(Separator): rename separator direction values

package.json, yarn.lock
- see GHSA-4wx3-54gh-9fr9
- https://redirect.github.com/styleguidist/react-styleguidist/issues/2167
---
Запихнул в resolutions, так как styleguidist скорее всего не обновится
-
=> build(dev-deps): Update markdown-to-jsx to 7.5.0

packages/vkui/src/components/FormItem/FormItem.tsx
@andres-kovalev заметил, что в доках просвечивается TODO параметра `topNode`. Удалил под **v6**.
- FormItem: удалён **TODO** текст у параметра `topNode`
=> [v6]fix(FormItem): rm TODO from topNode description

packages/vkui/src/components/Badge/Readme.md, packages/vkui/src/components/Flex/Readme.md, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx, packages/vkui/src/components/Typography/EllipsisText/Readme.md, packages/vkui/src/components/View/Readme.md
- caused by #7698
- caused by #7792
- caused by #7783
- caused by #7793
---
Исправляем неисправленное
=> fix: docs typos

packages/vkui/src/hooks/usePatchChildren.test.tsx, packages/vkui/src/hooks/usePatchChildren.ts, packages/vkui/src/index.ts
- related to #7611
---
Добавил тестов для покрытия `100%`.
- Добавлен экспорт `usePatchChildren()` – хук позволяет пропатчить переданный компонент так, чтобы можно было получить ссылку на его DOM-элемент. Также есть возможность прокинуть в компонент дополнительные параметры.
=> feat(usePatchChildren): add reexport

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
На touch устройстве не работает фокус на input при клике в зоне инпута ближе к стрелочке. Фокус есть на обертке, но сам инпут фокуса не имеет и клавиатура не появляется, как при клике на сам инпут, ближе к левому краю.
Воспроизводится в симуляторе Iphone и на реальном устройстве.
Дело в том, что не во всей видимой области инпута событие клика принимает input, и чтобы это победить мы программно вызываем фокус на инпуте.
Изначально, в https://github.com/VKCOM/VKUI/pull/6087, а конкретно в https://github.com/VKCOM/VKUI/commit/0f45bb9d02406a7db9bf918b27ccecc1f46f5621 это было реализовано с помощью отложенного вызова фокуса для кнопки очистки, а потом функция с отложенным фокусом перекочевала и на остальной новый код.
Объяснялось это тем, что без таймаута фокус просто не работал при клике на …
=> fix(CustomSelect): Fix input focus on arrow click on touch device

packages/vkui/src/components/ScreenSpinner/ScreenSpinnerLoader.tsx
Убираем текст по умолчанию, как договорились в [обсуждении](https://github.com/VKCOM/VKUI/pull/7505#discussion_r1754153438)
- ScreenSpinner: удалён `a11y`-текст по умолчанию, передавайте нужный текст в `children` или `label` свойства.
=> fix: remove default a11y text

packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/Spinner/Spinner.module.css
У `Spinner` есть проп `noColor`, вместо css-каскада рекомендуем использовать его.
- PanelHeader: теперь неявно не переопределяется цвет компонента `Spinner`, если вы использовали компонент `Spinner` внутри `PanelHeader` передавайте `<Spinner noColor />`
=> fix: remove spinner todo

packages/vkui/src/components/AppRoot/ScrollContext.tsx, packages/vkui/src/hooks/useCounter.test.tsx, packages/vkui/src/hooks/useCounter.ts
API useCounter не похоже на useState
- Делаем возврат функции useCounter похожим на useState
- Добавляем документацию
- Добавляем тестов
-
=> refactor(useCounter): add docs and tests

packages/vkui/scripts/postcss.js, packages/vkui/src/components/Badge/Badge.tsx, packages/vkui/src/components/ContentBadge/ContentBadge.tsx, packages/vkui/src/lib/platform.ts
Нужно убрать устаревшие `TODO >=7 `или поменять их на `>=8`
- В компоненте `ContentBadge` убрал `TODO [>=7]: переименовать в Badge`, в компоненте Badge убрал `TODO [>=7]: переименовать в Dot` (см. [ссылка на обсуждение](https://github.com/VKCOM/VKUI/issues/6444#issuecomment-2260272471))
- В `postcss.js` поменял `TODO [>=7]` на `TODO [>=8]` так как в `v7` `gap` так и не поддерживается всем браузерами
- В `platform.ts` поменял `TODO [>=7]` на `TODO [>=8]` , так как пока не договорились об именовании
-
=> fix: remove or edit TODO [>=7]

packages/codemods/src/transforms/v7/__tests__/__snapshots__/form-item.ts.snap, packages/codemods/src/transforms/v7/form-item.ts, packages/vkui/src/components/FormItem/FormItem.e2e-playground.tsx, packages/vkui/src/components/FormItem/FormItem.stories.tsx, packages/vkui/src/components/FormItem/FormItem.test.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/FormItem/FormItemTop/FormItemTop.mdx, packages/vkui/src/components/FormItem/Readme.md
Нужно в компоненте `FormItem` избавиться от свойства `topNode` и заменить на `top`.
Для сохранения совместимости теперь при прокидывании в top ReactElement она рендерится без оборачивания в другие компоненты, а при прокидывании строки, оборачивается в FormItemLabel
- FormItem: удалено свойство `topNode`, вместо него можно использовать свойство `top`
<details>
<summary>Пример миграции</summary>
```diff
<FormItem
- topNode={
+ top={
<FormItem.Top>
<FormItem.TopLabel htmlFor="about">Дополнительная информация</FormItem.TopLabel>
<FormItem.TopAside>0/100</FormItem.TopAside>
</FormItem.Top>
}
>
<Textarea id="about" name="about" />
</FormItem>
```
</details>
=> [BREAKING CHANGE] feat(FormItem): remove topNode

packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Button/Button.tsx
- Fixes #7663
---
Кнопка со свойством `loading` была кликабельна
Кнопка при `loading` теперь имеет атрибут `disabled`
- [Button](https://vkcom.github.io/VKUI/${version}/#/Button): кнопка со свойством `loading` была кликабельна
=> fix(Button): loading is disabled

packages/vkui/src/index.ts
Экспортируем тип
- Добавлен экспорт типа `CustomTouchEvent`
=> feat: add CustomTouchEvent export

packages/vkui/src/components/Button/Button.module.css, packages/vkui/src/components/Button/Button.tsx, packages/vkui/src/components/Flex/FlexItem/FlexItem.module.css, packages/vkui/src/components/Flex/FlexItem/FlexItem.tsx, packages/vkui/src/hooks/useAdaptivityConditionalRender/constants.ts, packages/vkui/src/hooks/useAdaptivityConditionalRender/helpers.ts, packages/vkui/src/hooks/useAdaptivityConditionalRender/useAdaptivityConditionalRender.test.tsx, packages/vkui/src/hooks/useAdaptivityConditionalRender/useAdaptivityConditionalRender.tsx, packages/vkui/src/styles/adaptivity.module.css
Удаляем мертвый css код
Перепилил слегка внутрянку useAdaptivityConditionalRender
-
=> refactor(css): rm deadly code

packages/vkui/src/components/BaseGallery/BaseGallery.tsx, packages/vkui/src/components/Gallery/Gallery.test.tsx
- close #7841
---
В условиях, когда слайды выравниваются по центру, у активного слайда слева появляется отступ от левого края, за счёт которого слайды смещаются вправо.
В такой ситуации перестаёт правильно работать условие, выключающее переключение между слайдами, когда общая ширина слайдов меньше контейнера. 
Если общая ширина слайдов меньше контейнера и они за счёт отступа всё же не помещаются в контейнере, то нужно также учесть этот отступ в условии, иначе при отключении навигации будет невозможно полностью увидеть скрытый слайд.
- Добавлено особое условия в режиме `align="center"` для подсчёта флага отключения навигации, учитывающее отступ, появляющийся при выравнивании по центру.
- Gallery: не работало переключение слайдов в условиях, когда общая ширина слайдов меньше контейнера, но …
=> fix(Gallery): navigation doesn't work when align="center" and slides overflow just a little

packages/vkui/src/components/BaseGallery/BaseGallery.tsx, packages/vkui/src/components/Gallery/Gallery.test.tsx
=> patch: pr7862

packages/vkui/src/components/AppRoot/ScrollContext.test.tsx, packages/vkui/src/components/AppRoot/ScrollContext.tsx
- cherry-pick #6759
---
`GlobalScrollController` теперь установливает `overscroll-behavior: none` на `<html>`, чтобы избегать **pull-to-refresh**.
- useScrollLock: теперь при `<AppRoot scroll="global" />` в `<html>` добавляется `overscroll-behavior: none`, чтобы избегать **pull-to-refresh**.
=> feat(AppRoot): set overscrollBehavior to <html>

packages/vkui/src/components/FocusTrap/FocusTrap.tsx, packages/vkui/src/hooks/useFocusTrap.ts
- cherry-pick #6759
---
Код `FocusTrap` вынесен в `useFocusTrap`, чтобы была возможность использовать его со своим DOM элементом.
-
=> refactor(FocusTrap): mv to hook

packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/hooks/useDateInput.ts
- close #7865 
---
Нужно для компонентов `DateInput`, `DateRangeInput` добавить свойство `onCalendarOpenChanged` колбэк, который будет срабатывать при изменении состояния открытости календаря
Добавил свойство `onCalendarOpenChanged` для компонентов  `DateInput`, `DateRangeInput`
- DateInput: добавлено свойство `onCalendarOpenChanged` - колбэк, срабатывающий при открытии/закрытии календаря
- DateRangeInput: добавлено свойство `onCalendarOpenChanged` - колбэк, срабатывающий при открытии/закрытии календаря
=> feat(DateInput, DateRangeInput): add prop `onCalendarOpenChanged`

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
- close #7774
---
Сейчас при наведении на стрелки в компоненте `HorizontalScroll` не происходит скролл колесиком мыши.
- Сделал небольшой рефакторинг компонента `HorizontalScroll`, а именно избавился от подписок на события `wheel` и `scroll` через `useEventListener`. Теперь используется стандартный механизм `React` для подписки на события
- Добавил обработчики `wheel` события на стрелках и обработал их, как событие `wheel` на scroll контейнере
- HorizontalScroll: исправлена проблема с отсутствием скрола при наведении на стрелки
=> fix(HorizontalScroll): fix scroll when mouse over arrow

packages/vkui/src/lib/animation/index.ts, packages/vkui/src/lib/animation/useCSSTransition.stories.module.css, packages/vkui/src/lib/animation/useCSSTransition.stories.tsx, packages/vkui/src/lib/animation/useCSSTransition.test.tsx, packages/vkui/src/lib/animation/useCSSTransition.ts
- cherry-pick #6759
---
По аналогии `useCSSKeyframesAnimationController`, а также на основе компонента `CSSTransition` из [react-transitiong-group](https://reactcommunity.org/react-transition-group/css-transition) создал хук, чтобы можно было управлять переходами монтирования/размонитрования
-
=> feat: create useCSSTransition()

packages/vkui/src/components/Flex/Readme.md
Добавляем в пример возможность убрать проп `gap`
- Flex: добавили возможность не задавать свойство `gap`
=> feat: add no gap to Flex example

packages/vkui/src/components/Gallery/Gallery.tsx, packages/vkui/src/components/Gallery/hooks.test.ts, packages/vkui/src/components/Gallery/hooks.ts
=> patch: pr7877

packages/vkui/src/components/Clickable/useState.tsx, packages/vkui/src/components/Tappable/Tappable.test.tsx
- related #7519
Условия: есть два вложенных в друг друга `Tappable`-компонента. Если мы управляем `active`-состоянием "сверху", то у нас всплывают вот такие артефакты, когда мы кликаем на родительский компонент (и при клике сетаем проп `activated=true`) и достаточно быстро на дочерний:
https://github.com/user-attachments/assets/c71d1687-2ce2-44aa-b4e4-b97c642be1e9
Из-за того, что в #7519 обновление `active`-состояния завязано на `ref`, то обновления родительского компонента мы не увидим до следующего ререндера.
- при вычисление `active/hover`-состояния при условии наличия `activated/hovered` пропов мы должны всегда полагаться на эти значения, вне зависимости от состояния `isLocked`.
- ещё заметила, что потерялось свойство `hasActive` - оно не прокидывалось и не участвовало в вычислении …
=> fix(Tappable): force activated/hovered state

packages/vkui/package.json, packages/vkui/src/components/Avatar/helpers.ts, packages/vkui/src/components/Placeholder/Placeholder.tsx, packages/vkui/src/index.ts
- related #7766
---
Некоторые типы остались со старыми названиями + добавляем импорт типов `FlexItem`, `ChipOptionValue`,
`ChipOptionLabel` и `CustomScrollViewProps`
- Flex: импортирован тип `FlexItem` для `Flex.Item`
- ChipsInput: импортированы типы `ChipOptionValue` и `ChipOptionLabel`
- CustomScrollView: импортирован тип `CustomScrollViewProps`
=> feat: add more exports

packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx
При ручном вводе даты (со временем и без), необходимо занулять секунды/миллисекунды (с часами и минутами, если дата без времени).
- DateInput: инициализируем секунды и миллисекунды (часы и минуты при вводе без времени) нулевыми значениями при ручном вводе даты
=> fix(DateInput): use zero values with keyboard input

packages/vkui/src/components/Calendar/Calendar.test.tsx, packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/CalendarDay/CalendarDay.test.tsx, packages/vkui/src/components/CalendarDay/CalendarDay.tsx, packages/vkui/src/components/CalendarDays/CalendarDays.tsx, packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx, packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
=> patch: pr7705 in v6

packages/vkui/src/components/Calendar/Calendar.test.tsx, packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/CalendarDay/CalendarDay.test.tsx, packages/vkui/src/components/CalendarDay/CalendarDay.tsx, packages/vkui/src/components/CalendarDays/CalendarDays.tsx, packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx, packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
=> patch: pr7705

packages/vkui/src/components/Clickable/Clickable.module.css, packages/vkui/src/components/Clickable/Clickable.tsx
Поправил значения свойства `-webkit-tap-highlight-color` на валидное `transparent` вместо `none`.
- caused by #6881
**UPD**
см. https://github.com/VKCOM/VKUI/pull/7908#pullrequestreview-2420505937
- перенёс `-webkit-tap-highlight-color` в `.realClicable`;
- перенёс логику `getUserAgentResetClassName` в CSS – увеличили специфичность, но для этих стилей допустимо
- Tappable: в кликабельных компонентах исправлена проблема, когда при касании через тач появлялся системный оверлей
=> fix(Clickable): use correct CSS property values

packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx
=> patch: pr7872

packages/vkui/src/components/Clickable/useState.tsx, packages/vkui/src/components/Tappable/Tappable.test.tsx
- cherry-pick #7906
- Tappable: вернули работу `hasActive` свойства, исправили отсутствие `activated`-состояния при некоторых условиях
=> fix(Tappable): force activated/hovered state (#7906)

packages/vkui/src/components/FocusTrap/FocusTrap.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/components/Popover/Readme.md, packages/vkui/src/lib/floating/types/component.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/index.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts, packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
=> patch: pr7806 in v6

packages/vkui/src/components/Gallery/Gallery.e2e-playground.tsx, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-webkit-light-1-snap.png
Задаем обертке фиксированную ширину, чтобы нивелировать родительскую обертку
-
=> fix(Gallery): try to fix flaky test

packages/vkui/src/components/Calendar/Calendar.tsx
- relates #7705 
---
Была проблема, что некоторые id для тестирование не прокидывались до `CalendarTime` через `Calendar`
=> fix(Calendar): fixed props passing with id for testing from Calendar to CalendarTime

packages/vkui/src/components/Group/Group.module.css
- Fixes #6977
---
Сепаратор в группе неверно отрисовывается на iPhone 15. Также размер отступа между группами не совпадает с дизайном
Исправил размер блока с сепаратором за счет отрицательного margin-block-end
- [Group](https://vkcom.github.io/VKUI/${version}/#/Group): исправлено отображение сепаратора на iPhone 15
=> fix(Group): separator size

packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx, packages/vkui/src/components/Skeleton/Skeleton.tsx, packages/vkui/src/hooks/usePrevious.ts, packages/vkui/src/hooks/useStateWithPrev.test.ts, packages/vkui/src/hooks/useStateWithPrev.ts, packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.ts, packages/vkui/src/lib/animation/useCSSTransition.ts, packages/vkui/src/lib/floating/usePlacementChangeCallback.ts
- see #6919
---
> ...
>
- Добавляем хук `useStateWithPrev`
- Депрекейтим `usePrevious`
-
=> feat: add useStateWithPrev

packages/vkui/src/components/View/useLayoutEffectCall.tsx
- see #6919
---
> ...
>
Заменяем useRef  на useState в хуке `useLayoutEffectCall`
-
=> fix(useLayoutEffectCall): rm useRef

packages/vkui/src/components/Link/Link.e2e-playground.tsx, packages/vkui/src/components/Link/Link.e2e.tsx, packages/vkui/src/components/Link/Link.module.css, packages/vkui/src/components/Link/Link.stories.tsx, packages/vkui/src/components/Link/Link.test.tsx, packages/vkui/src/components/Link/Link.tsx, packages/vkui/src/components/Link/Readme.md, packages/vkui/src/components/Link/__image_snapshots__/link-icon-gaps-android-chromium-light-1-snap.png
- close #6855
---
- ~[ ] Дизайн-ревью~ – вернул старое поведение
Решение из #7579 не подошло из-за того, что подчеркивания распространяется и на пробел.
_До #7579_
_После #7579_
По аналогии с другими компонентами, самое простое оказалось добавить `before` / `after` с указанием отступов через соответствующие CSS классы, что избавляет от каскада `.host :global(.vkuiIcon)`.
Заодно добавил свойство `noUnderline`.
<details><summary>Нюансы про альтернативное решение</summary>
<p>
Решение через `.host :global(.vkuiIcon:first-child)` и `.host :global(.vkuiIcon:last-child)` не работает без оборачивания текстового блока в DOM-элемент. Здесь без просьбы пользователя оборачивать в `<span>` никак.
</p>
</details> 
- Link: теперь для передачи иконок следует использовать параметры `before` и `after`, …
=> feat(Link): add props – before, after, noUnderline

packages/vkui/src/lib/SSR.tsx, packages/vkui/src/lib/dom.tsx
В компоненте SSRWrapper есть провайдер DOMContext который записывает в контекст те же данные, что и у контекста по умолчанию
Удалил DOMContext.Provider из SSRWrapper
-
=> refactor(SSR): rm DOMContext

packages/vkui/src/components/Accordion/Accordion.tsx, packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx, packages/vkui/src/components/FormItem/FormItem.tsx, packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx, packages/vkui/src/components/NavTransitionContext/NavTransitionContext.tsx, packages/vkui/src/components/SplitCol/SplitCol.tsx, packages/vkui/src/hooks/useObjectMemo.ts
- see #6919
---
> ...
>
Депрекейтим `useObjectMemo`, меняем в некоторых местах на `React.useObjectMemo`
-
=> fix: deprecate useObjectMemo

packages/vkui/src/hooks/useStableCallback.ts
- see #6919
---
> ...
>
Заменяем useRef  на useCallback в хуке `useStableCallback`
-
=> fix(useStableCallback): rm useRef

packages/vkui/src/components/Tappable/Tappable.tsx
- caused by #6132
---
В ходе рефакторинга потерялся глобальный класс `vkuiInternalTappable`
- Tappable: возвращена компенсация отступа при оборачивании `Header`
=> fix(Tappable): bring back vkuiInternalTappable

packages/vkui/src/components/Separator/Separator.e2e-playground.tsx, packages/vkui/src/components/Separator/Separator.tsx, packages/vkui/src/components/Separator/__image_snapshots__/separator-android-chromium-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-android-chromium-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-ios-webkit-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Separator/__image_snapshots__/separator-vkcom-webkit-light-1-snap.png, packages/vkui/src/components/Spacing/Spacing.e2e-playground.tsx, packages/vkui/src/components/Spacing/Spacing.test.tsx, packages/vkui/src/components/Spacing/Spacing.tsx, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-webkit-light-1-snap.png, packages/vkui/src/lib/spacings/sizes.ts
Иногда необходима возможность передать в кач-ве `size` просто `css`-переменную - для это даем возможность пробросить строку, которая начинается с `--`
- Spacing: добавлена возможность передать `css`-переменную в `size` 
- Separator: добавлена возможность передать `css`-переменную в `size`
=> feat(Spacing): add css variables support

packages/vkui/src/components/AspectRatio/AspectRatio.tsx, packages/vkui/src/components/Flex/Flex.tsx, packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx, packages/vkui/src/components/Image/Image.tsx, packages/vkui/src/components/Popper/Popper.tsx, packages/vkui/src/components/Progress/Progress.tsx, packages/vkui/src/components/Separator/Separator.tsx, packages/vkui/src/components/SimpleGrid/SimpleGrid.tsx, packages/vkui/src/components/Skeleton/Skeleton.tsx, packages/vkui/src/components/Spacing/Spacing.tsx, packages/vkui/src/helpers/mergeStyle.test.ts, packages/vkui/src/helpers/mergeStyle.ts
В свойствах стилей часто используются спреды, которые копируют значения объектов
- see https://github.com/VKCOM/VKUI/pull/7977#discussion_r1853765189
Добавляем функцию mergeStyle которая уменьшает количество компирований 
-
=> refactor: add mergeStyle

.github/workflows/branch_test_coverage.yml, .github/workflows/pull_request_packages_deploy.yml
Используем [OIDC](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect) подпись вместо токена для Codecov
-
=> ci(codecov): use_oidc

.github/workflows/monday.yml
Добавляем экшон для обновление пакетного менеджера по крону каждый понедельник.
Экшон запускает команду [corepack up](https://github.com/nodejs/corepack?tab=readme-ov-file#corepack-up) и пытается обновить поле `"packageManager"` в файле package.json
Если поле было изменено, автоматически создается Pull Reques
-
=> ci(cron): add corepack-up-pr

packages/vkui/src/components/AdaptivityProvider/AdaptivityContext.tsx, packages/vkui/src/components/ColorSchemeProvider/ColorSchemeProvider.tsx, packages/vkui/src/components/ConfigProvider/ConfigProviderContext.tsx, packages/vkui/src/components/ContentBadge/ContentBadgeContext.tsx, packages/vkui/src/components/ModalRoot/ModalRootContext.tsx, packages/vkui/src/components/NavIdContext/NavIdContext.tsx, packages/vkui/src/components/ScreenSpinner/context.ts
- fix #6288
---
Отсутствуют директивы `"use client"` в местах использования `createContext`
Добавил директив. Требуется добавить их обработку в eslint-plugin-react-server-components
- Добавлены директивы `"use client"` в местах использования `createContext`
=> fix: add use client for createContext

packages/vkui/src/components/Spinner/Spinner.tsx, packages/vkui/src/components/Spinner/SpinnerAnimation.tsx, packages/vkui/src/lib/animation/useReducedMotion.ts
- see #6919
---
> ...
>
- Используем useState вместо  useRef
- Делаем хук useReducedMotion более дружелюбным к SSR
- Оптимизируем …
=> fix(useReducedMotion): use state

packages/vkui/src/components/ModalCard/ModalCard.tsx
- caused by #6759
Параметр попадал в DOM
- ModalCard: в **DOM** попадал параметр `shouldPreserveSnapPoint`, из-за чего **React** кидал предупреждение в консоль.
=> fix(ModalCard): exclude unused `shouldPreserveSnapPoint`

packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/Calendar/Readme.md, packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/DateInput/DateInput.tsx
- close #7968 
---
Нужно добавить возможность установки кастомной кнопки "Готово" в компоненте Calendar
- Добавил проп DoneButton для компонента Calendar для отрисовки кастомной кнопки
- Calendar: добавлено свойство DoneButton для отрисовки кастомной кнопки "Готово"
<details>
<summary>Пример</summary>
```diff
<Calendar
value={value}
onChange={setValue}
+ DoneButton={(doneButtonProps) => (
+   <Button {...doneButtonProps} mode="primary" />
+ )}
/>
```
</details>
- DateInput: добавлено свойство DoneButton для отрисовки кастомной кнопки "Готово"
<details>
<summary>Пример</summary>
```diff
<DateInput
value={value}
onChange={setValue}
+ DoneButton={(doneButtonProps) => (
+   <Button {...doneButtonProps} mode="primary" />
+ )}
/>
```
</details>
=> feat(Calendar): add prop DoneButton to customize done button

packages/vkui/src/components/Pagination/Pagination.test.tsx, packages/vkui/src/components/Pagination/Pagination.tsx, packages/vkui/src/components/Pagination/PaginationNavigationButton/PaginationNavigationButton.tsx
- related https://github.com/VKCOM/VKUI/issues/6219
---
Добавляем пропы для передачи testid в кнопки страниц и кнопки `next/prev`.
В `Pagination` есть возможность рендерить кнопки кастомно и даже передётся `page-data` с номером кнопки, но это не то же самое, что и `data-testid`.  Унифицируем этот момент и добавляем в API.
- Pagination: добавлены новые свойства `pageButtonTestId`, `prevButtonTestId`, `nextButtonTestId` для передачи `data-testid` в интерактивные элементы.
=> feat(Pagination): Add testid for buttons

packages/vkui/src/components/NativeSelect/NativeSelect.tsx
`styleguidist` по умолчанию опирается на первый импорт чего-то, что напоминает реакт-компонент, поэтому иногда ловим артефакты с неправильным наименованием:
Т.к. мы не можем влиять на это поведение извне, а уносить эту функцию в отдельный файл не очень хочется - пока оставляем "костыль" 🙃  
- NativeSelect: исправлено наименование компонента
=> docs: fix NativeSelect name

packages/vkui/src/components/PanelHeader/PanelHeader.module.css
- close #7895 
---
Сейчас есть проблема, что при отключенном разделителе(`delimiter="none"`), при `float={true}` и при прозрачной панели(`transparent={true}`) все равно отображается разделитель, который наезжает на контент и портит вид.
Добавил проверку на отсутствие селектора `.trnsp` при отрисовке разделителя.
- PanelHeader: отключен разделитель при прозрачном `PanelHeader` и `delimiter="none"`
=> fix(PanelHeader): hide separator with transparent PanelHeader

packages/vkui/src/components/ActionSheet/ActionSheet.tsx
- close #8044
---
Сейчас в `ActionSheet` нельзя прокинуть свойства `FocusTrap` по типам, хотя он используется в компоненте. Нужно доработать тип `ActionSheetProps`
- Доработал тип пропсов компонента `ActionSheet`, так чтобы он принимал все пропсы компонента `FocusTrap` и прокидывал их до него
- ActionSheet: Добавлена возможность прокидывать свойства `FocusTrap`в компонент
=> fix(ActionSheet): add FocusTrap props to ActionSheet props

package.json, yarn.lock
см. https://github.com/VKCOM/VKUI/security/dependabot/150
> [!NOTE]
>
> `webpack-dev-server` и `@rspack/dev-server` используют старую версию `express`. Решаем это через поле `"resolutions"` (da223b00fb71b69ec209a9cf829ad17871c1b290)
=> build(deps): Bump path-to-regexp from 0.1.10 to 0.1.12

packages/vkui/src/components/CardScroll/CardScroll.test.tsx, packages/vkui/src/components/CardScroll/CardScroll.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
- related https://github.com/VKCOM/VKUI/pull/8032
---
В [комментарии](https://github.com/VKCOM/VKUI/pull/8032#issuecomment-2532013976) @inomdzhon обратил внимание на то, что мы придерживаемся других имен для кнопок переключения вперёд/назад. 
> в случае HorizontalScroll и CardScroll по семантике не стоило ли назвать prevArrowTestId и nextArrowTestId?
>
> UPD
> или prevButtonTestId и nextButtonTestId
Например, в Calendar или Pagination мы используем `prevButton`/`nextButton` а не названия из логических свойств.
https://github.com/VKCOM/VKUI/blob/ef2d07e80aaab4505e743aa364f1f0a766d0e0d9/packages/vkui/src/components/Calendar/Calendar.tsx#L140-L141
https://github.com/VKCOM/VKUI/blob/ef2d07e80aaab4505e743aa364f1f0a766d0e0d9/packages/vkui/src/components/Pagination/Pagination.tsx#L128-L129
-
=> feat(HorizontalScroll/CardScroll): Rename testId props to prevButton/nextButton

packages/vkui/src/components/Snackbar/Snackbar.test.tsx, packages/vkui/src/lib/dom.test.ts, packages/vkui/src/lib/sheet/useBottomSheet.test.tsx, packages/vkui/src/lib/touch/UIPanGestureRecognizer.test.ts, packages/vkui/src/testing/utils.tsx
Зарезолвил TODO в тесте `useBottomSheet()`, который оставлял в #6759
Упростил `getFakeTouchEvent` и `getFakeMouseEvent` до функций, которые возвращают объект.
Заметил, что если вторым аргументом в `fireEvent` из `testing-library/react` передавать объект события, то он работает не корректно – лучше передавать сразу опции, которые принимают те или иные события.
-
=> test(todo): mv getFake*Event to *EventMock

package.json, packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.module.css, yarn.lock
Обновляем prettier до 3.4.2, в нем есть поддержка require(ESM) которую включили в node 22.12.0
-
=> build(deps-dev): Bump prettier to 3.4.2

.github/dependabot.yml
Попытка проигнорировать экспериментальные версии react-compiler, чтобы упростить обновление группы `eslint` с `dependabot`.
- see https://github.com/VKCOM/VKUI/pull/7643#issuecomment-2368477097 – здесь полный лог ошибок
- related to https://github.com/facebook/react/issues/30782, https://github.com/facebook/react/issues/31330
- related to https://github.com/VKCOM/VKUI/pull/8073
=> build(deps): Ignore 0.0.0-experimental-* compiler version

packages/vkui/src/components/Calendar/Calendar.test.tsx, packages/vkui/src/components/Checkbox/Checkbox.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/Gallery/Gallery.test.tsx, packages/vkui/src/components/GridAvatar/GridAvatar.test.tsx, packages/vkui/src/components/Group/Group.test.tsx, packages/vkui/src/components/ImageBase/ImageBase.test.tsx, packages/vkui/src/components/TabsItem/TabsItem.test.tsx, packages/vkui/src/lib/getNavId.test.ts, packages/vkui/src/testing/utils.tsx, packages/vkui/types/env.d.ts
При интеграции в проект NextJS проекта, возникают ошибки при общей проверке типов в проекте (из-за конфликтующих глобальных типов - @inomdzhon глаз алмаз х)):
- в тех тестах, где мы подменяет `env`-переменную используем, утилиту `setDevNodeEnv`.
- в наших типах также устанавливаем переменную в `readonly`
-
=> chore: fix next integration

packages/vkui/src/components/Popper/Popper.tsx
- close #8067
---
Сейчас свойство `zIndex` компонента `Popper`  работает некорректно.
Поправил установку `z-index` в `style` в компоненте `Popper`
- Popper: свойство `zIndex` теперь корректно устанавливает свойство `z-index`
=> fix(Popper): add support of prop zIndex

packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/components/TooltipBase/TooltipBase.module.css, packages/vkui/src/components/TooltipBase/TooltipBase.tsx
- Добавляем перенос строки, если неразрывный текст в Tooltip слишком длинный и не помещается по ширине.
- Исправляем опечатку в описании свойства.
| До | После |
|---|---|
| <img width="537" alt="Screenshot 2024-12-18 at 13 09 23" src="https://github.com/user-attachments/assets/c29e69cc-716f-43bc-a3c3-1b0f9af65971" /> | <img width="537" alt="Screenshot 2024-12-18 at 13 10 00" src="https://github.com/user-attachments/assets/18d28adc-f17a-4f98-b1a8-9bf389a10b54" /> |
- Tooltip: добавлен перенос на следующую строчку для `title` и `tooltip`, если длинное неразрывное слово не помещается в ширину тултипа.
=> fix(Tooltip): break word in title and description

packages/vkui/src/components/ModalRoot/Readme.md, styleguide/pages/migration_v7.md
- caused by #8065
В #6759 пропустил момент про обёртки.
- ModalRoot: добавлен **FAQ** с информацией как создавать обёртки над `ModalPage` и `ModalCard`
- В документе **Миграция с v6 на v7** дополнена секция `ModalRoot` информацией касаемой обёртки над `ModalPage` / `ModalCard`
=> docs(ModalRoot): add info about wrappers of modals

packages/vkui/src/components/Pagination/Pagination.e2e-playground.tsx, packages/vkui/src/components/Pagination/Pagination.tsx, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-android-chromium-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-android-chromium-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-ios-webkit-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-webkit-light-1-snap.png
Сейчас в компоненте `Pagination` в режиме `rtl` иконки стрелок отображаются некорректно
При `rtl` поменял местами иконки стрелок вперед/назад
- Pagination: Поправлено отображение компонента в `rtl`
=> feat(Pagination): fix rtl view

packages/vkui/src/components/Removable/Removable.module.css, packages/vkui/src/components/Removable/Removable.tsx
Сейчас компонент `Cell` при `mode="removable"` в `rtl` отображается неправильно при появлении кнопки удаления
Доработал отображение компонента `Cell` при `mode="removable"` в `rtl`
- Cell: Поправлено отображение компонента в `rtl`
=> feat(Cell): fix rtl view

packages/vkui/src/components/AppRoot/ScrollContext.tsx
При первом рендере выполняется disableScrollLock, из-за чего пользователя может кинуть в 0 позицию, если он прокрутил страницу. Также вызывается лишний reflow
Проверяем что это не первый эффект при управлении скролллоком
- [AppRoot](https://vkcom.github.io/VKUI/${version}/#/AppRoot): исправлено отключение блокировки прокрутки при первом рендере
=> fix(useScrollLock): check first effect

packages/vkui/src/components/ImageBase/ImageBase.tsx
- ImageBase: добавлено свойство `elementTiming` для поддержки [elementtiming](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/elementtiming)
- Avatar: добавлено свойство `elementTiming` для поддержки [elementtiming](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/elementtiming)
- Image: добавлено свойство `elementTiming` для поддержки [elementtiming](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/elementtiming)
=> fix(ImageBase): support elementtiming

packages/vkui/src/components/TabsItem/TabsItem.tsx
В TabsItem требуется прокидывать в качестве компонента Link из Next.JS
Разрешаем прокидывать Component
- [TabsItem](https://vkcom.github.io/VKUI/${version}/#/TabsItem): разрешили прокидывать `Component`
=> fix(TabsItem): add Component prop

packages/vkui/src/components/Avatar/AvatarBadge/AvatarBadge.module.css, packages/vkui/src/components/Avatar/AvatarBadge/AvatarBadgeWithPreset.tsx
Сейчас бейдж у компонента `Avatar` отображает некорректно в `rtl`
Поправил отображение `AvatarBadge` при `rtl`
- Avatar: Поправлено отображение `AvatarBadge` в `rtl` режиме
=> feat(AvatarBadge): fix rtl view

packages/vkui/src/components/ModalCard/ModalCard.test.tsx, packages/vkui/src/components/ModalCard/ModalCardInternal.tsx, packages/vkui/src/components/ModalCard/types.ts, packages/vkui/src/components/ModalPage/ModalPage.test.tsx, packages/vkui/src/components/ModalPage/ModalPageInternal.tsx, packages/vkui/src/components/ModalPage/types.ts
- close #8069 
---
До  рефакторинга модалок контент модалок был обернуть в `FocusTrap` с параметрами `restoreFocus=false` всегда. Теперь же по  `restoreFocus` всегда `true`. Из-за этого при закрытии модалки будет происходить восстановление фокуса и доскрол по необходимости
- Добавил возможность прокинуть свойство `restoreFocus`  в компоненты `ModalCard`, `ModalPage`
- Добавил тесты
- ModalCard: Добавлена возможность прокинуть свойство `restoreFocus`, которое управляет тем, нужно ли восстанавливать фокус после закрытия модалки
=> feat(ModalCard,ModalPage): add prop restoreFocus

packages/vkui/src/components/Search/Search.e2e-playground.tsx, packages/vkui/src/components/Search/Search.module.css, packages/vkui/src/components/Search/Search.tsx, packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-light-1-snap.png
Сейчас в компоненте `Search` кнопка очистки некорректно отображается в `rtl`
Доработаны стили компонента `Search` в режиме `rtl`
- Search: Добавлена поддержка компонента в `rtl`
=> feat(Search): fix rtl view

packages/vkui/src/components/Alert/Alert.tsx
- close #8134 
---
Нужно добавить свойства `FocusTrap` в свойства компонента `Alert`, чтобы `ts` не ругался при прокидывании
- Alert: добавлены свойства `FocusTrap` в свойства `Alert`, так как они итак прокидывались в `FocusTrap`, но ругался `TS`
=> fix(Alert): add FocusTrap props to Alert props

yarn.lock
Automated dependencies deduplication
=> chore: Deduplicate dependencies on master

packages/vkui/src/components/Image/Image.stories.tsx, packages/vkui/src/components/ImageBase/ImageBase.module.css, packages/vkui/src/components/ImageBase/ImageBase.test.tsx, packages/vkui/src/components/ImageBase/ImageBase.tsx
- close #7754
---
Необходимо добавить свойство `filter` для компонента `Image/ImageBase`
- Image: добавлено свойство `filter`, которое применяет одноименный стиль к изображению
=> feat(Image): add prop filter

packages/vkui/src/components/Popper/Popper.tsx
- close #8175
---
Добавил свойство `strategy` в `Popper` и прокинул в `useFloating`
- Popper: Добавлено свойство `strategy`
=> feat(Popper): add prop strategy

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
- close #8176 
---
Перенес подписку события из нативного обработчика в подписку через `addEventListener`. Добавил preventDefault события при `scrollOnAnyWheel`
- HorizontalScroll: Поправлена остановка всплытия события `onwheel` при прокидывании `scrollOnAnyWheel`
=> fix(HorizontalScroll): fix prevent page scrolling

packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/index.ts
- close #8182 
Экспортируем тип `AlertActionProps`. В этом есть смысл, так как у Alert есть проп `renderAction` в который можно предать функцию с аргументами типа `AlertActionProps`
- Alert: экспортирован тип `AlertActionProps`, тип аргументов функции, которую можно передать в `renderAction`
=> feat(Alert): Export AlertActionProps from Alert

packages/vkui/src/components/RichCell/RichCell.e2e-playground.tsx, packages/vkui/src/components/RichCell/RichCell.module.css, packages/vkui/src/components/RichCell/RichCell.stories.tsx, packages/vkui/src/components/RichCell/RichCell.test.tsx, packages/vkui/src/components/RichCell/RichCell.tsx, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-light-1-snap.png
=> patch: pr8199

packages/vkui/src/components/ToolButton/ToolButton.module.css, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-android-chromium-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-ios-webkit-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-webkit-light-1-snap.png
- close #8198
---
см. #8198
- ToolButton:
- при `mode="secondary"` у фона теперь нет прозрачности;
- для `mode="primary" appearance="neutral"` заменён токен с `--vkui--color_background_modal_inverse` на `--vkui--color_background_content_inverse`.
=> fix(ToolButton): rm alpha from bg for `mode="secondary"`

packages/vkui/src/components/Tabs/Tabs.tsx
В доке, начиная в версиях 7.1.0 7.1.1 пропала страница Tabs. Точнее она есть, но под другим именем `TabsModeContext`: https://vkcom.github.io/VKUI/7.1.0/#/TabsModeContext
`Styleguide` перестал адекватно понимать где в файле `Tabs` именно компонент `Tabs`.
Можно были либо перенести `TabsModeContext` из файла `Tabs` в отдельный, либо добавить `displayName` в соответсвии с документацией [styleguide](https://react-styleguidist.js.org/docs/components#default-vs-named-exports)
Проверил по коду, с остальными компонентами такой проблемы нету.
----
Явных причин по коду в изменениях между 7.0.1 и 7.1.0 для такого эффекта не заметил, возможно, что что-то в типах поменялось.
=> doc: Help styleguidist to detect proper name for Tabs page

packages/vkui/src/components/ModalCard/ModalCard.module.css, packages/vkui/src/components/ModalCard/ModalCardInternal.tsx, packages/vkui/src/components/ModalOutlet/ModalOutlet.module.css, packages/vkui/src/components/ModalOutlet/ModalOutlet.tsx, packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalPage/ModalPageInternal.tsx, packages/vkui/src/components/ModalPageFooter/ModalPageFooter.module.css, packages/vkui/src/components/ModalPageFooter/ModalPageFooter.tsx
- close #8113, #8179
---
Возвращаем адаптивность через AdaptivityProvider для:
- `ModalOutlet`
- определяем классы `hostDesktop` и `hostMobile`;
- передаём `isDesktop` из `ModalPage` и `ModalCard`.
- `ModalPage`
- определяем классы `hostDesktop` и `hostMobile`; – также возвращаем ограничение по высоте, которое потерялось.
- `ModalPageHeader`
- определяем класс `hostDesktop`.
- `ModalPageFooter`
- определяем классы `hostDesktop` и `hostMobile`.
- `ModalCard`
- определяем классы `hostDesktop` и `hostMobile`; – по аналогии с `ModalPage` для **desktop** значение св-ва `box-sizing` заменено с `border-box` на `content-box`, чтобы не высчитывать `padding` из `max-width`.
Для `ModalOverlay` не стал применять …
=> fix(modal): return adaptivity by AdaptivityProvider

packages/vkui/src/components/ModalCard/ModalCard.module.css, packages/vkui/src/components/ModalCard/ModalCardInternal.tsx, packages/vkui/src/components/ModalOutlet/ModalOutlet.module.css, packages/vkui/src/components/ModalOutlet/ModalOutlet.tsx, packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalPage/ModalPageInternal.tsx, packages/vkui/src/components/ModalPageFooter/ModalPageFooter.module.css, packages/vkui/src/components/ModalPageFooter/ModalPageFooter.tsx
=> patch: pr8200

packages/vkui/src/components/ModalPage/ModalPageInternal.tsx
Раньше `height` вставлялся в `style`, что позволяло передать без `px`.  С переходом на CSS переменную эта возможность пропала, поэтому проверяем, что `height` это число и добавляем `px`.
- related to #6759
Применил `megeStyle` в `style`, чтобы не применять object-spread когда не надо.
- ModalPage: числовые значения в `height` не приводились к `${height}px`
=> fix(ModalPage): expect number for height

packages/vkui/src/components/AppRoot/ScrollContext.test.tsx, packages/vkui/src/components/AppRoot/ScrollContext.tsx
При анмаунте компонентов контроллер скролл лока ожидает ререндера для проверки на необходимость разблокирования, но он не произойдет 
Меняем функции обновления значения счетчика сразу вызывая функции управления скролл локом
- [AppRoot](https://vkcom.github.io/VKUI/${version}/#/AppRoot): Прокрутка могла не разблокироваться при анмаунте
=> fix: useScrollLockController rm useEffect

package.json, packages/vkui/.storybook/preview.ts, yarn.lock
При дебаге компонента в сторибуке через вызовы `console.log`(и других методов) приходится параллельно открывать консоль разработчика, чтобы посмотреть логи.  Это бывает очень неудобно, если использовать только один экран ноутбука. Чтобы упростить дебаг, можно подключить аддон для сторибука `@storybook/addon-console`, который позволяет выводить логи во вкладку `Actions`
- Подключил пакет `@storybook/addon-console`.
- Добавил `decorator` из пакета в `storybook/preview.ts` 
-
=> tech(Storybook): add `@storybook/addon-console` to storybook

packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.module.css, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.stories.tsx, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.test.tsx, packages/vkui/src/components/PopoutWrapper/PopoutWrapper.tsx, packages/vkui/src/components/ScreenSpinner/ScreenSpinner.tsx
- close #8211 
---
Нужно добавить свойство `strategy`, которое управляет свойством `position` у `PopoutWrapper`
- Добавил свойство `strategy`
- Задепрекейтил cвойство `fixed`, так как `fixed` позиционирование можно выставить через `strategy`
- Добавил тесты
- PopoutWrapper: Добавлено свойство `strategy` для управления способом позиционирования компонентом
=> feat(PopoutWrapper): add prop `strategy` and deprecate prop `fixed`

packages/vkui/src/components/Pagination/Pagination.tsx, packages/vkui/src/components/Pagination/PaginationPage/PaginationPageButton.tsx, packages/vkui/src/components/Pagination/Readme.md, packages/vkui/src/components/Pagination/utils.ts
- close #4737 
---
На основе обратной связи из #4737:
- оставляем только слово "Страницы" как значение по умолчанию у свойства `navigationLabel` (заголовок, `label` всего `Pagination`)
- убираем значение по умолчанию из свойства-функции `getPageLabel`, которое рендерило aria-label для кнопок пагинации. Так как дополнительный текст для кнопок создаёт избыточную информацию. Возможно, что стоит задеприкейтить эту функцию. Но пока оставлю.
- связываем контенер `nav` с заголовком компонента через `aria-labelledby`, чтобы упростить выполнение условия спецификации, в котором говорится, что при наличии более одного `nav` элемента на странице, каждый элемент должен иметь `aria-label`. Теперь для выполнения этого условия достаточно будет проставить соответстующий `navigationLabel`.
- добавили …
=> fix(Pagination):Update a11y labels

packages/vkui/.storybook/addons/source-tab/SourceTab.tsx, packages/vkui/.storybook/addons/source-tab/register.tsx
Сейчас на вкладке `Controls` в сторибуке отображается двойной скролл
Нужно избавиться от двойного скролла
Оказалось, чтоб проблема в том, что вкладка `Source` скрывается только визуально, но остается в верстке. А в стилях сторибука важные стили применяются только к первому элементу.
Получается есть два варианта решения проблемы:
1. Перемещаем вкладку `Source` после `Controls`
2. Не рендерим контент  `Source`, если вкладка неактивна
Решил выбрать второй вариант, чтобы не менять порядок вкладок.
**Результат:**
-
=> fix(Storybook): fix double scroll in controls panel

packages/vkui/src/components/TabbarItem/TabbarItem.test.tsx, packages/vkui/src/components/TabbarItem/TabbarItem.tsx
- close #2743 
---
Двойной фокус при переходе через `TabbarItem`'s табом происходит в основном из-за того, что внутри `TabbarItem`, который является кнопкой/ссылкой, лежит интерактивный `Tappable`. `Tappable` внутри нужен для того, чтобы на android был ripple эффект.
------
Видел решение https://github.com/VKCOM/VKUI/pull/5914. Тоже изначально думал как бы оставить один Tappable, но решил сделать быстрый фикс конкретно этого поведения. Но в целом, в будущем стоит отрефакторить TabbarItem, чтобы избавиться от ненужных нод и упростить компонент.
- убраем возможность фокуса на `Tappable` через tabindex="-1".
- добавляем focus-visible у `Tappable` при фокусировании на `TabbarItem`. Так как иначе при фокусе с клавиатуры вообще фокуса видно не будет, из-за tabindex="-1".
- TabItem: исправляем …
=> fix(TabbarItem): avoid double focus

packages/vkui/src/components/Select/Readme.md
- close #6780
---
Убираем использование CustomSelect в примерах документации Select
-
=> doc(Select): Use Select instead of CustomSelect in Select doc

.github/workflows/pull_request_common.yml
`github.actor` может быть слабым, требуется использовать `github.event.pull_request.user.login`
См https://www.synacktiv.com/publications/github-actions-exploitation-dependabot
-
=> ci: use github.event.pull_request.user.login

yarn.lock
=> build(deps-dev): Bump nanoid from 5.0.8 to 5.1.0

packages/vkui/src/components/Alert/Alert.stories.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Alert/Readme.md, packages/vkui/src/types.ts
- close #3042
---
В задаче #3042 указаны две явные проблемы:
- фокус должен попадать на заголовок, а он не попадает 
Исходя из рекоммендаций [W3C спецификации](https://w3c.github.io/aria/#alertdialog) и других ресурсов ([[1]](https://doka.guide/a11y/role-alertdialog/), [[2]](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role)) выходит, что лучше всего иммено фокус на интерактивном элементе, редко когда встречается совет фокусироваться на начале текста, и то, только если текста много.
Наш `Alert` требование фокуса выполняет. В это PR я лишь передвинул кнопку закрытия алерта выше в дереве, чтобы при её наличии фокус был на ней, и пользователь не мог случайно согласиться на какое-то действие.
Пожелание из #3042 от том, что нужен фокус на заголовке …
=> fix(Alert): Move dismiss button before actions to focus on it first

packages/vkui/src/components/CarouselBase/CarouselBase.tsx
- caused by #8042 
---
В #8042 реализации зацикленной и незацикленной галерии были объединены. При объединении была изменена логика перелистывания слайдов при изменении slideIndex. В новой реализации перелистывание происходило с помощью очереди анимаций. Поэтому при быстром изменении `slideIndex` создается не очень хорошее ощущение, что слайды перелистываются заторможено. Поэтому нужно для незацикленной галереи сделать перелистывание без использования очереди анимаций
Убрал анимацию через js и добавление ее в очередь при перелистывании слайдов в незацикленной галерее.
- Gallery: Поправлено перелистывание слайдов при быстром изменении `slideIndex`
=> fix(Gallery): remove add slide change animation to queue at not looped

packages/vkui/.storybook/addons/documentation-button/DocumentationButton.tsx, packages/vkui/.storybook/addons/documentation-button/constants.ts, packages/vkui/.storybook/addons/documentation-button/register.ts, packages/vkui/.storybook/addons/source-button/SourceButton.tsx, packages/vkui/.storybook/addons/source-button/constants.ts, packages/vkui/.storybook/helpers/index.ts, packages/vkui/.storybook/main.ts, packages/vkui/.storybook/preview.ts
Сейчас со страницы компонента в styleguide можно перейти на страницу компонента в storybook, а наоборот сделать не получится. Нужно добавить кнопку для перехода в styleguide
- Добавил аддон, который добавляет кнопку с помощью которой можно перейти на страницу с докой по компоненту
- Поскольку не все компоненты из сторибука имеют отдельную страницу в доке, на этапе сборки добавил получение конфига для styleguide-а, откуда вытаскиваю список компонентов. И уже в зависимости от того, есть ли компонент в списке, показываю кнопку для перехода к доке
- Получение базовой ссылки на доку сделал через вытаскивание из package.json ссылки на homepage
- Также переделал получение ссылки на репозиторий проекта, через парсинг package.json 
- в storybook добавлена возможность перейти к странице с …
=> tech(storybook): add storybook addon documentation link button

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
- reverts #7882, #8177
---
В **Firefox** событие `onwheel` на контейнере и одновременная прокрутка скроллируемого элемента (`scrollBy` или `scrollLeft`) **тач-падом** негативно влияет на перерисовку контента во время скролла.
Чтобы решить проблему #7774, можно навесить `onwheel` на каждую из стрелок навигации, но у этого решения есть свой баг: если начать крутить колесо с сначала или конца, то появление стрелки навигации заблоркирует прокрутку, то тех пор пока не двинешь мышкой над ней, чтобы началась обработка события `onwheel` на стрелке.
Из-за этих проблем оптимальным будет откатить фикс #7774 и пометить его как **Won't Fix**. Это будет являться ограничением компонента.
Тестировалось на версиях …
=> fix(HorizontalScroll): remove wheels event from container

packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx, packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
=> patch: pr8293

packages/vkui/src/components/Textarea/Textarea.module.css
`Textarea` нет возможности прокрутить, если она `disabled`
- Textarea: компонент со свойством `disabled` теперь можно прокручивать
=> fix(Textarea): fix scroll when disabled

packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx, packages/vkui/src/components/Alert/AlertTypography.tsx
Добавляем `data-testid` для `title` и `description`
Пример:
- Alert: добавлены `data-testid` для `title` (`titleTestId`) и `description` (`descriptionTestId`)
=> feat(Alert): add testid for title and description

packages/vkui/.storybook/addons/documentation-button/DocumentationButton.tsx, packages/vkui/.storybook/addons/source-button/SourceButton.tsx
- caused by #8259 
---
После pr #8259 после перехода на стори и последующей перезагрузки стори не открываетя. Почему-то кнопка открытия доки отрисовывается раньше, чем инициализируются глобальные переменные. Поэтому падает ошибка.
Добавил проверку, что необходимые глобальные переменные проинициализированы 
-
=> fix: fix reload story

packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.stories.tsx, packages/vkui/src/components/FormLayoutGroup/Readme.md
- close #7867
---
Пока изучал проблематику задачи #7867 вспомнил, что возможноcть передачи `placeholder` в `DateInput` мы уже реализовали с помощью свойства `rederCustomValue` в #8168
Собственно проблема задачи #7867 в том, что вот такой дизайн, где лейблы над полями отстутсвуют, и текст лэйблов на самом деле лежит как `placeholder` у инпутов, было сложно реализовать без #8168
Оставался лишь вопрос как это реализовать доступно, чтобы скринридер зачитал названия полей, например, даже когда в них введен текст.
Как решение можно воспользоваться нашим сервисным компонентом `VisuallyHidden`, в котором можно задать тег `label` через свойство `Component="label"`, продублировать текст из плейсхолдера и связать через `id` и `htmlFor` с инпутом.
Добавли пример в сторибук и в доку, чтобы ссылаться …
=> doc(DateInput/FormLayoutGroup): Segmented example without visible labels

packages/vkui/src/components/CellButtonGroup/CellButtonGroup.e2e-playground.tsx, packages/vkui/src/components/CellButtonGroup/CellButtonGroup.e2e.tsx, packages/vkui/src/components/CellButtonGroup/CellButtonGroup.module.css, packages/vkui/src/components/CellButtonGroup/CellButtonGroup.stories.tsx, packages/vkui/src/components/CellButtonGroup/CellButtonGroup.test.tsx, packages/vkui/src/components/CellButtonGroup/CellButtonGroup.tsx, packages/vkui/src/components/CellButtonGroup/Readme.md, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-android-chromium-dark-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-android-chromium-light-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-ios-webkit-dark-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-ios-webkit-light-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-vkcom-firefox-dark-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-vkcom-firefox-light-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-vkcom-webkit-dark-1-snap.png, packages/vkui/src/components/CellButtonGroup/__image_snapshots__/cellbuttongroup-vkcom-webkit-light-1-snap.png, styleguide/config.js
- close #6360 
---
Создаем компонент для группировки
- CellButtonGroup: компонент для группировки `CellButton`
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/cc0a8aba-1635-4dfd-aa93-e03345f72aac" />
</picture>
=> feat(CellButtonGroup): add component

packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/components/Popover/usePopover.tsx, packages/vkui/src/lib/floating/types/component.ts
- relates to #8291 
---
Для pr #8291 нужно добавить свойство `disableFocusTrap` для компонентов `Popover` и `OnboardingTooltip`, чтобы отключить захват фокуса
- Popover: Добавлено свойство `disableFocusTrap` для отключения захвата фокуса
- OnboardingTooltip: Добавлено свойство `disableFocusTrap` для отключения захвата фокуса
=> feat(Popover, OnboardingTooltip): add prop disableFocusTrap

.github/dependabot.yml
dependabot присылает два PR-а для next зависимостей
Группируем обновления для next, чтобы не создавалось несколько PR-ов
-
=> ci(dependabot): group next

tsconfig.json
Включаем [erasableSyntaxOnly](https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/#the---erasablesyntaxonly-option)
-
=> ci: enable erasableSyntaxOnly

packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/components/Popper/Popper.tsx, packages/vkui/src/lib/floating/adapters.ts, packages/vkui/src/lib/floating/useFloatingMiddlewaresBootstrap/index.ts
Было замечено, что при наличии переноса в опции, и при недостатке места по вертикали, CustomSelect может отрендерить список сбоку от инпута. По дизайну у нас нету такой поддержки, и стили выглядят странно.
<details>
<summary>
Пример кода
</summary>
```tsx
import {
CustomSelect,
FormItem,
Group,
Panel,
PanelHeader,
SimpleCell,
View,
} from "@vkontakte/vkui";
export default function App() {
const options = [
{
value: "1",
label:
"Lorem Ipsum is simply dummy text of the printing and typesetting industry",
},
{
value: "2",
label: "Lorem Ipsum",
},
];
return (
<View activePanel="profile">
<Panel id="profile">
<PanelHeader>VKUI</PanelHeader>
<div
style={{
width: "360px",
}}
>
<FormItem>
<CustomSelect options={options} />
</FormItem>
</div>
</Panel>
</View>
);
}
```
</details>
В качестве решения …
=> fix(CustomSelect/DateInput): placement configuration

packages/vkui/src/components/Search/Search.test.tsx, packages/vkui/src/components/Search/Search.tsx
Добавляем `testid` для find button чтобы упростить тестирование компонента в `e2e`.
related: #8333 
- Search: добавлено новое свойство `findButtonTestId` для e2e тестирования кнопки поиска.
=> feat(Search): Add testid for find button

packages/vkui/src/components/AppRoot/AppRoot.test.tsx, packages/vkui/src/components/AppRoot/ScrollContext.test.tsx, packages/vkui/src/components/AppRoot/ScrollContext.tsx
Блокировка прокрутки происходит на body элементе, хотя глобальная прокрутка находится выше на html элементе
Переносим блокировку с `document.body` на `document.documentElement`
- [AppRoot](https://vkcom.github.io/VKUI/${version}/#/AppRoot): блокировка прокрутки теперь происходит на html элементе
=> fix(AppRoot): scrollLock on html

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- close #8334 
---
В #8334 видно, что при асинхронной загрузке опций есть лаг между тем когда `fetching` уже не `true`, но опций ещё нет и мы в дропдауне, вместо лоадера, выводим `Ничего не найдено`.
Опций нет по той причине, что рендерим мы опции из локального стейта, который мы синхронизируем с props.options, а синхронизируем мы через `useEffect`. 
Получается, что должен сработать `useEffect` прежде чем новые, загруженные опции пользователя, переданные через `props.options`, попадут в рендер дропдауна.
- Убран локальный стейт `options`, вместо этого `options` это результат фильтрации `props.options`, обёрнутой в `useMemo`.
- Изменилась логика проверки необходимости вызова `onChange` при клике на опцию из списка.
Раньше она была основана на проверке по индексам опций в списке, типа …
=> fix(CustomSelect): fix props.options and local state option syncronization

packages/vkui/src/components/ChipsInputBase/types.ts
​В компоненте `ChipsSelect` второй аргумент функции, передаваемой через рендер проп `renderChip`,  имеет тип `any`, даже при явном указании дженерика.
Прокинул дженерик в тип `RenderChip`, чтобы использовать правильный тип вместо типа по умолчанию.
- ChipsSelect: Исправлена типизация – в `renderChip` не передавался аргумент дженерик
=> fix(ChipsSelect): renderChip prop type fix

packages/vkui-docs-theme/package.json, packages/vkui/jest.config.ts, packages/vkui/package.json, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-android-chromium-dark-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-android-chromium-light-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-chromium-dark-1-snap.png, packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-chromium-light-1-snap.png, packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.tsx, packages/vkui/src/components/ImageBase/validators.ts, packages/vkui/src/components/Spinner/Spinner.tsx, packages/vkui/src/components/Spinner/icons.tsx, packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-dark-1-snap.png, packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-light-1-snap.png, yarn.lock
Обновляем иконки до [@vkontakte/icons@3.0.0](https://github.com/VKCOM/icons/releases/tag/%40vkontakte%2Ficons%403.0.0).
Иконки для спиннера вынес отдельно, поскольку в сафари animateTransform не работает для svg
- @vkontakte/icons обновлены до v3
=> feat: icons v3

packages/vkui/src/components/ModalCard/ModalCard.tsx, packages/vkui/src/components/ModalPage/ModalPage.tsx, packages/vkui/src/components/ModalRoot/useModalManager.tsx
Мы ошибочно генерируем предупреждение об отсутствующем `id`/`nav` для `ModalPage`/`ModalCard` в случае, когда они рендерятся без `ModalRoot`. 
- ModalPage: исправлено предупреждение об отсутствующем `id`/`nav` при использовании вне `ModalRoot`
- ModalCard: исправлено предупреждение об отсутствующем `id`/`nav` при использовании вне `ModalRoot`
=> fix(ModalPage, ModalCard): fix id warn

packages/vkui/src/components/ContentCard/ContentCard.tsx, packages/vkui/src/components/Link/Link.tsx, packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx, packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx, packages/vkui/src/components/TabsItem/TabsItem.tsx, packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
Сейчас некоторые компоненты перезатирают переданные во внутренний компонент `Tappable` свойства . Отдаём приоритет пользовательским свойствам (так работает подавляющее большинство компонентов). 
- все компоненты теперь отдают приоритет пользовательским `Tappable`-свойствам
=> feat: do not rewrite user props

packages/vkui/src/components/Tappable/Tappable.tsx
Сейчас все компоненты на базе `Tappable` могут задавать либо `activeClassName`, либо `activeMode` (`activeClassName` частный случай `activeMode`), оставляем только `activeMode`, чтобы не дублировать функционал (то же самое про `hover*`).
- cвойства интерактивных компонентов `activeClassName` и `hoverClassName` устарели, используйте  `activeMode` и `hoverMode` соответственно.
=> fix(Tappable): deprecate duplicate props

packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Предположим мы хотим , чтобы у некоторых опций в `CustomSelect` был отрисован дополнительный элемент `after`
```typescript
options: [
{
label: 'Санкт-Петербург',
description: 'Россия',
value: '0',
after: <ContentBadge>Badge</ContentBadge>,
},
{
label: 'Москва',
description: 'Россия',
value: '1',
},
],
```
Сейчас по умолчанию в `renderOption` используется `CustomSelectOption`, который может принимать `after` и ожидается, что все должно сработать. Но `after` не отрисовывается, потому что не прокидывается до функции отрисовки `renderOption`, хотя по логике должно. Помимо `after` есть и другие свойства, которые не доходят до функции отрисовки и по сути они вообще никогда ничего не делают
Добавил прокидывание свойств `option` из массива `options` при вызове `renderOption`
- CustomSelect: …
=> fix(CustomSelect): fix option props drilling

packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
- close #6772
---
Если ChipsSelect близко к нижнему краю страницы, то как только выбирается итем, который переносит контент на следующую строку и сдвигает всплывающую область вниз, всплывающая область пытается отразиться наверх, на пол секунды у неё получается, но потом она просто закрывается. Тот же баг есть, если наверху не хватает места, и он пытается отражаться вниз.
Поисследовал проблему, оказалось, что:
- При mousedown на опцию, она сразу добавляется
- Происходит перерисовка и высота инпута увеличивается
- Дропдаун не помещается и отзеркаливается
- При отпускании мыши срабатывает `onClick`, который уже срабатывает за пределами дропдауна
- Срабатывает закрытие дропдауна, потому что клик за пределами 
Добавил флаг `forbidCloseByOutsideClick`, который устанавливается в `true` при …
=> fix(ChipsSelect): fix closing dropdown when placement change

packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx, packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx, packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
- close https://github.com/VKCOM/VKUI/issues/8455
---
Исправляем поведение CalendarTime и логику фокуса.
Сейчас, если мы рендерим `Calendar` со временем, но без кнопки "Готово", то при проходе по `Calendar` с помощью `Tab` мы застреваем на инпуте с минутами.
С одной стороны это из-за того, что мы не учли, что кнопки "Готово" может не быть в https://github.com/VKCOM/VKUI/pull/8002
Но даже если это исправить, можно заметить, что фокус, если дропдаун селекта открыт, хоть и переходит из инпута минут куда-то, но он явно не попадает на следующий интерактивный элемент при одном нажатии `Tab`. Только со следующего нажатия `Tab` фокус действительно переходит дальше. (Это доводльно фрустрирующее поведение).
Оказалось, что причина в том, что в `CustomSelect`, когда дропдаун с опциями открыт и имеет …
=> fix(Calendar): fix tab ordering when we use enableTime and doneButtonShow

packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/CalendarDays/CalendarDays.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/components/DateInput/DateInput.tsx, packages/vkui/src/components/DateInput/hooks.test.ts, packages/vkui/src/components/DateInput/hooks.ts, packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx, packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx, packages/vkui/src/hooks/useCalendar.ts, packages/vkui/src/hooks/useDateInput.ts, packages/vkui/src/lib/date.ts
- close #8451
---
Если DateInput контролируемый и дата задана, то кнопка очистки значения срабатывает только со второго раза.
Хорошо воспроизводиться в доке: [v7.2.0](https://vkcom.github.io/VKUI/7.2.0/#/DateInput)
Поисследовал проблему: у нас для пустого состояния сейчас используется значение `undefined` и это же значение является индикатором того, что компонент неконтролируемый. Получается ситуация, что компонент был контролируемым и вдруг стал неконтроллируемым.
По идее нужно явно разделить неконтроллируемое состояние и пустое. Предлагаю для пустого использовать `null`.
У компонента `Calendar` расширил тип для `value` и `defaultValue`, добавив `null`. Это изменение не ломающее обратную совместимость. По идее, также надо бы сделать для типа свойства `onChange`:
сейчас он
```typescript …
```
=> fix(DateInput): fix clear date by button

packages/vkui/src/components/ModalRoot/Readme.md, packages/vkui/src/components/ModalRoot/types.ts, packages/vkui/src/components/ModalRoot/useModalRootContext.ts
По документации useModalRootContext должен возвращать `activeModal`
- [useModalRootContext](https://vkcom.github.io/VKUI/${version}/#/ModalRoot): useModalRootContext не возвращал `activeModal`
=> fix(useModalRootContext): add activeModal

packages/vkui/src/components/AdaptivityProvider/AdaptivityContext.tsx, packages/vkui/src/components/Tappable/Tappable.e2e-playground.tsx
- related #6009
Депрекейтим свойство, которое нигде не используется
- AdaptivityProvider: неиспользуемое свойство `hasHover` устарело и будет удалено в следующем мажорном релизе
=> feat: deprecate hasHover for AdaptivityProvider

styleguide/Components/Preview.js, styleguide/lib/theme/functions.js, styleguide/lib/theme/index.js
Хардкод токенов не позволяет точечно переопределять платформу
- Вернули возможность переопределять платформу через `PlatformProvider`
=> fix: docs theme redefine

packages/vkui/src/lib/platform.ts
`vkcom` это платформа предназначенная для миниприложений которые встраиваются в vk.com. Ее не требуется переименовывать в `web`
-
=> chore: vkcom is not web

packages/vkui/src/components/Calendar/Calendar.test.tsx, packages/vkui/src/components/Calendar/Calendar.tsx, packages/vkui/src/components/CalendarDay/CalendarDay.tsx, packages/vkui/src/components/CalendarDays/CalendarDays.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx, packages/vkui/src/components/CalendarRange/CalendarRange.tsx, packages/vkui/src/components/DateInput/DateInput.test.tsx, packages/vkui/src/hooks/useCalendar.ts, packages/vkui/src/lib/calendar.test.tsx, packages/vkui/src/lib/calendar.ts
- related to #4932
- часть большого PR https://github.com/VKCOM/VKUI/pull/8419
- первая часть: #8487 (ревью начинать с неё)
- вторая часть: https://github.com/VKCOM/VKUI/pull/8488
---
Переработана структура календаря так, что его элементы были доступны пользователям ассистивных технологий.
- Данные календаря теперь лежат в таблице. Таблица описана с помощью ролей (`role="grid"`), а не нативных элементов, чтобы не портить текущие стили.  
Заголовком таблицы являются названия дней недели, основное тело таблицы это дни. 
Заголовок размечен с помощью роли `columnheader`. 
Ячейки с помощью роли `gridcell`.
Это позволяет пользователям NVDA эффективнее перемещаться по элементам календаря. Они привыкли к тому, что календарь это всегда таблица, и ожидают, что смогут прыгнуть в тело ближайшей …
=> feat(Calendar): Make Calendar accessible from keyboard and screen reader

packages/vkui/src/components/Link/Link.module.css, packages/vkui/src/components/Link/Link.test.tsx, packages/vkui/src/components/Link/Link.tsx
- Fixes #7609
---
Link без свойств превращается в button
Также наведение не отрабатывает при использовании мышки на планшете
Используем механизм наведения из Clickable, убираем превращение в button
- [Link](https://vkcom.github.io/VKUI/${version}/#/Link): наведение могло не отрабатываться на сенсорных экранах при использовании мышки или стилуса
- [Link](https://vkcom.github.io/VKUI/${version}/#/Link): не интерактивный компонент не превращается в button
=> fix(Link): not interactive

packages/vkui/src/components/Alert/Alert.tsx
Свойство `autoFocus` наследовалось из стандартных свойств, но переопределяем мы его для `FocusTrap`. Изменение не ломающее, потому что  `autoFocus` у `FocusTrap` расширяет стандартное свойство.
- Alert: свойство `autoFocus` теперь принимает значение `"root"`
=> feat: add autoFocus prop from FocusTrap

packages/vkui/src/components/ActionSheet/ActionSheet.tsx, packages/vkui/src/components/ActionSheet/ActionSheetDefaultIosCloseItem.tsx, packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
- пропы `mount` и `disabled` депрекейтим, как будто для этого компонента они не имеют смысла (ну и не работают сейчас так, как ожидается). 
- для `ActionSheetDefaultIosCloseItem` добавила возможность перебить `children`
- ActionSheet: свойства `mount` и `disabled` устарели и будут удалены в `v8`
- [ActionSheetDefaultIosCloseItem](https://vkcom.github.io/VKUI/7.3.0/#/ActionSheet): добавлена возможность переопределять `children`
=> feat(ActionSheet): cleanup

packages/vkui/src/components/Alert/Alert.test.tsx, packages/vkui/src/components/Alert/Alert.tsx
Добавляем вариант "none", чтобы дать возможность скрыть крестик. Добавлены тесты на это.
- Alert: добавлено значение `"none"` для свойства `dismissButtonMode`, для возможности скрыть крестик
=> feat(Alert): add dismissButtonMode none option

packages/vkui/src/components/AppRoot/ScrollContext.tsx
- close #8524 
---
Сейчас есть баг, что при открытии модального окна пропадает PanelHeader. Чтобы он вернулся, нужно, чтобы произошла перерисовка. Воспроизводится только в Safari
После долго исследования удалось понять, что сломалось в пр #8137 . Если в кратце, то в этом pr при включении блокировки скролла логика установки стилей была разделена на два `Object.assign(style, {...})`, и видимо из-за этого Safari так реагирует. 
- Вернул установку стилей для блокировки скролла через один `Object.assign`
- PanelHeader: Исправлен баг с тем, что при открытии модального окна `PanelHeader` пропадал
=> fix(ScrollContext): fix scroll lock

packages/vkui/src/lib/calendar.ts
В некоторых таймзонах используемый метод получения месяца давал ненужное смещение, делаем получение месяца более "безопасным"
- DateInput: исправили неверные наименования месяцев в некоторых таймзонах
=> fix(DateInput): fix month names

.github/workflows/branch_test_coverage.yml, .github/workflows/dedupe_deps.yml, .github/workflows/deploy_docs_on_branch_push.yml, .github/workflows/monday.yml, .github/workflows/pr_close.yml, .github/workflows/pr_close_undeploy.yml, .github/workflows/publish.yml, .github/workflows/publish_deploy.yml, .github/workflows/publish_prerelease.yml, .github/workflows/pull_request_common.yml, .github/workflows/pull_request_packages.yml, .github/workflows/pull_request_packages_deploy.yml, .github/workflows/reusable_workflow_test.yml, .github/workflows/reusable_workflow_test_e2e.yml, .github/workflows/update_screens.yml, packages/vkui/src/components/Button/Button.module.css
Пробуем починить ошибки в CI:
```
Download action repository 'VKCOM/VKUI@master' (SHA:c419a9d34380aeb65b52ce3870c9ccf9ca171d1e)
Warning: Failed to download action 'https://api.github.com/repos/VKCOM/VKUI/tarball/c419a9d34380aeb65b52ce3870c9ccf9ca171d1e'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Warning: Back off 16.528 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/VKCOM/VKUI/tarball/c419a9d34380aeb65b52ce3870c9ccf9ca171d1e'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Warning: Back off 16.76 seconds before retry.
Error: Action 'https://api.github.com/repos/VKCOM/VKUI/tarball/c419a9d34380aeb65b52ce3870c9ccf9ca171d1e' download has timed out. …
```
=> ci: use local path for repo actions

packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx
`disabled` не прокидывался в `removable` компонент, позволяем это делать (по аналогии с `Cell` компонентов).
Ранее обсуждали с дизайном, что этот проп может быть не нужен, но `disabled` на компоненте `fieldset` (именно он рендерится по умолчанию) имеет значение для `a11y`.
- FormLayoutGroup: свойство `disabled` теперь влияет на режим `removable`
=> fix(FormLayoutGroup): add disabled to removable

packages/vkui/src/components/FormItem/FormItem.tsx
Свойство `disabled` прокидывалось просто на `div`, не влияя на компонент, прокидываем на `removable` компонент, чтобы дизейблить кнопку удаления.
- FormItem: свойство `disabled` теперь влияет на компонент
=> fix(FormItem): add disabled to removable

packages/vkui/src/components/Touch/Touch.tsx
- caused by #7272
---
В рамках #7272 стал навешивать `touchstart` через React, опустив момент, что есть задачи, которые требуют вызова `preventDefault()` на `touchstart`, а т.к. React использует `passive: true` под капотом, то `preventDefault()` не срабатывает.
Инцидент: из-за не работающего `preventDefault()` глючит `<Cell draggable />` на Android. На iOS не воспроизводится, есть только ошибки в консоли.
Версия: `>= 6.6.0`
После фикса также проверил на работоспособность `Gallery`, `View`/`Panel`, `PullToRefresh`, `Slider`.
- ОС: Android 14
- Браузеры:
- Chrome 136.0.7103.87
- Samsung Internet 28.0.0.59
<details><summary>Пример для Storybook</summary>
<p>
```tsx
import { useState } from '@storybook/preview-api';
import type { Meta, StoryObj } from '@storybook/react';
import { …
```
=> fix(Touch): handle touchstart events by DOM API

packages/vkui/src/components/CarouselBase/CarouselBase.tsx, packages/vkui/src/components/CarouselBase/ScrollArrows.tsx, packages/vkui/src/components/Gallery/Gallery.test.tsx
В компоненте карусели не прокидываются свойства лейблов для стрелок
Возвращаем эту возможность
- [Gallery](https://vkcom.github.io/VKUI/${version}/#/Gallery): свойства `arrowPrevLabel` и `arrowNextLabel` не прокидывались к стрелкам
=> fix(Gallery): fix arrow label

packages/vkui/src/components/ContentBadge/ContentBadge.e2e-playground.tsx, packages/vkui/src/components/ContentBadge/ContentBadge.stories.tsx, packages/vkui/src/components/ContentBadge/ContentBadge.test.tsx, packages/vkui/src/components/ContentBadge/ContentBadge.tsx, packages/vkui/src/components/ContentBadge/ContentBadgeIconSlot.tsx, packages/vkui/src/components/ContentBadge/Readme.md
Подкомпонент `ContentBadge.SlotIcon` не совсем соответствует названию - это же не SlotIcon (иконка слота), а IconSlot (слот для иконки)
- [ContentBadge](https://vkcom.github.io/VKUI/${version}/#/ContentBadge): Подкомпонент `SlotIcon` помечен устаревщим, используйте `IconSlot`
=> fix(ContentBadge): IconSlot

packages/vkui/src/components/Spinner/icons.tsx
В коде есть завязки на vkuiIcon классы. В идеале таких завязок не должно быть
- [Spinner](https://vkcom.github.io/VKUI/${version}/#/Spinner): возвращены vkuiIcon классы
=> fix(Spinner): icons add className

packages/vkui/src/components/ChipsInput/useChipsInput.ts, packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
- caused by #8435
---
После #8435 появился баг - в `onChange` `ChipsSelect` и `ChipsInput` в values не прокидывались кастомные поля, заданные пользователем в `options` из-за того, что потерялся spread при расчете новых значений. Вернул spread и написал тест кейса
- ChipsSelect: Поправлен баг с тем, что в `onChange` не прокидывались кастомные поля `options`
=> fix(ChipsSelect): fix onChange with custom fields

packages/vkui/src/components/Clickable/useState.tsx
- Tappable: Поправлена опечатка в документации свойства `activeEffectDelay`
=> docs(Tappable): mv `activated` to `active`

packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx, packages/vkui/src/hooks/useGlobalOnClickOutside.test.tsx, packages/vkui/src/hooks/useGlobalOnClickOutside.ts
- caused by #8454
---
В pr #8454 был поправлен баг, но был допущен другой - при `closeAfterSelect={false}` после выбора одной из опций дропдаун не закрывается после первого нажатия за пределами дропдауна. 
Поисследовав, пришел к решению, что изменения #8454 нужно откатить, а также необходимо доработать хук `useGlobalClickOutside`, точнее добавить другой хук `useGlobalOnMouseDownOutside`, который бы слушал событие `mouseDown`. Такое решени починит текущий баг и не сломает баг из #8454.
Как альтернатива, можно было бы у `option` слушать не `onMouseDown`, а `onClick`, но ,поисследовав историю изменений, я так и не понял почему был выбран именно этот обработчик, возможно он был использован специально.
- ChipsSelect: Поправлен баг, с тем, что дропдаун не закрывался после первого нажатия за …
=> fix(ChipsSelect): fix close dropdown with `closeAfterSelect`

packages/vkui-date-fns-tz/package.json
Временно удаляем подпись чтобы опубликовать пакет первый раз
> Can't generate provenance for new or private package, you must set `access` to public.
-
=> ci(vkui-date-fns-tz): tmp rm provenance

packages/vkui-date-fns-tz/package.json
> Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/VKCOM/VKUI" from provenance
-
=> ci(vkui-date-fns-tz): add repository.url

packages/vkui-date-fns-tz/package.json, packages/vkui/jest.config.ts, packages/vkui/package.json, packages/vkui/src/lib/date.ts, yarn.lock
Используем vkui-date-fns-tz
- related to #8581
- Зависимость @date-fns/tz теперь скомпилирована под es2017
=> fix: use vkui-date-fns-tz

packages/vkui/src/components/Clickable/Clickable.tsx, packages/vkui/src/components/Tappable/Tappable.test.tsx
Если передавать `undefined` в свойство `Component`, оно будет перезаписывать автоопределённые значения
Игнорируем проп `Component`, потому что он обрабатывается в функции `component`
- Tappable: исправлена обработка свойства `Component={undefined}`
=> fix(Clickable): ignore undefined Component

packages/vkui/src/components/ScreenSpinner/ScreenSpinner.test.tsx, packages/vkui/src/components/ScreenSpinner/ScreenSpinner.tsx, packages/vkui/src/components/ScreenSpinner/ScreenSpinnerContainer.tsx, packages/vkui/src/components/Skeleton/Skeleton.test.tsx, packages/vkui/src/components/Skeleton/Skeleton.tsx, packages/vkui/src/components/Spinner/Spinner.test.tsx, packages/vkui/src/components/Spinner/Spinner.tsx, packages/vkui/src/styles/animationVisibilityDelay.module.css, packages/vkui/src/styles/animationVisibilityDelay.ts
Добавляем для компонентов загрузки свойство `visibilityDelay ` которое скрывает элемент в начале отрисовки на заданное количество миллисекунд
- [Spinner](https://vkcom.github.io/VKUI/${version}/#/Spinner), [ScreenSpinner](https://vkcom.github.io/VKUI/${version}/#/ScreenSpinner), [PanelSpinner](https://vkcom.github.io/VKUI/${version}/#/PanelSpinner), [Skeleton](https://vkcom.github.io/VKUI/${version}/#/Skeleton): свойство `visibilityDelay ` скрывает компонент в начале отрисовки на заданное количество миллисекунд
=> feat: add visibilityDelay

packages/vkui/src/index.ts
- related to #8325 
Забыла экспортнуть, возможно, компонент никому не нужен в итоге 🤣 
- CellButtonGroup: компонент теперь доступен для импорта
=> fix: export CellButtonGroup

packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- close #8633 
---
В компоненте `CustomSelect` событие `onInputChange` корректно уведомляет об изменениях значения поискового поля ввода (`input`) при взаимодействии пользователя. Однако при закрытии селекта метод `close` принудительно сбрасывает значение `input` (через `setInputValue('')`), но событие `onInputChange` при этом не вызывается. Это создает неопределенность: значение поля ввода изменилось, но подписчики `onInputChange` не получают уведомления.
Значение поля ввода сбрасывается в методе `close` (через `setInputValue('')`), но событие `onInputChange` не вызывается, что нарушает ожидания разработчика, использующего это событие для отслеживания изменений.
- При сбросе значения в input сделал вызов нативного ивента 'input' на поле ввода, чтобы спровоцировать вызов `onInputChange` c …
=> fix(CustomSelect): fix onInputChange callback when reset input value

packages/vkui/src/components/CalendarTime/CalendarTime.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- revert #8636 
Изменение слишком рискованное, может сломать поведение в местах использования колбэка `onInputChange`
=> Revert #8636

packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx, packages/vkui/src/components/Popover/Popover.tsx, packages/vkui/src/components/Popover/usePopover.tsx, packages/vkui/src/components/Popper/Popper.tsx, packages/vkui/src/components/Tooltip/Tooltip.tsx, packages/vkui/src/components/Tooltip/useTooltip.tsx, packages/vkui/src/hooks/useFloatingElement.tsx, packages/vkui/src/lib/floating/useFloatingMiddlewaresBootstrap/index.ts
- close #8122
---
Нужна возможность отключения смещения по главной оси (shift middleware), в случаях, когда положение тултипа
просчитывается самостоятельно и нужно гарантировать положение относительно якорного элемента
- Все всплывающие элементы (`Tooltip`, `Popover`, `Popper`, `OnboardingTooltip`) теперь обладают свойством `disableShiftMiddleware` для возможности отключить смещение по главной оси
=> feat(floating): add disableShiftMiddleware prop

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- close #8572 
---
При первой отрисовке компонента, если передать в него `value={undefined}` и `allowClearButton`, вызывается `onChange` со значением `null`. По идее ничего не изменилось и `onChange` не должен вызываться
Перед вызовом onChange есть ряд проверок, одна из которых проверяет, что изменение вызвано нажатием на ClearButton. Но проверяется недостаточно факторов. Добавил еще проверку.
Добавил тест кейс из описания.
- CustomSelect: Поправлена проблема вызова `onChange` при первой отрисовке при использовании `allowClearButton` и `value={undefined}`
=> fix(CustomSelect): fix check before onChange call

packages/vkui/src/components/ModalCard/ModalCard.module.css, packages/vkui/src/components/ModalOutlet/ModalOutlet.module.css, packages/vkui/src/components/ModalPage/ModalPage.module.css, packages/vkui/src/components/ModalPage/ModalPage.test.tsx, packages/vkui/src/components/ModalPage/ModalPageInternal.tsx, packages/vkui/src/components/ModalPage/types.ts
- close #8817
---
- Добавляем для `size` поддержку  всех свойств, которые поддерживаются CSS свойством `width`.
- Переносим "безопасные" отступы, которые добавляются для desktop версии, с `ModalPage` и `ModalCard` в `ModalOutlet` (для `ModalCard` ).
- ModalPage: `size` теперь принимает все другие допустимые для CSS свойства `width` значения
=> feat(ModalPage): extend size prop with any other CSS properties

packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx, packages/vkui/src/components/CustomSelect/CustomSelect.tsx
- cased by #8663
---
В #8663 был добавлен лейбел с состояние подгрузки опций. Проблема в том, что по умолчанию при первой отрисовке выставляется лейбел с окончание загрузки опций. По идее изначально этого не должно быть
- CustomSelect: При первой отрисовке компонента озвучивался текст о том, что опции были загружены
=> fix(CustomSelect): fix fetching status by default

packages/vkui/src/components/TabsItem/TabsItem.tsx
- caused by #8484
---
После #8484 в `TabsItem` всегда прокидывается свойство `onClick` и, поскольку `TabsItem` использует внутри `Tappable`, компонент всегда интерактивный, что не очень правильно. Нужно сделать так, чтобы onClick в `Tappable` прокидывался только, если снаружи прокинут `onClick` или, если `Tabs` работает в контролируемом режиме
- TabsItem: Исправлена проблема, что `TabsItem` всегда был интерактивным
=> fix(TabsItem): fix onClick prop without controlled mode

packages/vkui/src/components/Popper/Popper.tsx
- close #9000
---
Добавлен новый проп `autoUpdateOnAnimationFrame` для компонента Popper, который позволяет автоматически обновлять позицию поппера на каждом кадре анимации.
- Popper: добавлен проп `autoUpdateOnAnimationFrame` для автоматического обновления позиции на каждом кадре анимации
=> feat(Popper): add autoUpdateOnAnimationFrame prop

packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx, packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
В `CalendarHeader` не работает свойство `yearDropdownTestId` при прокидывании в виде функции
- Calendar: свойство `yearDropdownTestId` не работало при прокидывании в виде функции
=> fix(CalendarHeader): fix yearDropdownTestId with function
